class BangleExecutor{
    public static void main(String[] args){
		
		
	Bangle bangle=new Bangle();
	System.out.println("before init instance variable");
	System.out.println("type : " + bangle.type);
	System.out.println("material : " + bangle.material);
	System.out.println("price  : " + bangle.price);
	System.out.println("quantity: " + bangle.quantity);
	System.out.println("brand: " + bangle.brand);
	System.out.println("colour: " + bangle.colour);
	System.out.println("isMultipleColour : " + bangle.isMultipleColour);
	System.out.println("isQualityGood: " + bangle.isQualityGood);
	System.out.println("size: " + bangle.size);
	System.out.println("weight: " + bangle.weight);
	System.out.println("isAntique: " + bangle.isAntique);
	System.out.println("warranty: " + bangle.warranty);
	System.out.println("manufactureDate: " + bangle.manufactureDate);
	System.out.println("isHandMade : " + bangle.isHandMade);
	System.out.println("discount : " + bangle.discount);
	System.out.println("sellerName : " + bangle.sellerName);
	System.out.println("numberOfStones : " + bangle.numberOfStones);
	System.out.println("customerReview : " + bangle.customerReview);
	System.out.println("rating : " + bangle.rating);
	System.out.println("isLightWeight : " + bangle.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle.countryOfOrigin);
	System.out.println("designType : " + bangle.designType);
	System.out.println("pattern : " + bangle.pattern);
	System.out.println("diameter : " + bangle.diameter);
	System.out.println("isStockAvailable : " + bangle.isStockAvailable);
	System.out.println("grams: " + bangle.grams);
	bangle.type = "Glass Bangle";
	bangle.material = "Glass";
	bangle.price = 299;
	bangle.quantity = 4;
	bangle.brand = "Sukkhi";
	bangle.colour = "Red";
	bangle.isMultipleColour = true;
	bangle.isQualityGood = true;
	bangle.size = "2.6";
	bangle.weight = "20 grams";
	bangle.isAntique = false;
	bangle.warranty = "3 months";
	bangle.manufactureDate = "10-02-2026";
	bangle.isHandMade = true;
	bangle.discount = "15%";
	bangle.sellerName = "Amazon Seller";
	bangle.numberOfStones = 10;
	bangle.customerReview = "Very beautiful bangles";
	bangle.rating = 4;
	bangle.isLightWeight = true;
	bangle.countryOfOrigin = "India";
	bangle.designType = "Traditional";
	bangle.pattern = "Floral";
	bangle.diameter = 6;
	bangle.isStockAvailable = true;
	bangle.grams = 20;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle.type);
	System.out.println("material : " + bangle.material);
	System.out.println("price  : " + bangle.price);
	System.out.println("quantity: " + bangle.quantity);
	System.out.println("brand: " + bangle.brand);
	System.out.println("colour: " + bangle.colour);
	System.out.println("isMultipleColour : " + bangle.isMultipleColour);
	System.out.println("isQualityGood: " + bangle.isQualityGood);
	System.out.println("size: " + bangle.size);
	System.out.println("weight: " + bangle.weight);
	System.out.println("isAntique: " + bangle.isAntique);
	System.out.println("warranty: " + bangle.warranty);
	System.out.println("manufactureDate: " + bangle.manufactureDate);
	System.out.println("isHandMade : " + bangle.isHandMade);
	System.out.println("discount : " + bangle.discount);
	System.out.println("sellerName : " + bangle.sellerName);
	System.out.println("numberOfStones : " + bangle.numberOfStones);
	System.out.println("customerReview : " + bangle.customerReview);
	System.out.println("rating : " + bangle.rating);
	System.out.println("isLightWeight : " + bangle.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle.countryOfOrigin);
	System.out.println("designType : " + bangle.designType);
	System.out.println("pattern : " + bangle.pattern);
	System.out.println("diameter : " + bangle.diameter);
	System.out.println("isStockAvailable : " + bangle.isStockAvailable);
	System.out.println("grams: " + bangle.grams);
	
	Bangle bangle1=new Bangle();
	bangle1.type = "Metal Bangle";
	bangle1.material = "Alloy";
	bangle1.price = 499;
	bangle1.quantity = 2;
	bangle1.brand = "Zaveri Pearls";
	bangle1.colour = "Gold";
	bangle1.isMultipleColour = false;
	bangle1.isQualityGood = true;
	bangle1.size = "2.4";
	bangle1.weight = "25 grams";
	bangle1.isAntique = true;
	bangle1.warranty = "6 months";
	bangle1.manufactureDate = "15-01-2026";
	bangle1.isHandMade = false;
	bangle1.discount = "20%";
	bangle1.sellerName = "Flipkart Seller";
	bangle1.numberOfStones = 12;
	bangle1.customerReview = "Elegant gold finish bangles";
	bangle1.rating = 5;
	bangle1.isLightWeight = false;
	bangle1.countryOfOrigin = "India";
	bangle1.designType = "Ethnic";
	bangle1.pattern = "Stone Work";
	bangle1.diameter = 6;
	bangle1.isStockAvailable = true;
	bangle1.grams = 25;
	System.out.println("after init instance variable");
    System.out.println("type : " + bangle1.type);
	System.out.println("material : " + bangle1.material);
	System.out.println("price  : " + bangle1.price);
	System.out.println("quantity: " + bangle1.quantity);
	System.out.println("brand: " + bangle1.brand);
	System.out.println("colour: " + bangle1.colour);
	System.out.println("isMultipleColour : " + bangle1.isMultipleColour);
	System.out.println("isQualityGood: " + bangle1.isQualityGood);
	System.out.println("size: " + bangle1.size);
	System.out.println("weight: " + bangle1.weight);
	System.out.println("isAntique: " + bangle1.isAntique);
	System.out.println("warranty: " + bangle1.warranty);
	System.out.println("manufactureDate: " + bangle1.manufactureDate);
	System.out.println("isHandMade : " + bangle1.isHandMade);
	System.out.println("discount : " + bangle1.discount);
	System.out.println("sellerName : " + bangle1.sellerName);
	System.out.println("numberOfStones : " + bangle1.numberOfStones);
	System.out.println("customerReview : " + bangle1.customerReview);
	System.out.println("rating : " + bangle1.rating);
	System.out.println("isLightWeight : " + bangle1.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle1.countryOfOrigin);
	System.out.println("designType : " + bangle1.designType);
	System.out.println("pattern : " + bangle1.pattern);
	System.out.println("diameter : " + bangle1.diameter);
	System.out.println("isStockAvailable : " + bangle1.isStockAvailable);
	System.out.println("grams: " + bangle1.grams);
	
	Bangle bangle2=new Bangle();
	bangle2.type = "Plastic Bangle";
	bangle2.material = "Plastic";
	bangle2.price = 199;
	bangle2.quantity = 6;
	bangle2.brand = "Fashion Diva";
	bangle2.colour = "Blue";
	bangle2.isMultipleColour = true;
	bangle2.isQualityGood = true;
	bangle2.size = "2.8";
	bangle2.weight = "15 grams";
	bangle2.isAntique = false;
	bangle2.warranty = "2 months";
	bangle2.manufactureDate = "05-02-2026";
	bangle2.isHandMade = false;
	bangle2.discount = "10%";
	bangle2.sellerName = "Meesho Seller";
	bangle2.numberOfStones = 5;
	bangle2.customerReview = "Nice casual bangles";
	bangle2.rating = 4;
	bangle2.isLightWeight = true;
	bangle2.countryOfOrigin = "India";
	bangle2.designType = "Casual";
	bangle2.pattern = "Striped";
	bangle2.diameter = 7;
	bangle2.isStockAvailable = true;
	bangle2.grams = 15;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle2.type);
	System.out.println("material : " + bangle2.material);
	System.out.println("price  : " + bangle2.price);
	System.out.println("quantity: " + bangle2.quantity);
	System.out.println("brand: " + bangle2.brand);
	System.out.println("colour: " + bangle2.colour);
	System.out.println("isMultipleColour : " + bangle2.isMultipleColour);
	System.out.println("isQualityGood: " + bangle2.isQualityGood);
	System.out.println("size: " + bangle2.size);
	System.out.println("weight: " + bangle2.weight);
	System.out.println("isAntique: " + bangle2.isAntique);
	System.out.println("warranty: " + bangle2.warranty);
	System.out.println("manufactureDate: " + bangle2.manufactureDate);
	System.out.println("isHandMade : " + bangle2.isHandMade);
	System.out.println("discount : " + bangle2.discount);
	System.out.println("sellerName : " + bangle2.sellerName);
	System.out.println("numberOfStones : " + bangle2.numberOfStones);
	System.out.println("customerReview : " + bangle2.customerReview);
	System.out.println("rating : " + bangle2.rating);
	System.out.println("isLightWeight : " + bangle2.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle2.countryOfOrigin);
	System.out.println("designType : " + bangle2.designType);
	System.out.println("pattern : " + bangle2.pattern);
	System.out.println("diameter : " + bangle2.diameter);
	System.out.println("isStockAvailable : " + bangle2.isStockAvailable);
	System.out.println("grams: " + bangle2.grams);
	
	Bangle bangle3=new Bangle();
	bangle3.type = "Wooden Bangle";
	bangle3.material = "Wood";
	bangle3.price = 349;
	bangle3.quantity = 3;
	bangle3.brand = "Craft Villa";
	bangle3.colour = "Brown";
	bangle3.isMultipleColour = false;
	bangle3.isQualityGood = true;
	bangle3.size = "2.6";
	bangle3.weight = "18 grams";
	bangle3.isAntique = false;
	bangle3.warranty = "4 months";
	bangle3.manufactureDate = "20-01-2026";
	bangle3.isHandMade = true;
	bangle3.discount = "12%";
	bangle3.sellerName = "Amazon Crafts Seller";
	bangle3.numberOfStones = 3;
	bangle3.customerReview = "Beautiful wooden bangles";
	bangle3.rating = 4;
	bangle3.isLightWeight = true;
	bangle3.countryOfOrigin = "India";
	bangle3.designType = "Ethnic";
	bangle3.pattern = "Carved";
	bangle3.diameter = 6;
	bangle3.isStockAvailable = true;
	bangle3.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle3.type);
	System.out.println("material : " + bangle3.material);
	System.out.println("price  : " + bangle3.price);
	System.out.println("quantity: " + bangle3.quantity);
	System.out.println("brand: " + bangle3.brand);
	System.out.println("colour: " + bangle3.colour);
	System.out.println("isMultipleColour : " + bangle3.isMultipleColour);
	System.out.println("isQualityGood: " + bangle3.isQualityGood);
	System.out.println("size: " + bangle3.size);
	System.out.println("weight: " + bangle3.weight);
	System.out.println("isAntique: " + bangle3.isAntique);
	System.out.println("warranty: " + bangle3.warranty);
	System.out.println("manufactureDate: " + bangle3.manufactureDate);
	System.out.println("isHandMade : " + bangle3.isHandMade);
	System.out.println("discount : " + bangle3.discount);
	System.out.println("sellerName : " + bangle3.sellerName);
	System.out.println("numberOfStones : " + bangle3.numberOfStones);
	System.out.println("customerReview : " + bangle3.customerReview);
	System.out.println("rating : " + bangle3.rating);
	System.out.println("isLightWeight : " + bangle3.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle3.countryOfOrigin);
	System.out.println("designType : " + bangle3.designType);
	System.out.println("pattern : " + bangle3.pattern);
	System.out.println("diameter : " + bangle3.diameter);
	System.out.println("isStockAvailable : " + bangle3.isStockAvailable);
	System.out.println("grams: " + bangle3.grams);
		
	Bangle bangle4=new Bangle();
	bangle4.type = "Silk Thread Bangle";
	bangle4.material = "Silk";
	bangle4.price = 399;
	bangle4.quantity = 2;
	bangle4.brand = "Anuradha Art";
	bangle4.colour = "Green";
	bangle4.isMultipleColour = true;
	bangle4.isQualityGood = true;
	bangle4.size = "2.4";
	bangle4.weight = "16 grams";
	bangle4.isAntique = false;
	bangle4.warranty = "3 months";
	bangle4.manufactureDate = "25-01-2026";
	bangle4.isHandMade = true;
	bangle4.discount = "18%";
	bangle4.sellerName = "Flipkart Seller";
	bangle4.numberOfStones = 8;
	bangle4.customerReview = "Very stylish silk bangles";
	bangle4.rating = 4;
	bangle4.isLightWeight = true;
	bangle4.countryOfOrigin = "India";
	bangle4.designType = "Traditional";
	bangle4.pattern = "Stone Work";
	bangle4.diameter = 6;
	bangle4.isStockAvailable = true;
	bangle4.grams = 16;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle4.type);
	System.out.println("material : " + bangle4.material);
	System.out.println("price  : " + bangle4.price);
	System.out.println("quantity: " + bangle4.quantity);
	System.out.println("brand: " + bangle4.brand);
	System.out.println("colour: " + bangle4.colour);
	System.out.println("isMultipleColour : " + bangle4.isMultipleColour);
	System.out.println("isQualityGood: " + bangle4.isQualityGood);
	System.out.println("size: " + bangle4.size);
	System.out.println("weight: " + bangle4.weight);
	System.out.println("isAntique: " + bangle4.isAntique);
	System.out.println("warranty: " + bangle4.warranty);
	System.out.println("manufactureDate: " + bangle4.manufactureDate);
	System.out.println("isHandMade : " + bangle4.isHandMade);
	System.out.println("discount : " + bangle4.discount);
	System.out.println("sellerName : " + bangle4.sellerName);
	System.out.println("numberOfStones : " + bangle4.numberOfStones);
	System.out.println("customerReview : " + bangle4.customerReview);
	System.out.println("rating : " + bangle4.rating);
	System.out.println("isLightWeight : " + bangle4.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle4.countryOfOrigin);
	System.out.println("designType : " + bangle4.designType);
	System.out.println("pattern : " + bangle4.pattern);
	System.out.println("diameter : " + bangle4.diameter);
	System.out.println("isStockAvailable : " + bangle4.isStockAvailable);
	System.out.println("grams: " + bangle4.grams);
	
	Bangle bangle5=new Bangle();
	bangle5.type = "Bridal Bangle";
	bangle5.material = "Metal";
	bangle5.price = 1299;
	bangle5.quantity = 1;
	bangle5.brand = "Zaveri Pearls";
	bangle5.colour = "Maroon";
	bangle5.isMultipleColour = true;
	bangle5.isQualityGood = true;
	bangle5.size = "2.6";
	bangle5.weight = "30 grams";
	bangle5.isAntique = true;
	bangle5.warranty = "6 months";
	bangle5.manufactureDate = "12-01-2026";
	bangle5.isHandMade = true;
	bangle5.discount = "25%";
	bangle5.sellerName = "Amazon Fashion Seller";
	bangle5.numberOfStones = 20;
	bangle5.customerReview = "Perfect for weddings";
	bangle5.rating = 5;
	bangle5.isLightWeight = false;
	bangle5.countryOfOrigin = "India";
	bangle5.designType = "Bridal";
	bangle5.pattern = "Kundan";
	bangle5.diameter = 7;
	bangle5.isStockAvailable = true;
	bangle5.grams = 30;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle5.type);
	System.out.println("material : " + bangle5.material);
	System.out.println("price  : " + bangle5.price);
	System.out.println("quantity: " + bangle5.quantity);
	System.out.println("brand: " + bangle5.brand);
	System.out.println("colour: " + bangle5.colour);
	System.out.println("isMultipleColour : " + bangle5.isMultipleColour);
	System.out.println("isQualityGood: " + bangle5.isQualityGood);
	System.out.println("size: " + bangle5.size);
	System.out.println("weight: " + bangle5.weight);
	System.out.println("isAntique: " + bangle5.isAntique);
	System.out.println("warranty: " + bangle5.warranty);
	System.out.println("manufactureDate: " + bangle5.manufactureDate);
	System.out.println("isHandMade : " + bangle5.isHandMade);
	System.out.println("discount : " + bangle5.discount);
	System.out.println("sellerName : " + bangle5.sellerName);
	System.out.println("numberOfStones : " + bangle5.numberOfStones);
	System.out.println("customerReview : " + bangle5.customerReview);
	System.out.println("rating : " + bangle5.rating);
	System.out.println("isLightWeight : " + bangle5.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle5.countryOfOrigin);
	System.out.println("designType : " + bangle5.designType);
	System.out.println("pattern : " + bangle5.pattern);
	System.out.println("diameter : " + bangle5.diameter);
	System.out.println("isStockAvailable : " + bangle5.isStockAvailable);
	System.out.println("grams: " + bangle5.grams);
	
	Bangle bangle6=new Bangle();
	bangle6.type = "Gold Plated Bangle";
	bangle6.material = "Alloy";
	bangle6.price = 899;
	bangle6.quantity = 2;
	bangle6.brand = "Voylla";
	bangle6.colour = "Gold";
	bangle6.isMultipleColour = false;
	bangle6.isQualityGood = true;
	bangle6.size = "2.8";
	bangle6.weight = "22 grams";
	bangle6.isAntique = false;
	bangle6.warranty = "5 months";
	bangle6.manufactureDate = "18-02-2026";
	bangle6.isHandMade = false;
	bangle6.discount = "20%";
	bangle6.sellerName = "Myntra Seller";
	bangle6.numberOfStones = 6;
	bangle6.customerReview = "Elegant gold finish";
	bangle6.rating = 4;
	bangle6.isLightWeight = false;
	bangle6.countryOfOrigin = "India";
	bangle6.designType = "Modern";
	bangle6.pattern = "Plain";
	bangle6.diameter = 6;
	bangle6.isStockAvailable = true;
	bangle6.grams = 22;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle6.type);
	System.out.println("material : " + bangle6.material);
	System.out.println("price  : " + bangle6.price);
	System.out.println("quantity: " + bangle6.quantity);
	System.out.println("brand: " + bangle6.brand);
	System.out.println("colour: " + bangle6.colour);
	System.out.println("isMultipleColour : " + bangle6.isMultipleColour);
	System.out.println("isQualityGood: " + bangle6.isQualityGood);
	System.out.println("size: " + bangle6.size);
	System.out.println("weight: " + bangle6.weight);
	System.out.println("isAntique: " + bangle6.isAntique);
	System.out.println("warranty: " + bangle6.warranty);
	System.out.println("manufactureDate: " + bangle6.manufactureDate);
	System.out.println("isHandMade : " + bangle6.isHandMade);
	System.out.println("discount : " + bangle6.discount);
	System.out.println("sellerName : " + bangle6.sellerName);
	System.out.println("numberOfStones : " + bangle6.numberOfStones);
	System.out.println("customerReview : " + bangle6.customerReview);
	System.out.println("rating : " + bangle6.rating);
	System.out.println("isLightWeight : " + bangle6.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle6.countryOfOrigin);
	System.out.println("designType : " + bangle6.designType);
	System.out.println("pattern : " + bangle6.pattern);
	System.out.println("diameter : " + bangle6.diameter);
	System.out.println("isStockAvailable : " + bangle6.isStockAvailable);
	System.out.println("grams: " + bangle6.grams);
			
	Bangle bangle7=new Bangle();		
	bangle7.type = "Stone Bangle";
	bangle7.material = "Metal";
	bangle7.price = 650;
	bangle7.quantity = 2;
	bangle7.brand = "Sukkhi";
	bangle7.colour = "Pink";
	bangle7.isMultipleColour = true;
	bangle7.isQualityGood = true;
	bangle7.size = "2.6";
	bangle7.weight = "19 grams";
	bangle7.isAntique = false;
	bangle7.warranty = "4 months";
	bangle7.manufactureDate = "10-02-2026";
	bangle7.isHandMade = false;
	bangle7.discount = "15%";
	bangle7.sellerName = "Flipkart Seller";
	bangle7.numberOfStones = 9;
	bangle7.customerReview = "Nice stone bangles";
	bangle7.rating = 4;
	bangle7.isLightWeight = true;
	bangle7.countryOfOrigin = "India";
	bangle7.designType = "Modern";
	bangle7.pattern = "Stone Work";
	bangle7.diameter = 6;
	bangle7.isStockAvailable = true;
	bangle7.grams = 19;
    System.out.println("after init instance variable");
	System.out.println("type : " + bangle7.type);
	System.out.println("material : " + bangle7.material);
	System.out.println("price  : " + bangle7.price);
	System.out.println("quantity: " + bangle7.quantity);
	System.out.println("brand: " + bangle7.brand);
	System.out.println("colour: " + bangle7.colour);
	System.out.println("isMultipleColour : " + bangle7.isMultipleColour);
	System.out.println("isQualityGood: " + bangle7.isQualityGood);
	System.out.println("size: " + bangle7.size);
	System.out.println("weight: " + bangle7.weight);
	System.out.println("isAntique: " + bangle7.isAntique);
	System.out.println("warranty: " + bangle7.warranty);
	System.out.println("manufactureDate: " + bangle7.manufactureDate);
	System.out.println("isHandMade : " + bangle7.isHandMade);
	System.out.println("discount : " + bangle7.discount);
	System.out.println("sellerName : " + bangle7.sellerName);
	System.out.println("numberOfStones : " + bangle7.numberOfStones);
	System.out.println("customerReview : " + bangle7.customerReview);
	System.out.println("rating : " + bangle7.rating);
	System.out.println("isLightWeight : " + bangle7.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle7.countryOfOrigin);
	System.out.println("designType : " + bangle7.designType);
	System.out.println("pattern : " + bangle7.pattern);
	System.out.println("diameter : " + bangle7.diameter);
	System.out.println("isStockAvailable : " + bangle7.isStockAvailable);
	System.out.println("grams: " + bangle7.grams);
	
	Bangle bangle8=new Bangle();
	bangle8.type = "Pearl Bangle";
	bangle8.material = "Pearl";
	bangle8.price = 720;
	bangle8.quantity = 1;
	bangle8.brand = "Voylla";
	bangle8.colour = "White";
	bangle8.isMultipleColour = false;
	bangle8.isQualityGood = true;
	bangle8.size = "2.4";
	bangle8.weight = "17 grams";
	bangle8.isAntique = false;
	bangle8.warranty = "5 months";
	bangle8.manufactureDate = "15-02-2026";
	bangle8.isHandMade = true;
	bangle8.discount = "18%";
	bangle8.sellerName = "Amazon Seller";
	bangle8.numberOfStones = 7;
	bangle8.customerReview = "Elegant pearl bangles";
	bangle8.rating = 5;
	bangle8.isLightWeight = true;
	bangle8.countryOfOrigin = "India";
	bangle8.designType = "Classic";
	bangle8.pattern = "Pearl Design";
	bangle8.diameter = 6;
	bangle8.isStockAvailable = true;
	bangle8.grams = 17;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle8.type);
	System.out.println("material : " + bangle8.material);
	System.out.println("price  : " + bangle8.price);
	System.out.println("quantity: " + bangle8.quantity);
	System.out.println("brand: " + bangle8.brand);
	System.out.println("colour: " + bangle8.colour);
	System.out.println("isMultipleColour : " + bangle8.isMultipleColour);
	System.out.println("isQualityGood: " + bangle8.isQualityGood);
	System.out.println("size: " + bangle8.size);
	System.out.println("weight: " + bangle8.weight);
	System.out.println("isAntique: " + bangle8.isAntique);
	System.out.println("warranty: " + bangle8.warranty);
	System.out.println("manufactureDate: " + bangle8.manufactureDate);
	System.out.println("isHandMade : " + bangle8.isHandMade);
	System.out.println("discount : " + bangle8.discount);
	System.out.println("sellerName : " + bangle8.sellerName);
	System.out.println("numberOfStones : " + bangle8.numberOfStones);
	System.out.println("customerReview : " + bangle8.customerReview);
	System.out.println("rating : " + bangle8.rating);
	System.out.println("isLightWeight : " + bangle8.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle8.countryOfOrigin);
	System.out.println("designType : " + bangle8.designType);
	System.out.println("pattern : " + bangle8.pattern);
	System.out.println("diameter : " + bangle8.diameter);
	System.out.println("isStockAvailable : " + bangle8.isStockAvailable);
	System.out.println("grams: " + bangle8.grams);
		
	
	Bangle bangle9=new Bangle();
	bangle9.type = "Crystal Bangle";
	bangle9.material = "Crystal";
	bangle9.price = 850;
	bangle9.quantity = 2;
	bangle9.brand = "Zaveri Pearls";
	bangle9.colour = "Purple";
	bangle9.isMultipleColour = true;
	bangle9.isQualityGood = true;
	bangle9.size = "2.8";
	bangle9.weight = "21 grams";
	bangle9.isAntique = false;
	bangle9.warranty = "6 months";
	bangle9.manufactureDate = "05-03-2026";
	bangle9.isHandMade = false;
	bangle9.discount = "20%";
	bangle9.sellerName = "Myntra Seller";
	bangle9.numberOfStones = 11;
	bangle9.customerReview = "Shiny crystal bangles";
	bangle9.rating = 4;
	bangle9.isLightWeight = false;
	bangle9.countryOfOrigin = "India";
	bangle9.designType = "Party";
	bangle9.pattern = "Crystal Work";
	bangle9.diameter = 7;
	bangle9.isStockAvailable = true;
	bangle9.grams = 21;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle9.type);
	System.out.println("material : " + bangle9.material);
	System.out.println("price  : " + bangle9.price);
	System.out.println("quantity: " + bangle9.quantity);
	System.out.println("brand: " + bangle9.brand);
	System.out.println("colour: " + bangle9.colour);
	System.out.println("isMultipleColour : " + bangle9.isMultipleColour);
	System.out.println("isQualityGood: " + bangle9.isQualityGood);
	System.out.println("size: " + bangle9.size);
	System.out.println("weight: " + bangle9.weight);
	System.out.println("isAntique: " + bangle9.isAntique);
	System.out.println("warranty: " + bangle9.warranty);
	System.out.println("manufactureDate: " + bangle9.manufactureDate);
	System.out.println("isHandMade : " + bangle9.isHandMade);
	System.out.println("discount : " + bangle9.discount);
	System.out.println("sellerName : " + bangle9.sellerName);
	System.out.println("numberOfStones : " + bangle9.numberOfStones);
	System.out.println("customerReview : " + bangle9.customerReview);
	System.out.println("rating : " + bangle9.rating);
	System.out.println("isLightWeight : " + bangle9.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle9.countryOfOrigin);
	System.out.println("designType : " + bangle9.designType);
	System.out.println("pattern : " + bangle9.pattern);
	System.out.println("diameter : " + bangle9.diameter);
	System.out.println("isStockAvailable : " + bangle9.isStockAvailable);
	System.out.println("grams: " + bangle9.grams);
	
	Bangle bangle10=new Bangle();
	bangle10.type = "Diamond Bangle";
	bangle10.material = "Diamond";
	bangle10.price = 2500;
	bangle10.quantity = 1;
	bangle10.brand = "Tanishq";
	bangle10.colour = "Silver";
	bangle10.isMultipleColour = false;
	bangle10.isQualityGood = true;
	bangle10.size = "2.6";
	bangle10.weight = "28 grams";
	bangle10.isAntique = true;
	bangle10.warranty = "1 year";
	bangle10.manufactureDate = "08-03-2026";
	bangle10.isHandMade = false;
	bangle10.discount = "10%";
	bangle10.sellerName = "Tanishq Store";
	bangle10.numberOfStones = 15;
	bangle10.customerReview = "Premium diamond bangles";
	bangle10.rating = 5;
	bangle10.isLightWeight = false;
	bangle10.countryOfOrigin = "India";
	bangle10.designType = "Luxury";
	bangle10.pattern = "Diamond Work";
	bangle10.diameter = 7;
	bangle10.isStockAvailable = true;
	bangle10.grams = 28;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle10.type);
	System.out.println("material : " + bangle10.material);
	System.out.println("price  : " + bangle10.price);
	System.out.println("quantity: " + bangle10.quantity);
	System.out.println("brand: " + bangle10.brand);
	System.out.println("colour: " + bangle10.colour);
	System.out.println("isMultipleColour : " + bangle10.isMultipleColour);
	System.out.println("isQualityGood: " + bangle10.isQualityGood);
	System.out.println("size: " + bangle10.size);
	System.out.println("weight: " + bangle10.weight);
	System.out.println("isAntique: " + bangle10.isAntique);
	System.out.println("warranty: " + bangle10.warranty);
	System.out.println("manufactureDate: " + bangle10.manufactureDate);
	System.out.println("isHandMade : " + bangle10.isHandMade);
	System.out.println("discount : " + bangle10.discount);
	System.out.println("sellerName : " + bangle10.sellerName);
	System.out.println("numberOfStones : " + bangle10.numberOfStones);
	System.out.println("customerReview : " + bangle10.customerReview);
	System.out.println("rating : " + bangle10.rating);
	System.out.println("isLightWeight : " + bangle10.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle10.countryOfOrigin);
	System.out.println("designType : " + bangle10.designType);
	System.out.println("pattern : " + bangle10.pattern);
	System.out.println("diameter : " + bangle10.diameter);
	System.out.println("isStockAvailable : " + bangle10.isStockAvailable);
	System.out.println("grams: " + bangle10.grams);
	
	Bangle bangle11=new Bangle();
	bangle11.type = "Gold Bangle";
	bangle11.material = "Gold";
	bangle11.price = 8500;
	bangle11.quantity = 2;
	bangle11.brand = "ZaveriPearls";
	bangle11.colour = "Golden";
	bangle11.isMultipleColour = false;
	bangle11.isQualityGood = true;
	bangle11.size = "2.4";
	bangle11.weight = "20 grams";
	bangle11.isAntique = false;
	bangle11.warranty = "1 year";
	bangle11.manufactureDate = "10-01-2026";
	bangle11.isHandMade = true;
	bangle11.discount = "10%";
	bangle11.sellerName = "Tanishq";
	bangle11.numberOfStones = 10;
	bangle11.customerReview = "Very Beautiful";
	bangle11.rating = 5;
	bangle11.isLightWeight = true;
	bangle11.countryOfOrigin = "India";
	bangle11.designType = "Traditional";
	bangle11.pattern = "Floral";
	bangle11.diameter = 6;
	bangle11.isStockAvailable = true;
	bangle11.grams = 20;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle11.type);
	System.out.println("material : " + bangle11.material);
	System.out.println("price  : " + bangle11.price);
	System.out.println("quantity: " + bangle11.quantity);
	System.out.println("brand: " + bangle11.brand);
	System.out.println("colour: " + bangle11.colour);
	System.out.println("isMultipleColour : " + bangle11.isMultipleColour);
	System.out.println("isQualityGood: " + bangle11.isQualityGood);
	System.out.println("size: " + bangle11.size);
	System.out.println("weight: " + bangle11.weight);
	System.out.println("isAntique: " + bangle11.isAntique);
	System.out.println("warranty: " + bangle11.warranty);
	System.out.println("manufactureDate: " + bangle11.manufactureDate);
	System.out.println("isHandMade : " + bangle11.isHandMade);
	System.out.println("discount : " + bangle11.discount);
	System.out.println("sellerName : " + bangle11.sellerName);
	System.out.println("numberOfStones : " + bangle11.numberOfStones);
	System.out.println("customerReview : " + bangle11.customerReview);
	System.out.println("rating : " + bangle11.rating);
	System.out.println("isLightWeight : " + bangle11.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle11.countryOfOrigin);
	System.out.println("designType : " + bangle11.designType);
	System.out.println("pattern : " + bangle11.pattern);
	System.out.println("diameter : " + bangle11.diameter);
	System.out.println("isStockAvailable : " + bangle11.isStockAvailable);
	System.out.println("grams: " + bangle11.grams);
	
	
	Bangle bangle12=new Bangle();
	bangle12.type = "Silver Bangle";
	bangle12.material = "Silver";
	bangle12.price = 4200;
	bangle12.quantity = 1;
	bangle12.brand = "MalabarGold";
	bangle12.colour = "Silver";
	bangle12.isMultipleColour = false;
	bangle12.isQualityGood = true;
	bangle12.size = "2.6";
	bangle12.weight = "18 grams";
	bangle12.isAntique = true;
	bangle12.warranty = "6 months";
	bangle12.manufactureDate = "15-02-2026";
	bangle12.isHandMade = false;
	bangle12.discount = "5%";
	bangle12.sellerName = "MalabarGold Store";
	bangle12.numberOfStones = 8;
	bangle12.customerReview = "Nice traditional design";
	bangle12.rating = 4;
	bangle12.isLightWeight = true;
	bangle12.countryOfOrigin = "India";
	bangle12.designType = "Classic";
	bangle12.pattern = "Plain";
	bangle12.diameter = 6;
	bangle12.isStockAvailable = true;
	bangle12.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle12.type);
	System.out.println("material : " + bangle12.material);
	System.out.println("price  : " + bangle12.price);
	System.out.println("quantity: " + bangle12.quantity);
	System.out.println("brand: " + bangle12.brand);
	System.out.println("colour: " + bangle12.colour);
	System.out.println("isMultipleColour : " + bangle12.isMultipleColour);
	System.out.println("isQualityGood: " + bangle12.isQualityGood);
	System.out.println("size: " + bangle12.size);
	System.out.println("weight: " + bangle12.weight);
	System.out.println("isAntique: " + bangle12.isAntique);
	System.out.println("warranty: " + bangle12.warranty);
	System.out.println("manufactureDate: " + bangle12.manufactureDate);
	System.out.println("isHandMade : " + bangle12.isHandMade);
	System.out.println("discount : " + bangle12.discount);
	System.out.println("sellerName : " + bangle12.sellerName);
	System.out.println("numberOfStones : " + bangle12.numberOfStones);
	System.out.println("customerReview : " + bangle12.customerReview);
	System.out.println("rating : " + bangle12.rating);
	System.out.println("isLightWeight : " + bangle12.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle12.countryOfOrigin);
	System.out.println("designType : " + bangle12.designType);
	System.out.println("pattern : " + bangle12.pattern);
	System.out.println("diameter : " + bangle12.diameter);
	System.out.println("isStockAvailable : " + bangle12.isStockAvailable);
	System.out.println("grams: " + bangle12.grams);
	

	Bangle bangle13 = new Bangle();
	bangle13.type = "Rose Gold Bangle";
	bangle13.material = "Rose Gold";
	bangle13.price = 12000;
	bangle13.quantity = 2;
	bangle13.brand = "Tanishq";
	bangle13.colour = "Rose Gold";
	bangle13.isMultipleColour = false;
	bangle13.isQualityGood = true;
	bangle13.size = "2.8";
	bangle13.weight = "25 grams";
	bangle13.isAntique = false;
	bangle13.warranty = "1 year";
	bangle13.manufactureDate = "20-01-2026";
	bangle13.isHandMade = true;
	bangle13.discount = "12%";
	bangle13.sellerName = "Reliance Jewels";
	bangle13.numberOfStones = 12;
	bangle13.customerReview = "Elegant designer bangle";
	bangle13.rating = 5;
	bangle13.isLightWeight = false;
	bangle13.countryOfOrigin = "India";
	bangle13.designType = "Designer";
	bangle13.pattern = "Leaf Design";
	bangle13.diameter = 7;
	bangle13.isStockAvailable = true;
	bangle13.grams = 25;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle13.type);
	System.out.println("material : " + bangle13.material);
	System.out.println("price  : " + bangle13.price);
	System.out.println("quantity: " + bangle13.quantity);
	System.out.println("brand: " + bangle13.brand);
	System.out.println("colour: " + bangle13.colour);
	System.out.println("isMultipleColour : " + bangle13.isMultipleColour);
	System.out.println("isQualityGood: " + bangle13.isQualityGood);
	System.out.println("size: " + bangle13.size);
	System.out.println("weight: " + bangle13.weight);
	System.out.println("isAntique: " + bangle13.isAntique);
	System.out.println("warranty: " + bangle13.warranty);
	System.out.println("manufactureDate: " + bangle13.manufactureDate);
	System.out.println("isHandMade : " + bangle13.isHandMade);
	System.out.println("discount : " + bangle13.discount);
	System.out.println("sellerName : " + bangle13.sellerName);
	System.out.println("numberOfStones : " + bangle13.numberOfStones);
	System.out.println("customerReview : " + bangle13.customerReview);
	System.out.println("rating : " + bangle13.rating);
	System.out.println("isLightWeight : " + bangle13.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle13.countryOfOrigin);
	System.out.println("designType : " + bangle13.designType);
	System.out.println("pattern : " + bangle13.pattern);
	System.out.println("diameter : " + bangle13.diameter);
	System.out.println("isStockAvailable : " + bangle13.isStockAvailable);
	System.out.println("grams: " + bangle13.grams);
		
	Bangle bangle14=new Bangle();
	bangle14.type = "Temple Gold Bangle";
	bangle14.material = "Gold";
	bangle14.price = 9800;
	bangle14.quantity = 2;
	bangle14.brand = "Kalyan Jewellers";
	bangle14.colour = "Yellow Gold";
	bangle14.isMultipleColour = false;
	bangle14.isQualityGood = true;
	bangle14.size = "2.6";
	bangle14.weight = "22 grams";
	bangle14.isAntique = true;
	bangle14.warranty = "1 year";
	bangle14.manufactureDate = "05-02-2026";
	bangle14.isHandMade = true;
	bangle14.discount = "8%";
	bangle14.sellerName = "MalabarGold Store";
	bangle14.numberOfStones = 9;
	bangle14.customerReview = "Beautiful temple design";
	bangle14.rating = 4;
	bangle14.isLightWeight = false;
	bangle14.countryOfOrigin = "India";
	bangle14.designType = "Traditional";
	bangle14.pattern = "Temple Pattern";
	bangle14.diameter = 6;
	bangle14.isStockAvailable = true;
	bangle14.grams = 22;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle14.type);
	System.out.println("material : " + bangle14.material);
	System.out.println("price  : " + bangle14.price);
	System.out.println("quantity: " + bangle14.quantity);
	System.out.println("brand: " + bangle14.brand);
	System.out.println("colour: " + bangle14.colour);
	System.out.println("isMultipleColour : " + bangle14.isMultipleColour);
	System.out.println("isQualityGood: " + bangle14.isQualityGood);
	System.out.println("size: " + bangle14.size);
	System.out.println("weight: " + bangle14.weight);
	System.out.println("isAntique: " + bangle14.isAntique);
	System.out.println("warranty: " + bangle14.warranty);
	System.out.println("manufactureDate: " + bangle14.manufactureDate);
	System.out.println("isHandMade : " + bangle14.isHandMade);
	System.out.println("discount : " + bangle14.discount);
	System.out.println("sellerName : " + bangle14.sellerName);
	System.out.println("numberOfStones : " + bangle14.numberOfStones);
	System.out.println("customerReview : " + bangle14.customerReview);
	System.out.println("rating : " + bangle14.rating);
	System.out.println("isLightWeight : " + bangle14.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle14.countryOfOrigin);
	System.out.println("designType : " + bangle14.designType);
	System.out.println("pattern : " + bangle14.pattern);
	System.out.println("diameter : " + bangle14.diameter);
	System.out.println("isStockAvailable : " + bangle14.isStockAvailable);
	System.out.println("grams: " + bangle14.grams);
	
	
	Bangle bangle15 = new Bangle();
	bangle15.type = "Designer Silver Bangle";
	bangle15.material = "Silver";
	bangle15.price = 3500;
	bangle15.quantity = 1;
	bangle15.brand = "Reliance Jewels";
	bangle15.colour = "White Silver";
	bangle15.isMultipleColour = false;
	bangle15.isQualityGood = true;
	bangle15.size = "2.4";
	bangle15.weight = "16 grams";
	bangle15.isAntique = false;
	bangle15.warranty = "6 months";
	bangle15.manufactureDate = "12-01-2026";
	bangle15.isHandMade = false;
	bangle15.discount = "5%";
	bangle15.sellerName = "Tanishq Store";
	bangle15.numberOfStones = 6;
	bangle15.customerReview = "Nice modern design";
	bangle15.rating = 4;
	bangle15.isLightWeight = true;
	bangle15.countryOfOrigin = "India";
	bangle15.designType = "Modern";
	bangle15.pattern = "Diamond Cut";
	bangle15.diameter = 6;
	bangle15.isStockAvailable = true;
	bangle15.grams = 16;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle15.type);
	System.out.println("material : " + bangle15.material);
	System.out.println("price  : " + bangle15.price);
	System.out.println("quantity: " + bangle15.quantity);
	System.out.println("brand: " + bangle15.brand);
	System.out.println("colour: " + bangle15.colour);
	System.out.println("isMultipleColour : " + bangle15.isMultipleColour);
	System.out.println("isQualityGood: " + bangle15.isQualityGood);
	System.out.println("size: " + bangle15.size);
	System.out.println("weight: " + bangle15.weight);
	System.out.println("isAntique: " + bangle15.isAntique);
	System.out.println("warranty: " + bangle15.warranty);
	System.out.println("manufactureDate: " + bangle15.manufactureDate);
	System.out.println("isHandMade : " + bangle15.isHandMade);
	System.out.println("discount : " + bangle15.discount);
	System.out.println("sellerName : " + bangle15.sellerName);
	System.out.println("numberOfStones : " + bangle15.numberOfStones);
	System.out.println("customerReview : " + bangle15.customerReview);
	System.out.println("rating : " + bangle15.rating);
	System.out.println("isLightWeight : " + bangle15.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle15.countryOfOrigin);
	System.out.println("designType : " + bangle15.designType);
	System.out.println("pattern : " + bangle15.pattern);
	System.out.println("diameter : " + bangle15.diameter);
	System.out.println("isStockAvailable : " + bangle15.isStockAvailable);
	System.out.println("grams: " + bangle15.grams);
	
	
	Bangle bangle16 = new Bangle();
	bangle16.type = "Gold Designer Bangle";
	bangle16.material = "Gold";
	bangle16.price = 10500;
	bangle16.quantity = 2;
	bangle16.brand = "ZaveriPearls";
	bangle16.colour = "Golden";
	bangle16.isMultipleColour = false;
	bangle16.isQualityGood = true;
	bangle16.size = "2.6";
	bangle16.weight = "24 grams";
	bangle16.isAntique = false;
	bangle16.warranty = "1 year";
	bangle16.manufactureDate = "18-02-2026";
	bangle16.isHandMade = true;
	bangle16.discount = "10%";
	bangle16.sellerName = "Kalyan Jewellers";
	bangle16.numberOfStones = 11;
	bangle16.customerReview = "Elegant gold design";
	bangle16.rating = 5;
	bangle16.isLightWeight = false;
	bangle16.countryOfOrigin = "India";
	bangle16.designType = "Traditional";
	bangle16.pattern = "Peacock Design";
	bangle16.diameter = 7;
	bangle16.isStockAvailable = true;
	bangle16.grams = 24;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle16.type);
	System.out.println("material : " + bangle16.material);
	System.out.println("price  : " + bangle16.price);
	System.out.println("quantity: " + bangle16.quantity);
	System.out.println("brand: " + bangle16.brand);
	System.out.println("colour: " + bangle16.colour);
	System.out.println("isMultipleColour : " + bangle16.isMultipleColour);
	System.out.println("isQualityGood: " + bangle16.isQualityGood);
	System.out.println("size: " + bangle16.size);
	System.out.println("weight: " + bangle16.weight);
	System.out.println("isAntique: " + bangle16.isAntique);
	System.out.println("warranty: " + bangle16.warranty);
	System.out.println("manufactureDate: " + bangle16.manufactureDate);
	System.out.println("isHandMade : " + bangle16.isHandMade);
	System.out.println("discount : " + bangle16.discount);
	System.out.println("sellerName : " + bangle16.sellerName);
	System.out.println("numberOfStones : " + bangle16.numberOfStones);
	System.out.println("customerReview : " + bangle16.customerReview);
	System.out.println("rating : " + bangle16.rating);
	System.out.println("isLightWeight : " + bangle16.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle16.countryOfOrigin);
	System.out.println("designType : " + bangle16.designType);
	System.out.println("pattern : " + bangle16.pattern);
	System.out.println("diameter : " + bangle16.diameter);
	System.out.println("isStockAvailable : " + bangle16.isStockAvailable);
	System.out.println("grams: " + bangle16.grams);
	
	
	Bangle bangle17 = new Bangle();
	bangle17.type = "Classic Silver Bangle";
	bangle17.material = "Silver";
	bangle17.price = 3900;
	bangle17.quantity = 1;
	bangle17.brand = "MalabarGold";
	bangle17.colour = "Silver";
	bangle17.isMultipleColour = false;
	bangle17.isQualityGood = true;
	bangle17.size = "2.4";
	bangle17.weight = "18 grams";
	bangle17.isAntique = true;
	bangle17.warranty = "6 months";
	bangle17.manufactureDate = "25-01-2026";
	bangle17.isHandMade = false;
	bangle17.discount = "7%";
	bangle17.sellerName = "Reliance Jewels";
	bangle17.numberOfStones = 5;
	bangle17.customerReview = "Simple and elegant";
	bangle17.rating = 4;
	bangle17.isLightWeight = true;
	bangle17.countryOfOrigin = "India";
	bangle17.designType = "Classic";
	bangle17.pattern = "Line Pattern";
	bangle17.diameter = 6;
	bangle17.isStockAvailable = true;
	bangle17.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle17.type);
	System.out.println("material : " + bangle17.material);
	System.out.println("price  : " + bangle17.price);
	System.out.println("quantity: " + bangle17.quantity);
	System.out.println("brand: " + bangle17.brand);
	System.out.println("colour: " + bangle17.colour);
	System.out.println("isMultipleColour : " + bangle17.isMultipleColour);
	System.out.println("isQualityGood: " + bangle17.isQualityGood);
	System.out.println("size: " + bangle17.size);
	System.out.println("weight: " + bangle17.weight);
	System.out.println("isAntique: " + bangle17.isAntique);
	System.out.println("warranty: " + bangle17.warranty);
	System.out.println("manufactureDate: " + bangle17.manufactureDate);
	System.out.println("isHandMade : " + bangle17.isHandMade);
	System.out.println("discount : " + bangle17.discount);
	System.out.println("sellerName : " + bangle17.sellerName);
	System.out.println("numberOfStones : " + bangle17.numberOfStones);
	System.out.println("customerReview : " + bangle17.customerReview);
	System.out.println("rating : " + bangle17.rating);
	System.out.println("isLightWeight : " + bangle17.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle17.countryOfOrigin);
	System.out.println("designType : " + bangle17.designType);
	System.out.println("pattern : " + bangle17.pattern);
	System.out.println("diameter : " + bangle17.diameter);
	System.out.println("isStockAvailable : " + bangle17.isStockAvailable);
	System.out.println("grams: " + bangle17.grams);
	

	Bangle bangle18 = new Bangle();
	bangle18.type = "Floral Gold Bangle";
	bangle18.material = "Gold";
	bangle18.price = 13200;
	bangle18.quantity = 2;
	bangle18.brand = "Tanishq";
	bangle18.colour = "Rose Gold";
	bangle18.isMultipleColour = false;
	bangle18.isQualityGood = true;
	bangle18.size = "2.8";
	bangle18.weight = "26 grams";
	bangle18.isAntique = false;
	bangle18.warranty = "1 year";
	bangle18.manufactureDate = "10-02-2026";
	bangle18.isHandMade = true;
	bangle18.discount = "9%";
	bangle18.sellerName = "ZaveriPearls";
	bangle18.numberOfStones = 14;
	bangle18.customerReview = "Beautiful floral design";
	bangle18.rating = 5;
	bangle18.isLightWeight = false;
	bangle18.countryOfOrigin = "India";
	bangle18.designType = "Designer";
	bangle18.pattern = "Floral Pattern";
	bangle18.diameter = 7;
	bangle18.isStockAvailable = true;
	bangle18.grams = 26;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle18.type);
	System.out.println("material : " + bangle18.material);
	System.out.println("price  : " + bangle18.price);
	System.out.println("quantity: " + bangle18.quantity);
	System.out.println("brand: " + bangle18.brand);
	System.out.println("colour: " + bangle18.colour);
	System.out.println("isMultipleColour : " + bangle18.isMultipleColour);
	System.out.println("isQualityGood: " + bangle18.isQualityGood);
	System.out.println("size: " + bangle18.size);
	System.out.println("weight: " + bangle18.weight);
	System.out.println("isAntique: " + bangle18.isAntique);
	System.out.println("warranty: " + bangle18.warranty);
	System.out.println("manufactureDate: " + bangle18.manufactureDate);
	System.out.println("isHandMade : " + bangle18.isHandMade);
	System.out.println("discount : " + bangle18.discount);
	System.out.println("sellerName : " + bangle18.sellerName);
	System.out.println("numberOfStones : " + bangle18.numberOfStones);
	System.out.println("customerReview : " + bangle18.customerReview);
	System.out.println("rating : " + bangle18.rating);
	System.out.println("isLightWeight : " + bangle18.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle18.countryOfOrigin);
	System.out.println("designType : " + bangle18.designType);
	System.out.println("pattern : " + bangle18.pattern);
	System.out.println("diameter : " + bangle18.diameter);
	System.out.println("isStockAvailable : " + bangle18.isStockAvailable);
	System.out.println("grams: " + bangle18.grams);
	
	
	
	Bangle bangle19 = new Bangle();
	bangle19.type = "Temple Design Gold Bangle";
	bangle19.material = "Gold";
	bangle19.price = 11500;
	bangle19.quantity = 2;
	bangle19.brand = "Reliance Jewels";
	bangle19.colour = "Yellow Gold";
	bangle19.isMultipleColour = false;
	bangle19.isQualityGood = true;
	bangle19.size = "2.6";
	bangle19.weight = "23 grams";
	bangle19.isAntique = true;
	bangle19.warranty = "1 year";
	bangle19.manufactureDate = "22-02-2026";
	bangle19.isHandMade = false;
	bangle19.discount = "11%";
	bangle19.sellerName = "Tanishq Store";
	bangle19.numberOfStones = 10;
	bangle19.customerReview = "Rich traditional temple design";
	bangle19.rating = 5;
	bangle19.isLightWeight = false;
	bangle19.countryOfOrigin = "India";
	bangle19.designType = "Traditional";
	bangle19.pattern = "Temple Pattern";
	bangle19.diameter = 7;
	bangle19.isStockAvailable = true;
	bangle19.grams = 23;
	System.out.println("after init instance variable");
	System.out.println("type : " + bangle19.type);
	System.out.println("material : " + bangle19.material);
	System.out.println("price  : " + bangle19.price);
	System.out.println("quantity: " + bangle19.quantity);
	System.out.println("brand: " + bangle19.brand);
	System.out.println("colour: " + bangle19.colour);
	System.out.println("isMultipleColour : " + bangle19.isMultipleColour);
	System.out.println("isQualityGood: " + bangle19.isQualityGood);
	System.out.println("size: " + bangle19.size);
	System.out.println("weight: " + bangle19.weight);
	System.out.println("isAntique: " + bangle19.isAntique);
	System.out.println("warranty: " + bangle19.warranty);
	System.out.println("manufactureDate: " + bangle19.manufactureDate);
	System.out.println("isHandMade : " + bangle19.isHandMade);
	System.out.println("discount : " + bangle19.discount);
	System.out.println("sellerName : " + bangle19.sellerName);
	System.out.println("numberOfStones : " + bangle19.numberOfStones);
	System.out.println("customerReview : " + bangle19.customerReview);
	System.out.println("rating : " + bangle19.rating);
	System.out.println("isLightWeight : " + bangle19.isLightWeight);
	System.out.println("countryOfOrigin : " + bangle19.countryOfOrigin);
	System.out.println("designType : " + bangle19.designType);
	System.out.println("pattern : " + bangle19.pattern);
	System.out.println("diameter : " + bangle19.diameter);
	System.out.println("isStockAvailable : " + bangle19.isStockAvailable);
	System.out.println("grams: " + bangle19.grams);
	}
}