class BouquetExecutor{

  public static void main(String [] args){
Bouquet bouq1 = new Bouquet();

bouq1.flowerType="Rose";
bouq1.colour="Red";
bouq1.numberOfFlowers=20;
bouq1.wrapperType="Paper";
bouq1.wrapperColour="Pink";
bouq1.price=500;
bouq1.isFresh=true;
bouq1.hasFragrance=true;
bouq1.occasion="Birthday";
bouq1.size="Medium";
bouq1.weight=0.5;
bouq1.brand="FlowerWorld";
bouq1.sellerName="BloomStore";
bouq1.countryOfOrigin="India";
bouq1.manufactureDate="01-02-2026";
bouq1.expiryDays=3;
bouq1.isArtificial=false;
bouq1.isEcoFriendly=true;
bouq1.hasRibbon=true;
bouq1.ribbonColour="Gold";
bouq1.rating=5;
bouq1.customerReview="Beautiful bouquet";
bouq1.packagingType="Box";
bouq1.discount=10;
bouq1.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq1.flowerType);
System.out.println("Colour: "+bouq1.colour);
System.out.println("Number Of Flowers: "+bouq1.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq1.wrapperType);
System.out.println("Wrapper Colour: "+bouq1.wrapperColour);
System.out.println("Price: "+bouq1.price);
System.out.println("Fresh: "+bouq1.isFresh);
System.out.println("Fragrance: "+bouq1.hasFragrance);
System.out.println("Occasion: "+bouq1.occasion);
System.out.println("Size: "+bouq1.size);
System.out.println("Weight: "+bouq1.weight);
System.out.println("Brand: "+bouq1.brand);
System.out.println("Seller Name: "+bouq1.sellerName);
System.out.println("Country Of Origin: "+bouq1.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq1.manufactureDate);
System.out.println("Expiry Days: "+bouq1.expiryDays);
System.out.println("Artificial: "+bouq1.isArtificial);
System.out.println("Eco Friendly: "+bouq1.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq1.hasRibbon);
System.out.println("Ribbon Colour: "+bouq1.ribbonColour);
System.out.println("Rating: "+bouq1.rating);
System.out.println("Customer Review: "+bouq1.customerReview);
System.out.println("Packaging Type: "+bouq1.packagingType);
System.out.println("Discount: "+bouq1.discount);
System.out.println("Delivery Available: "+bouq1.deliveryAvailable);

/* ----------- BOUQUET 2 ----------- */
Bouquet bouq2= new Bouquet();

bouq2.flowerType="Lily";
bouq2.colour="White";
bouq2.numberOfFlowers=15;
bouq2.wrapperType="Plastic";
bouq2.wrapperColour="Blue";
bouq2.price=450;
bouq2.isFresh=true;
bouq2.hasFragrance=true;
bouq2.occasion="Anniversary";
bouq2.size="Medium";
bouq2.weight=0.4;
bouq2.brand="FreshFlowers";
bouq2.sellerName="FlowerHub";
bouq2.countryOfOrigin="India";
bouq2.manufactureDate="02-02-2026";
bouq2.expiryDays=3;
bouq2.isArtificial=false;
bouq2.isEcoFriendly=true;
bouq2.hasRibbon=true;
bouq2.ribbonColour="Silver";
bouq2.rating=4;
bouq2.customerReview="Nice bouquet";
bouq2.packagingType="Box";
bouq2.discount=8;
bouq2.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq2.flowerType);
System.out.println("Colour: "+bouq2.colour);
System.out.println("Number Of Flowers: "+bouq2.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq2.wrapperType);
System.out.println("Wrapper Colour: "+bouq2.wrapperColour);
System.out.println("Price: "+bouq2.price);
System.out.println("Fresh: "+bouq2.isFresh);
System.out.println("Fragrance: "+bouq2.hasFragrance);
System.out.println("Occasion: "+bouq2.occasion);
System.out.println("Size: "+bouq2.size);
System.out.println("Weight: "+bouq2.weight);
System.out.println("Brand: "+bouq2.brand);
System.out.println("Seller Name: "+bouq2.sellerName);
System.out.println("Country Of Origin: "+bouq2.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq2.manufactureDate);
System.out.println("Expiry Days: "+bouq2.expiryDays);
System.out.println("Artificial: "+bouq2.isArtificial);
System.out.println("Eco Friendly: "+bouq2.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq2.hasRibbon);
System.out.println("Ribbon Colour: "+bouq2.ribbonColour);
System.out.println("Rating: "+bouq2.rating);
System.out.println("Customer Review: "+bouq2.customerReview);
System.out.println("Packaging Type: "+bouq2.packagingType);
System.out.println("Discount: "+bouq2.discount);
System.out.println("Delivery Available: "+bouq2.deliveryAvailable);


Bouquet bouq3 = new Bouquet();

bouq3.flowerType="Tulip";
bouq3.colour="Yellow";
bouq3.numberOfFlowers=18;
bouq3.wrapperType="Paper";
bouq3.wrapperColour="Green";
bouq3.price=480;
bouq3.isFresh=true;
bouq3.hasFragrance=true;
bouq3.occasion="Wedding";
bouq3.size="Large";
bouq3.weight=0.6;
bouq3.brand="RoyalBloom";
bouq3.sellerName="PetalShop";
bouq3.countryOfOrigin="Netherlands";
bouq3.manufactureDate="03-02-2026";
bouq3.expiryDays=4;
bouq3.isArtificial=false;
bouq3.isEcoFriendly=true;
bouq3.hasRibbon=true;
bouq3.ribbonColour="Red";
bouq3.rating=5;
bouq3.customerReview="Amazing flowers";
bouq3.packagingType="Box";
bouq3.discount=12;
bouq3.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq3.flowerType);
System.out.println("Colour: "+bouq3.colour);
System.out.println("Number Of Flowers: "+bouq3.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq3.wrapperType);
System.out.println("Wrapper Colour: "+bouq3.wrapperColour);
System.out.println("Price: "+bouq3.price);
System.out.println("Fresh: "+bouq3.isFresh);
System.out.println("Fragrance: "+bouq3.hasFragrance);
System.out.println("Occasion: "+bouq3.occasion);
System.out.println("Size: "+bouq3.size);
System.out.println("Weight: "+bouq3.weight);
System.out.println("Brand: "+bouq3.brand);
System.out.println("Seller Name: "+bouq3.sellerName);
System.out.println("Country Of Origin: "+bouq3.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq3.manufactureDate);
System.out.println("Expiry Days: "+bouq3.expiryDays);
System.out.println("Artificial: "+bouq3.isArtificial);
System.out.println("Eco Friendly: "+bouq3.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq3.hasRibbon);
System.out.println("Ribbon Colour: "+bouq3.ribbonColour);
System.out.println("Rating: "+bouq3.rating);
System.out.println("Customer Review: "+bouq3.customerReview);
System.out.println("Packaging Type: "+bouq3.packagingType);
System.out.println("Discount: "+bouq3.discount);
System.out.println("Delivery Available: "+bouq3.deliveryAvailable);


Bouquet bouq4 = new Bouquet();

bouq4.flowerType="Orchid";
bouq4.colour="Purple";
bouq4.numberOfFlowers=10;
bouq4.wrapperType="Paper";
bouq4.wrapperColour="White";
bouq4.price=550;
bouq4.isFresh=true;
bouq4.hasFragrance=true;
bouq4.occasion="Gift";
bouq4.size="Small";
bouq4.weight=0.3;
bouq4.brand="OrchidBloom";
bouq4.sellerName="FlowerCity";
bouq4.countryOfOrigin="Thailand";
bouq4.manufactureDate="04-02-2026";
bouq4.expiryDays=3;
bouq4.isArtificial=false;
bouq4.isEcoFriendly=true;
bouq4.hasRibbon=true;
bouq4.ribbonColour="Pink";
bouq4.rating=4;
bouq4.customerReview="Good flowers";
bouq4.packagingType="Box";
bouq4.discount=6;
bouq4.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq4.flowerType);
System.out.println("Colour: "+bouq4.colour);
System.out.println("Number Of Flowers: "+bouq4.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq4.wrapperType);
System.out.println("Wrapper Colour: "+bouq4.wrapperColour);
System.out.println("Price: "+bouq4.price);
System.out.println("Fresh: "+bouq4.isFresh);
System.out.println("Fragrance: "+bouq4.hasFragrance);
System.out.println("Occasion: "+bouq4.occasion);
System.out.println("Size: "+bouq4.size);
System.out.println("Weight: "+bouq4.weight);
System.out.println("Brand: "+bouq4.brand);
System.out.println("Seller Name: "+bouq4.sellerName);
System.out.println("Country Of Origin: "+bouq4.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq4.manufactureDate);
System.out.println("Expiry Days: "+bouq4.expiryDays);
System.out.println("Artificial: "+bouq4.isArtificial);
System.out.println("Eco Friendly: "+bouq4.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq4.hasRibbon);
System.out.println("Ribbon Colour: "+bouq4.ribbonColour);
System.out.println("Rating: "+bouq4.rating);
System.out.println("Customer Review: "+bouq4.customerReview);
System.out.println("Packaging Type: "+bouq4.packagingType);
System.out.println("Discount: "+bouq4.discount);
System.out.println("Delivery Available: "+bouq4.deliveryAvailable);

Bouquet bouq5 = new Bouquet();

bouq5.flowerType="Sunflower";
bouq5.colour="Yellow";
bouq5.numberOfFlowers=12;
bouq5.wrapperType="Paper";
bouq5.wrapperColour="Brown";
bouq5.price=400;
bouq5.isFresh=true;
bouq5.hasFragrance=false;
bouq5.occasion="Friendship";
bouq5.size="Medium";
bouq5.weight=0.5;
bouq5.brand="NatureBloom";
bouq5.sellerName="GreenShop";
bouq5.countryOfOrigin="India";
bouq5.manufactureDate="05-02-2026";
bouq5.expiryDays=4;
bouq5.isArtificial=false;
bouq5.isEcoFriendly=true;
bouq5.hasRibbon=true;
bouq5.ribbonColour="Yellow";
bouq5.rating=4;
bouq5.customerReview="Bright flowers";
bouq5.packagingType="Box";
bouq5.discount=5;
bouq5.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq5.flowerType);
System.out.println("Colour: "+bouq5.colour);
System.out.println("Number Of Flowers: "+bouq5.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq5.wrapperType);
System.out.println("Wrapper Colour: "+bouq5.wrapperColour);
System.out.println("Price: "+bouq5.price);
System.out.println("Fresh: "+bouq5.isFresh);
System.out.println("Fragrance: "+bouq5.hasFragrance);
System.out.println("Occasion: "+bouq5.occasion);
System.out.println("Size: "+bouq5.size);
System.out.println("Weight: "+bouq5.weight);
System.out.println("Brand: "+bouq5.brand);
System.out.println("Seller Name: "+bouq5.sellerName);
System.out.println("Country Of Origin: "+bouq5.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq5.manufactureDate);
System.out.println("Expiry Days: "+bouq5.expiryDays);
System.out.println("Artificial: "+bouq5.isArtificial);
System.out.println("Eco Friendly: "+bouq5.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq5.hasRibbon);
System.out.println("Ribbon Colour: "+bouq5.ribbonColour);
System.out.println("Rating: "+bouq5.rating);
System.out.println("Customer Review: "+bouq5.customerReview);
System.out.println("Packaging Type: "+bouq5.packagingType);
System.out.println("Discount: "+bouq5.discount);
System.out.println("Delivery Available: "+bouq5.deliveryAvailable);


Bouquet bouq6 = new Bouquet();

bouq6.flowerType="Carnation";
bouq6.colour="Pink";
bouq6.numberOfFlowers=16;
bouq6.wrapperType="Plastic";
bouq6.wrapperColour="White";
bouq6.price=420;
bouq6.isFresh=true;
bouq6.hasFragrance=true;
bouq6.occasion="Love";
bouq6.size="Medium";
bouq6.weight=0.45;
bouq6.brand="SweetBloom";
bouq6.sellerName="PetalWorld";
bouq6.countryOfOrigin="India";
bouq6.manufactureDate="06-02-2026";
bouq6.expiryDays=3;
bouq6.isArtificial=false;
bouq6.isEcoFriendly=true;
bouq6.hasRibbon=true;
bouq6.ribbonColour="Pink";
bouq6.rating=4;
bouq6.customerReview="Lovely bouquet";
bouq6.packagingType="Box";
bouq6.discount=7;
bouq6.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq6.flowerType);
System.out.println("Colour: "+bouq6.colour);
System.out.println("Number Of Flowers: "+bouq6.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq6.wrapperType);
System.out.println("Wrapper Colour: "+bouq6.wrapperColour);
System.out.println("Price: "+bouq6.price);
System.out.println("Fresh: "+bouq6.isFresh);
System.out.println("Fragrance: "+bouq6.hasFragrance);
System.out.println("Occasion: "+bouq6.occasion);
System.out.println("Size: "+bouq6.size);
System.out.println("Weight: "+bouq6.weight);
System.out.println("Brand: "+bouq6.brand);
System.out.println("Seller Name: "+bouq6.sellerName);
System.out.println("Country Of Origin: "+bouq6.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq6.manufactureDate);
System.out.println("Expiry Days: "+bouq6.expiryDays);
System.out.println("Artificial: "+bouq6.isArtificial);
System.out.println("Eco Friendly: "+bouq6.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq6.hasRibbon);
System.out.println("Ribbon Colour: "+bouq6.ribbonColour);
System.out.println("Rating: "+bouq6.rating);
System.out.println("Customer Review: "+bouq6.customerReview);
System.out.println("Packaging Type: "+bouq6.packagingType);
System.out.println("Discount: "+bouq6.discount);
System.out.println("Delivery Available: "+bouq6.deliveryAvailable);



Bouquet bouq7 = new Bouquet();

bouq7.flowerType="Daisy";
bouq7.colour="White";
bouq7.numberOfFlowers=14;
bouq7.wrapperType="Paper";
bouq7.wrapperColour="Yellow";
bouq7.price=390;
bouq7.isFresh=true;
bouq7.hasFragrance=true;
bouq7.occasion="Friendship";
bouq7.size="Medium";
bouq7.weight=0.4;
bouq7.brand="BloomGarden";
bouq7.sellerName="FlowerShop";
bouq7.countryOfOrigin="India";
bouq7.manufactureDate="07-02-2026";
bouq7.expiryDays=3;
bouq7.isArtificial=false;
bouq7.isEcoFriendly=true;
bouq7.hasRibbon=true;
bouq7.ribbonColour="Yellow";
bouq7.rating=4;
bouq7.customerReview="Fresh bouquet";
bouq7.packagingType="Box";
bouq7.discount=6;
bouq7.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq7.flowerType);
System.out.println("Colour: "+bouq7.colour);
System.out.println("Number Of Flowers: "+bouq7.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq7.wrapperType);
System.out.println("Wrapper Colour: "+bouq7.wrapperColour);
System.out.println("Price: "+bouq7.price);
System.out.println("Fresh: "+bouq7.isFresh);
System.out.println("Fragrance: "+bouq7.hasFragrance);
System.out.println("Occasion: "+bouq7.occasion);
System.out.println("Size: "+bouq7.size);
System.out.println("Weight: "+bouq7.weight);
System.out.println("Brand: "+bouq7.brand);
System.out.println("Seller Name: "+bouq7.sellerName);
System.out.println("Country Of Origin: "+bouq7.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq7.manufactureDate);
System.out.println("Expiry Days: "+bouq7.expiryDays);
System.out.println("Artificial: "+bouq7.isArtificial);
System.out.println("Eco Friendly: "+bouq7.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq7.hasRibbon);
System.out.println("Ribbon Colour: "+bouq7.ribbonColour);
System.out.println("Rating: "+bouq7.rating);
System.out.println("Customer Review: "+bouq7.customerReview);
System.out.println("Packaging Type: "+bouq7.packagingType);
System.out.println("Discount: "+bouq7.discount);
System.out.println("Delivery Available: "+bouq7.deliveryAvailable);

Bouquet bouq8= new Bouquet();

bouq8.flowerType="Gerbera";
bouq8.colour="Orange";
bouq8.numberOfFlowers=16;
bouq8.wrapperType="Plastic";
bouq8.wrapperColour="Pink";
bouq8.price=410;
bouq8.isFresh=true;
bouq8.hasFragrance=false;
bouq8.occasion="Birthday";
bouq8.size="Medium";
bouq8.weight=0.45;
bouq8.brand="FlowerMagic";
bouq8.sellerName="BloomShop";
bouq8.countryOfOrigin="India";
bouq8.manufactureDate="08-02-2026";
bouq8.expiryDays=3;
bouq8.isArtificial=false;
bouq8.isEcoFriendly=true;
bouq8.hasRibbon=true;
bouq8.ribbonColour="Red";
bouq8.rating=4;
bouq8.customerReview="Nice flowers";
bouq8.packagingType="Box";
bouq8.discount=7;
bouq8.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq8.flowerType);
System.out.println("Colour: "+bouq8.colour);
System.out.println("Number Of Flowers: "+bouq8.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq8.wrapperType);
System.out.println("Wrapper Colour: "+bouq8.wrapperColour);
System.out.println("Price: "+bouq8.price);
System.out.println("Fresh: "+bouq8.isFresh);
System.out.println("Fragrance: "+bouq8.hasFragrance);
System.out.println("Occasion: "+bouq8.occasion);
System.out.println("Size: "+bouq8.size);
System.out.println("Weight: "+bouq8.weight);
System.out.println("Brand: "+bouq8.brand);
System.out.println("Seller Name: "+bouq8.sellerName);
System.out.println("Country Of Origin: "+bouq8.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq8.manufactureDate);
System.out.println("Expiry Days: "+bouq8.expiryDays);
System.out.println("Artificial: "+bouq8.isArtificial);
System.out.println("Eco Friendly: "+bouq8.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq8.hasRibbon);
System.out.println("Ribbon Colour: "+bouq8.ribbonColour);
System.out.println("Rating: "+bouq8.rating);
System.out.println("Customer Review: "+bouq8.customerReview);
System.out.println("Packaging Type: "+bouq8.packagingType);
System.out.println("Discount: "+bouq8.discount);
System.out.println("Delivery Available: "+bouq8.deliveryAvailable);


Bouquet bouq9 = new Bouquet();

bouq9.flowerType="Rose";
bouq9.colour="Pink";
bouq9.numberOfFlowers=20;
bouq9.wrapperType="Paper";
bouq9.wrapperColour="White";
bouq9.price=520;
bouq9.isFresh=true;
bouq9.hasFragrance=true;
bouq9.occasion="Love";
bouq9.size="Large";
bouq9.weight=0.6;
bouq9.brand="RoyalBloom";
bouq9.sellerName="PetalStore";
bouq9.countryOfOrigin="India";
bouq9.manufactureDate="09-02-2026";
bouq9.expiryDays=4;
bouq9.isArtificial=false;
bouq9.isEcoFriendly=true;
bouq9.hasRibbon=true;
bouq9.ribbonColour="Pink";
bouq9.rating=5;
bouq9.customerReview="Very beautiful";
bouq9.packagingType="Box";
bouq9.discount=10;
bouq9.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq9.flowerType);
System.out.println("Colour: "+bouq9.colour);
System.out.println("Number Of Flowers: "+bouq9.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq9.wrapperType);
System.out.println("Wrapper Colour: "+bouq9.wrapperColour);
System.out.println("Price: "+bouq9.price);
System.out.println("Fresh: "+bouq9.isFresh);
System.out.println("Fragrance: "+bouq9.hasFragrance);
System.out.println("Occasion: "+bouq9.occasion);
System.out.println("Size: "+bouq9.size);
System.out.println("Weight: "+bouq9.weight);
System.out.println("Brand: "+bouq9.brand);
System.out.println("Seller Name: "+bouq9.sellerName);
System.out.println("Country Of Origin: "+bouq9.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq9.manufactureDate);
System.out.println("Expiry Days: "+bouq9.expiryDays);
System.out.println("Artificial: "+bouq9.isArtificial);
System.out.println("Eco Friendly: "+bouq9.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq9.hasRibbon);
System.out.println("Ribbon Colour: "+bouq9.ribbonColour);
System.out.println("Rating: "+bouq9.rating);
System.out.println("Customer Review: "+bouq9.customerReview);
System.out.println("Packaging Type: "+bouq9.packagingType);
System.out.println("Discount: "+bouq9.discount);
System.out.println("Delivery Available: "+bouq9.deliveryAvailable);


Bouquet bouq10 = new Bouquet();

bouq10.flowerType="Tulip";
bouq10.colour="Purple";
bouq10.numberOfFlowers=18;
bouq10.wrapperType="Paper";
bouq10.wrapperColour="Blue";
bouq10.price=480;
bouq10.isFresh=true;
bouq10.hasFragrance=true;
bouq10.occasion="Wedding";
bouq10.size="Medium";
bouq10.weight=0.5;
bouq10.brand="FlowerMagic";
bouq10.sellerName="BloomShop";
bouq10.countryOfOrigin="Netherlands";
bouq10.manufactureDate="10-02-2026";
bouq10.expiryDays=3;
bouq10.isArtificial=false;
bouq10.isEcoFriendly=true;
bouq10.hasRibbon=true;
bouq10.ribbonColour="Purple";
bouq10.rating=4;
bouq10.customerReview="Lovely bouquet";
bouq10.packagingType="Box";
bouq10.discount=8;
bouq10.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq10.flowerType);
System.out.println("Colour: "+bouq10.colour);
System.out.println("Number Of Flowers: "+bouq10.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq10.wrapperType);
System.out.println("Wrapper Colour: "+bouq10.wrapperColour);
System.out.println("Price: "+bouq10.price);
System.out.println("Fresh: "+bouq10.isFresh);
System.out.println("Fragrance: "+bouq10.hasFragrance);
System.out.println("Occasion: "+bouq10.occasion);
System.out.println("Size: "+bouq10.size);
System.out.println("Weight: "+bouq10.weight);
System.out.println("Brand: "+bouq10.brand);
System.out.println("Seller Name: "+bouq10.sellerName);
System.out.println("Country Of Origin: "+bouq10.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq10.manufactureDate);
System.out.println("Expiry Days: "+bouq10.expiryDays);
System.out.println("Artificial: "+bouq10.isArtificial);
System.out.println("Eco Friendly: "+bouq10.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq10.hasRibbon);
System.out.println("Ribbon Colour: "+bouq10.ribbonColour);
System.out.println("Rating: "+bouq10.rating);
System.out.println("Customer Review: "+bouq10.customerReview);
System.out.println("Packaging Type: "+bouq10.packagingType);
System.out.println("Discount: "+bouq10.discount);
System.out.println("Delivery Available: "+bouq10.deliveryAvailable);


Bouquet bouq11 = new Bouquet();

bouq11.flowerType="Orchid";
bouq11.colour="White";
bouq11.numberOfFlowers=12;
bouq11.wrapperType="Plastic";
bouq11.wrapperColour="Silver";
bouq11.price=560;
bouq11.isFresh=true;
bouq11.hasFragrance=true;
bouq11.occasion="Gift";
bouq11.size="Small";
bouq11.weight=0.4;
bouq11.brand="OrchidBloom";
bouq11.sellerName="FlowerCity";
bouq11.countryOfOrigin="Thailand";
bouq11.manufactureDate="11-02-2026";
bouq11.expiryDays=3;
bouq11.isArtificial=false;
bouq11.isEcoFriendly=true;
bouq11.hasRibbon=true;
bouq11.ribbonColour="Silver";
bouq11.rating=4;
bouq11.customerReview="Beautiful flowers";
bouq11.packagingType="Box";
bouq11.discount=7;
bouq11.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq11.flowerType);
System.out.println("Colour: "+bouq11.colour);
System.out.println("Number Of Flowers: "+bouq11.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq11.wrapperType);
System.out.println("Wrapper Colour: "+bouq11.wrapperColour);
System.out.println("Price: "+bouq11.price);
System.out.println("Fresh: "+bouq11.isFresh);
System.out.println("Fragrance: "+bouq11.hasFragrance);
System.out.println("Occasion: "+bouq11.occasion);
System.out.println("Size: "+bouq11.size);
System.out.println("Weight: "+bouq11.weight);
System.out.println("Brand: "+bouq11.brand);
System.out.println("Seller Name: "+bouq11.sellerName);
System.out.println("Country Of Origin: "+bouq11.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq11.manufactureDate);
System.out.println("Expiry Days: "+bouq11.expiryDays);
System.out.println("Artificial: "+bouq11.isArtificial);
System.out.println("Eco Friendly: "+bouq11.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq11.hasRibbon);
System.out.println("Ribbon Colour: "+bouq11.ribbonColour);
System.out.println("Rating: "+bouq11.rating);
System.out.println("Customer Review: "+bouq11.customerReview);
System.out.println("Packaging Type: "+bouq11.packagingType);
System.out.println("Discount: "+bouq11.discount);
System.out.println("Delivery Available: "+bouq11.deliveryAvailable);


Bouquet bouq12= new Bouquet();

bouq12.flowerType="Sunflower";
bouq12.colour="Yellow";
bouq12.numberOfFlowers=15;
bouq12.wrapperType="Paper";
bouq12.wrapperColour="Green";
bouq12.price=430;
bouq12.isFresh=true;
bouq12.hasFragrance=true;
bouq12.occasion="Birthday";
bouq12.size="Medium";
bouq12.weight=0.5;
bouq12.brand="SunshineBlooms";
bouq12.sellerName="BloomCart";
bouq12.countryOfOrigin="India";
bouq12.manufactureDate="12-02-2026";
bouq12.expiryDays=4;
bouq12.isArtificial=false;
bouq12.isEcoFriendly=true;
bouq12.hasRibbon=true;
bouq12.ribbonColour="Yellow";
bouq12.rating=5;
bouq12.customerReview="Bright and fresh";
bouq12.packagingType="Box";
bouq12.discount=8;
bouq12.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq12.flowerType);
System.out.println("Colour: "+bouq12.colour);
System.out.println("Number Of Flowers: "+bouq12.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq12.wrapperType);
System.out.println("Wrapper Colour: "+bouq12.wrapperColour);
System.out.println("Price: "+bouq12.price);
System.out.println("Fresh: "+bouq12.isFresh);
System.out.println("Fragrance: "+bouq12.hasFragrance);
System.out.println("Occasion: "+bouq12.occasion);
System.out.println("Size: "+bouq12.size);
System.out.println("Weight: "+bouq12.weight);
System.out.println("Brand: "+bouq12.brand);
System.out.println("Seller Name: "+bouq12.sellerName);
System.out.println("Country Of Origin: "+bouq12.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq12.manufactureDate);
System.out.println("Expiry Days: "+bouq12.expiryDays);
System.out.println("Artificial: "+bouq12.isArtificial);
System.out.println("Eco Friendly: "+bouq12.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq12.hasRibbon);
System.out.println("Ribbon Colour: "+bouq12.ribbonColour);
System.out.println("Rating: "+bouq12.rating);
System.out.println("Customer Review: "+bouq12.customerReview);
System.out.println("Packaging Type: "+bouq12.packagingType);
System.out.println("Discount: "+bouq12.discount);
System.out.println("Delivery Available: "+bouq12.deliveryAvailable);


Bouquet bouq13 = new Bouquet();

bouq13.flowerType="Gerbera";
bouq13.colour="Orange";
bouq13.numberOfFlowers=16;
bouq13.wrapperType="Plastic";
bouq13.wrapperColour="Pink";
bouq13.price=410;
bouq13.isFresh=true;
bouq13.hasFragrance=true;
bouq13.occasion="Anniversary";
bouq13.size="Medium";
bouq13.weight=0.45;
bouq13.brand="GerberaGlow";
bouq13.sellerName="PetalHub";
bouq13.countryOfOrigin="India";
bouq13.manufactureDate="13-02-2026";
bouq13.expiryDays=3;
bouq13.isArtificial=false;
bouq13.isEcoFriendly=true;
bouq13.hasRibbon=true;
bouq13.ribbonColour="Orange";
bouq13.rating=4;
bouq13.customerReview="Very vibrant";
bouq13.packagingType="Box";
bouq13.discount=6;
bouq13.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq13.flowerType);
System.out.println("Colour: "+bouq13.colour);
System.out.println("Number Of Flowers: "+bouq13.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq13.wrapperType);
System.out.println("Wrapper Colour: "+bouq13.wrapperColour);
System.out.println("Price: "+bouq13.price);
System.out.println("Fresh: "+bouq13.isFresh);
System.out.println("Fragrance: "+bouq13.hasFragrance);
System.out.println("Occasion: "+bouq13.occasion);
System.out.println("Size: "+bouq13.size);
System.out.println("Weight: "+bouq13.weight);
System.out.println("Brand: "+bouq13.brand);
System.out.println("Seller Name: "+bouq13.sellerName);
System.out.println("Country Of Origin: "+bouq13.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq13.manufactureDate);
System.out.println("Expiry Days: "+bouq13.expiryDays);
System.out.println("Artificial: "+bouq13.isArtificial);
System.out.println("Eco Friendly: "+bouq13.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq13.hasRibbon);
System.out.println("Ribbon Colour: "+bouq13.ribbonColour);
System.out.println("Rating: "+bouq13.rating);
System.out.println("Customer Review: "+bouq13.customerReview);
System.out.println("Packaging Type: "+bouq13.packagingType);
System.out.println("Discount: "+bouq13.discount);
System.out.println("Delivery Available: "+bouq13.deliveryAvailable);


Bouquet bouq14 = new Bouquet();

bouq14.flowerType="Carnation";
bouq14.colour="Red";
bouq14.numberOfFlowers=17;
bouq14.wrapperType="Paper";
bouq14.wrapperColour="White";
bouq14.price=440;
bouq14.isFresh=true;
bouq14.hasFragrance=true;
bouq14.occasion="Valentine";
bouq14.size="Medium";
bouq14.weight=0.5;
bouq14.brand="CarnationCreations";
bouq14.sellerName="FlowerMart";
bouq14.countryOfOrigin="India";
bouq14.manufactureDate="14-02-2026";
bouq14.expiryDays=3;
bouq14.isArtificial=false;
bouq14.isEcoFriendly=true;
bouq14.hasRibbon=true;
bouq14.ribbonColour="Red";
bouq14.rating=5;
bouq14.customerReview="Perfect gift";
bouq14.packagingType="Box";
bouq14.discount=9;
bouq14.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq14.flowerType);
System.out.println("Colour: "+bouq14.colour);
System.out.println("Number Of Flowers: "+bouq14.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq14.wrapperType);
System.out.println("Wrapper Colour: "+bouq14.wrapperColour);
System.out.println("Price: "+bouq14.price);
System.out.println("Fresh: "+bouq14.isFresh);
System.out.println("Fragrance: "+bouq14.hasFragrance);
System.out.println("Occasion: "+bouq14.occasion);
System.out.println("Size: "+bouq14.size);
System.out.println("Weight: "+bouq14.weight);
System.out.println("Brand: "+bouq14.brand);
System.out.println("Seller Name: "+bouq14.sellerName);
System.out.println("Country Of Origin: "+bouq14.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq14.manufactureDate);
System.out.println("Expiry Days: "+bouq14.expiryDays);
System.out.println("Artificial: "+bouq14.isArtificial);
System.out.println("Eco Friendly: "+bouq14.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq14.hasRibbon);
System.out.println("Ribbon Colour: "+bouq14.ribbonColour);
System.out.println("Rating: "+bouq14.rating);
System.out.println("Customer Review: "+bouq14.customerReview);
System.out.println("Packaging Type: "+bouq14.packagingType);
System.out.println("Discount: "+bouq14.discount);
System.out.println("Delivery Available: "+bouq14.deliveryAvailable);


Bouquet bouq15 = new Bouquet();

bouq15.flowerType="Rose";
bouq15.colour="Pink";
bouq15.numberOfFlowers=20;
bouq15.wrapperType="Plastic";
bouq15.wrapperColour="Pink";
bouq15.price=600;
bouq15.isFresh=true;
bouq15.hasFragrance=true;
bouq15.occasion="Anniversary";
bouq15.size="Large";
bouq15.weight=0.8;
bouq15.brand="RoseElegance";
bouq15.sellerName="FlowerWorld";
bouq15.countryOfOrigin="India";
bouq15.manufactureDate="15-02-2026";
bouq15.expiryDays=5;
bouq15.isArtificial=false;
bouq15.isEcoFriendly=true;
bouq15.hasRibbon=true;
bouq15.ribbonColour="Pink";
bouq15.rating=5;
bouq15.customerReview="Elegant and fresh";
bouq15.packagingType="Box";
bouq15.discount=10;
bouq15.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq15.flowerType);
System.out.println("Colour: "+bouq15.colour);
System.out.println("Number Of Flowers: "+bouq15.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq15.wrapperType);
System.out.println("Wrapper Colour: "+bouq15.wrapperColour);
System.out.println("Price: "+bouq15.price);
System.out.println("Fresh: "+bouq15.isFresh);
System.out.println("Fragrance: "+bouq15.hasFragrance);
System.out.println("Occasion: "+bouq15.occasion);
System.out.println("Size: "+bouq15.size);
System.out.println("Weight: "+bouq15.weight);
System.out.println("Brand: "+bouq15.brand);
System.out.println("Seller Name: "+bouq15.sellerName);
System.out.println("Country Of Origin: "+bouq15.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq15.manufactureDate);
System.out.println("Expiry Days: "+bouq15.expiryDays);
System.out.println("Artificial: "+bouq15.isArtificial);
System.out.println("Eco Friendly: "+bouq15.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq15.hasRibbon);
System.out.println("Ribbon Colour: "+bouq15.ribbonColour);
System.out.println("Rating: "+bouq15.rating);
System.out.println("Customer Review: "+bouq15.customerReview);
System.out.println("Packaging Type: "+bouq15.packagingType);
System.out.println("Discount: "+bouq15.discount);
System.out.println("Delivery Available: "+bouq15.deliveryAvailable);


Bouquet bouq16 = new Bouquet();

bouq16.flowerType="Lilies";
bouq16.colour="White";
bouq16.numberOfFlowers=10;
bouq16.wrapperType="Paper";
bouq16.wrapperColour="White";
bouq16.price=500;
bouq16.isFresh=true;
bouq16.hasFragrance=true;
bouq16.occasion="Wedding";
bouq16.size="Medium";
bouq16.weight=0.6;
bouq16.brand="LilyCharm";
bouq16.sellerName="PetalStore";
bouq16.countryOfOrigin="India";
bouq16.manufactureDate="16-02-2026";
bouq16.expiryDays=4;
bouq16.isArtificial=false;
bouq16.isEcoFriendly=true;
bouq16.hasRibbon=true;
bouq16.ribbonColour="White";
bouq16.rating=5;
bouq16.customerReview="Fresh and elegant";
bouq16.packagingType="Box";
bouq16.discount=8;
bouq16.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq16.flowerType);
System.out.println("Colour: "+bouq16.colour);
System.out.println("Number Of Flowers: "+bouq16.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq16.wrapperType);
System.out.println("Wrapper Colour: "+bouq16.wrapperColour);
System.out.println("Price: "+bouq16.price);
System.out.println("Fresh: "+bouq16.isFresh);
System.out.println("Fragrance: "+bouq16.hasFragrance);
System.out.println("Occasion: "+bouq16.occasion);
System.out.println("Size: "+bouq16.size);
System.out.println("Weight: "+bouq16.weight);
System.out.println("Brand: "+bouq16.brand);
System.out.println("Seller Name: "+bouq16.sellerName);
System.out.println("Country Of Origin: "+bouq16.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq16.manufactureDate);
System.out.println("Expiry Days: "+bouq16.expiryDays);
System.out.println("Artificial: "+bouq16.isArtificial);
System.out.println("Eco Friendly: "+bouq16.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq16.hasRibbon);
System.out.println("Ribbon Colour: "+bouq16.ribbonColour);
System.out.println("Rating: "+bouq16.rating);
System.out.println("Customer Review: "+bouq16.customerReview);
System.out.println("Packaging Type: "+bouq16.packagingType);
System.out.println("Discount: "+bouq16.discount);
System.out.println("Delivery Available: "+bouq16.deliveryAvailable);

Bouquet bouq17 = new Bouquet();

bouq17.flowerType="Tulip";
bouq17.colour="Purple";
bouq17.numberOfFlowers=18;
bouq17.wrapperType="Plastic";
bouq17.wrapperColour="Purple";
bouq17.price=550;
bouq17.isFresh=true;
bouq17.hasFragrance=true;
bouq17.occasion="Birthday";
bouq17.size="Medium";
bouq17.weight=0.65;
bouq17.brand="TulipHeaven";
bouq17.sellerName="BloomShop";
bouq17.countryOfOrigin="Netherlands";
bouq17.manufactureDate="17-02-2026";
bouq17.expiryDays=5;
bouq17.isArtificial=false;
bouq17.isEcoFriendly=true;
bouq17.hasRibbon=true;
bouq17.ribbonColour="Purple";
bouq17.rating=4;
bouq17.customerReview="Vibrant tulips";
bouq17.packagingType="Box";
bouq17.discount=9;
bouq17.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq17.flowerType);
System.out.println("Colour: "+bouq17.colour);
System.out.println("Number Of Flowers: "+bouq17.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq17.wrapperType);
System.out.println("Wrapper Colour: "+bouq17.wrapperColour);
System.out.println("Price: "+bouq17.price);
System.out.println("Fresh: "+bouq17.isFresh);
System.out.println("Fragrance: "+bouq17.hasFragrance);
System.out.println("Occasion: "+bouq17.occasion);
System.out.println("Size: "+bouq17.size);
System.out.println("Weight: "+bouq17.weight);
System.out.println("Brand: "+bouq17.brand);
System.out.println("Seller Name: "+bouq17.sellerName);
System.out.println("Country Of Origin: "+bouq17.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq17.manufactureDate);
System.out.println("Expiry Days: "+bouq17.expiryDays);
System.out.println("Artificial: "+bouq17.isArtificial);
System.out.println("Eco Friendly: "+bouq17.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq17.hasRibbon);
System.out.println("Ribbon Colour: "+bouq17.ribbonColour);
System.out.println("Rating: "+bouq17.rating);
System.out.println("Customer Review: "+bouq17.customerReview);
System.out.println("Packaging Type: "+bouq17.packagingType);
System.out.println("Discount: "+bouq17.discount);
System.out.println("Delivery Available: "+bouq17.deliveryAvailable);


Bouquet bouq18 = new Bouquet();

bouq18.flowerType="Daisy";
bouq18.colour="White";
bouq18.numberOfFlowers=25;
bouq18.wrapperType="Paper";
bouq18.wrapperColour="Blue";
bouq18.price=480;
bouq18.isFresh=true;
bouq18.hasFragrance=true;
bouq18.occasion="Get Well Soon";
bouq18.size="Medium";
bouq18.weight=0.7;
bouq18.brand="DaisyDelight";
bouq18.sellerName="FloraMart";
bouq18.countryOfOrigin="India";
bouq18.manufactureDate="18-02-2026";
bouq18.expiryDays=4;
bouq18.isArtificial=false;
bouq18.isEcoFriendly=true;
bouq18.hasRibbon=true;
bouq18.ribbonColour="Blue";
bouq18.rating=5;
bouq18.customerReview="Lovely bouquet";
bouq18.packagingType="Box";
bouq18.discount=7;
bouq18.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq18.flowerType);
System.out.println("Colour: "+bouq18.colour);
System.out.println("Number Of Flowers: "+bouq18.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq18.wrapperType);
System.out.println("Wrapper Colour: "+bouq18.wrapperColour);
System.out.println("Price: "+bouq18.price);
System.out.println("Fresh: "+bouq18.isFresh);
System.out.println("Fragrance: "+bouq18.hasFragrance);
System.out.println("Occasion: "+bouq18.occasion);
System.out.println("Size: "+bouq18.size);
System.out.println("Weight: "+bouq18.weight);
System.out.println("Brand: "+bouq18.brand);
System.out.println("Seller Name: "+bouq18.sellerName);
System.out.println("Country Of Origin: "+bouq18.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq18.manufactureDate);
System.out.println("Expiry Days: "+bouq18.expiryDays);
System.out.println("Artificial: "+bouq18.isArtificial);
System.out.println("Eco Friendly: "+bouq18.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq18.hasRibbon);
System.out.println("Ribbon Colour: "+bouq18.ribbonColour);
System.out.println("Rating: "+bouq18.rating);
System.out.println("Customer Review: "+bouq18.customerReview);
System.out.println("Packaging Type: "+bouq18.packagingType);
System.out.println("Discount: "+bouq18.discount);
System.out.println("Delivery Available: "+bouq18.deliveryAvailable);

Bouquet bouq19 = new Bouquet();

bouq19.flowerType="Jasmine";
bouq19.colour="White";
bouq19.numberOfFlowers=30;
bouq19.wrapperType="Plastic";
bouq19.wrapperColour="White";
bouq19.price=520;
bouq19.isFresh=true;
bouq19.hasFragrance=true;
bouq19.occasion="Wedding";
bouq19.size="Large";
bouq19.weight=0.9;
bouq19.brand="JasmineJoy";
bouq19.sellerName="FloralHub";
bouq19.countryOfOrigin="India";
bouq19.manufactureDate="19-02-2026";
bouq19.expiryDays=5;
bouq19.isArtificial=false;
bouq19.isEcoFriendly=true;
bouq19.hasRibbon=true;
bouq19.ribbonColour="White";
bouq19.rating=5;
bouq19.customerReview="Perfect for weddings";
bouq19.packagingType="Box";
bouq19.discount=10;
bouq19.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq19.flowerType);
System.out.println("Colour: "+bouq19.colour);
System.out.println("Number Of Flowers: "+bouq19.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq19.wrapperType);
System.out.println("Wrapper Colour: "+bouq19.wrapperColour);
System.out.println("Price: "+bouq19.price);
System.out.println("Fresh: "+bouq19.isFresh);
System.out.println("Fragrance: "+bouq19.hasFragrance);
System.out.println("Occasion: "+bouq19.occasion);
System.out.println("Size: "+bouq19.size);
System.out.println("Weight: "+bouq19.weight);
System.out.println("Brand: "+bouq19.brand);
System.out.println("Seller Name: "+bouq19.sellerName);
System.out.println("Country Of Origin: "+bouq19.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq19.manufactureDate);
System.out.println("Expiry Days: "+bouq19.expiryDays);
System.out.println("Artificial: "+bouq19.isArtificial);
System.out.println("Eco Friendly: "+bouq19.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq19.hasRibbon);
System.out.println("Ribbon Colour: "+bouq19.ribbonColour);
System.out.println("Rating: "+bouq19.rating);
System.out.println("Customer Review: "+bouq19.customerReview);
System.out.println("Packaging Type: "+bouq19.packagingType);
System.out.println("Discount: "+bouq19.discount);
System.out.println("Delivery Available: "+bouq19.deliveryAvailable);

Bouquet bouq20= new Bouquet();

bouq20.flowerType="Marigold";
bouq20.colour="Orange";
bouq20.numberOfFlowers=35;
bouq20.wrapperType="Paper";
bouq20.wrapperColour="Orange";
bouq20.price=580;
bouq20.isFresh=true;
bouq20.hasFragrance=true;
bouq20.occasion="Festival";
bouq20.size="Large";
bouq20.weight=1.0;
bouq20.brand="MarigoldMagic";
bouq20.sellerName="FloralBazaar";
bouq20.countryOfOrigin="India";
bouq20.manufactureDate="20-02-2026";
bouq20.expiryDays=6;
bouq20.isArtificial=false;
bouq20.isEcoFriendly=true;
bouq20.hasRibbon=true;
bouq20.ribbonColour="Orange";
bouq20.rating=5;
bouq20.customerReview="Festive and bright";
bouq20.packagingType="Box";
bouq20.discount=12;
bouq20.deliveryAvailable=true;

System.out.println("Flower Type: "+bouq20.flowerType);
System.out.println("Colour: "+bouq20.colour);
System.out.println("Number Of Flowers: "+bouq20.numberOfFlowers);
System.out.println("Wrapper Type: "+bouq20.wrapperType);
System.out.println("Wrapper Colour: "+bouq20.wrapperColour);
System.out.println("Price: "+bouq20.price);
System.out.println("Fresh: "+bouq20.isFresh);
System.out.println("Fragrance: "+bouq20.hasFragrance);
System.out.println("Occasion: "+bouq20.occasion);
System.out.println("Size: "+bouq20.size);
System.out.println("Weight: "+bouq20.weight);
System.out.println("Brand: "+bouq20.brand);
System.out.println("Seller Name: "+bouq20.sellerName);
System.out.println("Country Of Origin: "+bouq20.countryOfOrigin);
System.out.println("Manufacture Date: "+bouq20.manufactureDate);
System.out.println("Expiry Days: "+bouq20.expiryDays);
System.out.println("Artificial: "+bouq20.isArtificial);
System.out.println("Eco Friendly: "+bouq20.isEcoFriendly);
System.out.println("Has Ribbon: "+bouq20.hasRibbon);
System.out.println("Ribbon Colour: "+bouq20.ribbonColour);
System.out.println("Rating: "+bouq20.rating);
System.out.println("Customer Review: "+bouq20.customerReview);
System.out.println("Packaging Type: "+bouq20.packagingType);
System.out.println("Discount: "+bouq20.discount);
System.out.println("Delivery Available: "+bouq20.deliveryAvailable);
}

}