class ClipExecutor{
   public static void main(String[] args){
   HairClip hairClip1 = new HairClip();
	hairClip1.type = "Claw Clip";
	hairClip1.material = "Plastic";
	hairClip1.colour = "Black";
	hairClip1.price = 150;
	hairClip1.quantity = 2;
	hairClip1.brand = "GlamHair";
	hairClip1.isHandMade = false;
	hairClip1.isQualityGood = true;
	hairClip1.size = "Medium";
	hairClip1.weight = "15 grams";
	hairClip1.isAntique = false;
	hairClip1.warranty = "3 months";
	hairClip1.manufactureDate = "01-02-2026";
	hairClip1.isFlexible = true;
	hairClip1.shape = "Rectangular";
	hairClip1.designType = "Plain";
	hairClip1.isStoneStudded = false;
	hairClip1.pattern = "Solid";
	hairClip1.sellerName = "Amazon Seller";
	hairClip1.countryOfOrigin = "India";
	hairClip1.numberOfTeeth = 12;
	hairClip1.customerReview = "Strong and durable";
	hairClip1.rating = 5;
	hairClip1.isStockAvailable = true;
	hairClip1.grams = 15;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip1.type);
	System.out.println("material : " + hairClip1.material);
	System.out.println("colour : " + hairClip1.colour);
	System.out.println("price : " + hairClip1.price);
	System.out.println("quantity : " + hairClip1.quantity);
	System.out.println("brand : " + hairClip1.brand);
	System.out.println("isHandMade : " + hairClip1.isHandMade);
	System.out.println("isQualityGood : " + hairClip1.isQualityGood);
	System.out.println("size : " + hairClip1.size);
	System.out.println("weight : " + hairClip1.weight);
	System.out.println("isAntique : " + hairClip1.isAntique);
	System.out.println("warranty : " + hairClip1.warranty);
	System.out.println("manufactureDate : " + hairClip1.manufactureDate);
	System.out.println("isFlexible : " + hairClip1.isFlexible);
	System.out.println("shape : " + hairClip1.shape);
	System.out.println("designType : " + hairClip1.designType);
	System.out.println("isStoneStudded : " + hairClip1.isStoneStudded);
	System.out.println("pattern : " + hairClip1.pattern);
	System.out.println("sellerName : " + hairClip1.sellerName);
	System.out.println("countryOfOrigin : " + hairClip1.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip1.numberOfTeeth);
	System.out.println("customerReview : " + hairClip1.customerReview);
	System.out.println("rating : " + hairClip1.rating);
	System.out.println("isStockAvailable : " + hairClip1.isStockAvailable);
	System.out.println("grams : " + hairClip1.grams);

	HairClip hairClip2 = new HairClip();
	hairClip2.type = "Alligator Clip";
	hairClip2.material = "Metal";
	hairClip2.colour = "Silver";
	hairClip2.price = 200;
	hairClip2.quantity = 3;
	hairClip2.brand = "StylePro";
	hairClip2.isHandMade = true;
	hairClip2.isQualityGood = true;
	hairClip2.size = "Small";
	hairClip2.weight = "12 grams";
	hairClip2.isAntique = false;
	hairClip2.warranty = "6 months";
	hairClip2.manufactureDate = "15-01-2026";
	hairClip2.isFlexible = false;
	hairClip2.shape = "Curved";
	hairClip2.designType = "Floral";
	hairClip2.isStoneStudded = true;
	hairClip2.pattern = "Engraved";
	hairClip2.sellerName = "Flipkart Seller";
	hairClip2.countryOfOrigin = "India";
	hairClip2.numberOfTeeth = 10;
	hairClip2.customerReview = "Looks elegant";
	hairClip2.rating = 4;
	hairClip2.isStockAvailable = true;
	hairClip2.grams = 12;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip2.type);
	System.out.println("material : " + hairClip2.material);
	System.out.println("colour : " + hairClip2.colour);
	System.out.println("price : " + hairClip2.price);
	System.out.println("quantity : " + hairClip2.quantity);
	System.out.println("brand : " + hairClip2.brand);
	System.out.println("isHandMade : " + hairClip2.isHandMade);
	System.out.println("isQualityGood : " + hairClip2.isQualityGood);
	System.out.println("size : " + hairClip2.size);
	System.out.println("weight : " + hairClip2.weight);
	System.out.println("isAntique : " + hairClip2.isAntique);
	System.out.println("warranty : " + hairClip2.warranty);
	System.out.println("manufactureDate : " + hairClip2.manufactureDate);
	System.out.println("isFlexible : " + hairClip2.isFlexible);
	System.out.println("shape : " + hairClip2.shape);
	System.out.println("designType : " + hairClip2.designType);
	System.out.println("isStoneStudded : " + hairClip2.isStoneStudded);
	System.out.println("pattern : " + hairClip2.pattern);
	System.out.println("sellerName : " + hairClip2.sellerName);
	System.out.println("countryOfOrigin : " + hairClip2.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip2.numberOfTeeth);
	System.out.println("customerReview : " + hairClip2.customerReview);
	System.out.println("rating : " + hairClip2.rating);
	System.out.println("isStockAvailable : " + hairClip2.isStockAvailable);
	System.out.println("grams : " + hairClip2.grams);

	HairClip hairClip3 = new HairClip();
	hairClip3.type = "Claw Clip";
	hairClip3.material = "Plastic";
	hairClip3.colour = "Brown";
	hairClip3.price = 120;
	hairClip3.quantity = 5;
	hairClip3.brand = "HairStyle";
	hairClip3.isHandMade = false;
	hairClip3.isQualityGood = true;
	hairClip3.size = "Medium";
	hairClip3.weight = "14 grams";
	hairClip3.isAntique = false;
	hairClip3.warranty = "3 months";
	hairClip3.manufactureDate = "05-02-2026";
	hairClip3.isFlexible = true;
	hairClip3.shape = "Round";
	hairClip3.designType = "Plain";
	hairClip3.isStoneStudded = false;
	hairClip3.pattern = "Solid";
	hairClip3.sellerName = "Local Shop";
	hairClip3.countryOfOrigin = "India";
	hairClip3.numberOfTeeth = 11;
	hairClip3.customerReview = "Good quality";
	hairClip3.rating = 4;
	hairClip3.isStockAvailable = true;
	hairClip3.grams = 14;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip3.type);
	System.out.println("material : " + hairClip3.material);
	System.out.println("colour : " + hairClip3.colour);
	System.out.println("price : " + hairClip3.price);
	System.out.println("quantity : " + hairClip3.quantity);
	System.out.println("brand : " + hairClip3.brand);
	System.out.println("isHandMade : " + hairClip3.isHandMade);
	System.out.println("isQualityGood : " + hairClip3.isQualityGood);
	System.out.println("size : " + hairClip3.size);
	System.out.println("weight : " + hairClip3.weight);
	System.out.println("isAntique : " + hairClip3.isAntique);
	System.out.println("warranty : " + hairClip3.warranty);
	System.out.println("manufactureDate : " + hairClip3.manufactureDate);
	System.out.println("isFlexible : " + hairClip3.isFlexible);
	System.out.println("shape : " + hairClip3.shape);
	System.out.println("designType : " + hairClip3.designType);
	System.out.println("isStoneStudded : " + hairClip3.isStoneStudded);
	System.out.println("pattern : " + hairClip3.pattern);
	System.out.println("sellerName : " + hairClip3.sellerName);
	System.out.println("countryOfOrigin : " + hairClip3.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip3.numberOfTeeth);
	System.out.println("customerReview : " + hairClip3.customerReview);
	System.out.println("rating : " + hairClip3.rating);
	System.out.println("isStockAvailable : " + hairClip3.isStockAvailable);
	System.out.println("grams : " + hairClip3.grams);



	HairClip hairClip4 = new HairClip();
	hairClip4.type = "Alligator Clip";
	hairClip4.material = "Metal";
	hairClip4.colour = "Gold";
	hairClip4.price = 250;
	hairClip4.quantity = 2;
	hairClip4.brand = "Glamour";
	hairClip4.isHandMade = true;
	hairClip4.isQualityGood = true;
	hairClip4.size = "Small";
	hairClip4.weight = "18 grams";
	hairClip4.isAntique = false;
	hairClip4.warranty = "6 months";
	hairClip4.manufactureDate = "10-01-2026";
	hairClip4.isFlexible = false;
	hairClip4.shape = "Rectangular";
	hairClip4.designType = "Floral";
	hairClip4.isStoneStudded = true;
	hairClip4.pattern = "Engraved";
	hairClip4.sellerName = "Amazon";
	hairClip4.countryOfOrigin = "India";
	hairClip4.numberOfTeeth = 12;
	hairClip4.customerReview = "Very shiny";
	hairClip4.rating = 5;
	hairClip4.isStockAvailable = true;
	hairClip4.grams = 18;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip4.type);
	System.out.println("material : " + hairClip4.material);
	System.out.println("colour : " + hairClip4.colour);
	System.out.println("price : " + hairClip4.price);
	System.out.println("quantity : " + hairClip4.quantity);
	System.out.println("brand : " + hairClip4.brand);
	System.out.println("isHandMade : " + hairClip4.isHandMade);
	System.out.println("isQualityGood : " + hairClip4.isQualityGood);
	System.out.println("size : " + hairClip4.size);
	System.out.println("weight : " + hairClip4.weight);
	System.out.println("isAntique : " + hairClip4.isAntique);
	System.out.println("warranty : " + hairClip4.warranty);
	System.out.println("manufactureDate : " + hairClip4.manufactureDate);
	System.out.println("isFlexible : " + hairClip4.isFlexible);
	System.out.println("shape : " + hairClip4.shape);
	System.out.println("designType : " + hairClip4.designType);
	System.out.println("isStoneStudded : " + hairClip4.isStoneStudded);
	System.out.println("pattern : " + hairClip4.pattern);
	System.out.println("sellerName : " + hairClip4.sellerName);
	System.out.println("countryOfOrigin : " + hairClip4.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip4.numberOfTeeth);
	System.out.println("customerReview : " + hairClip4.customerReview);
	System.out.println("rating : " + hairClip4.rating);
	System.out.println("isStockAvailable : " + hairClip4.isStockAvailable);
	System.out.println("grams : " + hairClip4.grams);


	HairClip hairClip5 = new HairClip();
	hairClip5.type = "Snap Clip";
	hairClip5.material = "Plastic";
	hairClip5.colour = "Red";
	hairClip5.price = 100;
	hairClip5.quantity = 4;
	hairClip5.brand = "BeautyPro";
	hairClip5.isHandMade = false;
	hairClip5.isQualityGood = true;
	hairClip5.size = "Small";
	hairClip5.weight = "10 grams";
	hairClip5.isAntique = false;
	hairClip5.warranty = "3 months";
	hairClip5.manufactureDate = "12-01-2026";
	hairClip5.isFlexible = true;
	hairClip5.shape = "Oval";
	hairClip5.designType = "Plain";
	hairClip5.isStoneStudded = false;
	hairClip5.pattern = "Solid";
	hairClip5.sellerName = "Flipkart";
	hairClip5.countryOfOrigin = "India";
	hairClip5.numberOfTeeth = 8;
	hairClip5.customerReview = "Nice color";
	hairClip5.rating = 4;
	hairClip5.isStockAvailable = true;
	hairClip5.grams = 10;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip5.type);
	System.out.println("material : " + hairClip5.material);
	System.out.println("colour : " + hairClip5.colour);
	System.out.println("price : " + hairClip5.price);
	System.out.println("quantity : " + hairClip5.quantity);
	System.out.println("brand : " + hairClip5.brand);
	System.out.println("isHandMade : " + hairClip5.isHandMade);
	System.out.println("isQualityGood : " + hairClip5.isQualityGood);
	System.out.println("size : " + hairClip5.size);
	System.out.println("weight : " + hairClip5.weight);
	System.out.println("isAntique : " + hairClip5.isAntique);
	System.out.println("warranty : " + hairClip5.warranty);
	System.out.println("manufactureDate : " + hairClip5.manufactureDate);
	System.out.println("isFlexible : " + hairClip5.isFlexible);
	System.out.println("shape : " + hairClip5.shape);
	System.out.println("designType : " + hairClip5.designType);
	System.out.println("isStoneStudded : " + hairClip5.isStoneStudded);
	System.out.println("pattern : " + hairClip5.pattern);
	System.out.println("sellerName : " + hairClip5.sellerName);
	System.out.println("countryOfOrigin : " + hairClip5.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip5.numberOfTeeth);
	System.out.println("customerReview : " + hairClip5.customerReview);
	System.out.println("rating : " + hairClip5.rating);
	System.out.println("isStockAvailable : " + hairClip5.isStockAvailable);
	System.out.println("grams : " + hairClip5.grams);


	HairClip hairClip6 = new HairClip();
	hairClip6.type = "Claw Clip";
	hairClip6.material = "Metal";
	hairClip6.colour = "Silver";
	hairClip6.price = 220;
	hairClip6.quantity = 2;
	hairClip6.brand = "StyleQueen";
	hairClip6.isHandMade = true;
	hairClip6.isQualityGood = true;
	hairClip6.size = "Medium";
	hairClip6.weight = "16 grams";
	hairClip6.isAntique = false;
	hairClip6.warranty = "6 months";
	hairClip6.manufactureDate = "18-01-2026";
	hairClip6.isFlexible = false;
	hairClip6.shape = "Round";
	hairClip6.designType = "Floral";
	hairClip6.isStoneStudded = true;
	hairClip6.pattern = "Engraved";
	hairClip6.sellerName = "Amazon";
	hairClip6.countryOfOrigin = "India";
	hairClip6.numberOfTeeth = 14;
	hairClip6.customerReview = "Elegant design";
	hairClip6.rating = 5;
	hairClip6.isStockAvailable = true;
	hairClip6.grams = 16;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip6.type);
	System.out.println("material : " + hairClip6.material);
	System.out.println("colour : " + hairClip6.colour);
	System.out.println("price : " + hairClip6.price);
	System.out.println("quantity : " + hairClip6.quantity);
	System.out.println("brand : " + hairClip6.brand);
	System.out.println("isHandMade : " + hairClip6.isHandMade);
	System.out.println("isQualityGood : " + hairClip6.isQualityGood);
	System.out.println("size : " + hairClip6.size);
	System.out.println("weight : " + hairClip6.weight);
	System.out.println("isAntique : " + hairClip6.isAntique);
	System.out.println("warranty : " + hairClip6.warranty);
	System.out.println("manufactureDate : " + hairClip6.manufactureDate);
	System.out.println("isFlexible : " + hairClip6.isFlexible);
	System.out.println("shape : " + hairClip6.shape);
	System.out.println("designType : " + hairClip6.designType);
	System.out.println("isStoneStudded : " + hairClip6.isStoneStudded);
	System.out.println("pattern : " + hairClip6.pattern);
	System.out.println("sellerName : " + hairClip6.sellerName);
	System.out.println("countryOfOrigin : " + hairClip6.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip6.numberOfTeeth);
	System.out.println("customerReview : " + hairClip6.customerReview);
	System.out.println("rating : " + hairClip6.rating);
	System.out.println("isStockAvailable : " + hairClip6.isStockAvailable);
	System.out.println("grams : " + hairClip6.grams);
	   
	   
	HairClip hairClip7 = new HairClip();
	hairClip7.type = "Snap Clip";
	hairClip7.material = "Plastic";
	hairClip7.colour = "Pink";
	hairClip7.price = 130;
	hairClip7.quantity = 4;
	hairClip7.brand = "BeautyPro";
	hairClip7.isHandMade = false;
	hairClip7.isQualityGood = true;
	hairClip7.size = "Small";
	hairClip7.weight = "11 grams";
	hairClip7.isAntique = false;
	hairClip7.warranty = "3 months";
	hairClip7.manufactureDate = "20-01-2026";
	hairClip7.isFlexible = true;
	hairClip7.shape = "Oval";
	hairClip7.designType = "Plain";
	hairClip7.isStoneStudded = false;
	hairClip7.pattern = "Solid";
	hairClip7.sellerName = "Flipkart";
	hairClip7.countryOfOrigin = "India";
	hairClip7.numberOfTeeth = 9;
	hairClip7.customerReview = "Bright color";
	hairClip7.rating = 4;
	hairClip7.isStockAvailable = true;
	hairClip7.grams = 11;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip7.type);
	System.out.println("material : " + hairClip7.material);
	System.out.println("colour : " + hairClip7.colour);
	System.out.println("price : " + hairClip7.price);
	System.out.println("quantity : " + hairClip7.quantity);
	System.out.println("brand : " + hairClip7.brand);
	System.out.println("isHandMade : " + hairClip7.isHandMade);
	System.out.println("isQualityGood : " + hairClip7.isQualityGood);
	System.out.println("size : " + hairClip7.size);
	System.out.println("weight : " + hairClip7.weight);
	System.out.println("isAntique : " + hairClip7.isAntique);
	System.out.println("warranty : " + hairClip7.warranty);
	System.out.println("manufactureDate : " + hairClip7.manufactureDate);
	System.out.println("isFlexible : " + hairClip7.isFlexible);
	System.out.println("shape : " + hairClip7.shape);
	System.out.println("designType : " + hairClip7.designType);
	System.out.println("isStoneStudded : " + hairClip7.isStoneStudded);
	System.out.println("pattern : " + hairClip7.pattern);
	System.out.println("sellerName : " + hairClip7.sellerName);
	System.out.println("countryOfOrigin : " + hairClip7.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip7.numberOfTeeth);
	System.out.println("customerReview : " + hairClip7.customerReview);
	System.out.println("rating : " + hairClip7.rating);
	System.out.println("isStockAvailable : " + hairClip7.isStockAvailable);
	System.out.println("grams : " + hairClip7.grams);


	HairClip hairClip8 = new HairClip();
	hairClip8.type = "Banana Clip";
	hairClip8.material = "Plastic";
	hairClip8.colour = "Brown";
	hairClip8.price = 180;
	hairClip8.quantity = 2;
	hairClip8.brand = "HairTrend";
	hairClip8.isHandMade = false;
	hairClip8.isQualityGood = true;
	hairClip8.size = "Large";
	hairClip8.weight = "20 grams";
	hairClip8.isAntique = false;
	hairClip8.warranty = "6 months";
	hairClip8.manufactureDate = "22-01-2026";
	hairClip8.isFlexible = true;
	hairClip8.shape = "Curved";
	hairClip8.designType = "Plain";
	hairClip8.isStoneStudded = false;
	hairClip8.pattern = "Solid";
	hairClip8.sellerName = "Amazon";
	hairClip8.countryOfOrigin = "India";
	hairClip8.numberOfTeeth = 14;
	hairClip8.customerReview = "Strong and flexible";
	hairClip8.rating = 5;
	hairClip8.isStockAvailable = true;
	hairClip8.grams = 20;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip8.type);
	System.out.println("material : " + hairClip8.material);
	System.out.println("colour : " + hairClip8.colour);
	System.out.println("price : " + hairClip8.price);
	System.out.println("quantity : " + hairClip8.quantity);
	System.out.println("brand : " + hairClip8.brand);
	System.out.println("isHandMade : " + hairClip8.isHandMade);
	System.out.println("isQualityGood : " + hairClip8.isQualityGood);
	System.out.println("size : " + hairClip8.size);
	System.out.println("weight : " + hairClip8.weight);
	System.out.println("isAntique : " + hairClip8.isAntique);
	System.out.println("warranty : " + hairClip8.warranty);
	System.out.println("manufactureDate : " + hairClip8.manufactureDate);
	System.out.println("isFlexible : " + hairClip8.isFlexible);
	System.out.println("shape : " + hairClip8.shape);
	System.out.println("designType : " + hairClip8.designType);
	System.out.println("isStoneStudded : " + hairClip8.isStoneStudded);
	System.out.println("pattern : " + hairClip8.pattern);
	System.out.println("sellerName : " + hairClip8.sellerName);
	System.out.println("countryOfOrigin : " + hairClip8.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip8.numberOfTeeth);
	System.out.println("customerReview : " + hairClip8.customerReview);
	System.out.println("rating : " + hairClip8.rating);
	System.out.println("isStockAvailable : " + hairClip8.isStockAvailable);
	System.out.println("grams : " + hairClip8.grams);



	HairClip hairClip9 = new HairClip();
	hairClip9.type = "Claw Clip";
	hairClip9.material = "Metal";
	hairClip9.colour = "Gold";
	hairClip9.price = 300;
	hairClip9.quantity = 2;
	hairClip9.brand = "GlamHair";
	hairClip9.isHandMade = true;
	hairClip9.isQualityGood = true;
	hairClip9.size = "Medium";
	hairClip9.weight = "18 grams";
	hairClip9.isAntique = false;
	hairClip9.warranty = "6 months";
	hairClip9.manufactureDate = "25-01-2026";
	hairClip9.isFlexible = false;
	hairClip9.shape = "Round";
	hairClip9.designType = "Floral";
	hairClip9.isStoneStudded = true;
	hairClip9.pattern = "Engraved";
	hairClip9.sellerName = "Amazon";
	hairClip9.countryOfOrigin = "India";
	hairClip9.numberOfTeeth = 12;
	hairClip9.customerReview = "Strong and stylish";
	hairClip9.rating = 5;
	hairClip9.isStockAvailable = true;
	hairClip9.grams = 18;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip9.type);
	System.out.println("material : " + hairClip9.material);
	System.out.println("colour : " + hairClip9.colour);
	System.out.println("price : " + hairClip9.price);
	System.out.println("quantity : " + hairClip9.quantity);
	System.out.println("brand : " + hairClip9.brand);
	System.out.println("isHandMade : " + hairClip9.isHandMade);
	System.out.println("isQualityGood : " + hairClip9.isQualityGood);
	System.out.println("size : " + hairClip9.size);
	System.out.println("weight : " + hairClip9.weight);
	System.out.println("isAntique : " + hairClip9.isAntique);
	System.out.println("warranty : " + hairClip9.warranty);
	System.out.println("manufactureDate : " + hairClip9.manufactureDate);
	System.out.println("isFlexible : " + hairClip9.isFlexible);
	System.out.println("shape : " + hairClip9.shape);
	System.out.println("designType : " + hairClip9.designType);
	System.out.println("isStoneStudded : " + hairClip9.isStoneStudded);
	System.out.println("pattern : " + hairClip9.pattern);
	System.out.println("sellerName : " + hairClip9.sellerName);
	System.out.println("countryOfOrigin : " + hairClip9.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip9.numberOfTeeth);
	System.out.println("customerReview : " + hairClip9.customerReview);
	System.out.println("rating : " + hairClip9.rating);
	System.out.println("isStockAvailable : " + hairClip9.isStockAvailable);
	System.out.println("grams : " + hairClip9.grams);



	HairClip hairClip10 = new HairClip();
	hairClip10.type = "Snap Clip";
	hairClip10.material = "Plastic";
	hairClip10.colour = "Blue";
	hairClip10.price = 110;
	hairClip10.quantity = 3;
	hairClip10.brand = "BeautyPro";
	hairClip10.isHandMade = false;
	hairClip10.isQualityGood = true;
	hairClip10.size = "Small";
	hairClip10.weight = "10 grams";
	hairClip10.isAntique = false;
	hairClip10.warranty = "3 months";
	hairClip10.manufactureDate = "28-01-2026";
	hairClip10.isFlexible = true;
	hairClip10.shape = "Oval";
	hairClip10.designType = "Plain";
	hairClip10.isStoneStudded = false;
	hairClip10.pattern = "Solid";
	hairClip10.sellerName = "Flipkart";
	hairClip10.countryOfOrigin = "India";
	hairClip10.numberOfTeeth = 8;
	hairClip10.customerReview = "Nice color";
	hairClip10.rating = 4;
	hairClip10.isStockAvailable = true;
	hairClip10.grams = 10;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip10.type);
	System.out.println("material : " + hairClip10.material);
	System.out.println("colour : " + hairClip10.colour);
	System.out.println("price : " + hairClip10.price);
	System.out.println("quantity : " + hairClip10.quantity);
	System.out.println("brand : " + hairClip10.brand);
	System.out.println("isHandMade : " + hairClip10.isHandMade);
	System.out.println("isQualityGood : " + hairClip10.isQualityGood);
	System.out.println("size : " + hairClip10.size);
	System.out.println("weight : " + hairClip10.weight);
	System.out.println("isAntique : " + hairClip10.isAntique);
	System.out.println("warranty : " + hairClip10.warranty);
	System.out.println("manufactureDate : " + hairClip10.manufactureDate);
	System.out.println("isFlexible : " + hairClip10.isFlexible);
	System.out.println("shape : " + hairClip10.shape);
	System.out.println("designType : " + hairClip10.designType);
	System.out.println("isStoneStudded : " + hairClip10.isStoneStudded);
	System.out.println("pattern : " + hairClip10.pattern);
	System.out.println("sellerName : " + hairClip10.sellerName);
	System.out.println("countryOfOrigin : " + hairClip10.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip10.numberOfTeeth);
	System.out.println("customerReview : " + hairClip10.customerReview);
	System.out.println("rating : " + hairClip10.rating);
	System.out.println("isStockAvailable : " + hairClip10.isStockAvailable);
	System.out.println("grams : " + hairClip10.grams);


	HairClip hairClip11 = new HairClip();
	hairClip11.type = "Banana Clip";
	hairClip11.material = "Plastic";
	hairClip11.colour = "Black";
	hairClip11.price = 200;
	hairClip11.quantity = 2;
	hairClip11.brand = "HairTrend";
	hairClip11.isHandMade = false;
	hairClip11.isQualityGood = true;
	hairClip11.size = "Large";
	hairClip11.weight = "22 grams";
	hairClip11.isAntique = false;
	hairClip11.warranty = "6 months";
	hairClip11.manufactureDate = "30-01-2026";
	hairClip11.isFlexible = true;
	hairClip11.shape = "Curved";
	hairClip11.designType = "Plain";
	hairClip11.isStoneStudded = false;
	hairClip11.pattern = "Solid";
	hairClip11.sellerName = "Amazon";
	hairClip11.countryOfOrigin = "India";
	hairClip11.numberOfTeeth = 15;
	hairClip11.customerReview = "Strong clip";
	hairClip11.rating = 5;
	hairClip11.isStockAvailable = true;
	hairClip11.grams = 22;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip11.type);
	System.out.println("material : " + hairClip11.material);
	System.out.println("colour : " + hairClip11.colour);
	System.out.println("price : " + hairClip11.price);
	System.out.println("quantity : " + hairClip11.quantity);
	System.out.println("brand : " + hairClip11.brand);
	System.out.println("isHandMade : " + hairClip11.isHandMade);
	System.out.println("isQualityGood : " + hairClip11.isQualityGood);
	System.out.println("size : " + hairClip11.size);
	System.out.println("weight : " + hairClip11.weight);
	System.out.println("isAntique : " + hairClip11.isAntique);
	System.out.println("warranty : " + hairClip11.warranty);
	System.out.println("manufactureDate : " + hairClip11.manufactureDate);
	System.out.println("isFlexible : " + hairClip11.isFlexible);
	System.out.println("shape : " + hairClip11.shape);
	System.out.println("designType : " + hairClip11.designType);
	System.out.println("isStoneStudded : " + hairClip11.isStoneStudded);
	System.out.println("pattern : " + hairClip11.pattern);
	System.out.println("sellerName : " + hairClip11.sellerName);
	System.out.println("countryOfOrigin : " + hairClip11.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip11.numberOfTeeth);
	System.out.println("customerReview : " + hairClip11.customerReview);
	System.out.println("rating : " + hairClip11.rating);
	System.out.println("isStockAvailable : " + hairClip11.isStockAvailable);
	System.out.println("grams : " + hairClip11.grams);



	HairClip hairClip12 = new HairClip();
	hairClip12.type = "Claw Clip";
	hairClip12.material = "Metal";
	hairClip12.colour = "Rose Gold";
	hairClip12.price = 350;
	hairClip12.quantity = 2;
	hairClip12.brand = "GlamHair";
	hairClip12.isHandMade = true;
	hairClip12.isQualityGood = true;
	hairClip12.size = "Medium";
	hairClip12.weight = "19 grams";
	hairClip12.isAntique = false;
	hairClip12.warranty = "6 months";
	hairClip12.manufactureDate = "02-02-2026";
	hairClip12.isFlexible = false;
	hairClip12.shape = "Round";
	hairClip12.designType = "Floral";
	hairClip12.isStoneStudded = true;
	hairClip12.pattern = "Engraved";
	hairClip12.sellerName = "Amazon";
	hairClip12.countryOfOrigin = "India";
	hairClip12.numberOfTeeth = 12;
	hairClip12.customerReview = "Stylish and strong";
	hairClip12.rating = 5;
	hairClip12.isStockAvailable = true;
	hairClip12.grams = 19;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip12.type);
	System.out.println("material : " + hairClip12.material);
	System.out.println("colour : " + hairClip12.colour);
	System.out.println("price : " + hairClip12.price);
	System.out.println("quantity : " + hairClip12.quantity);
	System.out.println("brand : " + hairClip12.brand);
	System.out.println("isHandMade : " + hairClip12.isHandMade);
	System.out.println("isQualityGood : " + hairClip12.isQualityGood);
	System.out.println("size : " + hairClip12.size);
	System.out.println("weight : " + hairClip12.weight);
	System.out.println("isAntique : " + hairClip12.isAntique);
	System.out.println("warranty : " + hairClip12.warranty);
	System.out.println("manufactureDate : " + hairClip12.manufactureDate);
	System.out.println("isFlexible : " + hairClip12.isFlexible);
	System.out.println("shape : " + hairClip12.shape);
	System.out.println("designType : " + hairClip12.designType);
	System.out.println("isStoneStudded : " + hairClip12.isStoneStudded);
	System.out.println("pattern : " + hairClip12.pattern);
	System.out.println("sellerName : " + hairClip12.sellerName);
	System.out.println("countryOfOrigin : " + hairClip12.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip12.numberOfTeeth);
	System.out.println("customerReview : " + hairClip12.customerReview);
	System.out.println("rating : " + hairClip12.rating);
	System.out.println("isStockAvailable : " + hairClip12.isStockAvailable);
	System.out.println("grams : " + hairClip12.grams);



	HairClip hairClip13 = new HairClip();
	hairClip13.type = "Snap Clip";
	hairClip13.material = "Plastic";
	hairClip13.colour = "Purple";
	hairClip13.price = 120;
	hairClip13.quantity = 3;
	hairClip13.brand = "BeautyPro";
	hairClip13.isHandMade = false;
	hairClip13.isQualityGood = true;
	hairClip13.size = "Small";
	hairClip13.weight = "12 grams";
	hairClip13.isAntique = false;
	hairClip13.warranty = "3 months";
	hairClip13.manufactureDate = "04-02-2026";
	hairClip13.isFlexible = true;
	hairClip13.shape = "Oval";
	hairClip13.designType = "Plain";
	hairClip13.isStoneStudded = false;
	hairClip13.pattern = "Solid";
	hairClip13.sellerName = "Flipkart";
	hairClip13.countryOfOrigin = "India";
	hairClip13.numberOfTeeth = 9;
	hairClip13.customerReview = "Good color";
	hairClip13.rating = 4;
	hairClip13.isStockAvailable = true;
	hairClip13.grams = 12;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip13.type);
	System.out.println("material : " + hairClip13.material);
	System.out.println("colour : " + hairClip13.colour);
	System.out.println("price : " + hairClip13.price);
	System.out.println("quantity : " + hairClip13.quantity);
	System.out.println("brand : " + hairClip13.brand);
	System.out.println("isHandMade : " + hairClip13.isHandMade);
	System.out.println("isQualityGood : " + hairClip13.isQualityGood);
	System.out.println("size : " + hairClip13.size);
	System.out.println("weight : " + hairClip13.weight);
	System.out.println("isAntique : " + hairClip13.isAntique);
	System.out.println("warranty : " + hairClip13.warranty);
	System.out.println("manufactureDate : " + hairClip13.manufactureDate);
	System.out.println("isFlexible : " + hairClip13.isFlexible);
	System.out.println("shape : " + hairClip13.shape);
	System.out.println("designType : " + hairClip13.designType);
	System.out.println("isStoneStudded : " + hairClip13.isStoneStudded);
	System.out.println("pattern : " + hairClip13.pattern);
	System.out.println("sellerName : " + hairClip13.sellerName);
	System.out.println("countryOfOrigin : " + hairClip13.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip13.numberOfTeeth);
	System.out.println("customerReview : " + hairClip13.customerReview);
	System.out.println("rating : " + hairClip13.rating);
	System.out.println("isStockAvailable : " + hairClip13.isStockAvailable);
	System.out.println("grams : " + hairClip13.grams);

	HairClip hairClip14 = new HairClip();
	hairClip14.type = "Banana Clip";
	hairClip14.material = "Plastic";
	hairClip14.colour = "Brown";
	hairClip14.price = 190;
	hairClip14.quantity = 2;
	hairClip14.brand = "HairTrend";
	hairClip14.isHandMade = false;
	hairClip14.isQualityGood = true;
	hairClip14.size = "Large";
	hairClip14.weight = "21 grams";
	hairClip14.isAntique = false;
	hairClip14.warranty = "6 months";
	hairClip14.manufactureDate = "06-02-2026";
	hairClip14.isFlexible = true;
	hairClip14.shape = "Curved";
	hairClip14.designType = "Plain";
	hairClip14.isStoneStudded = false;
	hairClip14.pattern = "Solid";
	hairClip14.sellerName = "Amazon";
	hairClip14.countryOfOrigin = "India";
	hairClip14.numberOfTeeth = 14;
	hairClip14.customerReview = "Durable and stylish";
	hairClip14.rating = 5;
	hairClip14.isStockAvailable = true;
	hairClip14.grams = 21;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip14.type);
	System.out.println("material : " + hairClip14.material);
	System.out.println("colour : " + hairClip14.colour);
	System.out.println("price : " + hairClip14.price);
	System.out.println("quantity : " + hairClip14.quantity);
	System.out.println("brand : " + hairClip14.brand);
	System.out.println("isHandMade : " + hairClip14.isHandMade);
	System.out.println("isQualityGood : " + hairClip14.isQualityGood);
	System.out.println("size : " + hairClip14.size);
	System.out.println("weight : " + hairClip14.weight);
	System.out.println("isAntique : " + hairClip14.isAntique);
	System.out.println("warranty : " + hairClip14.warranty);
	System.out.println("manufactureDate : " + hairClip14.manufactureDate);
	System.out.println("isFlexible : " + hairClip14.isFlexible);
	System.out.println("shape : " + hairClip14.shape);
	System.out.println("designType : " + hairClip14.designType);
	System.out.println("isStoneStudded : " + hairClip14.isStoneStudded);
	System.out.println("pattern : " + hairClip14.pattern);
	System.out.println("sellerName : " + hairClip14.sellerName);
	System.out.println("countryOfOrigin : " + hairClip14.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip14.numberOfTeeth);
	System.out.println("customerReview : " + hairClip14.customerReview);
	System.out.println("rating : " + hairClip14.rating);
	System.out.println("isStockAvailable : " + hairClip14.isStockAvailable);
	System.out.println("grams : " + hairClip14.grams);




	HairClip hairClip15 = new HairClip();
	hairClip15.type = "Claw Clip";
	hairClip15.material = "Metal";
	hairClip15.colour = "Gold";
	hairClip15.price = 320;
	hairClip15.quantity = 2;
	hairClip15.brand = "GlamHair";
	hairClip15.isHandMade = true;
	hairClip15.isQualityGood = true;
	hairClip15.size = "Medium";
	hairClip15.weight = "20 grams";
	hairClip15.isAntique = false;
	hairClip15.warranty = "6 months";
	hairClip15.manufactureDate = "08-02-2026";
	hairClip15.isFlexible = false;
	hairClip15.shape = "Round";
	hairClip15.designType = "Floral";
	hairClip15.isStoneStudded = true;
	hairClip15.pattern = "Engraved";
	hairClip15.sellerName = "Amazon";
	hairClip15.countryOfOrigin = "India";
	hairClip15.numberOfTeeth = 13;
	hairClip15.customerReview = "Beautiful design";
	hairClip15.rating = 5;
	hairClip15.isStockAvailable = true;
	hairClip15.grams = 20;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip15.type);
	System.out.println("material : " + hairClip15.material);
	System.out.println("colour : " + hairClip15.colour);
	System.out.println("price : " + hairClip15.price);
	System.out.println("quantity : " + hairClip15.quantity);
	System.out.println("brand : " + hairClip15.brand);
	System.out.println("isHandMade : " + hairClip15.isHandMade);
	System.out.println("isQualityGood : " + hairClip15.isQualityGood);
	System.out.println("size : " + hairClip15.size);
	System.out.println("weight : " + hairClip15.weight);
	System.out.println("isAntique : " + hairClip15.isAntique);
	System.out.println("warranty : " + hairClip15.warranty);
	System.out.println("manufactureDate : " + hairClip15.manufactureDate);
	System.out.println("isFlexible : " + hairClip15.isFlexible);
	System.out.println("shape : " + hairClip15.shape);
	System.out.println("designType : " + hairClip15.designType);
	System.out.println("isStoneStudded : " + hairClip15.isStoneStudded);
	System.out.println("pattern : " + hairClip15.pattern);
	System.out.println("sellerName : " + hairClip15.sellerName);
	System.out.println("countryOfOrigin : " + hairClip15.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip15.numberOfTeeth);
	System.out.println("customerReview : " + hairClip15.customerReview);
	System.out.println("rating : " + hairClip15.rating);
	System.out.println("isStockAvailable : " + hairClip15.isStockAvailable);
	System.out.println("grams : " + hairClip15.grams);


	HairClip hairClip16 = new HairClip();
	hairClip16.type = "Snap Clip";
	hairClip16.material = "Plastic";
	hairClip16.colour = "Red";
	hairClip16.price = 125;
	hairClip16.quantity = 4;
	hairClip16.brand = "BeautyPro";
	hairClip16.isHandMade = false;
	hairClip16.isQualityGood = true;
	hairClip16.size = "Small";
	hairClip16.weight = "11 grams";
	hairClip16.isAntique = false;
	hairClip16.warranty = "3 months";
	hairClip16.manufactureDate = "10-02-2026";
	hairClip16.isFlexible = true;
	hairClip16.shape = "Oval";
	hairClip16.designType = "Plain";
	hairClip16.isStoneStudded = false;
	hairClip16.pattern = "Solid";
	hairClip16.sellerName = "Flipkart";
	hairClip16.countryOfOrigin = "India";
	hairClip16.numberOfTeeth = 8;
	hairClip16.customerReview = "Nice and bright";
	hairClip16.rating = 4;
	hairClip16.isStockAvailable = true;
	hairClip16.grams = 11;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip16.type);
	System.out.println("material : " + hairClip16.material);
	System.out.println("colour : " + hairClip16.colour);
	System.out.println("price : " + hairClip16.price);
	System.out.println("quantity : " + hairClip16.quantity);
	System.out.println("brand : " + hairClip16.brand);
	System.out.println("isHandMade : " + hairClip16.isHandMade);
	System.out.println("isQualityGood : " + hairClip16.isQualityGood);
	System.out.println("size : " + hairClip16.size);
	System.out.println("weight : " + hairClip16.weight);
	System.out.println("isAntique : " + hairClip16.isAntique);
	System.out.println("warranty : " + hairClip16.warranty);
	System.out.println("manufactureDate : " + hairClip16.manufactureDate);
	System.out.println("isFlexible : " + hairClip16.isFlexible);
	System.out.println("shape : " + hairClip16.shape);
	System.out.println("designType : " + hairClip16.designType);
	System.out.println("isStoneStudded : " + hairClip16.isStoneStudded);
	System.out.println("pattern : " + hairClip16.pattern);
	System.out.println("sellerName : " + hairClip16.sellerName);
	System.out.println("countryOfOrigin : " + hairClip16.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip16.numberOfTeeth);
	System.out.println("customerReview : " + hairClip16.customerReview);
	System.out.println("rating : " + hairClip16.rating);
	System.out.println("isStockAvailable : " + hairClip16.isStockAvailable);
	System.out.println("grams : " + hairClip16.grams);


	HairClip hairClip17 = new HairClip();
	hairClip17.type = "Claw Clip";
	hairClip17.material = "Metal";
	hairClip17.colour = "Silver";
	hairClip17.price = 340;
	hairClip17.quantity = 2;
	hairClip17.brand = "GlamHair";
	hairClip17.isHandMade = true;
	hairClip17.isQualityGood = true;
	hairClip17.size = "Medium";
	hairClip17.weight = "21 grams";
	hairClip17.isAntique = false;
	hairClip17.warranty = "6 months";
	hairClip17.manufactureDate = "12-02-2026";
	hairClip17.isFlexible = false;
	hairClip17.shape = "Round";
	hairClip17.designType = "Floral";
	hairClip17.isStoneStudded = true;
	hairClip17.pattern = "Engraved";
	hairClip17.sellerName = "Amazon";
	hairClip17.countryOfOrigin = "India";
	hairClip17.numberOfTeeth = 12;
	hairClip17.customerReview = "Elegant and sturdy";
	hairClip17.rating = 5;
	hairClip17.isStockAvailable = true;
	hairClip17.grams = 21;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip17.type);
	System.out.println("material : " + hairClip17.material);
	System.out.println("colour : " + hairClip17.colour);
	System.out.println("price : " + hairClip17.price);
	System.out.println("quantity : " + hairClip17.quantity);
	System.out.println("brand : " + hairClip17.brand);
	System.out.println("isHandMade : " + hairClip17.isHandMade);
	System.out.println("isQualityGood : " + hairClip17.isQualityGood);
	System.out.println("size : " + hairClip17.size);
	System.out.println("weight : " + hairClip17.weight);
	System.out.println("isAntique : " + hairClip17.isAntique);
	System.out.println("warranty : " + hairClip17.warranty);
	System.out.println("manufactureDate : " + hairClip17.manufactureDate);
	System.out.println("isFlexible : " + hairClip17.isFlexible);
	System.out.println("shape : " + hairClip17.shape);
	System.out.println("designType : " + hairClip17.designType);
	System.out.println("isStoneStudded : " + hairClip17.isStoneStudded);
	System.out.println("pattern : " + hairClip17.pattern);
	System.out.println("sellerName : " + hairClip17.sellerName);
	System.out.println("countryOfOrigin : " + hairClip17.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip17.numberOfTeeth);
	System.out.println("customerReview : " + hairClip17.customerReview);
	System.out.println("rating : " + hairClip17.rating);
	System.out.println("isStockAvailable : " + hairClip17.isStockAvailable);
	System.out.println("grams : " + hairClip17.grams);

	HairClip hairClip18 = new HairClip();
	hairClip18.type = "Snap Clip";
	hairClip18.material = "Plastic";
	hairClip18.colour = "Green";
	hairClip18.price = 130;
	hairClip18.quantity = 3;
	hairClip18.brand = "BeautyPro";
	hairClip18.isHandMade = false;
	hairClip18.isQualityGood = true;
	hairClip18.size = "Small";
	hairClip18.weight = "12 grams";
	hairClip18.isAntique = false;
	hairClip18.warranty = "3 months";
	hairClip18.manufactureDate = "14-02-2026";
	hairClip18.isFlexible = true;
	hairClip18.shape = "Oval";
	hairClip18.designType = "Plain";
	hairClip18.isStoneStudded = false;
	hairClip18.pattern = "Solid";
	hairClip18.sellerName = "Flipkart";
	hairClip18.countryOfOrigin = "India";
	hairClip18.numberOfTeeth = 8;
	hairClip18.customerReview = "Nice and durable";
	hairClip18.rating = 4;
	hairClip18.isStockAvailable = true;
	hairClip18.grams = 12;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip18.type);
	System.out.println("material : " + hairClip18.material);
	System.out.println("colour : " + hairClip18.colour);
	System.out.println("price : " + hairClip18.price);
	System.out.println("quantity : " + hairClip18.quantity);
	System.out.println("brand : " + hairClip18.brand);
	System.out.println("isHandMade : " + hairClip18.isHandMade);
	System.out.println("isQualityGood : " + hairClip18.isQualityGood);
	System.out.println("size : " + hairClip18.size);
	System.out.println("weight : " + hairClip18.weight);
	System.out.println("isAntique : " + hairClip18.isAntique);
	System.out.println("warranty : " + hairClip18.warranty);
	System.out.println("manufactureDate : " + hairClip18.manufactureDate);
	System.out.println("isFlexible : " + hairClip18.isFlexible);
	System.out.println("shape : " + hairClip18.shape);
	System.out.println("designType : " + hairClip18.designType);
	System.out.println("isStoneStudded : " + hairClip18.isStoneStudded);
	System.out.println("pattern : " + hairClip18.pattern);
	System.out.println("sellerName : " + hairClip18.sellerName);
	System.out.println("countryOfOrigin : " + hairClip18.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip18.numberOfTeeth);
	System.out.println("customerReview : " + hairClip18.customerReview);
	System.out.println("rating : " + hairClip18.rating);
	System.out.println("isStockAvailable : " + hairClip18.isStockAvailable);
	System.out.println("grams : " + hairClip18.grams);


	HairClip hairClip19 = new HairClip();
	hairClip19.type = "Banana Clip";
	hairClip19.material = "Plastic";
	hairClip19.colour = "Pink";
	hairClip19.price = 180;
	hairClip19.quantity = 2;
	hairClip19.brand = "HairTrend";
	hairClip19.isHandMade = false;
	hairClip19.isQualityGood = true;
	hairClip19.size = "Large";
	hairClip19.weight = "20 grams";
	hairClip19.isAntique = false;
	hairClip19.warranty = "6 months";
	hairClip19.manufactureDate = "16-02-2026";
	hairClip19.isFlexible = true;
	hairClip19.shape = "Curved";
	hairClip19.designType = "Plain";
	hairClip19.isStoneStudded = false;
	hairClip19.pattern = "Solid";
	hairClip19.sellerName = "Amazon";
	hairClip19.countryOfOrigin = "India";
	hairClip19.numberOfTeeth = 14;
	hairClip19.customerReview = "Good quality and flexible";
	hairClip19.rating = 5;
	hairClip19.isStockAvailable = true;
	hairClip19.grams = 20;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip19.type);
	System.out.println("material : " + hairClip19.material);
	System.out.println("colour : " + hairClip19.colour);
	System.out.println("price : " + hairClip19.price);
	System.out.println("quantity : " + hairClip19.quantity);
	System.out.println("brand : " + hairClip19.brand);
	System.out.println("isHandMade : " + hairClip19.isHandMade);
	System.out.println("isQualityGood : " + hairClip19.isQualityGood);
	System.out.println("size : " + hairClip19.size);
	System.out.println("weight : " + hairClip19.weight);
	System.out.println("isAntique : " + hairClip19.isAntique);
	System.out.println("warranty : " + hairClip19.warranty);
	System.out.println("manufactureDate : " + hairClip19.manufactureDate);
	System.out.println("isFlexible : " + hairClip19.isFlexible);
	System.out.println("shape : " + hairClip19.shape);
	System.out.println("designType : " + hairClip19.designType);
	System.out.println("isStoneStudded : " + hairClip19.isStoneStudded);
	System.out.println("pattern : " + hairClip19.pattern);
	System.out.println("sellerName : " + hairClip19.sellerName);
	System.out.println("countryOfOrigin : " + hairClip19.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip19.numberOfTeeth);
	System.out.println("customerReview : " + hairClip19.customerReview);
	System.out.println("rating : " + hairClip19.rating);
	System.out.println("isStockAvailable : " + hairClip19.isStockAvailable);
	System.out.println("grams : " + hairClip19.grams);


	HairClip hairClip20 = new HairClip();
	hairClip20.type = "Claw Clip";
	hairClip20.material = "Metal";
	hairClip20.colour = "Bronze";
	hairClip20.price = 360;
	hairClip20.quantity = 2;
	hairClip20.brand = "GlamHair";
	hairClip20.isHandMade = true;
	hairClip20.isQualityGood = true;
	hairClip20.size = "Medium";
	hairClip20.weight = "22 grams";
	hairClip20.isAntique = false;
	hairClip20.warranty = "6 months";
	hairClip20.manufactureDate = "18-02-2026";
	hairClip20.isFlexible = false;
	hairClip20.shape = "Round";
	hairClip20.designType = "Floral";
	hairClip20.isStoneStudded = true;
	hairClip20.pattern = "Engraved";
	hairClip20.sellerName = "Amazon";
	hairClip20.countryOfOrigin = "India";
	hairClip20.numberOfTeeth = 13;
	hairClip20.customerReview = "Strong and elegant";
	hairClip20.rating = 5;
	hairClip20.isStockAvailable = true;
	hairClip20.grams = 22;

	System.out.println("after init instance variable");
	System.out.println("type : " + hairClip20.type);
	System.out.println("material : " + hairClip20.material);
	System.out.println("colour : " + hairClip20.colour);
	System.out.println("price : " + hairClip20.price);
	System.out.println("quantity : " + hairClip20.quantity);
	System.out.println("brand : " + hairClip20.brand);
	System.out.println("isHandMade : " + hairClip20.isHandMade);
	System.out.println("isQualityGood : " + hairClip20.isQualityGood);
	System.out.println("size : " + hairClip20.size);
	System.out.println("weight : " + hairClip20.weight);
	System.out.println("isAntique : " + hairClip20.isAntique);
	System.out.println("warranty : " + hairClip20.warranty);
	System.out.println("manufactureDate : " + hairClip20.manufactureDate);
	System.out.println("isFlexible : " + hairClip20.isFlexible);
	System.out.println("shape : " + hairClip20.shape);
	System.out.println("designType : " + hairClip20.designType);
	System.out.println("isStoneStudded : " + hairClip20.isStoneStudded);
	System.out.println("pattern : " + hairClip20.pattern);
	System.out.println("sellerName : " + hairClip20.sellerName);
	System.out.println("countryOfOrigin : " + hairClip20.countryOfOrigin);
	System.out.println("numberOfTeeth : " + hairClip20.numberOfTeeth);
	System.out.println("customerReview : " + hairClip20.customerReview);
	System.out.println("rating : " + hairClip20.rating);
	System.out.println("isStockAvailable : " + hairClip20.isStockAvailable);
	System.out.println("grams : " + hairClip20.grams);

	}

	}