class CombExecutor{
    public static void main(String[] args){
	HairComb comb1 = new HairComb();
	System.out.println("after init instance variable");
	System.out.println("type : " + comb1.type);
	System.out.println("material : " + comb1.material);
	System.out.println("price : " + comb1.price);
	System.out.println("quantity : " + comb1.quantity);
	System.out.println("brand : " + comb1.brand);
	System.out.println("colour : " + comb1.colour);
	System.out.println("isMultipleColour : " + comb1.isMultipleColour);
	System.out.println("isQualityGood : " + comb1.isQualityGood);
	System.out.println("size : " + comb1.size);
	System.out.println("weight : " + comb1.weight);
	System.out.println("isAntique : " + comb1.isAntique);
	System.out.println("warranty : " + comb1.warranty);
	System.out.println("manufactureDate : " + comb1.manufactureDate);
	System.out.println("isHandMade : " + comb1.isHandMade);
	System.out.println("discount : " + comb1.discount);
	System.out.println("sellerName : " + comb1.sellerName);
	System.out.println("numberOfTeeth : " + comb1.numberOfTeeth);
	System.out.println("customerReview : " + comb1.customerReview);
	System.out.println("rating : " + comb1.rating);
	System.out.println("isLightWeight : " + comb1.isLightWeight);
	System.out.println("countryOfOrigin : " + comb1.countryOfOrigin);
	System.out.println("designType : " + comb1.designType);
	System.out.println("pattern : " + comb1.pattern);
	System.out.println("length : " + comb1.length);
	System.out.println("isStockAvailable : " + comb1.isStockAvailable);
	System.out.println("grams : " + comb1.grams);
	comb1.type = "Wide Tooth Comb";
	comb1.material = "Plastic";
	comb1.price = 120;
	comb1.quantity = 1;
	comb1.brand = "Vega";
	comb1.colour = "Black";
	comb1.isMultipleColour = false;
	comb1.isQualityGood = true;
	comb1.size = "Medium";
	comb1.weight = "20 grams";
	comb1.isAntique = false;
	comb1.warranty = "6 months";
	comb1.manufactureDate = "10-03-2026";
	comb1.isHandMade = false;
	comb1.discount = "5%";
	comb1.sellerName = "Amazon Seller";
	comb1.numberOfTeeth = 25;
	comb1.customerReview = "Good for daily use";
	comb1.rating = 4;
	comb1.isLightWeight = true;
	comb1.countryOfOrigin = "India";
	comb1.designType = "Classic";
	comb1.pattern = "Straight";
	comb1.length = 18;
	comb1.isStockAvailable = true;
	comb1.grams = 20;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb1.type);
	System.out.println("material : " + comb1.material);
	System.out.println("price : " + comb1.price);
	System.out.println("quantity : " + comb1.quantity);
	System.out.println("brand : " + comb1.brand);
	System.out.println("colour : " + comb1.colour);
	System.out.println("isMultipleColour : " + comb1.isMultipleColour);
	System.out.println("isQualityGood : " + comb1.isQualityGood);
	System.out.println("size : " + comb1.size);
	System.out.println("weight : " + comb1.weight);
	System.out.println("isAntique : " + comb1.isAntique);
	System.out.println("warranty : " + comb1.warranty);
	System.out.println("manufactureDate : " + comb1.manufactureDate);
	System.out.println("isHandMade : " + comb1.isHandMade);
	System.out.println("discount : " + comb1.discount);
	System.out.println("sellerName : " + comb1.sellerName);
	System.out.println("numberOfTeeth : " + comb1.numberOfTeeth);
	System.out.println("customerReview : " + comb1.customerReview);
	System.out.println("rating : " + comb1.rating);
	System.out.println("isLightWeight : " + comb1.isLightWeight);
	System.out.println("countryOfOrigin : " + comb1.countryOfOrigin);
	System.out.println("designType : " + comb1.designType);
	System.out.println("pattern : " + comb1.pattern);
	System.out.println("length : " + comb1.length);
	System.out.println("isStockAvailable : " + comb1.isStockAvailable);
	System.out.println("grams : " + comb1.grams);



	HairComb comb2 = new HairComb();
	comb2.type = "Wide Tooth Comb";
	comb2.material = "Plastic";
	comb2.price = 120;
	comb2.quantity = 1;
	comb2.brand = "Vega";
	comb2.colour = "Black";
	comb2.isMultipleColour = false;
	comb2.isQualityGood = true;
	comb2.size = "Medium";
	comb2.weight = "20 grams";
	comb2.isAntique = false;
	comb2.warranty = "6 months";
	comb2.manufactureDate = "05-03-2026";
	comb2.isHandMade = false;
	comb2.discount = "5%";
	comb2.sellerName = "Amazon Seller";
	comb2.numberOfTeeth = 25;
	comb2.customerReview = "Good for daily use";
	comb2.rating = 4;
	comb2.isLightWeight = true;
	comb2.countryOfOrigin = "India";
	comb2.designType = "Classic";
	comb2.pattern = "Straight";
	comb2.length = 18;
	comb2.isStockAvailable = true;
	comb2.grams = 20;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb2.type);
	System.out.println("material : " + comb2.material);
	System.out.println("price : " + comb2.price);
	System.out.println("quantity : " + comb2.quantity);
	System.out.println("brand : " + comb2.brand);
	System.out.println("colour : " + comb2.colour);
	System.out.println("isMultipleColour : " + comb2.isMultipleColour);
	System.out.println("isQualityGood : " + comb2.isQualityGood);
	System.out.println("size : " + comb2.size);
	System.out.println("weight : " + comb2.weight);
	System.out.println("isAntique : " + comb2.isAntique);
	System.out.println("warranty : " + comb2.warranty);
	System.out.println("manufactureDate : " + comb2.manufactureDate);
	System.out.println("isHandMade : " + comb2.isHandMade);
	System.out.println("discount : " + comb2.discount);
	System.out.println("sellerName : " + comb2.sellerName);
	System.out.println("numberOfTeeth : " + comb2.numberOfTeeth);
	System.out.println("customerReview : " + comb2.customerReview);
	System.out.println("rating : " + comb2.rating);
	System.out.println("isLightWeight : " + comb2.isLightWeight);
	System.out.println("countryOfOrigin : " + comb2.countryOfOrigin);
	System.out.println("designType : " + comb2.designType);
	System.out.println("pattern : " + comb2.pattern);
	System.out.println("length : " + comb2.length);
	System.out.println("isStockAvailable : " + comb2.isStockAvailable);
	System.out.println("grams : " + comb2.grams);



	HairComb comb3 = new HairComb();
	comb3.type = "Fine Tooth Comb";
	comb3.material = "Plastic";
	comb3.price = 90;
	comb3.quantity = 1;
	comb3.brand = "Syska";
	comb3.colour = "Blue";
	comb3.isMultipleColour = false;
	comb3.isQualityGood = true;
	comb3.size = "Small";
	comb3.weight = "15 grams";
	comb3.isAntique = false;
	comb3.warranty = "6 months";
	comb3.manufactureDate = "04-03-2026";
	comb3.isHandMade = false;
	comb3.discount = "3%";
	comb3.sellerName = "Flipkart Seller";
	comb3.numberOfTeeth = 40;
	comb3.customerReview = "Smooth combing";
	comb3.rating = 4;
	comb3.isLightWeight = true;
	comb3.countryOfOrigin = "India";
	comb3.designType = "Modern";
	comb3.pattern = "Straight";
	comb3.length = 16;
	comb3.isStockAvailable = true;
	comb3.grams = 15;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb3.type);
	System.out.println("material : " + comb3.material);
	System.out.println("price : " + comb3.price);
	System.out.println("quantity : " + comb3.quantity);
	System.out.println("brand : " + comb3.brand);
	System.out.println("colour : " + comb3.colour);
	System.out.println("isMultipleColour : " + comb3.isMultipleColour);
	System.out.println("isQualityGood : " + comb3.isQualityGood);
	System.out.println("size : " + comb3.size);
	System.out.println("weight : " + comb3.weight);
	System.out.println("isAntique : " + comb3.isAntique);
	System.out.println("warranty : " + comb3.warranty);
	System.out.println("manufactureDate : " + comb3.manufactureDate);
	System.out.println("isHandMade : " + comb3.isHandMade);
	System.out.println("discount : " + comb3.discount);
	System.out.println("sellerName : " + comb3.sellerName);
	System.out.println("numberOfTeeth : " + comb3.numberOfTeeth);
	System.out.println("customerReview : " + comb3.customerReview);
	System.out.println("rating : " + comb3.rating);
	System.out.println("isLightWeight : " + comb3.isLightWeight);
	System.out.println("countryOfOrigin : " + comb3.countryOfOrigin);
	System.out.println("designType : " + comb3.designType);
	System.out.println("pattern : " + comb3.pattern);
	System.out.println("length : " + comb3.length);
	System.out.println("isStockAvailable : " + comb3.isStockAvailable);
	System.out.println("grams : " + comb3.grams);



	HairComb comb4 = new HairComb();
	comb4.type = "Wooden Comb";
	comb4.material = "Wood";
	comb4.price = 250;
	comb4.quantity = 1;
	comb4.brand = "Forest Essentials";
	comb4.colour = "Brown";
	comb4.isMultipleColour = false;
	comb4.isQualityGood = true;
	comb4.size = "Medium";
	comb4.weight = "30 grams";
	comb4.isAntique = false;
	comb4.warranty = "1 year";
	comb4.manufactureDate = "02-03-2026";
	comb4.isHandMade = true;
	comb4.discount = "8%";
	comb4.sellerName = "Organic Store";
	comb4.numberOfTeeth = 20;
	comb4.customerReview = "Good for hair health";
	comb4.rating = 5;
	comb4.isLightWeight = false;
	comb4.countryOfOrigin = "India";
	comb4.designType = "Traditional";
	comb4.pattern = "Wood Grain";
	comb4.length = 19;
	comb4.isStockAvailable = true;
	comb4.grams = 30;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb4.type);
	System.out.println("material : " + comb4.material);
	System.out.println("price : " + comb4.price);
	System.out.println("quantity : " + comb4.quantity);
	System.out.println("brand : " + comb4.brand);
	System.out.println("colour : " + comb4.colour);
	System.out.println("isMultipleColour : " + comb4.isMultipleColour);
	System.out.println("isQualityGood : " + comb4.isQualityGood);
	System.out.println("size : " + comb4.size);
	System.out.println("weight : " + comb4.weight);
	System.out.println("isAntique : " + comb4.isAntique);
	System.out.println("warranty : " + comb4.warranty);
	System.out.println("manufactureDate : " + comb4.manufactureDate);
	System.out.println("isHandMade : " + comb4.isHandMade);
	System.out.println("discount : " + comb4.discount);
	System.out.println("sellerName : " + comb4.sellerName);
	System.out.println("numberOfTeeth : " + comb4.numberOfTeeth);
	System.out.println("customerReview : " + comb4.customerReview);
	System.out.println("rating : " + comb4.rating);
	System.out.println("isLightWeight : " + comb4.isLightWeight);
	System.out.println("countryOfOrigin : " + comb4.countryOfOrigin);
	System.out.println("designType : " + comb4.designType);
	System.out.println("pattern : " + comb4.pattern);
	System.out.println("length : " + comb4.length);
	System.out.println("isStockAvailable : " + comb4.isStockAvailable);
	System.out.println("grams : " + comb4.grams);

	HairComb comb5 = new HairComb();
	comb5.type = "Pocket Comb";
	comb5.material = "Plastic";
	comb5.price = 60;
	comb5.quantity = 1;
	comb5.brand = "Vega";
	comb5.colour = "Red";
	comb5.isMultipleColour = false;
	comb5.isQualityGood = true;
	comb5.size = "Small";
	comb5.weight = "10 grams";
	comb5.isAntique = false;
	comb5.warranty = "3 months";
	comb5.manufactureDate = "01-03-2026";
	comb5.isHandMade = false;
	comb5.discount = "2%";
	comb5.sellerName = "Local Store";
	comb5.numberOfTeeth = 35;
	comb5.customerReview = "Easy to carry";
	comb5.rating = 4;
	comb5.isLightWeight = true;
	comb5.countryOfOrigin = "India";
	comb5.designType = "Simple";
	comb5.pattern = "Plain";
	comb5.length = 14;
	comb5.isStockAvailable = true;
	comb5.grams = 10;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb5.type);
	System.out.println("material : " + comb5.material);
	System.out.println("price : " + comb5.price);
	System.out.println("quantity : " + comb5.quantity);
	System.out.println("brand : " + comb5.brand);
	System.out.println("colour : " + comb5.colour);
	System.out.println("isMultipleColour : " + comb5.isMultipleColour);
	System.out.println("isQualityGood : " + comb5.isQualityGood);
	System.out.println("size : " + comb5.size);
	System.out.println("weight : " + comb5.weight);
	System.out.println("isAntique : " + comb5.isAntique);
	System.out.println("warranty : " + comb5.warranty);
	System.out.println("manufactureDate : " + comb5.manufactureDate);
	System.out.println("isHandMade : " + comb5.isHandMade);
	System.out.println("discount : " + comb5.discount);
	System.out.println("sellerName : " + comb5.sellerName);
	System.out.println("numberOfTeeth : " + comb5.numberOfTeeth);
	System.out.println("customerReview : " + comb5.customerReview);
	System.out.println("rating : " + comb5.rating);
	System.out.println("isLightWeight : " + comb5.isLightWeight);
	System.out.println("countryOfOrigin : " + comb5.countryOfOrigin);
	System.out.println("designType : " + comb5.designType);
	System.out.println("pattern : " + comb5.pattern);
	System.out.println("length : " + comb5.length);
	System.out.println("isStockAvailable : " + comb5.isStockAvailable);
	System.out.println("grams : " + comb5.grams);


	HairComb comb6 = new HairComb();
	comb6.type = "Detangling Comb";
	comb6.material = "Plastic";
	comb6.price = 180;
	comb6.quantity = 1;
	comb6.brand = "Philips";
	comb6.colour = "Green";
	comb6.isMultipleColour = false;
	comb6.isQualityGood = true;
	comb6.size = "Large";
	comb6.weight = "22 grams";
	comb6.isAntique = false;
	comb6.warranty = "6 months";
	comb6.manufactureDate = "06-03-2026";
	comb6.isHandMade = false;
	comb6.discount = "6%";
	comb6.sellerName = "Amazon";
	comb6.numberOfTeeth = 18;
	comb6.customerReview = "Good for long hair";
	comb6.rating = 4;
	comb6.isLightWeight = true;
	comb6.countryOfOrigin = "India";
	comb6.designType = "Modern";
	comb6.pattern = "Curved";
	comb6.length = 20;
	comb6.isStockAvailable = true;
	comb6.grams = 22;
	System.out.println("after init instance variable");
	System.out.println("after init instance variable");
	System.out.println("type : " + comb6.type);
	System.out.println("material : " + comb6.material);
	System.out.println("price : " + comb6.price);
	System.out.println("quantity : " + comb6.quantity);
	System.out.println("brand : " + comb6.brand);
	System.out.println("colour : " + comb6.colour);
	System.out.println("isMultipleColour : " + comb6.isMultipleColour);
	System.out.println("isQualityGood : " + comb6.isQualityGood);
	System.out.println("size : " + comb6.size);
	System.out.println("weight : " + comb6.weight);
	System.out.println("isAntique : " + comb6.isAntique);
	System.out.println("warranty : " + comb6.warranty);
	System.out.println("manufactureDate : " + comb6.manufactureDate);
	System.out.println("isHandMade : " + comb6.isHandMade);
	System.out.println("discount : " + comb6.discount);
	System.out.println("sellerName : " + comb6.sellerName);
	System.out.println("numberOfTeeth : " + comb6.numberOfTeeth);
	System.out.println("customerReview : " + comb6.customerReview);
	System.out.println("rating : " + comb6.rating);
	System.out.println("isLightWeight : " + comb6.isLightWeight);
	System.out.println("countryOfOrigin : " + comb6.countryOfOrigin);
	System.out.println("designType : " + comb6.designType);
	System.out.println("pattern : " + comb6.pattern);
	System.out.println("length : " + comb6.length);
	System.out.println("isStockAvailable : " + comb6.isStockAvailable);
	System.out.println("grams : " + comb6.grams);



	HairComb comb7 = new HairComb();
	comb7.type = "Handle Comb";
	comb7.material = "Plastic";
	comb7.price = 140;
	comb7.quantity = 1;
	comb7.brand = "Vega";
	comb7.colour = "Pink";
	comb7.isMultipleColour = false;
	comb7.isQualityGood = true;
	comb7.size = "Medium";
	comb7.weight = "18 grams";
	comb7.isAntique = false;
	comb7.warranty = "6 months";
	comb7.manufactureDate = "07-03-2026";
	comb7.isHandMade = false;
	comb7.discount = "4%";
	comb7.sellerName = "Beauty Store";
	comb7.numberOfTeeth = 28;
	comb7.customerReview = "Comfortable handle";
	comb7.rating = 4;
	comb7.isLightWeight = true;
	comb7.countryOfOrigin = "India";
	comb7.designType = "Modern";
	comb7.pattern = "Handle Design";
	comb7.length = 19;
	comb7.isStockAvailable = true;
	comb7.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb7.type);
	System.out.println("material : " + comb7.material);
	System.out.println("price : " + comb7.price);
	System.out.println("quantity : " + comb7.quantity);
	System.out.println("brand : " + comb7.brand);
	System.out.println("colour : " + comb7.colour);
	System.out.println("isMultipleColour : " + comb7.isMultipleColour);
	System.out.println("isQualityGood : " + comb7.isQualityGood);
	System.out.println("size : " + comb7.size);
	System.out.println("weight : " + comb7.weight);
	System.out.println("isAntique : " + comb7.isAntique);
	System.out.println("warranty : " + comb7.warranty);
	System.out.println("manufactureDate : " + comb7.manufactureDate);
	System.out.println("isHandMade : " + comb7.isHandMade);
	System.out.println("discount : " + comb7.discount);
	System.out.println("sellerName : " + comb7.sellerName);
	System.out.println("numberOfTeeth : " + comb7.numberOfTeeth);
	System.out.println("customerReview : " + comb7.customerReview);
	System.out.println("rating : " + comb7.rating);
	System.out.println("isLightWeight : " + comb7.isLightWeight);
	System.out.println("countryOfOrigin : " + comb7.countryOfOrigin);
	System.out.println("designType : " + comb7.designType);
	System.out.println("pattern : " + comb7.pattern);
	System.out.println("length : " + comb7.length);
	System.out.println("isStockAvailable : " + comb7.isStockAvailable);
	System.out.println("grams : " + comb7.grams);


	HairComb comb8 = new HairComb();
	comb8.type = "Styling Comb";
	comb8.material = "Plastic";
	comb8.price = 160;
	comb8.quantity = 1;
	comb8.brand = "Syska";
	comb8.colour = "Black";
	comb8.isMultipleColour = false;
	comb8.isQualityGood = true;
	comb8.size = "Medium";
	comb8.weight = "17 grams";
	comb8.isAntique = false;
	comb8.warranty = "6 months";
	comb8.manufactureDate = "06-03-2026";
	comb8.isHandMade = false;
	comb8.discount = "5%";
	comb8.sellerName = "Flipkart";
	comb8.numberOfTeeth = 30;
	comb8.customerReview = "Good for styling";
	comb8.rating = 4;
	comb8.isLightWeight = true;
	comb8.countryOfOrigin = "India";
	comb8.designType = "Designer";
	comb8.pattern = "Slim";
	comb8.length = 18;
	comb8.isStockAvailable = true;
	comb8.grams = 17;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb8.type);
	System.out.println("material : " + comb8.material);
	System.out.println("price : " + comb8.price);
	System.out.println("quantity : " + comb8.quantity);
	System.out.println("brand : " + comb8.brand);
	System.out.println("colour : " + comb8.colour);
	System.out.println("isMultipleColour : " + comb8.isMultipleColour);
	System.out.println("isQualityGood : " + comb8.isQualityGood);
	System.out.println("size : " + comb8.size);
	System.out.println("weight : " + comb8.weight);
	System.out.println("isAntique : " + comb8.isAntique);
	System.out.println("warranty : " + comb8.warranty);
	System.out.println("manufactureDate : " + comb8.manufactureDate);
	System.out.println("isHandMade : " + comb8.isHandMade);
	System.out.println("discount : " + comb8.discount);
	System.out.println("sellerName : " + comb8.sellerName);
	System.out.println("numberOfTeeth : " + comb8.numberOfTeeth);
	System.out.println("customerReview : " + comb8.customerReview);
	System.out.println("rating : " + comb8.rating);
	System.out.println("isLightWeight : " + comb8.isLightWeight);
	System.out.println("countryOfOrigin : " + comb8.countryOfOrigin);
	System.out.println("designType : " + comb8.designType);
	System.out.println("pattern : " + comb8.pattern);
	System.out.println("length : " + comb8.length);
	System.out.println("isStockAvailable : " + comb8.isStockAvailable);
	System.out.println("grams : " + comb8.grams);


	HairComb comb9 = new HairComb();
	comb9.type = "Barber Comb";
	comb9.material = "Plastic";
	comb9.price = 200;
	comb9.quantity = 1;
	comb9.brand = "Professional";
	comb9.colour = "Black";
	comb9.isMultipleColour = false;
	comb9.isQualityGood = true;
	comb9.size = "Large";
	comb9.weight = "25 grams";
	comb9.isAntique = false;
	comb9.warranty = "1 year";
	comb9.manufactureDate = "08-03-2026";
	comb9.isHandMade = false;
	comb9.discount = "7%";
	comb9.sellerName = "Salon Supply";
	comb9.numberOfTeeth = 45;
	comb9.customerReview = "Best for salon use";
	comb9.rating = 5;
	comb9.isLightWeight = false;
	comb9.countryOfOrigin = "India";
	comb9.designType = "Professional";
	comb9.pattern = "Straight";
	comb9.length = 21;
	comb9.isStockAvailable = true;
	comb9.grams = 25;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb9.type);
	System.out.println("material : " + comb9.material);
	System.out.println("price : " + comb9.price);
	System.out.println("quantity : " + comb9.quantity);
	System.out.println("brand : " + comb9.brand);
	System.out.println("colour : " + comb9.colour);
	System.out.println("isMultipleColour : " + comb9.isMultipleColour);
	System.out.println("isQualityGood : " + comb9.isQualityGood);
	System.out.println("size : " + comb9.size);
	System.out.println("weight : " + comb9.weight);
	System.out.println("isAntique : " + comb9.isAntique);
	System.out.println("warranty : " + comb9.warranty);
	System.out.println("manufactureDate : " + comb9.manufactureDate);
	System.out.println("isHandMade : " + comb9.isHandMade);
	System.out.println("discount : " + comb9.discount);
	System.out.println("sellerName : " + comb9.sellerName);
	System.out.println("numberOfTeeth : " + comb9.numberOfTeeth);
	System.out.println("customerReview : " + comb9.customerReview);
	System.out.println("rating : " + comb9.rating);
	System.out.println("isLightWeight : " + comb9.isLightWeight);
	System.out.println("countryOfOrigin : " + comb9.countryOfOrigin);
	System.out.println("designType : " + comb9.designType);
	System.out.println("pattern : " + comb9.pattern);
	System.out.println("length : " + comb9.length);
	System.out.println("isStockAvailable : " + comb9.isStockAvailable);
	System.out.println("grams : " + comb9.grams);



	HairComb comb10 = new HairComb();
	comb10.type = "Wide Tooth Comb";
	comb10.material = "Plastic";
	comb10.price = 110;
	comb10.quantity = 1;
	comb10.brand = "Vega";
	comb10.colour = "Black";
	comb10.isMultipleColour = false;
	comb10.isQualityGood = true;
	comb10.size = "Medium";
	comb10.weight = "20 grams";
	comb10.isAntique = false;
	comb10.warranty = "6 months";
	comb10.manufactureDate = "08-03-2026";
	comb10.isHandMade = false;
	comb10.discount = "5%";
	comb10.sellerName = "Amazon";
	comb10.numberOfTeeth = 26;
	comb10.customerReview = "Good quality comb";
	comb10.rating = 4;
	comb10.isLightWeight = true;
	comb10.countryOfOrigin = "India";
	comb10.designType = "Classic";
	comb10.pattern = "Straight";
	comb10.length = 18;
	comb10.isStockAvailable = true;
	comb10.grams = 20;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb10.type);
	System.out.println("material : " + comb10.material);
	System.out.println("price : " + comb10.price);
	System.out.println("quantity : " + comb10.quantity);
	System.out.println("brand : " + comb10.brand);
	System.out.println("colour : " + comb10.colour);
	System.out.println("isMultipleColour : " + comb10.isMultipleColour);
	System.out.println("isQualityGood : " + comb10.isQualityGood);
	System.out.println("size : " + comb10.size);
	System.out.println("weight : " + comb10.weight);
	System.out.println("isAntique : " + comb10.isAntique);
	System.out.println("warranty : " + comb10.warranty);
	System.out.println("manufactureDate : " + comb10.manufactureDate);
	System.out.println("isHandMade : " + comb10.isHandMade);
	System.out.println("discount : " + comb10.discount);
	System.out.println("sellerName : " + comb10.sellerName);
	System.out.println("numberOfTeeth : " + comb10.numberOfTeeth);
	System.out.println("customerReview : " + comb10.customerReview);
	System.out.println("rating : " + comb10.rating);
	System.out.println("isLightWeight : " + comb10.isLightWeight);
	System.out.println("countryOfOrigin : " + comb10.countryOfOrigin);
	System.out.println("designType : " + comb10.designType);
	System.out.println("pattern : " + comb10.pattern);
	System.out.println("length : " + comb10.length);
	System.out.println("isStockAvailable : " + comb10.isStockAvailable);
	System.out.println("grams : " + comb10.grams);


	HairComb comb11 = new HairComb();
	comb11.type = "Fine Tooth Comb";
	comb11.material = "Plastic";
	comb11.price = 90;
	comb11.quantity = 1;
	comb11.brand = "Syska";
	comb11.colour = "Blue";
	comb11.isMultipleColour = false;
	comb11.isQualityGood = true;
	comb11.size = "Small";
	comb11.weight = "15 grams";
	comb11.isAntique = false;
	comb11.warranty = "6 months";
	comb11.manufactureDate = "07-03-2026";
	comb11.isHandMade = false;
	comb11.discount = "3%";
	comb11.sellerName = "Flipkart";
	comb11.numberOfTeeth = 40;
	comb11.customerReview = "Smooth combing";
	comb11.rating = 4;
	comb11.isLightWeight = true;
	comb11.countryOfOrigin = "India";
	comb11.designType = "Modern";
	comb11.pattern = "Straight";
	comb11.length = 16;
	comb11.isStockAvailable = true;
	comb11.grams = 15;
	System.out.println("type : " + comb11.type);
	System.out.println("material : " + comb11.material);
	System.out.println("price : " + comb11.price);
	System.out.println("quantity : " + comb11.quantity);
	System.out.println("brand : " + comb11.brand);
	System.out.println("colour : " + comb11.colour);
	System.out.println("isMultipleColour : " + comb11.isMultipleColour);
	System.out.println("isQualityGood : " + comb11.isQualityGood);
	System.out.println("size : " + comb11.size);
	System.out.println("weight : " + comb11.weight);
	System.out.println("isAntique : " + comb11.isAntique);
	System.out.println("warranty : " + comb11.warranty);
	System.out.println("manufactureDate : " + comb11.manufactureDate);
	System.out.println("isHandMade : " + comb11.isHandMade);
	System.out.println("discount : " + comb11.discount);
	System.out.println("sellerName : " + comb11.sellerName);
	System.out.println("numberOfTeeth : " + comb11.numberOfTeeth);
	System.out.println("customerReview : " + comb11.customerReview);
	System.out.println("rating : " + comb11.rating);
	System.out.println("isLightWeight : " + comb11.isLightWeight);
	System.out.println("countryOfOrigin : " + comb11.countryOfOrigin);
	System.out.println("designType : " + comb11.designType);
	System.out.println("pattern : " + comb11.pattern);
	System.out.println("length : " + comb11.length);
	System.out.println("isStockAvailable : " + comb11.isStockAvailable);
	System.out.println("grams : " + comb11.grams);

	HairComb comb12 = new HairComb();
	comb12.type = "Wooden Comb";
	comb12.material = "Wood";
	comb12.price = 250;
	comb12.quantity = 1;
	comb12.brand = "Forest Essentials";
	comb12.colour = "Brown";
	comb12.isMultipleColour = false;
	comb12.isQualityGood = true;
	comb12.size = "Medium";
	comb12.weight = "30 grams";
	comb12.isAntique = false;
	comb12.warranty = "1 year";
	comb12.manufactureDate = "06-03-2026";
	comb12.isHandMade = true;
	comb12.discount = "8%";
	comb12.sellerName = "Organic Store";
	comb12.numberOfTeeth = 20;
	comb12.customerReview = "Healthy for hair";
	comb12.rating = 5;
	comb12.isLightWeight = false;
	comb12.countryOfOrigin = "India";
	comb12.designType = "Traditional";
	comb12.pattern = "Wood Grain";
	comb12.length = 19;
	comb12.isStockAvailable = true;
	comb12.grams = 30;
	System.out.println("type : " + comb12.type);
	System.out.println("material : " + comb12.material);
	System.out.println("price : " + comb12.price);
	System.out.println("quantity : " + comb12.quantity);
	System.out.println("brand : " + comb12.brand);
	System.out.println("colour : " + comb12.colour);
	System.out.println("isMultipleColour : " + comb12.isMultipleColour);
	System.out.println("isQualityGood : " + comb12.isQualityGood);
	System.out.println("size : " + comb12.size);
	System.out.println("weight : " + comb12.weight);
	System.out.println("isAntique : " + comb12.isAntique);
	System.out.println("warranty : " + comb12.warranty);
	System.out.println("manufactureDate : " + comb12.manufactureDate);
	System.out.println("isHandMade : " + comb12.isHandMade);
	System.out.println("discount : " + comb12.discount);
	System.out.println("sellerName : " + comb12.sellerName);
	System.out.println("numberOfTeeth : " + comb12.numberOfTeeth);
	System.out.println("customerReview : " + comb12.customerReview);
	System.out.println("rating : " + comb12.rating);
	System.out.println("isLightWeight : " + comb12.isLightWeight);
	System.out.println("countryOfOrigin : " + comb12.countryOfOrigin);
	System.out.println("designType : " + comb12.designType);
	System.out.println("pattern : " + comb12.pattern);
	System.out.println("length : " + comb12.length);
	System.out.println("isStockAvailable : " + comb12.isStockAvailable);
	System.out.println("grams : " + comb12.grams);



	HairComb comb13 = new HairComb();
	comb13.type = "Pocket Comb";
	comb13.material = "Plastic";
	comb13.price = 60;
	comb13.quantity = 1;
	comb13.brand = "Vega";
	comb13.colour = "Red";
	comb13.isMultipleColour = false;
	comb13.isQualityGood = true;
	comb13.size = "Small";
	comb13.weight = "10 grams";
	comb13.isAntique = false;
	comb13.warranty = "3 months";
	comb13.manufactureDate = "05-03-2026";
	comb13.isHandMade = false;
	comb13.discount = "2%";
	comb13.sellerName = "Local Store";
	comb13.numberOfTeeth = 35;
	comb13.customerReview = "Easy to carry";
	comb13.rating = 4;
	comb13.isLightWeight = true;
	comb13.countryOfOrigin = "India";
	comb13.designType = "Simple";
	comb13.pattern = "Plain";
	comb13.length = 14;
	comb13.isStockAvailable = true;
	comb13.grams = 10;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb13.type);
	System.out.println("material : " + comb13.material);
	System.out.println("price : " + comb13.price);
	System.out.println("quantity : " + comb13.quantity);
	System.out.println("brand : " + comb13.brand);
	System.out.println("colour : " + comb13.colour);
	System.out.println("isMultipleColour : " + comb13.isMultipleColour);
	System.out.println("isQualityGood : " + comb13.isQualityGood);
	System.out.println("size : " + comb13.size);
	System.out.println("weight : " + comb13.weight);
	System.out.println("isAntique : " + comb13.isAntique);
	System.out.println("warranty : " + comb13.warranty);
	System.out.println("manufactureDate : " + comb13.manufactureDate);
	System.out.println("isHandMade : " + comb13.isHandMade);
	System.out.println("discount : " + comb13.discount);
	System.out.println("sellerName : " + comb13.sellerName);
	System.out.println("numberOfTeeth : " + comb13.numberOfTeeth);
	System.out.println("customerReview : " + comb13.customerReview);
	System.out.println("rating : " + comb13.rating);
	System.out.println("isLightWeight : " + comb13.isLightWeight);
	System.out.println("countryOfOrigin : " + comb13.countryOfOrigin);
	System.out.println("designType : " + comb13.designType);
	System.out.println("pattern : " + comb13.pattern);
	System.out.println("length : " + comb13.length);
	System.out.println("isStockAvailable : " + comb13.isStockAvailable);
	System.out.println("grams : " + comb13.grams);


	HairComb comb14 = new HairComb();
	comb14.type = "Detangling Comb";
	comb14.material = "Plastic";
	comb14.price = 180;
	comb14.quantity = 1;
	comb14.brand = "Philips";
	comb14.colour = "Green";
	comb14.isMultipleColour = false;
	comb14.isQualityGood = true;
	comb14.size = "Large";
	comb14.weight = "22 grams";
	comb14.isAntique = false;
	comb14.warranty = "6 months";
	comb14.manufactureDate = "04-03-2026";
	comb14.isHandMade = false;
	comb14.discount = "6%";
	comb14.sellerName = "Amazon";
	comb14.numberOfTeeth = 18;
	comb14.customerReview = "Good for long hair";
	comb14.rating = 4;
	comb14.isLightWeight = true;
	comb14.countryOfOrigin = "India";
	comb14.designType = "Modern";
	comb14.pattern = "Curved";
	comb14.length = 20;
	comb14.isStockAvailable = true;
	comb14.grams = 22;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb14.type);
	System.out.println("material : " + comb14.material);
	System.out.println("price : " + comb14.price);
	System.out.println("quantity : " + comb14.quantity);
	System.out.println("brand : " + comb14.brand);
	System.out.println("colour : " + comb14.colour);
	System.out.println("isMultipleColour : " + comb14.isMultipleColour);
	System.out.println("isQualityGood : " + comb14.isQualityGood);
	System.out.println("size : " + comb14.size);
	System.out.println("weight : " + comb14.weight);
	System.out.println("isAntique : " + comb14.isAntique);
	System.out.println("warranty : " + comb14.warranty);
	System.out.println("manufactureDate : " + comb14.manufactureDate);
	System.out.println("isHandMade : " + comb14.isHandMade);
	System.out.println("discount : " + comb14.discount);
	System.out.println("sellerName : " + comb14.sellerName);
	System.out.println("numberOfTeeth : " + comb14.numberOfTeeth);
	System.out.println("customerReview : " + comb14.customerReview);
	System.out.println("rating : " + comb14.rating);
	System.out.println("isLightWeight : " + comb14.isLightWeight);
	System.out.println("countryOfOrigin : " + comb14.countryOfOrigin);
	System.out.println("designType : " + comb14.designType);
	System.out.println("pattern : " + comb14.pattern);
	System.out.println("length : " + comb14.length);
	System.out.println("isStockAvailable : " + comb14.isStockAvailable);
	System.out.println("grams : " + comb14.grams);



	HairComb comb15 = new HairComb();
	comb15.type = "Handle Comb";
	comb15.material = "Plastic";
	comb15.price = 140;
	comb15.quantity = 1;
	comb15.brand = "Vega";
	comb15.colour = "Pink";
	comb15.isMultipleColour = false;
	comb15.isQualityGood = true;
	comb15.size = "Medium";
	comb15.weight = "18 grams";
	comb15.isAntique = false;
	comb15.warranty = "6 months";
	comb15.manufactureDate = "03-03-2026";
	comb15.isHandMade = false;
	comb15.discount = "4%";
	comb15.sellerName = "Beauty Store";
	comb15.numberOfTeeth = 28;
	comb15.customerReview = "Comfortable handle";
	comb15.rating = 4;
	comb15.isLightWeight = true;
	comb15.countryOfOrigin = "India";
	comb15.designType = "Modern";
	comb15.pattern = "Handle Design";
	comb15.length = 19;
	comb15.isStockAvailable = true;
	comb15.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb15.type);
	System.out.println("material : " + comb15.material);
	System.out.println("price : " + comb15.price);
	System.out.println("quantity : " + comb15.quantity);
	System.out.println("brand : " + comb15.brand);
	System.out.println("colour : " + comb15.colour);
	System.out.println("isMultipleColour : " + comb15.isMultipleColour);
	System.out.println("isQualityGood : " + comb15.isQualityGood);
	System.out.println("size : " + comb15.size);
	System.out.println("weight : " + comb15.weight);
	System.out.println("isAntique : " + comb15.isAntique);
	System.out.println("warranty : " + comb15.warranty);
	System.out.println("manufactureDate : " + comb15.manufactureDate);
	System.out.println("isHandMade : " + comb15.isHandMade);
	System.out.println("discount : " + comb15.discount);
	System.out.println("sellerName : " + comb15.sellerName);
	System.out.println("numberOfTeeth : " + comb15.numberOfTeeth);
	System.out.println("customerReview : " + comb15.customerReview);
	System.out.println("rating : " + comb15.rating);
	System.out.println("isLightWeight : " + comb15.isLightWeight);
	System.out.println("countryOfOrigin : " + comb15.countryOfOrigin);
	System.out.println("designType : " + comb15.designType);
	System.out.println("pattern : " + comb15.pattern);
	System.out.println("length : " + comb15.length);
	System.out.println("isStockAvailable : " + comb15.isStockAvailable);
	System.out.println("grams : " + comb15.grams);




	HairComb comb16 = new HairComb();
	comb16.type = "Styling Comb";
	comb16.material = "Plastic";
	comb16.price = 160;
	comb16.quantity = 1;
	comb16.brand = "Syska";
	comb16.colour = "Black";
	comb16.isMultipleColour = false;
	comb16.isQualityGood = true;
	comb16.size = "Medium";
	comb16.weight = "17 grams";
	comb16.isAntique = false;
	comb16.warranty = "6 months";
	comb16.manufactureDate = "02-03-2026";
	comb16.isHandMade = false;
	comb16.discount = "5%";
	comb16.sellerName = "Flipkart";
	comb16.numberOfTeeth = 30;
	comb16.customerReview = "Good for styling";
	comb16.rating = 4;
	comb16.isLightWeight = true;
	comb16.countryOfOrigin = "India";
	comb16.designType = "Designer";
	comb16.pattern = "Slim";
	comb16.length = 18;
	comb16.isStockAvailable = true;
	comb16.grams = 17;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb16.type);
	System.out.println("material : " + comb16.material);
	System.out.println("price : " + comb16.price);
	System.out.println("quantity : " + comb16.quantity);
	System.out.println("brand : " + comb16.brand);
	System.out.println("colour : " + comb16.colour);
	System.out.println("isMultipleColour : " + comb16.isMultipleColour);
	System.out.println("isQualityGood : " + comb16.isQualityGood);
	System.out.println("size : " + comb16.size);
	System.out.println("weight : " + comb16.weight);
	System.out.println("isAntique : " + comb16.isAntique);
	System.out.println("warranty : " + comb16.warranty);
	System.out.println("manufactureDate : " + comb16.manufactureDate);
	System.out.println("isHandMade : " + comb16.isHandMade);
	System.out.println("discount : " + comb16.discount);
	System.out.println("sellerName : " + comb16.sellerName);
	System.out.println("numberOfTeeth : " + comb16.numberOfTeeth);
	System.out.println("customerReview : " + comb16.customerReview);
	System.out.println("rating : " + comb16.rating);
	System.out.println("isLightWeight : " + comb16.isLightWeight);
	System.out.println("countryOfOrigin : " + comb16.countryOfOrigin);
	System.out.println("designType : " + comb16.designType);
	System.out.println("pattern : " + comb16.pattern);
	System.out.println("length : " + comb16.length);
	System.out.println("isStockAvailable : " + comb16.isStockAvailable);
	System.out.println("grams : " + comb16.grams);




	HairComb comb17 = new HairComb();
	comb17.type = "Barber Comb";
	comb17.material = "Plastic";
	comb17.price = 200;
	comb17.quantity = 1;
	comb17.brand = "Professional";
	comb17.colour = "Black";
	comb17.isMultipleColour = false;
	comb17.isQualityGood = true;
	comb17.size = "Large";
	comb17.weight = "25 grams";
	comb17.isAntique = false;
	comb17.warranty = "1 year";
	comb17.manufactureDate = "01-03-2026";
	comb17.isHandMade = false;
	comb17.discount = "7%";
	comb17.sellerName = "Salon Supply";
	comb17.numberOfTeeth = 45;
	comb17.customerReview = "Best for salon use";
	comb17.rating = 5;
	comb17.isLightWeight = false;
	comb17.countryOfOrigin = "India";
	comb17.designType = "Professional";
	comb17.pattern = "Straight";
	comb17.length = 21;
	comb17.isStockAvailable = true;
	comb17.grams = 25;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb17.type);
	System.out.println("material : " + comb17.material);
	System.out.println("price : " + comb17.price);
	System.out.println("quantity : " + comb17.quantity);
	System.out.println("brand : " + comb17.brand);
	System.out.println("colour : " + comb17.colour);
	System.out.println("isMultipleColour : " + comb17.isMultipleColour);
	System.out.println("isQualityGood : " + comb17.isQualityGood);
	System.out.println("size : " + comb17.size);
	System.out.println("weight : " + comb17.weight);
	System.out.println("isAntique : " + comb17.isAntique);
	System.out.println("warranty : " + comb17.warranty);
	System.out.println("manufactureDate : " + comb17.manufactureDate);
	System.out.println("isHandMade : " + comb17.isHandMade);
	System.out.println("discount : " + comb17.discount);
	System.out.println("sellerName : " + comb17.sellerName);
	System.out.println("numberOfTeeth : " + comb17.numberOfTeeth);
	System.out.println("customerReview : " + comb17.customerReview);
	System.out.println("rating : " + comb17.rating);
	System.out.println("isLightWeight : " + comb17.isLightWeight);
	System.out.println("countryOfOrigin : " + comb17.countryOfOrigin);
	System.out.println("designType : " + comb17.designType);
	System.out.println("pattern : " + comb17.pattern);
	System.out.println("length : " + comb17.length);
	System.out.println("isStockAvailable : " + comb17.isStockAvailable);
	System.out.println("grams : " + comb17.grams);




	HairComb comb18 = new HairComb();
	comb18.type = "Carbon Comb";
	comb18.material = "Carbon Fiber";
	comb18.price = 220;
	comb18.quantity = 1;
	comb18.brand = "Vega";
	comb18.colour = "Black";
	comb18.isMultipleColour = false;
	comb18.isQualityGood = true;
	comb18.size = "Medium";
	comb18.weight = "19 grams";
	comb18.isAntique = false;
	comb18.warranty = "1 year";
	comb18.manufactureDate = "28-02-2026";
	comb18.isHandMade = false;
	comb18.discount = "6%";
	comb18.sellerName = "Salon Store";
	comb18.numberOfTeeth = 32;
	comb18.customerReview = "Strong and durable";
	comb18.rating = 5;
	comb18.isLightWeight = true;
	comb18.countryOfOrigin = "India";
	comb18.designType = "Professional";
	comb18.pattern = "Slim";
	comb18.length = 20;
	comb18.isStockAvailable = true;
	comb18.grams = 19;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb18.type);
	System.out.println("material : " + comb18.material);
	System.out.println("price : " + comb18.price);
	System.out.println("quantity : " + comb18.quantity);
	System.out.println("brand : " + comb18.brand);
	System.out.println("colour : " + comb18.colour);
	System.out.println("isMultipleColour : " + comb18.isMultipleColour);
	System.out.println("isQualityGood : " + comb18.isQualityGood);
	System.out.println("size : " + comb18.size);
	System.out.println("weight : " + comb18.weight);
	System.out.println("isAntique : " + comb18.isAntique);
	System.out.println("warranty : " + comb18.warranty);
	System.out.println("manufactureDate : " + comb18.manufactureDate);
	System.out.println("isHandMade : " + comb18.isHandMade);
	System.out.println("discount : " + comb18.discount);
	System.out.println("sellerName : " + comb18.sellerName);
	System.out.println("numberOfTeeth : " + comb18.numberOfTeeth);
	System.out.println("customerReview : " + comb18.customerReview);
	System.out.println("rating : " + comb18.rating);
	System.out.println("isLightWeight : " + comb18.isLightWeight);
	System.out.println("countryOfOrigin : " + comb18.countryOfOrigin);
	System.out.println("designType : " + comb18.designType);
	System.out.println("pattern : " + comb18.pattern);
	System.out.println("length : " + comb18.length);
	System.out.println("isStockAvailable : " + comb18.isStockAvailable);
	System.out.println("grams : " + comb18.grams);



	HairComb comb19 = new HairComb();
	comb19.type = "Curved Comb";
	comb19.material = "Plastic";
	comb19.price = 150;
	comb19.quantity = 1;
	comb19.brand = "Philips";
	comb19.colour = "Blue";
	comb19.isMultipleColour = false;
	comb19.isQualityGood = true;
	comb19.size = "Medium";
	comb19.weight = "18 grams";
	comb19.isAntique = false;
	comb19.warranty = "6 months";
	comb19.manufactureDate = "27-02-2026";
	comb19.isHandMade = false;
	comb19.discount = "4%";
	comb19.sellerName = "Online Store";
	comb19.numberOfTeeth = 29;
	comb19.customerReview = "Comfortable design";
	comb19.rating = 4;
	comb19.isLightWeight = true;
	comb19.countryOfOrigin = "India";
	comb19.designType = "Modern";
	comb19.pattern = "Curved";
	comb19.length = 19;
	comb19.isStockAvailable = true;
	comb19.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb19.type);
	System.out.println("material : " + comb19.material);
	System.out.println("price : " + comb19.price);
	System.out.println("quantity : " + comb19.quantity);
	System.out.println("brand : " + comb19.brand);
	System.out.println("colour : " + comb19.colour);
	System.out.println("isMultipleColour : " + comb19.isMultipleColour);
	System.out.println("isQualityGood : " + comb19.isQualityGood);
	System.out.println("size : " + comb19.size);
	System.out.println("weight : " + comb19.weight);
	System.out.println("isAntique : " + comb19.isAntique);
	System.out.println("warranty : " + comb19.warranty);
	System.out.println("manufactureDate : " + comb19.manufactureDate);
	System.out.println("isHandMade : " + comb19.isHandMade);
	System.out.println("discount : " + comb19.discount);
	System.out.println("sellerName : " + comb19.sellerName);
	System.out.println("numberOfTeeth : " + comb19.numberOfTeeth);
	System.out.println("customerReview : " + comb19.customerReview);
	System.out.println("rating : " + comb19.rating);
	System.out.println("isLightWeight : " + comb19.isLightWeight);
	System.out.println("countryOfOrigin : " + comb19.countryOfOrigin);
	System.out.println("designType : " + comb19.designType);
	System.out.println("pattern : " + comb19.pattern);
	System.out.println("length : " + comb19.length);
	System.out.println("isStockAvailable : " + comb19.isStockAvailable);
	System.out.println("grams : " + comb19.grams);



	HairComb comb20 = new HairComb();
	comb20.type = "Professional Styling Comb";
	comb20.material = "Plastic";
	comb20.price = 240;
	comb20.quantity = 1;
	comb20.brand = "Professional";
	comb20.colour = "Black";
	comb20.isMultipleColour = false;
	comb20.isQualityGood = true;
	comb20.size = "Large";
	comb20.weight = "24 grams";
	comb20.isAntique = false;
	comb20.warranty = "1 year";
	comb20.manufactureDate = "26-02-2026";
	comb20.isHandMade = false;
	comb20.discount = "8%";
	comb20.sellerName = "Salon Shop";
	comb20.numberOfTeeth = 38;
	comb20.customerReview = "Perfect for styling";
	comb20.rating = 5;
	comb20.isLightWeight = false;
	comb20.countryOfOrigin = "India";
	comb20.designType = "Professional";
	comb20.pattern = "Slim";
	comb20.length = 21;
	comb20.isStockAvailable = true;
	comb20.grams = 24;
	System.out.println("after init instance variable");
	System.out.println("type : " + comb20.type);
	System.out.println("material : " + comb20.material);
	System.out.println("price : " + comb20.price);
	System.out.println("quantity : " + comb20.quantity);
	System.out.println("brand : " + comb20.brand);
	System.out.println("colour : " + comb20.colour);
	System.out.println("isMultipleColour : " + comb20.isMultipleColour);
	System.out.println("isQualityGood : " + comb20.isQualityGood);
	System.out.println("size : " + comb20.size);
	System.out.println("weight : " + comb20.weight);
	System.out.println("isAntique : " + comb20.isAntique);
	System.out.println("warranty : " + comb20.warranty);
	System.out.println("manufactureDate : " + comb20.manufactureDate);
	System.out.println("isHandMade : " + comb20.isHandMade);
	System.out.println("discount : " + comb20.discount);
	System.out.println("sellerName : " + comb20.sellerName);
	System.out.println("numberOfTeeth : " + comb20.numberOfTeeth);
	System.out.println("customerReview : " + comb20.customerReview);
	System.out.println("rating : " + comb20.rating);
	System.out.println("isLightWeight : " + comb20.isLightWeight);
	System.out.println("countryOfOrigin : " + comb20.countryOfOrigin);
	System.out.println("designType : " + comb20.designType);
	System.out.println("pattern : " + comb20.pattern);
	System.out.println("length : " + comb20.length);
	System.out.println("isStockAvailable : " + comb20.isStockAvailable);
	System.out.println("grams : " + comb20.grams);
		}
	}