class CountryMain {

    public static void main(String[] args) {

        String[] countries = {
            "India",
            "United States",
            "Australia",
            "Canada",
            "Germany",
            "France",
            "Japan",
            "Brazil",
            "China",
            "United Kingdom",
            "Italy",
            "Spain",
            "South Korea",
            "Mexico",
            "Russia",
            "South Africa",
            "Argentina",
            "Indonesia",
            "Saudi Arabia",
            "Turkey",
            "Switzerland",
            "Netherlands",
            "Belgium",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "New Zealand",
            "Pakistan",
            "Bangladesh",
            "Nepal",
            "Sri Lanka",
            "Egypt",
            "Nigeria",
            "Kenya",
            "Ethiopia",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Ghana",
            "Uganda",
            "Tanzania",
            "Philippines",
            "Thailand",
            "Vietnam",
            "Malaysia",
            "Singapore",
            "Myanmar",
            "Cambodia",
            "Laos",
            "Mongolia",
            "Kazakhstan",
            "Uzbekistan",
            "Afghanistan",
            "Iran",
            "Iraq",
            "Israel",
            "Jordan",
            "Qatar",
            "UAE",
            "Oman",
            "Kuwait",
            "Chile",
            "Peru",
            "Colombia",
            "Venezuela",
            "Bolivia",
            "Paraguay",
            "Uruguay",
            "Cuba",
            "Dominican Republic",
            "Haiti",
            "Panama",
            "Costa Rica",
            "Guatemala",
            "Honduras",
            "El Salvador",
            "Nicaragua",
            "Jamaica",
            "Iceland",
            "Ireland",
            "Portugal",
            "Austria",
            "Hungary",
            "Poland",
            "Czech Republic",
            "Slovakia",
            "Romania",
            "Bulgaria",
            "Croatia",
            "Slovenia",
            "Serbia",
            "Bosnia",
            "Montenegro",
            "Albania",
            "North Macedonia",
            "Ukraine",
            "Belarus",
            "Lithuania",
            "Latvia",
            "Estonia",
            "Luxembourg",
            "Malta",
            "Cyprus",
            "Greece",
            "Georgia",
            "Armenia",
            "Azerbaijan",
            "Maldives",
            "Bhutan",
            "Brunei",
            "Timor-Leste",
            "Papua New Guinea",
            "Fiji",
            "Solomon Islands",
            "Samoa",
            "Tonga",
            "Vanuatu",
            "Micronesia",
            "Palau",
            "Marshall Islands",
            "Kiribati",
            "Nauru",
            "Tuvalu",
            "Seychelles",
            "Mauritius",
            "Madagascar",
            "Zambia",
            "Zimbabwe",
            "Botswana",
            "Namibia",
            "Lesotho",
            "Eswatini",
            "Rwanda",
            "Burundi",
            "Somalia",
            "Sudan",
            "South Sudan",
            "Libya",
            "Angola",
            "Cameroon",
            "Senegal",
            "Ivory Coast",
            "Mali",
            "Niger",
            "Chad",
            "Central African Republic",
            "Democratic Republic of Congo",
            "Republic of Congo",
            "Gabon",
            "Equatorial Guinea",
            "Guinea",
            "Sierra Leone",
            "Liberia"
        };

        for (String country : countries) {

            System.out.println("States in " + country + " :");

            String[] states = Country.findStatesByCountry(country);

            Country.displayStates(states);

            System.out.println("-----------------------------------");
        }
    }
}
