class EaringExecutor{

    public static void main(String[] args){
	Earing ear=new Earing();
	System.out.println("before init instance variable");
	System.out.println("type : " + ear.Type);
	System.out.println("length : " + ear.length);
	System.out.println("price  : " + ear.price);
	System.out.println("quantity: " + ear.quantity);
	System.out.println("brand: " + ear.brand);
	System.out.println("colour: " + ear.colour);
	System.out.println("isMultipleColour : " + ear.isMultipleColour);
	System.out.println("isqualityGood: " + ear.isqualityGood);
	System.out.println("size: " + ear.size);
	System.out.println("Weight: " + ear.Weight);
	System.out.println("isAntique: " + ear.isAntique);
	System.out.println("warranty: " + ear.warranty);
	System.out.println("manufactureDate: " + ear.manufactureDate);
	System.out.println("isHandMade : " + ear.isHandMade);
	System.out.println("Discount : " + ear.Discount);
	System.out.println("sellername : " + ear.sellername);
	System.out.println("numberOfStone : " + ear.numberOfStone);
	System.out.println("coustomreview : " + ear.coustomreview);
	System.out.println("rating : " + ear.rating);
	System.out.println("isLightweight : " + ear.isLightweight);
	System.out.println("Country Of origin : " + ear.CountryOforigin);
	System.out.println("stoneType : " + ear.stoneType);
	System.out.println("Design Type : " + ear.DesignType);
	System.out.println("width : " + ear.width);
	System.out.println("isStockAvailable : " + ear.isStockAvailable);
	System.out.println("grams: " + ear.grams);
	
	ear.Type = "Jhumka";
	ear.length = "5 cm";
	ear.price = 899;
	ear.quantity = 2;
	ear.brand = "ZeveriPearls";
	ear.colour = "Gold";
	ear.isMultipleColour = true;
	ear.isqualityGood = true;
	ear.size = "Medium";
	ear.Weight = "25 grams";
	ear.isAntique = false;
	ear.warranty = "6 months";
	ear.manufactureDate = "10-01-2026";
	ear.isHandMade = true;
	ear.Discount = "20%";
	ear.sellername = "Amazon Seller";
	ear.numberOfStone = 15;
	ear.coustomreview = "Very beautiful earrings";
	ear.rating = 5;
	ear.isLightweight = true;
	ear.CountryOforigin = "India";
	ear.stoneType = "Pearl";
	ear.DesignType = "Traditional";
	ear.width = 3;
	ear.isStockAvailable = true;
	ear.grams = 25;
	
	System.out.println("after init instance variable");
	System.out.println("type : " + ear.Type);
	System.out.println("length : " + ear.length);
	System.out.println("price  : " + ear.price);
	System.out.println("quantity: " + ear.quantity);
	System.out.println("brand: " + ear.brand);
	System.out.println("colour: " + ear.colour);
	System.out.println("isMultipleColour : " + ear.isMultipleColour);
	System.out.println("isqualityGood: " + ear.isqualityGood);
	System.out.println("size: " + ear.size);
	System.out.println("Weight: " + ear.Weight);
	System.out.println("isAntique: " + ear.isAntique);
	System.out.println("warranty: " + ear.warranty);
	System.out.println("manufactureDate: " + ear.manufactureDate);
	System.out.println("isHandMade : " + ear.isHandMade);
	System.out.println("Discount : " + ear.Discount);
	System.out.println("sellername : " + ear.sellername);
	System.out.println("numberOfStone : " + ear.numberOfStone);
	System.out.println("coustomreview : " + ear.coustomreview);
	System.out.println("rating : " + ear.rating);
	System.out.println("isLightweight : " + ear.isLightweight);
	System.out.println("Country Of origin : " + ear.CountryOforigin);
	System.out.println("stoneType : " + ear.stoneType);
	System.out.println("Design Type : " + ear.DesignType);
	System.out.println("width : " + ear.width);
	System.out.println("isStockAvailable : " + ear.isStockAvailable);
	System.out.println("grams: " + ear.grams);
	
	
    Earing ear1=new Earing();
    ear1.Type = "Chandbali";
	ear1.length = "6 cm";
	ear1.price = 1299;
	ear1.quantity = 1;
	ear1.brand = "Voylla";
	ear1.colour = "Silver";
	ear1.isMultipleColour = false;
	ear1.isqualityGood = true;
	ear1.size = "Large";
	ear1.Weight = "30 grams";
	ear1.isAntique = true;
	ear1.warranty = "1 year";
	ear1.manufactureDate = "15-02-2026";
	ear1.isHandMade = false;
	ear1.Discount = "15%";
	ear1.sellername = "Flipkart Seller";
	ear1.numberOfStone = 10;
	ear1.coustomreview = "Elegant and stylish design";
	ear1.rating = 4;
	ear1.isLightweight = false;
	ear1.CountryOforigin = "Thailand";
	ear1.stoneType = "Ruby";
	ear1.DesignType = "Modern";
	ear1.width = 4;
	ear1.isStockAvailable = true;
	ear1.grams = 30;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear1.Type);
	System.out.println("length : " + ear1.length);
	System.out.println("price  : " + ear1.price);
	System.out.println("quantity: " + ear1.quantity);
	System.out.println("brand: " + ear1.brand);
	System.out.println("colour: " + ear1.colour);
	System.out.println("isMultipleColour : " + ear1.isMultipleColour);
	System.out.println("isqualityGood: " + ear1.isqualityGood);
	System.out.println("size: " + ear1.size);
	System.out.println("Weight: " + ear1.Weight);
	System.out.println("isAntique: " + ear1.isAntique);
	System.out.println("warranty: " + ear1.warranty);
	System.out.println("manufactureDate: " + ear1.manufactureDate);
	System.out.println("isHandMade : " + ear1.isHandMade);
	System.out.println("Discount : " + ear1.Discount);
	System.out.println("sellername : " + ear1.sellername);
	System.out.println("numberOfStone : " + ear1.numberOfStone);
	System.out.println("coustomreview : " + ear1.coustomreview);
	System.out.println("rating : " + ear1.rating);
	System.out.println("isLightweight : " + ear1.isLightweight);
	System.out.println("Country Of origin : " + ear1.CountryOforigin);
	System.out.println("stoneType : " + ear1.stoneType);
	System.out.println("Design Type : " + ear1.DesignType);
	System.out.println("width : " + ear1.width);
	System.out.println("isStockAvailable : " + ear1.isStockAvailable);
	System.out.println("grams: " + ear1.grams);
	
	
	
	Earing ear2=new Earing();
	ear2.Type = "Stud";
	ear2.length = "2 cm";
	ear2.price = 499;
	ear2.quantity = 3;
	ear2.brand = "Priyaasi";
	ear2.colour = "Rose Gold";
	ear2.isMultipleColour = true;
	ear2.isqualityGood = true;
	ear2.size = "Small";
	ear2.Weight = "10 grams";
	ear2.isAntique = false;
	ear2.warranty = "3 months";
	ear2.manufactureDate = "05-03-2026";
	ear2.isHandMade = true;
	ear2.Discount = "10%";
	ear2.sellername = "Meesho Seller";
	ear2.numberOfStone = 5;
	ear2.coustomreview = "Cute and comfortable to wear";
	ear2.rating = 4;
	ear2.isLightweight = true;
	ear2.CountryOforigin = "South Korea";
	ear2.stoneType = "Diamond";
	ear2.DesignType = "Casual";
	ear2.width = 1;
	ear2.isStockAvailable = true;
	ear2.grams = 10;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear2.Type);
	System.out.println("length : " + ear2.length);
	System.out.println("price  : " + ear2.price);
	System.out.println("quantity: " + ear2.quantity);
	System.out.println("brand: " + ear2.brand);
	System.out.println("colour: " + ear2.colour);
	System.out.println("isMultipleColour : " + ear2.isMultipleColour);
	System.out.println("isqualityGood: " + ear2.isqualityGood);
	System.out.println("size: " + ear2.size);
	System.out.println("Weight: " + ear2.Weight);
	System.out.println("isAntique: " + ear2.isAntique);
	System.out.println("warranty: " + ear2.warranty);
	System.out.println("manufactureDate: " + ear2.manufactureDate);
	System.out.println("isHandMade : " + ear2.isHandMade);
	System.out.println("Discount : " + ear2.Discount);
	System.out.println("sellername : " + ear2.sellername);
	System.out.println("numberOfStone : " + ear2.numberOfStone);
	System.out.println("coustomreview : " + ear2.coustomreview);
	System.out.println("rating : " + ear2.rating);
	System.out.println("isLightweight : " + ear2.isLightweight);
	System.out.println("Country Of origin : " + ear2.CountryOforigin);
	System.out.println("stoneType : " + ear2.stoneType);
	System.out.println("Design Type : " + ear2.DesignType);
	System.out.println("width : " + ear2.width);
	System.out.println("isStockAvailable : " + ear2.isStockAvailable);
	System.out.println("grams: " + ear2.grams);
	
	
	Earing ear3=new Earing();
	ear3.Type = "Hoop";
	ear3.length = "4 cm";
	ear3.price = 699;
	ear3.quantity = 2;
	ear3.brand = "Sukkhi";
	ear3.colour = "Black";
	ear3.isMultipleColour = false;
	ear3.isqualityGood = true;
	ear3.size = "Medium";
	ear3.Weight = "18 grams";
	ear3.isAntique = false;
	ear3.warranty = "9 months";
	ear3.manufactureDate = "20-12-2025";
	ear3.isHandMade = false;
	ear3.Discount = "25%";
	ear3.sellername = "Myntra Seller";
	ear3.numberOfStone = 8;
	ear3.coustomreview = "Nice trendy earrings";
	ear3.rating = 4;
	ear3.isLightweight = true;
	ear3.CountryOforigin = "China";
	ear3.stoneType = "Crystal";
	ear3.DesignType = "Western";
	ear3.width = 2;
	ear3.isStockAvailable = true;
	ear3.grams = 18;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear3.Type);
	System.out.println("length : " + ear3.length);
	System.out.println("price  : " + ear3.price);
	System.out.println("quantity: " + ear3.quantity);
	System.out.println("brand: " + ear3.brand);
	System.out.println("colour: " + ear3.colour);
	System.out.println("isMultipleColour : " + ear3.isMultipleColour);
	System.out.println("isqualityGood: " + ear3.isqualityGood);
	System.out.println("size: " + ear3.size);
	System.out.println("Weight: " + ear3.Weight);
	System.out.println("isAntique: " + ear3.isAntique);
	System.out.println("warranty: " + ear3.warranty);
	System.out.println("manufactureDate: " + ear3.manufactureDate);
	System.out.println("isHandMade : " + ear3.isHandMade);
	System.out.println("Discount : " + ear3.Discount);
	System.out.println("sellername : " + ear3.sellername);
	System.out.println("numberOfStone : " + ear3.numberOfStone);
	System.out.println("coustomreview : " + ear3.coustomreview);
	System.out.println("rating : " + ear3.rating);
	System.out.println("isLightweight : " + ear3.isLightweight);
	System.out.println("Country Of origin : " + ear3.CountryOforigin);
	System.out.println("stoneType : " + ear3.stoneType);
	System.out.println("Design Type : " + ear3.DesignType);
	System.out.println("width : " + ear3.width);
	System.out.println("isStockAvailable : " + ear3.isStockAvailable);
	System.out.println("grams: " + ear3.grams);

    Earing ear4= new Earing();
	ear4.Type = "Drop";
	ear4.length = "7 cm";
	ear4.price = 1599;
	ear4.quantity = 1;
	ear4.brand = "PipaBella";
	ear4.colour = "Green";
	ear4.isMultipleColour = true;
	ear4.isqualityGood = true;
	ear4.size = "Large";
	ear4.Weight = "35 grams";
	ear4.isAntique = true;
	ear4.warranty = "1.5 years";
	ear4.manufactureDate = "25-11-2025";
	ear4.isHandMade = true;
	ear4.Discount = "30%";
	ear4.sellername = "Ajio Seller";
	ear4.numberOfStone = 20;
	ear4.coustomreview = "Beautiful traditional design";
	ear4.rating = 5;
	ear4.isLightweight = false;
	ear4.CountryOforigin = "Japan";
	ear4.stoneType = "Emerald";
	ear4.DesignType = "Ethnic";
	ear4.width = 5;
	ear4.isStockAvailable = false;
	ear4.grams = 35;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear4.Type);
	System.out.println("length : " + ear4.length);
	System.out.println("price  : " + ear4.price);
	System.out.println("quantity: " + ear4.quantity);
	System.out.println("brand: " + ear4.brand);
	System.out.println("colour: " + ear4.colour);
	System.out.println("isMultipleColour : " + ear4.isMultipleColour);
	System.out.println("isqualityGood: " + ear4.isqualityGood);
	System.out.println("size: " + ear4.size);
	System.out.println("Weight: " + ear4.Weight);
	System.out.println("isAntique: " + ear4.isAntique);
	System.out.println("warranty: " + ear4.warranty);
	System.out.println("manufactureDate: " + ear4.manufactureDate);
	System.out.println("isHandMade : " + ear4.isHandMade);
	System.out.println("Discount : " + ear4.Discount);
	System.out.println("sellername : " + ear4.sellername);
	System.out.println("numberOfStone : " + ear4.numberOfStone);
	System.out.println("coustomreview : " + ear4.coustomreview);
	System.out.println("rating : " + ear4.rating);
	System.out.println("isLightweight : " + ear4.isLightweight);
	System.out.println("Country Of origin : " + ear4.CountryOforigin);
	System.out.println("stoneType : " + ear4.stoneType);
	System.out.println("Design Type : " + ear4.DesignType);
	System.out.println("width : " + ear4.width);
	System.out.println("isStockAvailable : " + ear4.isStockAvailable);
	System.out.println("grams: " + ear4.grams);
	
	
	Earing ear5 = new Earing();
	ear5.Type = "Kundan";
	ear5.length = "8 cm";
	ear5.price = 1899;
	ear5.quantity = 1;
	ear5.brand = "ZaveriPearls";
	ear5.colour = "Red";
	ear5.isMultipleColour = true;
	ear5.isqualityGood = true;
	ear5.size = "Extra Large";
	ear5.Weight = "40 grams";
	ear5.isAntique = true;
	ear5.warranty = "2 years";
	ear5.manufactureDate = "18-01-2026";
	ear5.isHandMade = true;
	ear5.Discount = "35%";
	ear5.sellername = "Nykaa Fashion Seller";
	ear5.numberOfStone = 25;
	ear5.coustomreview = "Very rich and royal looking earrings";
	ear5.rating = 5;
	ear5.isLightweight = false;
	ear5.CountryOforigin = "UAE";
	ear5.stoneType = "Kundan Stone";
	ear5.DesignType = "Bridal";
	ear5.width = 6;
	ear5.isStockAvailable = true;
	ear5.grams = 40;	
	System.out.println("after init instance variable");
	System.out.println("type : " + ear5.Type);
	System.out.println("length : " + ear5.length);
	System.out.println("price  : " + ear5.price);
	System.out.println("quantity: " + ear5.quantity);
	System.out.println("brand: " + ear5.brand);
	System.out.println("colour: " + ear5.colour);
	System.out.println("isMultipleColour : " + ear5.isMultipleColour);
	System.out.println("isqualityGood: " + ear5.isqualityGood);
	System.out.println("size: " + ear5.size);
	System.out.println("Weight: " + ear5.Weight);
	System.out.println("isAntique: " + ear5.isAntique);
	System.out.println("warranty: " + ear5.warranty);
	System.out.println("manufactureDate: " + ear5.manufactureDate);
	System.out.println("isHandMade : " + ear5.isHandMade);
	System.out.println("Discount : " + ear5.Discount);
	System.out.println("sellername : " + ear5.sellername);
	System.out.println("numberOfStone : " + ear5.numberOfStone);
	System.out.println("coustomreview : " + ear5.coustomreview);
	System.out.println("rating : " + ear5.rating);
	System.out.println("isLightweight : " + ear5.isLightweight);
	System.out.println("Country Of origin : " + ear5.CountryOforigin);
	System.out.println("stoneType : " + ear5.stoneType);
	System.out.println("Design Type : " + ear5.DesignType);
	System.out.println("width : " + ear5.width);
	System.out.println("isStockAvailable : " + ear5.isStockAvailable);
	System.out.println("grams: " + ear5.grams);
	
	Earing ear6= new Earing();
	ear6.Type = "EarCuff";
	ear6.length = "4.5 cm";
	ear6.price = 749;
	ear6.quantity = 1;
	ear6.brand = "Rubans";
	ear6.colour = "White";
	ear6.isMultipleColour = false;
	ear6.isqualityGood = true;
	ear6.size = "Medium";
	ear6.Weight = "16 grams";
	ear6.isAntique = false;
	ear6.warranty = "8 months";
	ear6.manufactureDate = "28-01-2026";
	ear6.isHandMade = false;
	ear6.Discount = "22%";
	ear6.sellername = "TataCliq Seller";
	ear6.numberOfStone = 7;
	ear6.coustomreview = "Unique and fashionable design";
	ear6.rating = 4;
	ear6.isLightweight = true;
	ear6.CountryOforigin = "Italy";
	ear6.stoneType = "Opal";
	ear6.DesignType = "Designer";
	ear6.width = 2;
	ear6.isStockAvailable = true;
	ear6.grams = 16;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear6.Type);
	System.out.println("length : " + ear6.length);
	System.out.println("price  : " + ear6.price);
	System.out.println("quantity: " + ear6.quantity);
	System.out.println("brand: " + ear6.brand);
	System.out.println("colour: " + ear6.colour);
	System.out.println("isMultipleColour : " + ear6.isMultipleColour);
	System.out.println("isqualityGood: " + ear6.isqualityGood);
	System.out.println("size: " + ear6.size);
	System.out.println("Weight: " + ear6.Weight);
	System.out.println("isAntique: " + ear6.isAntique);
	System.out.println("warranty: " + ear6.warranty);
	System.out.println("manufactureDate: " + ear6.manufactureDate);
	System.out.println("isHandMade : " + ear6.isHandMade);
	System.out.println("Discount : " + ear6.Discount);
	System.out.println("sellername : " + ear6.sellername);
	System.out.println("numberOfStone : " + ear6.numberOfStone);
	System.out.println("coustomreview : " + ear6.coustomreview);
	System.out.println("rating : " + ear6.rating);
	System.out.println("isLightweight : " + ear6.isLightweight);
	System.out.println("Country Of origin : " + ear6.CountryOforigin);
	System.out.println("stoneType : " + ear6.stoneType);
	System.out.println("Design Type : " + ear6.DesignType);
	System.out.println("width : " + ear6.width);
	System.out.println("isStockAvailable : " + ear6.isStockAvailable);
	System.out.println("grams: " + ear6.grams);
			
	
	Earing ear7 = new Earing();
	ear7.Type = "Huggie";
	ear7.length = "3 cm";
	ear7.price = 799;
	ear7.quantity = 2;
	ear7.brand = "YellowChimes";
	ear7.colour = "Blue";
	ear7.isMultipleColour = true;
	ear7.isqualityGood = true;
	ear7.size = "Small";
	ear7.Weight = "12 grams";
	ear7.isAntique = false;
	ear7.warranty = "4 months";
	ear7.manufactureDate = "12-02-2026";
	ear7.isHandMade = false;
	ear7.Discount = "12%";
	ear7.sellername = "Snapdeal Seller";
	ear7.numberOfStone = 6;
	ear7.coustomreview = "Stylish and comfortable earrings";
	ear7.rating = 4;
	ear7.isLightweight = true;
	ear7.CountryOforigin = "Singapore";
	ear7.stoneType = "Sapphire";
	ear7.DesignType = "Contemporary";
	ear7.width = 2;
	ear7.isStockAvailable = true;
	ear7.grams = 12;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear7.Type);
	System.out.println("length : " + ear7.length);
	System.out.println("price  : " + ear7.price);
	System.out.println("quantity: " + ear7.quantity);
	System.out.println("brand: " + ear7.brand);
	System.out.println("colour: " + ear7.colour);
	System.out.println("isMultipleColour : " + ear7.isMultipleColour);
	System.out.println("isqualityGood: " + ear7.isqualityGood);
	System.out.println("size: " + ear7.size);
	System.out.println("Weight: " + ear7.Weight);
	System.out.println("isAntique: " + ear7.isAntique);
	System.out.println("warranty: " + ear7.warranty);
	System.out.println("manufactureDate: " + ear7.manufactureDate);
	System.out.println("isHandMade : " + ear7.isHandMade);
	System.out.println("Discount : " + ear7.Discount);
	System.out.println("sellername : " + ear7.sellername);
	System.out.println("numberOfStone : " + ear7.numberOfStone);
	System.out.println("coustomreview : " + ear7.coustomreview);
	System.out.println("rating : " + ear7.rating);
	System.out.println("isLightweight : " + ear7.isLightweight);
	System.out.println("Country Of origin : " + ear7.CountryOforigin);
	System.out.println("stoneType : " + ear7.stoneType);
	System.out.println("Design Type : " + ear7.DesignType);
	System.out.println("width : " + ear7.width);
	System.out.println("isStockAvailable : " + ear7.isStockAvailable);
	System.out.println("grams: " + ear7.grams);
	
	
	Earing ear8 = new Earing();
	ear8.Type = "Tassel";
	ear8.length = "9 cm";
	ear8.price = 999;
	ear8.quantity = 2;
	ear8.brand = "FashionFrill";
	ear8.colour = "Purple";
	ear8.isMultipleColour = true;
	ear8.isqualityGood = true;
	ear8.size = "Large";
	ear8.Weight = "28 grams";
	ear8.isAntique = false;
	ear8.warranty = "5 months";
	ear8.manufactureDate = "22-02-2026";
	ear8.isHandMade = true;
	ear8.Discount = "18%";
	ear8.sellername = "ShopClues Seller";
	ear8.numberOfStone = 12;
	ear8.coustomreview = "Trendy and eye catching earrings";
	ear8.rating = 4;
	ear8.isLightweight = false;
	ear8.CountryOforigin = "Malaysia";
	ear8.stoneType = "Amethyst";
	ear8.DesignType = "Party Wear";
	ear8.width = 4;
	ear8.isStockAvailable = true;
	ear8.grams = 28;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear8.Type);
	System.out.println("length : " + ear8.length);
	System.out.println("price  : " + ear8.price);
	System.out.println("quantity: " + ear8.quantity);
	System.out.println("brand: " + ear8.brand);
	System.out.println("colour: " + ear8.colour);
	System.out.println("isMultipleColour : " + ear8.isMultipleColour);
	System.out.println("isqualityGood: " + ear8.isqualityGood);
	System.out.println("size: " + ear8.size);
	System.out.println("Weight: " + ear8.Weight);
	System.out.println("isAntique: " + ear8.isAntique);
	System.out.println("warranty: " + ear8.warranty);
	System.out.println("manufactureDate: " + ear8.manufactureDate);
	System.out.println("isHandMade : " + ear8.isHandMade);
	System.out.println("Discount : " + ear8.Discount);
	System.out.println("sellername : " + ear8.sellername);
	System.out.println("numberOfStone : " + ear8.numberOfStone);
	System.out.println("coustomreview : " + ear8.coustomreview);
	System.out.println("rating : " + ear8.rating);
	System.out.println("isLightweight : " + ear8.isLightweight);
	System.out.println("Country Of origin : " + ear8.CountryOforigin);
	System.out.println("stoneType : " + ear8.stoneType);
	System.out.println("Design Type : " + ear8.DesignType);
	System.out.println("width : " + ear8.width);
	System.out.println("isStockAvailable : " + ear8.isStockAvailable);
	System.out.println("grams: " + ear8.grams);
	
	
	Earing ear9 = new Earing();
	ear9.Type = "Danglers";
	ear9.length = "10 cm";
	ear9.price = 1399;
	ear9.quantity = 1;
	ear9.brand = "Peora";
	ear9.colour = "Pink";
	ear9.isMultipleColour = true;
	ear9.isqualityGood = true;
	ear9.size = "Large";
	ear9.Weight = "32 grams";
	ear9.isAntique = false;
	ear9.warranty = "1 year";
	ear9.manufactureDate = "02-03-2026";
	ear9.isHandMade = true;
	ear9.Discount = "28%";
	ear9.sellername = "Reliance Trends Seller";
	ear9.numberOfStone = 18;
	ear9.coustomreview = "Very stylish and perfect for parties";
	ear9.rating = 5;
	ear9.isLightweight = false;
	ear9.CountryOforigin = "France";
	ear9.stoneType = "Topaz";
	ear9.DesignType = "Party";
	ear9.width = 5;
	ear9.isStockAvailable = true;
	ear9.grams = 32;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear9.Type);
	System.out.println("length : " + ear9.length);
	System.out.println("price  : " + ear9.price);
	System.out.println("quantity: " + ear9.quantity);
	System.out.println("brand: " + ear9.brand);
	System.out.println("colour: " + ear9.colour);
	System.out.println("isMultipleColour : " + ear9.isMultipleColour);
	System.out.println("isqualityGood: " + ear9.isqualityGood);
	System.out.println("size: " + ear9.size);
	System.out.println("Weight: " + ear9.Weight);
	System.out.println("isAntique: " + ear9.isAntique);
	System.out.println("warranty: " + ear9.warranty);
	System.out.println("manufactureDate: " + ear9.manufactureDate);
	System.out.println("isHandMade : " + ear9.isHandMade);
	System.out.println("Discount : " + ear9.Discount);
	System.out.println("sellername : " + ear9.sellername);
	System.out.println("numberOfStone : " + ear9.numberOfStone);
	System.out.println("coustomreview : " + ear9.coustomreview);
	System.out.println("rating : " + ear9.rating);
	System.out.println("isLightweight : " + ear9.isLightweight);
	System.out.println("Country Of origin : " + ear9.CountryOforigin);
	System.out.println("stoneType : " + ear9.stoneType);
	System.out.println("Design Type : " + ear9.DesignType);
	System.out.println("width : " + ear9.width);
	System.out.println("isStockAvailable : " + ear9.isStockAvailable);
	System.out.println("grams: " + ear9.grams);
	
	
    Earing ear10 = new Earing();
    ear10.Type = "ClipOn";
	ear10.length = "3.5 cm";
	ear10.price = 649;
	ear10.quantity = 2;
	ear10.brand = "Estele";
	ear10.colour = "Orange";
	ear10.isMultipleColour = false;
	ear10.isqualityGood = true;
	ear10.size = "Small";
	ear10.Weight = "14 grams";
	ear10.isAntique = false;
	ear10.warranty = "7 months";
	ear10.manufactureDate = "05-02-2026";
	ear10.isHandMade = false;
	ear10.Discount = "16%";
	ear10.sellername = "Paytm Mall Seller";
	ear10.numberOfStone = 9;
	ear10.coustomreview = "Comfortable and simple design";
	ear10.rating = 4;
	ear10.isLightweight = true;
	ear10.CountryOforigin = "Turkey";
	ear10.stoneType = "Cubic Zirconia";
	ear10.DesignType = "Minimal";
	ear10.width = 2;
	ear10.isStockAvailable = true;
	ear10.grams = 14;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear10.Type);
	System.out.println("length : " + ear10.length);
	System.out.println("price  : " + ear10.price);
	System.out.println("quantity: " + ear10.quantity);
	System.out.println("brand: " + ear10.brand);
	System.out.println("colour: " + ear10.colour);
	System.out.println("isMultipleColour : " + ear10.isMultipleColour);
	System.out.println("isqualityGood: " + ear10.isqualityGood);
	System.out.println("size: " + ear10.size);
	System.out.println("Weight: " + ear10.Weight);
	System.out.println("isAntique: " + ear10.isAntique);
	System.out.println("warranty: " + ear10.warranty);
	System.out.println("manufactureDate: " + ear10.manufactureDate);
	System.out.println("isHandMade : " + ear10.isHandMade);
	System.out.println("Discount : " + ear10.Discount);
	System.out.println("sellername : " + ear10.sellername);
	System.out.println("numberOfStone : " + ear10.numberOfStone);
	System.out.println("coustomreview : " + ear10.coustomreview);
	System.out.println("rating : " + ear10.rating);
	System.out.println("isLightweight : " + ear10.isLightweight);
	System.out.println("Country Of origin : " + ear10.CountryOforigin);
	System.out.println("stoneType : " + ear10.stoneType);
	System.out.println("Design Type : " + ear10.DesignType);
	System.out.println("width : " + ear10.width);
	System.out.println("isStockAvailable : " + ear10.isStockAvailable);
	System.out.println("grams: " + ear10.grams);
	
	Earing ear11 = new Earing();
	ear11.Type = "Chandelier";
	ear11.length = "11 cm";
	ear11.price = 2199;
	ear11.quantity = 1;
	ear11.brand = "Shining Diva";
	ear11.colour = "Maroon";
	ear11.isMultipleColour = true;
	ear11.isqualityGood = true;
	ear11.size = "Extra Large";
	ear11.Weight = "45 grams";
	ear11.isAntique = true;
	ear11.warranty = "1 year";
	ear11.manufactureDate = "14-01-2026";
	ear11.isHandMade = true;
	ear11.Discount = "32%";
	ear11.sellername = "Lifestyle Seller";
	ear11.numberOfStone = 30;
	ear11.coustomreview = "Grand and attractive earrings";
	ear11.rating = 5;
	ear11.isLightweight = false;
	ear11.CountryOforigin = "Spain";
	ear11.stoneType = "Garnet";
	ear11.DesignType = "Wedding";
	ear11.width = 7;
	ear11.isStockAvailable = true;
	ear11.grams = 45;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear11.Type);
	System.out.println("length : " + ear11.length);
	System.out.println("price  : " + ear11.price);
	System.out.println("quantity: " + ear11.quantity);
	System.out.println("brand: " + ear11.brand);
	System.out.println("colour: " + ear11.colour);
	System.out.println("isMultipleColour : " + ear11.isMultipleColour);
	System.out.println("isqualityGood: " + ear11.isqualityGood);
	System.out.println("size: " + ear11.size);
	System.out.println("Weight: " + ear11.Weight);
	System.out.println("isAntique: " + ear11.isAntique);
	System.out.println("warranty: " + ear11.warranty);
	System.out.println("manufactureDate: " + ear11.manufactureDate);
	System.out.println("isHandMade : " + ear11.isHandMade);
	System.out.println("Discount : " + ear11.Discount);
	System.out.println("sellername : " + ear11.sellername);
	System.out.println("numberOfStone : " + ear11.numberOfStone);
	System.out.println("coustomreview : " + ear11.coustomreview);
	System.out.println("rating : " + ear11.rating);
	System.out.println("isLightweight : " + ear11.isLightweight);
	System.out.println("Country Of origin : " + ear11.CountryOforigin);
	System.out.println("stoneType : " + ear11.stoneType);
	System.out.println("Design Type : " + ear11.DesignType);
	System.out.println("width : " + ear11.width);
	System.out.println("isStockAvailable : " + ear11.isStockAvailable);
	System.out.println("grams: " + ear11.grams);
	
	
	Earing ear12 = new Earing();
	ear12.Type = "Teardrop";
	ear12.length = "6.5 cm";
	ear12.price = 1099;
	ear12.quantity = 2;
	ear12.brand = "Anmi";
	ear12.colour = "Turquoise";
	ear12.isMultipleColour = true;
	ear12.isqualityGood = true;
	ear12.size = "Medium";
	ear12.Weight = "22 grams";
	ear12.isAntique = false;
	ear12.warranty = "10 months";
	ear12.manufactureDate = "08-02-2026";
	ear12.isHandMade = true;
	ear12.Discount = "24%";
	ear12.sellername = "Craftsvilla Seller";
	ear12.numberOfStone = 14;
	ear12.coustomreview = "Beautiful colour and elegant look";
	ear12.rating = 4;
	ear12.isLightweight = true;
	ear12.CountryOforigin = "Indonesia";
	ear12.stoneType = "Turquoise Stone";
	ear12.DesignType = "Boho";
	ear12.width = 3;
	ear12.isStockAvailable = true;
	ear12.grams = 22;
	System.out.println("after init instance variable");
	System.out.println("length : " + ear12.length);
	System.out.println("price  : " + ear12.price);
	System.out.println("quantity: " + ear12.quantity);
	System.out.println("brand: " + ear12.brand);
	System.out.println("colour: " + ear12.colour);
	System.out.println("isMultipleColour : " + ear12.isMultipleColour);
	System.out.println("isqualityGood: " + ear12.isqualityGood);
	System.out.println("size: " + ear12.size);
	System.out.println("Weight: " + ear12.Weight);
	System.out.println("isAntique: " + ear12.isAntique);
	System.out.println("warranty: " + ear12.warranty);
	System.out.println("manufactureDate: " + ear12.manufactureDate);
	System.out.println("isHandMade : " + ear12.isHandMade);
	System.out.println("Discount : " + ear12.Discount);
	System.out.println("sellername : " + ear12.sellername);
	System.out.println("numberOfStone : " + ear12.numberOfStone);
	System.out.println("coustomreview : " + ear12.coustomreview);
	System.out.println("rating : " + ear12.rating);
	System.out.println("isLightweight : " + ear12.isLightweight);
	System.out.println("Country Of origin : " + ear12.CountryOforigin);
	System.out.println("stoneType : " + ear12.stoneType);
	System.out.println("Design Type : " + ear12.DesignType);
	System.out.println("width : " + ear12.width);
	System.out.println("isStockAvailable : " + ear12.isStockAvailable);
	System.out.println("grams: " + ear12.grams);
	
	Earing ear13 = new Earing();
	ear13.Type = "Threader";
	ear13.length = "7.5 cm";
	ear13.price = 899;
	ear13.quantity = 2;
	ear13.brand = "Jewels Galaxy";
	ear13.colour = "Lavender";
	ear13.isMultipleColour = true;
	ear13.isqualityGood = true;
	ear13.size = "Medium";
	ear13.Weight = "20 grams";
	ear13.isAntique = false;
	ear13.warranty = "11 months";
	ear13.manufactureDate = "18-02-2026";
	ear13.isHandMade = false;
	ear13.Discount = "21%";
	ear13.sellername = "Limeroad Seller";
	ear13.numberOfStone = 11;
	ear13.coustomreview = "Trendy and lightweight design";
	ear13.rating = 4;
	ear13.isLightweight = true;
	ear13.CountryOforigin = "Vietnam";
	ear13.stoneType = "Quartz";
	ear13.DesignType = "Modern Chic";
	ear13.width = 3;
	ear13.isStockAvailable = true;
	ear13.grams = 20;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear13.Type);
	System.out.println("length : " + ear13.length);
	System.out.println("price  : " + ear13.price);
	System.out.println("quantity: " + ear13.quantity);
	System.out.println("brand: " + ear13.brand);
	System.out.println("colour: " + ear13.colour);
	System.out.println("isMultipleColour : " + ear13.isMultipleColour);
	System.out.println("isqualityGood: " + ear13.isqualityGood);
	System.out.println("size: " + ear13.size);
	System.out.println("Weight: " + ear13.Weight);
	System.out.println("isAntique: " + ear13.isAntique);
	System.out.println("warranty: " + ear13.warranty);
	System.out.println("manufactureDate: " + ear13.manufactureDate);
	System.out.println("isHandMade : " + ear13.isHandMade);
	System.out.println("Discount : " + ear13.Discount);
	System.out.println("sellername : " + ear13.sellername);
	System.out.println("numberOfStone : " + ear13.numberOfStone);
	System.out.println("coustomreview : " + ear13.coustomreview);
	System.out.println("rating : " + ear13.rating);
	System.out.println("isLightweight : " + ear13.isLightweight);
	System.out.println("Country Of origin : " + ear13.CountryOforigin);
	System.out.println("stoneType : " + ear13.stoneType);
	System.out.println("Design Type : " + ear13.DesignType);
	System.out.println("width : " + ear13.width);
	System.out.println("isStockAvailable : " + ear13.isStockAvailable);
	System.out.println("grams: " + ear13.grams);
	
	
	Earing ear14 = new Earing();
    ear14.Type = "Crawler";
	ear14.length = "5.5 cm";
	ear14.price = 1199;
	ear14.quantity = 1;
	ear14.brand = "YouBella";
	ear14.colour = "Champagne";
	ear14.isMultipleColour = false;
	ear14.isqualityGood = true;
	ear14.size = "Medium";
	ear14.Weight = "21 grams";
	ear14.isAntique = false;
	ear14.warranty = "6 months";
	ear14.manufactureDate = "11-02-2026";
	ear14.isHandMade = true;
	ear14.Discount = "19%";
	ear14.sellername = "Flipkart Fashion Seller";
	ear14.numberOfStone = 13;
	ear14.coustomreview = "Elegant and unique ear crawler";
	ear14.rating = 4;
	ear14.isLightweight = true;
	ear14.CountryOforigin = "Germany";
	ear14.stoneType = "Moonstone";
	ear14.DesignType = "Minimalist";
	ear14.width = 3;
	ear14.isStockAvailable = true;
	ear14.grams = 21;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear14.Type);
	System.out.println("length : " + ear14.length);
	System.out.println("price  : " + ear14.price);
	System.out.println("quantity: " + ear14.quantity);
	System.out.println("brand: " + ear14.brand);
	System.out.println("colour: " + ear14.colour);
	System.out.println("isMultipleColour : " + ear14.isMultipleColour);
	System.out.println("isqualityGood: " + ear14.isqualityGood);
	System.out.println("size: " + ear14.size);
	System.out.println("Weight: " + ear14.Weight);
	System.out.println("isAntique: " + ear14.isAntique);
	System.out.println("warranty: " + ear14.warranty);
	System.out.println("manufactureDate: " + ear14.manufactureDate);
	System.out.println("isHandMade : " + ear14.isHandMade);
	System.out.println("Discount : " + ear14.Discount);
	System.out.println("sellername : " + ear14.sellername);
	System.out.println("numberOfStone : " + ear14.numberOfStone);
	System.out.println("coustomreview : " + ear14.coustomreview);
	System.out.println("rating : " + ear14.rating);
	System.out.println("isLightweight : " + ear14.isLightweight);
	System.out.println("Country Of origin : " + ear14.CountryOforigin);
	System.out.println("stoneType : " + ear14.stoneType);
	System.out.println("Design Type : " + ear14.DesignType);
	System.out.println("width : " + ear14.width);
	System.out.println("isStockAvailable : " + ear14.isStockAvailable);
	System.out.println("grams: " + ear14.grams);
		
		
    Earing ear15= new Earing();
	ear15.Type = "Bali";
	ear15.length = "3 cm";
	ear15.price = 559;
	ear15.quantity = 2;
	ear15.brand = "Spargz";
	ear15.colour = "Bronze";
	ear15.isMultipleColour = false;
	ear15.isqualityGood = true;
	ear15.size = "Small";
	ear15.Weight = "13 grams";
	ear15.isAntique = true;
	ear15.warranty = "5 months";
	ear15.manufactureDate = "03-02-2026";
	ear15.isHandMade = false;
	ear15.Discount = "14%";
	ear15.sellername = "Snapdeal Fashion Seller";
	ear15.numberOfStone = 4;
	ear15.coustomreview = "Simple traditional bali design";
	ear15.rating = 4;
	ear15.isLightweight = true;
	ear15.CountryOforigin = "Nepal";
	ear15.stoneType = "Agate";
	ear15.DesignType = "Traditional";
	ear15.width = 2;
	ear15.isStockAvailable = true;
	ear15.grams = 13;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear15.Type);
	System.out.println("length : " + ear15.length);
	System.out.println("price  : " + ear15.price);
	System.out.println("quantity: " + ear15.quantity);
	System.out.println("brand: " + ear15.brand);
	System.out.println("colour: " + ear15.colour);
	System.out.println("isMultipleColour : " + ear15.isMultipleColour);
	System.out.println("isqualityGood: " + ear15.isqualityGood);
	System.out.println("size: " + ear15.size);
	System.out.println("Weight: " + ear15.Weight);
	System.out.println("isAntique: " + ear15.isAntique);
	System.out.println("warranty: " + ear15.warranty);
	System.out.println("manufactureDate: " + ear15.manufactureDate);
	System.out.println("isHandMade : " + ear15.isHandMade);
	System.out.println("Discount : " + ear15.Discount);
	System.out.println("sellername : " + ear15.sellername);
	System.out.println("numberOfStone : " + ear15.numberOfStone);
	System.out.println("coustomreview : " + ear15.coustomreview);
	System.out.println("rating : " + ear15.rating);
	System.out.println("isLightweight : " + ear15.isLightweight);
	System.out.println("Country Of origin : " + ear15.CountryOforigin);
	System.out.println("stoneType : " + ear15.stoneType);
	System.out.println("Design Type : " + ear15.DesignType);
	System.out.println("width : " + ear15.width);
	System.out.println("isStockAvailable : " + ear15.isStockAvailable);
	System.out.println("grams: " + ear15.grams);
	
	Earing ear16= new Earing();
	ear16.Type = "Leaf";
	ear16.length = "6 cm";
	ear16.price = 949;
	ear16.quantity = 1;
	ear16.brand = "Style Quotient";
	ear16.colour = "Teal";
	ear16.isMultipleColour = true;
	ear16.isqualityGood = true;
	ear16.size = "Medium";
	ear16.Weight = "24 grams";
	ear16.isAntique = false;
	ear16.warranty = "9 months";
	ear16.manufactureDate = "21-01-2026";
	ear16.isHandMade = true;
	ear16.Discount = "23%";
	ear16.sellername = "Amazon Fashion Seller";
	ear16.numberOfStone = 16;
	ear16.coustomreview = "Nature inspired elegant design";
	ear16.rating = 5;
	ear16.isLightweight = false;
	ear16.CountryOforigin = "Philippines";
	ear16.stoneType = "Peridot";
	ear16.DesignType = "Nature";
	ear16.width = 4;
	ear16.isStockAvailable = true;
	ear16.grams = 24;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear16.Type);
	System.out.println("length : " + ear16.length);
	System.out.println("price  : " + ear16.price);
	System.out.println("quantity: " + ear16.quantity);
	System.out.println("brand: " + ear16.brand);
	System.out.println("colour: " + ear16.colour);
	System.out.println("isMultipleColour : " + ear16.isMultipleColour);
	System.out.println("isqualityGood: " + ear16.isqualityGood);
	System.out.println("size: " + ear16.size);
	System.out.println("Weight: " + ear16.Weight);
	System.out.println("isAntique: " + ear16.isAntique);
	System.out.println("warranty: " + ear16.warranty);
	System.out.println("manufactureDate: " + ear16.manufactureDate);
	System.out.println("isHandMade : " + ear16.isHandMade);
	System.out.println("Discount : " + ear16.Discount);
	System.out.println("sellername : " + ear16.sellername);
	System.out.println("numberOfStone : " + ear16.numberOfStone);
	System.out.println("coustomreview : " + ear16.coustomreview);
	System.out.println("rating : " + ear16.rating);
	System.out.println("isLightweight : " + ear16.isLightweight);
	System.out.println("Country Of origin : " + ear16.CountryOforigin);
	System.out.println("stoneType : " + ear16.stoneType);
	System.out.println("Design Type : " + ear16.DesignType);
	System.out.println("width : " + ear16.width);
	System.out.println("isStockAvailable : " + ear16.isStockAvailable);
	System.out.println("grams: " + ear16.grams);
	
	Earing ear17= new Earing();
	ear17.Type = "Feather";
	ear17.length = "8.5 cm";
	ear17.price = 1199;
	ear17.quantity = 1;
	ear17.brand = "UrbanMela";
	ear17.colour = "Sky Blue";
	ear17.isMultipleColour = true;
	ear17.isqualityGood = true;
	ear17.size = "Large";
	ear17.Weight = "26 grams";
	ear17.isAntique = false;
	ear17.warranty = "6 months";
	ear17.manufactureDate = "01-03-2026";
	ear17.isHandMade = true;
	ear17.Discount = "26%";
	ear17.sellername = "Ajio Fashion Seller";
	ear17.numberOfStone = 9;
	ear17.coustomreview = "Light and stylish feather design";
	ear17.rating = 4;
	ear17.isLightweight = true;
	ear17.CountryOforigin = "Brazil";
	ear17.stoneType = "Aquamarine";
	ear17.DesignType = "Bohemian";
	ear17.width = 4;
	ear17.isStockAvailable = true;
	ear17.grams = 26;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear17.Type);
	System.out.println("length : " + ear17.length);
	System.out.println("price  : " + ear17.price);
	System.out.println("quantity: " + ear17.quantity);
	System.out.println("brand: " + ear17.brand);
	System.out.println("colour: " + ear17.colour);
	System.out.println("isMultipleColour : " + ear17.isMultipleColour);
	System.out.println("isqualityGood: " + ear17.isqualityGood);
	System.out.println("size: " + ear17.size);
	System.out.println("Weight: " + ear17.Weight);
	System.out.println("isAntique: " + ear17.isAntique);
	System.out.println("warranty: " + ear17.warranty);
	System.out.println("manufactureDate: " + ear17.manufactureDate);
	System.out.println("isHandMade : " + ear17.isHandMade);
	System.out.println("Discount : " + ear17.Discount);
	System.out.println("sellername : " + ear17.sellername);
	System.out.println("numberOfStone : " + ear17.numberOfStone);
	System.out.println("coustomreview : " + ear17.coustomreview);
	System.out.println("rating : " + ear17.rating);
	System.out.println("isLightweight : " + ear17.isLightweight);
	System.out.println("Country Of origin : " + ear17.CountryOforigin);
	System.out.println("stoneType : " + ear17.stoneType);
	System.out.println("Design Type : " + ear17.DesignType);
	System.out.println("width : " + ear17.width);
	System.out.println("isStockAvailable : " + ear17.isStockAvailable);
	System.out.println("grams: " + ear17.grams);
	
	Earing ear18= new Earing();
	ear18.Type = "Lotus";
	ear18.length = "7 cm";
	ear18.price = 1299;
	ear18.quantity = 1;
	ear18.brand = "Panash";
	ear18.colour = "Magenta";
	ear18.isMultipleColour = true;
	ear18.isqualityGood = true;
	ear18.size = "Medium";
	ear18.Weight = "27 grams";
	ear18.isAntique = false;
	ear18.warranty = "8 months";
	ear18.manufactureDate = "10-03-2026";
	ear18.isHandMade = true;
	ear18.Discount = "27%";
	ear18.sellername = "Nykaa Fashion Seller";
	ear18.numberOfStone = 17;
	ear18.coustomreview = "Beautiful lotus shaped earrings";
	ear18.rating = 5;
	ear18.isLightweight = false;
	ear18.CountryOforigin = "Sri Lanka";
	ear18.stoneType = "Spinel";
	ear18.DesignType = "Floral";
	ear18.width = 4;
	ear18.isStockAvailable = true;
	ear18.grams = 27;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear18.Type);
	System.out.println("length : " + ear18.length);
	System.out.println("price  : " + ear18.price);
	System.out.println("quantity: " + ear18.quantity);
	System.out.println("brand: " + ear18.brand);
	System.out.println("colour: " + ear18.colour);
	System.out.println("isMultipleColour : " + ear18.isMultipleColour);
	System.out.println("isqualityGood: " + ear18.isqualityGood);
	System.out.println("size: " + ear18.size);
	System.out.println("Weight: " + ear18.Weight);
	System.out.println("isAntique: " + ear18.isAntique);
	System.out.println("warranty: " + ear18.warranty);
	System.out.println("manufactureDate: " + ear18.manufactureDate);
	System.out.println("isHandMade : " + ear18.isHandMade);
	System.out.println("Discount : " + ear18.Discount);
	System.out.println("sellername : " + ear18.sellername);
	System.out.println("numberOfStone : " + ear18.numberOfStone);
	System.out.println("coustomreview : " + ear18.coustomreview);
	System.out.println("rating : " + ear18.rating);
	System.out.println("isLightweight : " + ear18.isLightweight);
	System.out.println("Country Of origin : " + ear18.CountryOforigin);
	System.out.println("stoneType : " + ear18.stoneType);
	System.out.println("Design Type : " + ear18.DesignType);
	System.out.println("width : " + ear18.width);
	System.out.println("isStockAvailable : " + ear18.isStockAvailable);
	System.out.println("grams: " + ear18.grams);
	
	Earing ear19= new Earing();
	ear19.Type = "Butterfly";
	ear19.length = "6.8 cm";
	ear19.price = 1349;
	ear19.quantity = 1;
	ear19.brand = "Kriaa";
	ear19.colour = "Peach";
	ear19.isMultipleColour = true;
	ear19.isqualityGood = true;
	ear19.size = "Medium";
	ear19.Weight = "23 grams";
	ear19.isAntique = false;
	ear19.warranty = "7 months";
	ear19.manufactureDate = "12-03-2026";
	ear19.isHandMade = true;
	ear19.Discount = "29%";
	ear19.sellername = "Amazon Handcraft Seller";
	ear19.numberOfStone = 19;
	ear19.coustomreview = "Beautiful butterfly design earrings";
	ear19.rating = 5;
	ear19.isLightweight = true;
	ear19.CountryOforigin = "Bangladesh";
	ear19.stoneType = "Morganite";
	ear19.DesignType = "Artistic";
	ear19.width = 4;
	ear19.isStockAvailable = true;
	ear19.grams = 23;
	System.out.println("after init instance variable");
	System.out.println("type : " + ear19.Type);
	System.out.println("length : " + ear19.length);
	System.out.println("price  : " + ear19.price);
	System.out.println("quantity: " + ear19.quantity);
	System.out.println("brand: " + ear19.brand);
	System.out.println("colour: " + ear19.colour);
	System.out.println("isMultipleColour : " + ear19.isMultipleColour);
	System.out.println("isqualityGood: " + ear19.isqualityGood);
	System.out.println("size: " + ear19.size);
	System.out.println("Weight: " + ear19.Weight);
	System.out.println("isAntique: " + ear19.isAntique);
	System.out.println("warranty: " + ear19.warranty);
	System.out.println("manufactureDate: " + ear19.manufactureDate);
	System.out.println("isHandMade : " + ear19.isHandMade);
	System.out.println("Discount : " + ear19.Discount);
	System.out.println("sellername : " + ear19.sellername);
	System.out.println("numberOfStone : " + ear19.numberOfStone);
	System.out.println("coustomreview : " + ear19.coustomreview);
	System.out.println("rating : " + ear19.rating);
	System.out.println("isLightweight : " + ear19.isLightweight);
	System.out.println("Country Of origin : " + ear19.CountryOforigin);
	System.out.println("stoneType : " + ear19.stoneType);
	System.out.println("Design Type : " + ear19.DesignType);
	System.out.println("width : " + ear19.width);
	System.out.println("isStockAvailable : " + ear19.isStockAvailable);
	System.out.println("grams: " + ear19.grams);
	}
}