class FaceWashExecutor{
    public static void main(String[] args){
	FaceWash faceWash1 = new FaceWash();
	faceWash1.name = "Oil Control Face Wash";
	faceWash1.brand = "Himalaya";
	faceWash1.skinType = "Oily";
	faceWash1.formulation = "Gel";
	faceWash1.fragrance = "Herbal";
	faceWash1.packagingType = "Tube";
	faceWash1.volumeInML = 150;
	faceWash1.price = 180;
	faceWash1.quantity = 2;
	faceWash1.isParabenFree = true;
	faceWash1.isSulfateFree = true;
	faceWash1.isDermatologistTested = true;
	faceWash1.isForSensitiveSkin = false;
	faceWash1.mainIngredients = "Neem, Turmeric";
	faceWash1.expiryDate = "12-2027";
	faceWash1.manufactureDate = "01-2026";
	faceWash1.instructions = "Apply on wet face, lather, rinse";
	faceWash1.benefits = "Controls oil, reduces pimples";
	faceWash1.texture = "Smooth gel";
	faceWash1.colour = "Light green";
	faceWash1.scentStrength = "Mild";
	faceWash1.rating = 5;
	faceWash1.customerReview = "Keeps my skin fresh and oil-free";
	faceWash1.isStockAvailable = true;
	faceWash1.countryOfOrigin = "India";

	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash1.name);
	System.out.println("brand : " + faceWash1.brand);
	System.out.println("skinType : " + faceWash1.skinType);
	System.out.println("formulation : " + faceWash1.formulation);
	System.out.println("fragrance : " + faceWash1.fragrance);
	System.out.println("packagingType : " + faceWash1.packagingType);
	System.out.println("volumeInML : " + faceWash1.volumeInML);
	System.out.println("price : " + faceWash1.price);
	System.out.println("quantity : " + faceWash1.quantity);
	System.out.println("isParabenFree : " + faceWash1.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash1.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash1.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash1.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash1.mainIngredients);
	System.out.println("expiryDate : " + faceWash1.expiryDate);
	System.out.println("manufactureDate : " + faceWash1.manufactureDate);
	System.out.println("instructions : " + faceWash1.instructions);
	System.out.println("benefits : " + faceWash1.benefits);
	System.out.println("texture : " + faceWash1.texture);
	System.out.println("colour : " + faceWash1.colour);
	System.out.println("scentStrength : " + faceWash1.scentStrength);
	System.out.println("rating : " + faceWash1.rating);
	System.out.println("customerReview : " + faceWash1.customerReview);
	System.out.println("isStockAvailable : " + faceWash1.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash1.countryOfOrigin);


	// FaceWash2
	FaceWash faceWash2 = new FaceWash();
	faceWash2.name = "Hydrating Face Wash";
	faceWash2.brand = "Neutrogena";
	faceWash2.skinType = "Dry";
	faceWash2.formulation = "Cream";
	faceWash2.fragrance = "Mild";
	faceWash2.packagingType = "Pump Bottle";
	faceWash2.volumeInML = 200;
	faceWash2.price = 320;
	faceWash2.quantity = 1;
	faceWash2.isParabenFree = true;
	faceWash2.isSulfateFree = true;
	faceWash2.isDermatologistTested = true;
	faceWash2.isForSensitiveSkin = true;
	faceWash2.mainIngredients = "Glycerin, Vitamin E";
	faceWash2.expiryDate = "03-2027";
	faceWash2.manufactureDate = "03-2026";
	faceWash2.instructions = "Apply on wet face, massage, rinse";
	faceWash2.benefits = "Moisturizes and soothes dry skin";
	faceWash2.texture = "Creamy";
	faceWash2.colour = "White";
	faceWash2.scentStrength = "Mild";
	faceWash2.rating = 5;
	faceWash2.customerReview = "Softens my skin instantly";
	faceWash2.isStockAvailable = true;
	faceWash2.countryOfOrigin = "USA";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash2.name);
	System.out.println("brand : " + faceWash2.brand);
	System.out.println("skinType : " + faceWash2.skinType);
	System.out.println("formulation : " + faceWash2.formulation);
	System.out.println("fragrance : " + faceWash2.fragrance);
	System.out.println("packagingType : " + faceWash2.packagingType);
	System.out.println("volumeInML : " + faceWash2.volumeInML);
	System.out.println("price : " + faceWash2.price);
	System.out.println("quantity : " + faceWash2.quantity);
	System.out.println("isParabenFree : " + faceWash2.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash2.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash2.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash2.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash2.mainIngredients);
	System.out.println("expiryDate : " + faceWash2.expiryDate);
	System.out.println("manufactureDate : " + faceWash2.manufactureDate);
	System.out.println("instructions : " + faceWash2.instructions);
	System.out.println("benefits : " + faceWash2.benefits);
	System.out.println("texture : " + faceWash2.texture);
	System.out.println("colour : " + faceWash2.colour);
	System.out.println("scentStrength : " + faceWash2.scentStrength);
	System.out.println("rating : " + faceWash2.rating);
	System.out.println("customerReview : " + faceWash2.customerReview);
	System.out.println("isStockAvailable : " + faceWash2.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash2.countryOfOrigin);

	// FaceWash3
	FaceWash faceWash3 = new FaceWash();
	faceWash3.name = "Charcoal Face Wash";
	faceWash3.brand = "Garnier";
	faceWash3.skinType = "Combination";
	faceWash3.formulation = "Gel";
	faceWash3.fragrance = "Neutral";
	faceWash3.packagingType = "Tube";
	faceWash3.volumeInML = 150;
	faceWash3.price = 250;
	faceWash3.quantity = 2;
	faceWash3.isParabenFree = false;
	faceWash3.isSulfateFree = false;
	faceWash3.isDermatologistTested = true;
	faceWash3.isForSensitiveSkin = false;
	faceWash3.mainIngredients = "Charcoal, Lemon Extract";
	faceWash3.expiryDate = "06-2027";
	faceWash3.manufactureDate = "06-2026";
	faceWash3.instructions = "Apply on damp face, lather, rinse";
	faceWash3.benefits = "Removes excess oil and dirt";
	faceWash3.texture = "Gel";
	faceWash3.colour = "Black";
	faceWash3.scentStrength = "Neutral";
	faceWash3.rating = 4;
	faceWash3.customerReview = "Feels clean, not too harsh";
	faceWash3.isStockAvailable = true;
	faceWash3.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash3.name);
	System.out.println("brand : " + faceWash3.brand);
	System.out.println("skinType : " + faceWash3.skinType);
	System.out.println("formulation : " + faceWash3.formulation);
	System.out.println("fragrance : " + faceWash3.fragrance);
	System.out.println("packagingType : " + faceWash3.packagingType);
	System.out.println("volumeInML : " + faceWash3.volumeInML);
	System.out.println("price : " + faceWash3.price);
	System.out.println("quantity : " + faceWash3.quantity);
	System.out.println("isParabenFree : " + faceWash3.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash3.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash3.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash3.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash3.mainIngredients);
	System.out.println("expiryDate : " + faceWash3.expiryDate);
	System.out.println("manufactureDate : " + faceWash3.manufactureDate);
	System.out.println("instructions : " + faceWash3.instructions);
	System.out.println("benefits : " + faceWash3.benefits);
	System.out.println("texture : " + faceWash3.texture);
	System.out.println("colour : " + faceWash3.colour);
	System.out.println("scentStrength : " + faceWash3.scentStrength);
	System.out.println("rating : " + faceWash3.rating);
	System.out.println("customerReview : " + faceWash3.customerReview);
	System.out.println("isStockAvailable : " + faceWash3.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash3.countryOfOrigin);

	// FaceWash4
	FaceWash faceWash4 = new FaceWash();
	faceWash4.name = "Aloe Vera Face Wash";
	faceWash4.brand = "Biotique";
	faceWash4.skinType = "Sensitive";
	faceWash4.formulation = "Gel";
	faceWash4.fragrance = "Herbal";
	faceWash4.packagingType = "Tube";
	faceWash4.volumeInML = 120;
	faceWash4.price = 180;
	faceWash4.quantity = 3;
	faceWash4.isParabenFree = true;
	faceWash4.isSulfateFree = true;
	faceWash4.isDermatologistTested = true;
	faceWash4.isForSensitiveSkin = true;
	faceWash4.mainIngredients = "Aloe Vera, Cucumber Extract";
	faceWash4.expiryDate = "08-2026";
	faceWash4.manufactureDate = "08-2025";
	faceWash4.instructions = "Apply gently, lather, rinse";
	faceWash4.benefits = "Soothes and hydrates sensitive skin";
	faceWash4.texture = "Gel";
	faceWash4.colour = "Light Green";
	faceWash4.scentStrength = "Mild";
	faceWash4.rating = 5;
	faceWash4.customerReview = "Gentle and refreshing";
	faceWash4.isStockAvailable = true;
	faceWash4.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash4.name);
	System.out.println("brand : " + faceWash4.brand);
	System.out.println("skinType : " + faceWash4.skinType);
	System.out.println("formulation : " + faceWash4.formulation);
	System.out.println("fragrance : " + faceWash4.fragrance);
	System.out.println("packagingType : " + faceWash4.packagingType);
	System.out.println("volumeInML : " + faceWash4.volumeInML);
	System.out.println("price : " + faceWash4.price);
	System.out.println("quantity : " + faceWash4.quantity);
	System.out.println("isParabenFree : " + faceWash4.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash4.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash4.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash4.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash4.mainIngredients);
	System.out.println("expiryDate : " + faceWash4.expiryDate);
	System.out.println("manufactureDate : " + faceWash4.manufactureDate);
	System.out.println("instructions : " + faceWash4.instructions);
	System.out.println("benefits : " + faceWash4.benefits);
	System.out.println("texture : " + faceWash4.texture);
	System.out.println("colour : " + faceWash4.colour);
	System.out.println("scentStrength : " + faceWash4.scentStrength);
	System.out.println("rating : " + faceWash4.rating);
	System.out.println("customerReview : " + faceWash4.customerReview);
	System.out.println("isStockAvailable : " + faceWash4.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash4.countryOfOrigin);

	// FaceWash5
	FaceWash faceWash5 = new FaceWash();
	faceWash5.name = "Vitamin C Face Wash";
	faceWash5.brand = "The Body Shop";
	faceWash5.skinType = "Normal";
	faceWash5.formulation = "Foam";
	faceWash5.fragrance = "Citrus";
	faceWash5.packagingType = "Tube";
	faceWash5.volumeInML = 150;
	faceWash5.price = 450;
	faceWash5.quantity = 1;
	faceWash5.isParabenFree = true;
	faceWash5.isSulfateFree = true;
	faceWash5.isDermatologistTested = true;
	faceWash5.isForSensitiveSkin = false;
	faceWash5.mainIngredients = "Vitamin C, Orange Extract";
	faceWash5.expiryDate = "12-2026";
	faceWash5.manufactureDate = "12-2025";
	faceWash5.instructions = "Apply on wet face, lather, rinse";
	faceWash5.benefits = "Brightens skin and reduces dullness";
	faceWash5.texture = "Foamy";
	faceWash5.colour = "Orange";
	faceWash5.scentStrength = "Fresh";
	faceWash5.rating = 5;
	faceWash5.customerReview = "Makes my skin glow";
	faceWash5.isStockAvailable = true;
	faceWash5.countryOfOrigin = "UK";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash5.name);
	System.out.println("brand : " + faceWash5.brand);
	System.out.println("skinType : " + faceWash5.skinType);
	System.out.println("formulation : " + faceWash5.formulation);
	System.out.println("fragrance : " + faceWash5.fragrance);
	System.out.println("packagingType : " + faceWash5.packagingType);
	System.out.println("volumeInML : " + faceWash5.volumeInML);
	System.out.println("price : " + faceWash5.price);
	System.out.println("quantity : " + faceWash5.quantity);
	System.out.println("isParabenFree : " + faceWash5.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash5.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash5.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash5.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash5.mainIngredients);
	System.out.println("expiryDate : " + faceWash5.expiryDate);
	System.out.println("manufactureDate : " + faceWash5.manufactureDate);
	System.out.println("instructions : " + faceWash5.instructions);
	System.out.println("benefits : " + faceWash5.benefits);
	System.out.println("texture : " + faceWash5.texture);
	System.out.println("colour : " + faceWash5.colour);
	System.out.println("scentStrength : " + faceWash5.scentStrength);
	System.out.println("rating : " + faceWash5.rating);
	System.out.println("customerReview : " + faceWash5.customerReview);
	System.out.println("isStockAvailable : " + faceWash5.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash5.countryOfOrigin);

	// FaceWash6
	FaceWash faceWash6 = new FaceWash();
	faceWash6.name = "Tea Tree Face Wash";
	faceWash6.brand = "Mamaearth";
	faceWash6.skinType = "Oily";
	faceWash6.formulation = "Gel";
	faceWash6.fragrance = "Mild Herbal";
	faceWash6.packagingType = "Pump Bottle";
	faceWash6.volumeInML = 160;
	faceWash6.price = 299;
	faceWash6.quantity = 2;
	faceWash6.isParabenFree = true;
	faceWash6.isSulfateFree = true;
	faceWash6.isDermatologistTested = true;
	faceWash6.isForSensitiveSkin = false;
	faceWash6.mainIngredients = "Tea Tree Oil, Aloe Vera";
	faceWash6.expiryDate = "01-2027";
	faceWash6.manufactureDate = "01-2026";
	faceWash6.instructions = "Apply on face, massage gently, rinse";
	faceWash6.benefits = "Reduces pimples and controls oil";
	faceWash6.texture = "Gel";
	faceWash6.colour = "Light Green";
	faceWash6.scentStrength = "Mild";
	faceWash6.rating = 5;
	faceWash6.customerReview = "Helps my acne-prone skin";
	faceWash6.isStockAvailable = true;
	faceWash6.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash6.name);
	System.out.println("brand : " + faceWash6.brand);
	System.out.println("skinType : " + faceWash6.skinType);
	System.out.println("formulation : " + faceWash6.formulation);
	System.out.println("fragrance : " + faceWash6.fragrance);
	System.out.println("packagingType : " + faceWash6.packagingType);
	System.out.println("volumeInML : " + faceWash6.volumeInML);
	System.out.println("price : " + faceWash6.price);
	System.out.println("quantity : " + faceWash6.quantity);
	System.out.println("isParabenFree : " + faceWash6.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash6.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash6.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash6.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash6.mainIngredients);
	System.out.println("expiryDate : " + faceWash6.expiryDate);
	System.out.println("manufactureDate : " + faceWash6.manufactureDate);
	System.out.println("instructions : " + faceWash6.instructions);
	System.out.println("benefits : " + faceWash6.benefits);
	System.out.println("texture : " + faceWash6.texture);
	System.out.println("colour : " + faceWash6.colour);
	System.out.println("scentStrength : " + faceWash6.scentStrength);
	System.out.println("rating : " + faceWash6.rating);
	System.out.println("customerReview : " + faceWash6.customerReview);
	System.out.println("isStockAvailable : " + faceWash6.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash6.countryOfOrigin);



	// FaceWash7
	FaceWash faceWash7 = new FaceWash();
	faceWash7.name = "Neem Face Wash";
	faceWash7.brand = "Pond's";
	faceWash7.skinType = "Oily";
	faceWash7.formulation = "Gel";
	faceWash7.fragrance = "Herbal";
	faceWash7.packagingType = "Tube";
	faceWash7.volumeInML = 100;
	faceWash7.price = 120;
	faceWash7.quantity = 2;
	faceWash7.isParabenFree = true;
	faceWash7.isSulfateFree = false;
	faceWash7.isDermatologistTested = true;
	faceWash7.isForSensitiveSkin = false;
	faceWash7.mainIngredients = "Neem, Turmeric";
	faceWash7.expiryDate = "10-2026";
	faceWash7.manufactureDate = "10-2025";
	faceWash7.instructions = "Apply on wet face, lather, rinse";
	faceWash7.benefits = "Reduces oil and prevents pimples";
	faceWash7.texture = "Gel";
	faceWash7.colour = "Light Green";
	faceWash7.scentStrength = "Mild";
	faceWash7.rating = 4;
	faceWash7.customerReview = "Effective for my oily skin";
	faceWash7.isStockAvailable = true;
	faceWash7.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash7.name);
	System.out.println("brand : " + faceWash7.brand);
	System.out.println("skinType : " + faceWash7.skinType);
	System.out.println("formulation : " + faceWash7.formulation);
	System.out.println("fragrance : " + faceWash7.fragrance);
	System.out.println("packagingType : " + faceWash7.packagingType);
	System.out.println("volumeInML : " + faceWash7.volumeInML);
	System.out.println("price : " + faceWash7.price);
	System.out.println("quantity : " + faceWash7.quantity);
	System.out.println("isParabenFree : " + faceWash7.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash7.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash7.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash7.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash7.mainIngredients);
	System.out.println("expiryDate : " + faceWash7.expiryDate);
	System.out.println("manufactureDate : " + faceWash7.manufactureDate);
	System.out.println("instructions : " + faceWash7.instructions);
	System.out.println("benefits : " + faceWash7.benefits);
	System.out.println("texture : " + faceWash7.texture);
	System.out.println("colour : " + faceWash7.colour);
	System.out.println("scentStrength : " + faceWash7.scentStrength);
	System.out.println("rating : " + faceWash7.rating);
	System.out.println("customerReview : " + faceWash7.customerReview);
	System.out.println("isStockAvailable : " + faceWash7.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash7.countryOfOrigin);

	// FaceWash8
	FaceWash faceWash8 = new FaceWash();
	faceWash8.name = "Moisturizing Face Wash";
	faceWash8.brand = "Cetaphil";
	faceWash8.skinType = "Dry";
	faceWash8.formulation = "Cream";
	faceWash8.fragrance = "Neutral";
	faceWash8.packagingType = "Pump Bottle";
	faceWash8.volumeInML = 200;
	faceWash8.price = 400;
	faceWash8.quantity = 1;
	faceWash8.isParabenFree = true;
	faceWash8.isSulfateFree = true;
	faceWash8.isDermatologistTested = true;
	faceWash8.isForSensitiveSkin = true;
	faceWash8.mainIngredients = "Glycerin, Aloe Vera";
	faceWash8.expiryDate = "02-2027";
	faceWash8.manufactureDate = "02-2026";
	faceWash8.instructions = "Apply gently, lather, rinse";
	faceWash8.benefits = "Hydrates and nourishes dry skin";
	faceWash8.texture = "Creamy";
	faceWash8.colour = "White";
	faceWash8.scentStrength = "Mild";
	faceWash8.rating = 5;
	faceWash8.customerReview = "Leaves skin soft and smooth";
	faceWash8.isStockAvailable = true;
	faceWash8.countryOfOrigin = "USA";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash8.name);
	System.out.println("brand : " + faceWash8.brand);
	System.out.println("skinType : " + faceWash8.skinType);
	System.out.println("formulation : " + faceWash8.formulation);
	System.out.println("fragrance : " + faceWash8.fragrance);
	System.out.println("packagingType : " + faceWash8.packagingType);
	System.out.println("volumeInML : " + faceWash8.volumeInML);
	System.out.println("price : " + faceWash8.price);
	System.out.println("quantity : " + faceWash8.quantity);
	System.out.println("isParabenFree : " + faceWash8.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash8.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash8.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash8.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash8.mainIngredients);
	System.out.println("expiryDate : " + faceWash8.expiryDate);
	System.out.println("manufactureDate : " + faceWash8.manufactureDate);
	System.out.println("instructions : " + faceWash8.instructions);
	System.out.println("benefits : " + faceWash8.benefits);
	System.out.println("texture : " + faceWash8.texture);
	System.out.println("colour : " + faceWash8.colour);
	System.out.println("scentStrength : " + faceWash8.scentStrength);
	System.out.println("rating : " + faceWash8.rating);
	System.out.println("customerReview : " + faceWash8.customerReview);
	System.out.println("isStockAvailable : " + faceWash8.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash8.countryOfOrigin);

	// FaceWash9
	FaceWash faceWash9 = new FaceWash();
	faceWash9.name = "Exfoliating Face Wash";
	faceWash9.brand = "St. Ives";
	faceWash9.skinType = "Normal";
	faceWash9.formulation = "Scrub Gel";
	faceWash9.fragrance = "Fruity";
	faceWash9.packagingType = "Tube";
	faceWash9.volumeInML = 150;
	faceWash9.price = 300;
	faceWash9.quantity = 2;
	faceWash9.isParabenFree = true;
	faceWash9.isSulfateFree = true;
	faceWash9.isDermatologistTested = true;
	faceWash9.isForSensitiveSkin = false;
	faceWash9.mainIngredients = "Apricot Extract, Walnut Shell Powder";
	faceWash9.expiryDate = "09-2026";
	faceWash9.manufactureDate = "09-2025";
	faceWash9.instructions = "Massage gently, rinse thoroughly";
	faceWash9.benefits = "Removes dead skin and dirt";
	faceWash9.texture = "Scrub Gel";
	faceWash9.colour = "Light Brown";
	faceWash9.scentStrength = "Fresh";
	faceWash9.rating = 4;
	faceWash9.customerReview = "Good exfoliation, not harsh";
	faceWash9.isStockAvailable = true;
	faceWash9.countryOfOrigin = "USA";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash9.name);
	System.out.println("brand : " + faceWash9.brand);
	System.out.println("skinType : " + faceWash9.skinType);
	System.out.println("formulation : " + faceWash9.formulation);
	System.out.println("fragrance : " + faceWash9.fragrance);
	System.out.println("packagingType : " + faceWash9.packagingType);
	System.out.println("volumeInML : " + faceWash9.volumeInML);
	System.out.println("price : " + faceWash9.price);
	System.out.println("quantity : " + faceWash9.quantity);
	System.out.println("isParabenFree : " + faceWash9.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash9.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash9.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash9.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash9.mainIngredients);
	System.out.println("expiryDate : " + faceWash9.expiryDate);
	System.out.println("manufactureDate : " + faceWash9.manufactureDate);
	System.out.println("instructions : " + faceWash9.instructions);
	System.out.println("benefits : " + faceWash9.benefits);
	System.out.println("texture : " + faceWash9.texture);
	System.out.println("colour : " + faceWash9.colour);
	System.out.println("scentStrength : " + faceWash9.scentStrength);
	System.out.println("rating : " + faceWash9.rating);
	System.out.println("customerReview : " + faceWash9.customerReview);
	System.out.println("isStockAvailable : " + faceWash9.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash9.countryOfOrigin);

	// FaceWash10
	FaceWash faceWash10 = new FaceWash();
	faceWash10.name = "Brightening Face Wash";
	faceWash10.brand = "Olay";
	faceWash10.skinType = "Normal to Dry";
	faceWash10.formulation = "Cream";
	faceWash10.fragrance = "Mild Citrus";
	faceWash10.packagingType = "Tube";
	faceWash10.volumeInML = 120;
	faceWash10.price = 350;
	faceWash10.quantity = 1;
	faceWash10.isParabenFree = true;
	faceWash10.isSulfateFree = true;
	faceWash10.isDermatologistTested = true;
	faceWash10.isForSensitiveSkin = true;
	faceWash10.mainIngredients = "Vitamin C, Glycerin";
	faceWash10.expiryDate = "11-2026";
	faceWash10.manufactureDate = "11-2025";
	faceWash10.instructions = "Apply on wet face, lather, rinse";
	faceWash10.benefits = "Brightens dull skin";
	faceWash10.texture = "Creamy";
	faceWash10.colour = "Light Orange";
	faceWash10.scentStrength = "Mild";
	faceWash10.rating = 5;
	faceWash10.customerReview = "My skin looks glowing";
	faceWash10.isStockAvailable = true;
	faceWash10.countryOfOrigin = "UK";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash10.name);
	System.out.println("brand : " + faceWash10.brand);
	System.out.println("skinType : " + faceWash10.skinType);
	System.out.println("formulation : " + faceWash10.formulation);
	System.out.println("fragrance : " + faceWash10.fragrance);
	System.out.println("packagingType : " + faceWash10.packagingType);
	System.out.println("volumeInML : " + faceWash10.volumeInML);
	System.out.println("price : " + faceWash10.price);
	System.out.println("quantity : " + faceWash10.quantity);
	System.out.println("isParabenFree : " + faceWash10.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash10.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash10.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash10.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash10.mainIngredients);
	System.out.println("expiryDate : " + faceWash10.expiryDate);
	System.out.println("manufactureDate : " + faceWash10.manufactureDate);
	System.out.println("instructions : " + faceWash10.instructions);
	System.out.println("benefits : " + faceWash10.benefits);
	System.out.println("texture : " + faceWash10.texture);
	System.out.println("colour : " + faceWash10.colour);
	System.out.println("scentStrength : " + faceWash10.scentStrength);
	System.out.println("rating : " + faceWash10.rating);
	System.out.println("customerReview : " + faceWash10.customerReview);
	System.out.println("isStockAvailable : " + faceWash10.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash10.countryOfOrigin);

	// FaceWash11
	FaceWash faceWash11 = new FaceWash();
	faceWash11.name = "Neem & Tea Tree Face Wash";
	faceWash11.brand = "Wow Skin Science";
	faceWash11.skinType = "Oily/Acne-prone";
	faceWash11.formulation = "Gel";
	faceWash11.fragrance = "Herbal";
	faceWash11.packagingType = "Tube";
	faceWash11.volumeInML = 160;
	faceWash11.price = 299;
	faceWash11.quantity = 2;
	faceWash11.isParabenFree = true;
	faceWash11.isSulfateFree = true;
	faceWash11.isDermatologistTested = true;
	faceWash11.isForSensitiveSkin = false;
	faceWash11.mainIngredients = "Neem Oil, Tea Tree Oil";
	faceWash11.expiryDate = "01-2027";
	faceWash11.manufactureDate = "01-2026";
	faceWash11.instructions = "Apply on face, massage gently, rinse";
	faceWash11.benefits = "Controls pimples and oil";
	faceWash11.texture = "Gel";
	faceWash11.colour = "Green";
	faceWash11.scentStrength = "Mild";
	faceWash11.rating = 5;
	faceWash11.customerReview = "Best for acne-prone skin";
	faceWash11.isStockAvailable = true;
	faceWash11.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash11.name);
	System.out.println("brand : " + faceWash11.brand);
	System.out.println("skinType : " + faceWash11.skinType);
	System.out.println("formulation : " + faceWash11.formulation);
	System.out.println("fragrance : " + faceWash11.fragrance);
	System.out.println("packagingType : " + faceWash11.packagingType);
	System.out.println("volumeInML : " + faceWash11.volumeInML);
	System.out.println("price : " + faceWash11.price);
	System.out.println("quantity : " + faceWash11.quantity);
	System.out.println("isParabenFree : " + faceWash11.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash11.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash11.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash11.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash11.mainIngredients);
	System.out.println("expiryDate : " + faceWash11.expiryDate);
	System.out.println("manufactureDate : " + faceWash11.manufactureDate);
	System.out.println("instructions : " + faceWash11.instructions);
	System.out.println("benefits : " + faceWash11.benefits);
	System.out.println("texture : " + faceWash11.texture);
	System.out.println("colour : " + faceWash11.colour);
	System.out.println("scentStrength : " + faceWash11.scentStrength);
	System.out.println("rating : " + faceWash11.rating);
	System.out.println("customerReview : " + faceWash11.customerReview);
	System.out.println("isStockAvailable : " + faceWash11.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash11.countryOfOrigin);


	// FaceWash12
	FaceWash faceWash12 = new FaceWash();
	faceWash12.name = "Cucumber & Aloe Face Wash";
	faceWash12.brand = "Biotique";
	faceWash12.skinType = "Normal";
	faceWash12.formulation = "Gel";
	faceWash12.fragrance = "Herbal";
	faceWash12.packagingType = "Tube";
	faceWash12.volumeInML = 150;
	faceWash12.price = 210;
	faceWash12.quantity = 2;
	faceWash12.isParabenFree = true;
	faceWash12.isSulfateFree = true;
	faceWash12.isDermatologistTested = true;
	faceWash12.isForSensitiveSkin = true;
	faceWash12.mainIngredients = "Cucumber Extract, Aloe Vera";
	faceWash12.expiryDate = "08-2026";
	faceWash12.manufactureDate = "08-2025";
	faceWash12.instructions = "Apply on wet face, massage gently, rinse";
	faceWash12.benefits = "Hydrates and refreshes skin";
	faceWash12.texture = "Gel";
	faceWash12.colour = "Light Green";
	faceWash12.scentStrength = "Mild";
	faceWash12.rating = 5;
	faceWash12.customerReview = "Feels refreshing and gentle";
	faceWash12.isStockAvailable = true;
	faceWash12.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash12.name);
	System.out.println("brand : " + faceWash12.brand);
	System.out.println("skinType : " + faceWash12.skinType);
	System.out.println("formulation : " + faceWash12.formulation);
	System.out.println("fragrance : " + faceWash12.fragrance);
	System.out.println("packagingType : " + faceWash12.packagingType);
	System.out.println("volumeInML : " + faceWash12.volumeInML);
	System.out.println("price : " + faceWash12.price);
	System.out.println("quantity : " + faceWash12.quantity);
	System.out.println("isParabenFree : " + faceWash12.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash12.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash12.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash12.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash12.mainIngredients);
	System.out.println("expiryDate : " + faceWash12.expiryDate);
	System.out.println("manufactureDate : " + faceWash12.manufactureDate);
	System.out.println("instructions : " + faceWash12.instructions);
	System.out.println("benefits : " + faceWash12.benefits);
	System.out.println("texture : " + faceWash12.texture);
	System.out.println("colour : " + faceWash12.colour);
	System.out.println("scentStrength : " + faceWash12.scentStrength);
	System.out.println("rating : " + faceWash12.rating);
	System.out.println("customerReview : " + faceWash12.customerReview);
	System.out.println("isStockAvailable : " + faceWash12.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash12.countryOfOrigin);

	// FaceWash13
	FaceWash faceWash13 = new FaceWash();
	faceWash13.name = "Charcoal & Lemon Face Wash";
	faceWash13.brand = "Himalaya";
	faceWash13.skinType = "Oily/Combination";
	faceWash13.formulation = "Gel";
	faceWash13.fragrance = "Fresh";
	faceWash13.packagingType = "Tube";
	faceWash13.volumeInML = 150;
	faceWash13.price = 180;
	faceWash13.quantity = 2;
	faceWash13.isParabenFree = true;
	faceWash13.isSulfateFree = true;
	faceWash13.isDermatologistTested = true;
	faceWash13.isForSensitiveSkin = false;
	faceWash13.mainIngredients = "Charcoal, Lemon Extract";
	faceWash13.expiryDate = "12-2026";
	faceWash13.manufactureDate = "12-2025";
	faceWash13.instructions = "Massage on wet face, rinse";
	faceWash13.benefits = "Removes oil and impurities";
	faceWash13.texture = "Gel";
	faceWash13.colour = "Black";
	faceWash13.scentStrength = "Fresh";
	faceWash13.rating = 4;
	faceWash13.customerReview = "Good for oily skin";
	faceWash13.isStockAvailable = true;
	faceWash13.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash13.name);
	System.out.println("brand : " + faceWash13.brand);
	System.out.println("skinType : " + faceWash13.skinType);
	System.out.println("formulation : " + faceWash13.formulation);
	System.out.println("fragrance : " + faceWash13.fragrance);
	System.out.println("packagingType : " + faceWash13.packagingType);
	System.out.println("volumeInML : " + faceWash13.volumeInML);
	System.out.println("price : " + faceWash13.price);
	System.out.println("quantity : " + faceWash13.quantity);
	System.out.println("isParabenFree : " + faceWash13.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash13.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash13.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash13.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash13.mainIngredients);
	System.out.println("expiryDate : " + faceWash13.expiryDate);
	System.out.println("manufactureDate : " + faceWash13.manufactureDate);
	System.out.println("instructions : " + faceWash13.instructions);
	System.out.println("benefits : " + faceWash13.benefits);
	System.out.println("texture : " + faceWash13.texture);
	System.out.println("colour : " + faceWash13.colour);
	System.out.println("scentStrength : " + faceWash13.scentStrength);
	System.out.println("rating : " + faceWash13.rating);
	System.out.println("customerReview : " + faceWash13.customerReview);
	System.out.println("isStockAvailable : " + faceWash13.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash13.countryOfOrigin);

	// FaceWash14
	FaceWash faceWash14 = new FaceWash();
	faceWash14.name = "Rose Face Wash";
	faceWash14.brand = "Lotus Herbals";
	faceWash14.skinType = "Dry/Sensitive";
	faceWash14.formulation = "Cream";
	faceWash14.fragrance = "Rose";
	faceWash14.packagingType = "Tube";
	faceWash14.volumeInML = 100;
	faceWash14.price = 250;
	faceWash14.quantity = 1;
	faceWash14.isParabenFree = true;
	faceWash14.isSulfateFree = true;
	faceWash14.isDermatologistTested = true;
	faceWash14.isForSensitiveSkin = true;
	faceWash14.mainIngredients = "Rose Extract, Vitamin E";
	faceWash14.expiryDate = "05-2027";
	faceWash14.manufactureDate = "05-2026";
	faceWash14.instructions = "Apply, lather, rinse gently";
	faceWash14.benefits = "Soothes and softens skin";
	faceWash14.texture = "Creamy";
	faceWash14.colour = "Pink";
	faceWash14.scentStrength = "Mild";
	faceWash14.rating = 5;
	faceWash14.customerReview = "Very gentle and refreshing";
	faceWash14.isStockAvailable = true;
	faceWash14.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash14.name);
	System.out.println("brand : " + faceWash14.brand);
	System.out.println("skinType : " + faceWash14.skinType);
	System.out.println("formulation : " + faceWash14.formulation);
	System.out.println("fragrance : " + faceWash14.fragrance);
	System.out.println("packagingType : " + faceWash14.packagingType);
	System.out.println("volumeInML : " + faceWash14.volumeInML);
	System.out.println("price : " + faceWash14.price);
	System.out.println("quantity : " + faceWash14.quantity);
	System.out.println("isParabenFree : " + faceWash14.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash14.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash14.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash14.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash14.mainIngredients);
	System.out.println("expiryDate : " + faceWash14.expiryDate);
	System.out.println("manufactureDate : " + faceWash14.manufactureDate);
	System.out.println("instructions : " + faceWash14.instructions);
	System.out.println("benefits : " + faceWash14.benefits);
	System.out.println("texture : " + faceWash14.texture);
	System.out.println("colour : " + faceWash14.colour);
	System.out.println("scentStrength : " + faceWash14.scentStrength);
	System.out.println("rating : " + faceWash14.rating);
	System.out.println("customerReview : " + faceWash14.customerReview);
	System.out.println("isStockAvailable : " + faceWash14.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash14.countryOfOrigin);

	// FaceWash15
	FaceWash faceWash15 = new FaceWash();
	faceWash15.name = "Green Tea Face Wash";
	faceWash15.brand = "Innisfree";
	faceWash15.skinType = "Combination";
	faceWash15.formulation = "Foam";
	faceWash15.fragrance = "Green Tea";
	faceWash15.packagingType = "Tube";
	faceWash15.volumeInML = 150;
	faceWash15.price = 400;
	faceWash15.quantity = 1;
	faceWash15.isParabenFree = true;
	faceWash15.isSulfateFree = true;
	faceWash15.isDermatologistTested = true;
	faceWash15.isForSensitiveSkin = false;
	faceWash15.mainIngredients = "Green Tea Extract, Glycerin";
	faceWash15.expiryDate = "07-2027";
	faceWash15.manufactureDate = "07-2026";
	faceWash15.instructions = "Lather on wet face, rinse";
	faceWash15.benefits = "Cleanses and refreshes skin";
	faceWash15.texture = "Foam";
	faceWash15.colour = "Green";
	faceWash15.scentStrength = "Mild";
	faceWash15.rating = 5;
	faceWash15.customerReview = "Refreshing and clean feel";
	faceWash15.isStockAvailable = true;
	faceWash15.countryOfOrigin = "Korea";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash15.name);
	System.out.println("brand : " + faceWash15.brand);
	System.out.println("skinType : " + faceWash15.skinType);
	System.out.println("formulation : " + faceWash15.formulation);
	System.out.println("fragrance : " + faceWash15.fragrance);
	System.out.println("packagingType : " + faceWash15.packagingType);
	System.out.println("volumeInML : " + faceWash15.volumeInML);
	System.out.println("price : " + faceWash15.price);
	System.out.println("quantity : " + faceWash15.quantity);
	System.out.println("isParabenFree : " + faceWash15.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash15.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash15.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash15.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash15.mainIngredients);
	System.out.println("expiryDate : " + faceWash15.expiryDate);
	System.out.println("manufactureDate : " + faceWash15.manufactureDate);
	System.out.println("instructions : " + faceWash15.instructions);
	System.out.println("benefits : " + faceWash15.benefits);
	System.out.println("texture : " + faceWash15.texture);
	System.out.println("colour : " + faceWash15.colour);
	System.out.println("scentStrength : " + faceWash15.scentStrength);
	System.out.println("rating : " + faceWash15.rating);
	System.out.println("customerReview : " + faceWash15.customerReview);
	System.out.println("isStockAvailable : " + faceWash15.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash15.countryOfOrigin);

	// FaceWash16
	FaceWash faceWash16 = new FaceWash();
	faceWash16.name = "Neem & Aloe Face Wash";
	faceWash16.brand = "Khadi Natural";
	faceWash16.skinType = "Oily/Sensitive";
	faceWash16.formulation = "Gel";
	faceWash16.fragrance = "Herbal";
	faceWash16.packagingType = "Tube";
	faceWash16.volumeInML = 125;
	faceWash16.price = 220;
	faceWash16.quantity = 2;
	faceWash16.isParabenFree = true;
	faceWash16.isSulfateFree = true;
	faceWash16.isDermatologistTested = true;
	faceWash16.isForSensitiveSkin = true;
	faceWash16.mainIngredients = "Neem, Aloe Vera";
	faceWash16.expiryDate = "12-2026";
	faceWash16.manufactureDate = "12-2025";
	faceWash16.instructions = "Massage on wet face, rinse";
	faceWash16.benefits = "Controls acne and soothes skin";
	faceWash16.texture = "Gel";
	faceWash16.colour = "Light Green";
	faceWash16.scentStrength = "Mild";
	faceWash16.rating = 5;
	faceWash16.customerReview = "Perfect for my sensitive skin";
	faceWash16.isStockAvailable = true;
	faceWash16.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash16.name);
	System.out.println("brand : " + faceWash16.brand);
	System.out.println("skinType : " + faceWash16.skinType);
	System.out.println("formulation : " + faceWash16.formulation);
	System.out.println("fragrance : " + faceWash16.fragrance);
	System.out.println("packagingType : " + faceWash16.packagingType);
	System.out.println("volumeInML : " + faceWash16.volumeInML);
	System.out.println("price : " + faceWash16.price);
	System.out.println("quantity : " + faceWash16.quantity);
	System.out.println("isParabenFree : " + faceWash16.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash16.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash16.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash16.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash16.mainIngredients);
	System.out.println("expiryDate : " + faceWash16.expiryDate);
	System.out.println("manufactureDate : " + faceWash16.manufactureDate);
	System.out.println("instructions : " + faceWash16.instructions);
	System.out.println("benefits : " + faceWash16.benefits);
	System.out.println("texture : " + faceWash16.texture);
	System.out.println("colour : " + faceWash16.colour);
	System.out.println("scentStrength : " + faceWash16.scentStrength);
	System.out.println("rating : " + faceWash16.rating);
	System.out.println("customerReview : " + faceWash16.customerReview);
	System.out.println("isStockAvailable : " + faceWash16.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash16.countryOfOrigin);


	// FaceWash17
	FaceWash faceWash17 = new FaceWash();
	faceWash17.name = "Vitamin E Face Wash";
	faceWash17.brand = "Nivea";
	faceWash17.skinType = "Dry/Normal";
	faceWash17.formulation = "Cream";
	faceWash17.fragrance = "Mild";
	faceWash17.packagingType = "Tube";
	faceWash17.volumeInML = 150;
	faceWash17.price = 300;
	faceWash17.quantity = 1;
	faceWash17.isParabenFree = true;
	faceWash17.isSulfateFree = true;
	faceWash17.isDermatologistTested = true;
	faceWash17.isForSensitiveSkin = true;
	faceWash17.mainIngredients = "Vitamin E, Glycerin";
	faceWash17.expiryDate = "06-2027";
	faceWash17.manufactureDate = "06-2026";
	faceWash17.instructions = "Apply, lather, rinse gently";
	faceWash17.benefits = "Moisturizes and nourishes skin";
	faceWash17.texture = "Creamy";
	faceWash17.colour = "White";
	faceWash17.scentStrength = "Mild";
	faceWash17.rating = 5;
	faceWash17.customerReview = "Leaves skin soft and smooth";
	faceWash17.isStockAvailable = true;
	faceWash17.countryOfOrigin = "Germany";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash17.name);
	System.out.println("brand : " + faceWash17.brand);
	System.out.println("skinType : " + faceWash17.skinType);
	System.out.println("formulation : " + faceWash17.formulation);
	System.out.println("fragrance : " + faceWash17.fragrance);
	System.out.println("packagingType : " + faceWash17.packagingType);
	System.out.println("volumeInML : " + faceWash17.volumeInML);
	System.out.println("price : " + faceWash17.price);
	System.out.println("quantity : " + faceWash17.quantity);
	System.out.println("isParabenFree : " + faceWash17.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash17.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash17.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash17.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash17.mainIngredients);
	System.out.println("expiryDate : " + faceWash17.expiryDate);
	System.out.println("manufactureDate : " + faceWash17.manufactureDate);
	System.out.println("instructions : " + faceWash17.instructions);
	System.out.println("benefits : " + faceWash17.benefits);
	System.out.println("texture : " + faceWash17.texture);
	System.out.println("colour : " + faceWash17.colour);
	System.out.println("scentStrength : " + faceWash17.scentStrength);
	System.out.println("rating : " + faceWash17.rating);
	System.out.println("customerReview : " + faceWash17.customerReview);
	System.out.println("isStockAvailable : " + faceWash17.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash17.countryOfOrigin);

	// FaceWash18
	FaceWash faceWash18 = new FaceWash();
	faceWash18.name = "AHA Face Wash";
	faceWash18.brand = "The Body Shop";
	faceWash18.skinType = "Normal/Combination";
	faceWash18.formulation = "Gel";
	faceWash18.fragrance = "Citrus";
	faceWash18.packagingType = "Tube";
	faceWash18.volumeInML = 120;
	faceWash18.price = 450;
	faceWash18.quantity = 1;
	faceWash18.isParabenFree = true;
	faceWash18.isSulfateFree = true;
	faceWash18.isDermatologistTested = true;
	faceWash18.isForSensitiveSkin = false;
	faceWash18.mainIngredients = "Vitamin C, Lemon Extract";
	faceWash18.expiryDate = "10-2027";
	faceWash18.manufactureDate = "10-2026";
	faceWash18.instructions = "Massage on wet face, rinse";
	faceWash18.benefits = "Brightens skin and reduces dullness";
	faceWash18.texture = "Gel";
	faceWash18.colour = "Light Yellow";
	faceWash18.scentStrength = "Fresh";
	faceWash18.rating = 5;
	faceWash18.customerReview = "Makes my skin glow instantly";
	faceWash18.isStockAvailable = true;
	faceWash18.countryOfOrigin = "UK";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash18.name);
	System.out.println("brand : " + faceWash18.brand);
	System.out.println("skinType : " + faceWash18.skinType);
	System.out.println("formulation : " + faceWash18.formulation);
	System.out.println("fragrance : " + faceWash18.fragrance);
	System.out.println("packagingType : " + faceWash18.packagingType);
	System.out.println("volumeInML : " + faceWash18.volumeInML);
	System.out.println("price : " + faceWash18.price);
	System.out.println("quantity : " + faceWash18.quantity);
	System.out.println("isParabenFree : " + faceWash18.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash18.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash18.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash18.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash18.mainIngredients);
	System.out.println("expiryDate : " + faceWash18.expiryDate);
	System.out.println("manufactureDate : " + faceWash18.manufactureDate);
	System.out.println("instructions : " + faceWash18.instructions);
	System.out.println("benefits : " + faceWash18.benefits);
	System.out.println("texture : " + faceWash18.texture);
	System.out.println("colour : " + faceWash18.colour);
	System.out.println("scentStrength : " + faceWash18.scentStrength);
	System.out.println("rating : " + faceWash18.rating);
	System.out.println("customerReview : " + faceWash18.customerReview);
	System.out.println("isStockAvailable : " + faceWash18.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash18.countryOfOrigin);

	// FaceWash19
	FaceWash faceWash19 = new FaceWash();
	faceWash19.name = "Activated Charcoal Face Wash";
	faceWash19.brand = "L'Oreal";
	faceWash19.skinType = "Oily/Acne-prone";
	faceWash19.formulation = "Gel";
	faceWash19.fragrance = "Neutral";
	faceWash19.packagingType = "Tube";
	faceWash19.volumeInML = 150;
	faceWash19.price = 350;
	faceWash19.quantity = 2;
	faceWash19.isParabenFree = true;
	faceWash19.isSulfateFree = true;
	faceWash19.isDermatologistTested = true;
	faceWash19.isForSensitiveSkin = false;
	faceWash19.mainIngredients = "Activated Charcoal, Tea Tree Oil";
	faceWash19.expiryDate = "09-2027";
	faceWash19.manufactureDate = "09-2026";
	faceWash19.instructions = "Apply on wet face, lather, rinse";
	faceWash19.benefits = "Removes excess oil and impurities";
	faceWash19.texture = "Gel";
	faceWash19.colour = "Black";
	faceWash19.scentStrength = "Neutral";
	faceWash19.rating = 5;
	faceWash19.customerReview = "Cleans deeply without irritation";
	faceWash19.isStockAvailable = true;
	faceWash19.countryOfOrigin = "France";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash19.name);
	System.out.println("brand : " + faceWash19.brand);
	System.out.println("skinType : " + faceWash19.skinType);
	System.out.println("formulation : " + faceWash19.formulation);
	System.out.println("fragrance : " + faceWash19.fragrance);
	System.out.println("packagingType : " + faceWash19.packagingType);
	System.out.println("volumeInML : " + faceWash19.volumeInML);
	System.out.println("price : " + faceWash19.price);
	System.out.println("quantity : " + faceWash19.quantity);
	System.out.println("isParabenFree : " + faceWash19.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash19.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash19.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash19.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash19.mainIngredients);
	System.out.println("expiryDate : " + faceWash19.expiryDate);
	System.out.println("manufactureDate : " + faceWash19.manufactureDate);
	System.out.println("instructions : " + faceWash19.instructions);
	System.out.println("benefits : " + faceWash19.benefits);
	System.out.println("texture : " + faceWash19.texture);
	System.out.println("colour : " + faceWash19.colour);
	System.out.println("scentStrength : " + faceWash19.scentStrength);
	System.out.println("rating : " + faceWash19.rating);
	System.out.println("customerReview : " + faceWash19.customerReview);
	System.out.println("isStockAvailable : " + faceWash19.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash19.countryOfOrigin);

	// FaceWash20
	FaceWash faceWash20 = new FaceWash();
	faceWash20.name = "Honey & Milk Face Wash";
	faceWash20.brand = "Himalaya";
	faceWash20.skinType = "Dry/Sensitive";
	faceWash20.formulation = "Cream";
	faceWash20.fragrance = "Mild Honey";
	faceWash20.packagingType = "Tube";
	faceWash20.volumeInML = 150;
	faceWash20.price = 250;
	faceWash20.quantity = 2;
	faceWash20.isParabenFree = true;
	faceWash20.isSulfateFree = true;
	faceWash20.isDermatologistTested = true;
	faceWash20.isForSensitiveSkin = true;
	faceWash20.mainIngredients = "Honey, Milk Protein";
	faceWash20.expiryDate = "11-2027";
	faceWash20.manufactureDate = "11-2026";
	faceWash20.instructions = "Apply gently, lather, rinse";
	faceWash20.benefits = "Moisturizes and nourishes dry skin";
	faceWash20.texture = "Creamy";
	faceWash20.colour = "Light Yellow";
	faceWash20.scentStrength = "Mild";
	faceWash20.rating = 5;
	faceWash20.customerReview = "Softens my skin and smells good";
	faceWash20.isStockAvailable = true;
	faceWash20.countryOfOrigin = "India";
	System.out.println("after init instance variable");
	System.out.println("name : " + faceWash20.name);
	System.out.println("brand : " + faceWash20.brand);
	System.out.println("skinType : " + faceWash20.skinType);
	System.out.println("formulation : " + faceWash20.formulation);
	System.out.println("fragrance : " + faceWash20.fragrance);
	System.out.println("packagingType : " + faceWash20.packagingType);
	System.out.println("volumeInML : " + faceWash20.volumeInML);
	System.out.println("price : " + faceWash20.price);
	System.out.println("quantity : " + faceWash20.quantity);
	System.out.println("isParabenFree : " + faceWash20.isParabenFree);
	System.out.println("isSulfateFree : " + faceWash20.isSulfateFree);
	System.out.println("isDermatologistTested : " + faceWash20.isDermatologistTested);
	System.out.println("isForSensitiveSkin : " + faceWash20.isForSensitiveSkin);
	System.out.println("mainIngredients : " + faceWash20.mainIngredients);
	System.out.println("expiryDate : " + faceWash20.expiryDate);
	System.out.println("manufactureDate : " + faceWash20.manufactureDate);
	System.out.println("instructions : " + faceWash20.instructions);
	System.out.println("benefits : " + faceWash20.benefits);
	System.out.println("texture : " + faceWash20.texture);
	System.out.println("colour : " + faceWash20.colour);
	System.out.println("scentStrength : " + faceWash20.scentStrength);
	System.out.println("rating : " + faceWash20.rating);
	System.out.println("customerReview : " + faceWash20.customerReview);
	System.out.println("isStockAvailable : " + faceWash20.isStockAvailable);
	System.out.println("countryOfOrigin : " + faceWash20.countryOfOrigin);
	}

	}