class HandkerchiefExecutor {

public static void main(String[] args) {

Handkerchief hanky1 = new Handkerchief();

hanky1.brand="Raymond";
hanky1.colour="White";
hanky1.material="Cotton";
hanky1.size="Medium";
hanky1.shape="Square";
hanky1.price=50;
hanky1.quantity=2;
hanky1.pattern="Plain";
hanky1.isCotton=true;
hanky1.isSilk=false;
hanky1.isSoft=true;
hanky1.isWashable=true;
hanky1.isPrinted=false;
hanky1.isPlain=true;
hanky1.manufactureDate="10-01-2026";
hanky1.countryOfOrigin="India";
hanky1.sellerName="TextileStore";
hanky1.warranty="No Warranty";
hanky1.rating=4;
hanky1.customerReview="Good quality";
hanky1.isEcoFriendly=true;
hanky1.isReusable=true;
hanky1.packagingType="Plastic Cover";
hanky1.weight=0.05;
hanky1.discount=5;

System.out.println("Brand: "+hanky1.brand);
System.out.println("Colour: "+hanky1.colour);
System.out.println("Material: "+hanky1.material);
System.out.println("Size: "+hanky1.size);
System.out.println("Shape: "+hanky1.shape);
System.out.println("Price: "+hanky1.price);
System.out.println("Quantity: "+hanky1.quantity);
System.out.println("Pattern: "+hanky1.pattern);
System.out.println("Cotton: "+hanky1.isCotton);
System.out.println("Silk: "+hanky1.isSilk);
System.out.println("Soft: "+hanky1.isSoft);
System.out.println("Washable: "+hanky1.isWashable);
System.out.println("Printed: "+hanky1.isPrinted);
System.out.println("Plain: "+hanky1.isPlain);
System.out.println("Manufacture Date: "+hanky1.manufactureDate);
System.out.println("Country: "+hanky1.countryOfOrigin);
System.out.println("Seller: "+hanky1.sellerName);
System.out.println("Warranty: "+hanky1.warranty);
System.out.println("Rating: "+hanky1.rating);
System.out.println("Customer Review: "+hanky1.customerReview);
System.out.println("Eco Friendly: "+hanky1.isEcoFriendly);
System.out.println("Reusable: "+hanky1.isReusable);
System.out.println("Packaging: "+hanky1.packagingType);
System.out.println("Weight: "+hanky1.weight);
System.out.println("Discount: "+hanky1.discount);

Handkerchief hanky2 = new Handkerchief();
hanky2.brand="VIP";
hanky2.colour="Blue";
hanky2.material="Cotton";
hanky2.size="Small";
hanky2.shape="Square";
hanky2.price=40;
hanky2.quantity=3;
hanky2.pattern="Printed";
hanky2.isCotton=true;
hanky2.isSilk=false;
hanky2.isSoft=true;
hanky2.isWashable=true;
hanky2.isPrinted=true;
hanky2.isPlain=false;
hanky2.manufactureDate="11-01-2026";
hanky2.countryOfOrigin="India";
hanky2.sellerName="ClothMart";
hanky2.warranty="No Warranty";
hanky2.rating=4;
hanky2.customerReview="Nice product";
hanky2.isEcoFriendly=true;
hanky2.isReusable=true;
hanky2.packagingType="Paper Cover";
hanky2.weight=0.04;
hanky2.discount=4;

System.out.println("Brand: "+hanky2.brand);
System.out.println("Colour: "+hanky2.colour);
System.out.println("Material: "+hanky2.material);
System.out.println("Size: "+hanky2.size);
System.out.println("Shape: "+hanky2.shape);
System.out.println("Price: "+hanky2.price);
System.out.println("Quantity: "+hanky2.quantity);
System.out.println("Pattern: "+hanky2.pattern);
System.out.println("Cotton: "+hanky2.isCotton);
System.out.println("Silk: "+hanky2.isSilk);
System.out.println("Soft: "+hanky2.isSoft);
System.out.println("Washable: "+hanky2.isWashable);
System.out.println("Printed: "+hanky2.isPrinted);
System.out.println("Plain: "+hanky2.isPlain);
System.out.println("Manufacture Date: "+hanky2.manufactureDate);
System.out.println("Country: "+hanky2.countryOfOrigin);
System.out.println("Seller: "+hanky2.sellerName);
System.out.println("Warranty: "+hanky2.warranty);
System.out.println("Rating: "+hanky2.rating);
System.out.println("Customer Review: "+hanky2.customerReview);
System.out.println("Eco Friendly: "+hanky2.isEcoFriendly);
System.out.println("Reusable: "+hanky2.isReusable);
System.out.println("Packaging: "+hanky2.packagingType);
System.out.println("Weight: "+hanky2.weight);
System.out.println("Discount: "+hanky2.discount);


Handkerchief hanky3 = new Handkerchief();
hanky3.brand="Zudio";
hanky3.colour="Red";
hanky3.material="Cotton";
hanky3.size="Medium";
hanky3.shape="Square";
hanky3.price=35;
hanky3.quantity=4;
hanky3.pattern="Plain";
hanky3.isCotton=true;
hanky3.isSilk=false;
hanky3.isSoft=true;
hanky3.isWashable=true;
hanky3.isPrinted=false;
hanky3.isPlain=true;
hanky3.manufactureDate="12-01-2026";
hanky3.countryOfOrigin="India";
hanky3.sellerName="FashionStore";
hanky3.warranty="No Warranty";
hanky3.rating=3;
hanky3.customerReview="Average quality";
hanky3.isEcoFriendly=true;
hanky3.isReusable=true;
hanky3.packagingType="Plastic Cover";
hanky3.weight=0.05;
hanky3.discount=3;

System.out.println("Brand: "+hanky3.brand);
System.out.println("Colour: "+hanky3.colour);
System.out.println("Material: "+hanky3.material);
System.out.println("Size: "+hanky3.size);
System.out.println("Shape: "+hanky3.shape);
System.out.println("Price: "+hanky3.price);
System.out.println("Quantity: "+hanky3.quantity);
System.out.println("Pattern: "+hanky3.pattern);
System.out.println("Cotton: "+hanky3.isCotton);
System.out.println("Silk: "+hanky3.isSilk);
System.out.println("Soft: "+hanky3.isSoft);
System.out.println("Washable: "+hanky3.isWashable);
System.out.println("Printed: "+hanky3.isPrinted);
System.out.println("Plain: "+hanky3.isPlain);
System.out.println("Manufacture Date: "+hanky3.manufactureDate);
System.out.println("Country: "+hanky3.countryOfOrigin);
System.out.println("Seller: "+hanky3.sellerName);
System.out.println("Warranty: "+hanky3.warranty);
System.out.println("Rating: "+hanky3.rating);
System.out.println("Customer Review: "+hanky3.customerReview);
System.out.println("Eco Friendly: "+hanky3.isEcoFriendly);
System.out.println("Reusable: "+hanky3.isReusable);
System.out.println("Packaging: "+hanky3.packagingType);
System.out.println("Weight: "+hanky3.weight);
System.out.println("Discount: "+hanky3.discount);


Handkerchief hanky4 = new Handkerchief();
hanky4.brand="PeterEngland";
hanky4.colour="White";
hanky4.material="Linen";
hanky4.size="Large";
hanky4.shape="Square";
hanky4.price=60;
hanky4.quantity=2;
hanky4.pattern="Plain";
hanky4.isCotton=false;
hanky4.isSilk=false;
hanky4.isSoft=true;
hanky4.isWashable=true;
hanky4.isPrinted=false;
hanky4.isPlain=true;
hanky4.manufactureDate="13-01-2026";
hanky4.countryOfOrigin="India";
hanky4.sellerName="MenWearShop";
hanky4.warranty="No Warranty";
hanky4.rating=5;
hanky4.customerReview="Excellent quality";
hanky4.isEcoFriendly=true;
hanky4.isReusable=true;
hanky4.packagingType="Box";
hanky4.weight=0.06;
hanky4.discount=6;

System.out.println("Brand: "+hanky4.brand);
System.out.println("Colour: "+hanky4.colour);
System.out.println("Material: "+hanky4.material);
System.out.println("Size: "+hanky4.size);
System.out.println("Shape: "+hanky4.shape);
System.out.println("Price: "+hanky4.price);
System.out.println("Quantity: "+hanky4.quantity);
System.out.println("Pattern: "+hanky4.pattern);
System.out.println("Cotton: "+hanky4.isCotton);
System.out.println("Silk: "+hanky4.isSilk);
System.out.println("Soft: "+hanky4.isSoft);
System.out.println("Washable: "+hanky4.isWashable);
System.out.println("Printed: "+hanky4.isPrinted);
System.out.println("Plain: "+hanky4.isPlain);
System.out.println("Manufacture Date: "+hanky4.manufactureDate);
System.out.println("Country: "+hanky4.countryOfOrigin);
System.out.println("Seller: "+hanky4.sellerName);
System.out.println("Warranty: "+hanky4.warranty);
System.out.println("Rating: "+hanky4.rating);
System.out.println("Customer Review: "+hanky4.customerReview);
System.out.println("Eco Friendly: "+hanky4.isEcoFriendly);
System.out.println("Reusable: "+hanky4.isReusable);
System.out.println("Packaging: "+hanky4.packagingType);
System.out.println("Weight: "+hanky4.weight);
System.out.println("Discount: "+hanky4.discount);


Handkerchief hanky5 = new Handkerchief();
hanky5.brand="AllenSolly";
hanky5.colour="Green";
hanky5.material="Cotton";
hanky5.size="Medium";
hanky5.shape="Square";
hanky5.price=55;
hanky5.quantity=3;
hanky5.pattern="Printed";
hanky5.isCotton=true;
hanky5.isSilk=false;
hanky5.isSoft=true;
hanky5.isWashable=true;
hanky5.isPrinted=true;
hanky5.isPlain=false;
hanky5.manufactureDate="14-01-2026";
hanky5.countryOfOrigin="India";
hanky5.sellerName="ClothWorld";
hanky5.warranty="No Warranty";
hanky5.rating=4;
hanky5.customerReview="Good fabric";
hanky5.isEcoFriendly=true;
hanky5.isReusable=true;
hanky5.packagingType="Plastic Cover";
hanky5.weight=0.05;
hanky5.discount=5;

System.out.println("Brand: "+hanky5.brand);
System.out.println("Colour: "+hanky5.colour);
System.out.println("Material: "+hanky5.material);
System.out.println("Size: "+hanky5.size);
System.out.println("Shape: "+hanky5.shape);
System.out.println("Price: "+hanky5.price);
System.out.println("Quantity: "+hanky5.quantity);
System.out.println("Pattern: "+hanky5.pattern);
System.out.println("Cotton: "+hanky5.isCotton);
System.out.println("Silk: "+hanky5.isSilk);
System.out.println("Soft: "+hanky5.isSoft);
System.out.println("Washable: "+hanky5.isWashable);
System.out.println("Printed: "+hanky5.isPrinted);
System.out.println("Plain: "+hanky5.isPlain);
System.out.println("Manufacture Date: "+hanky5.manufactureDate);
System.out.println("Country: "+hanky5.countryOfOrigin);
System.out.println("Seller: "+hanky5.sellerName);
System.out.println("Warranty: "+hanky5.warranty);
System.out.println("Rating: "+hanky5.rating);
System.out.println("Customer Review: "+hanky5.customerReview);
System.out.println("Eco Friendly: "+hanky5.isEcoFriendly);
System.out.println("Reusable: "+hanky5.isReusable);
System.out.println("Packaging: "+hanky5.packagingType);
System.out.println("Weight: "+hanky5.weight);
System.out.println("Discount: "+hanky5.discount);

Handkerchief hanky6 = new Handkerchief();
hanky6.brand="Puma";
hanky6.colour="Black";
hanky6.material="Cotton";
hanky6.size="Medium";
hanky6.shape="Square";
hanky6.price=45;
hanky6.quantity=2;
hanky6.pattern="Printed";
hanky6.isCotton=true;
hanky6.isSilk=false;
hanky6.isSoft=true;
hanky6.isWashable=true;
hanky6.isPrinted=true;
hanky6.isPlain=false;
hanky6.manufactureDate="15-01-2026";
hanky6.countryOfOrigin="India";
hanky6.sellerName="ClothStore";
hanky6.warranty="No Warranty";
hanky6.rating=4;
hanky6.customerReview="Nice design";
hanky6.isEcoFriendly=true;
hanky6.isReusable=true;
hanky6.packagingType="Plastic Cover";
hanky6.weight=0.05;
hanky6.discount=4;

System.out.println("Brand: "+hanky6.brand);
System.out.println("Colour: "+hanky6.colour);
System.out.println("Material: "+hanky6.material);
System.out.println("Size: "+hanky6.size);
System.out.println("Shape: "+hanky6.shape);
System.out.println("Price: "+hanky6.price);
System.out.println("Quantity: "+hanky6.quantity);
System.out.println("Pattern: "+hanky6.pattern);
System.out.println("Cotton: "+hanky6.isCotton);
System.out.println("Silk: "+hanky6.isSilk);
System.out.println("Soft: "+hanky6.isSoft);
System.out.println("Washable: "+hanky6.isWashable);
System.out.println("Printed: "+hanky6.isPrinted);
System.out.println("Plain: "+hanky6.isPlain);
System.out.println("Manufacture Date: "+hanky6.manufactureDate);
System.out.println("Country: "+hanky6.countryOfOrigin);
System.out.println("Seller: "+hanky6.sellerName);
System.out.println("Warranty: "+hanky6.warranty);
System.out.println("Rating: "+hanky6.rating);
System.out.println("Customer Review: "+hanky6.customerReview);
System.out.println("Eco Friendly: "+hanky6.isEcoFriendly);
System.out.println("Reusable: "+hanky6.isReusable);
System.out.println("Packaging: "+hanky6.packagingType);
System.out.println("Weight: "+hanky6.weight);
System.out.println("Discount: "+hanky6.discount);

Handkerchief hanky7 = new Handkerchief();
hanky7.brand="Nike";
hanky7.colour="Blue";
hanky7.material="Cotton";
hanky7.size="Small";
hanky7.shape="Square";
hanky7.price=48;
hanky7.quantity=3;
hanky7.pattern="Plain";
hanky7.isCotton=true;
hanky7.isSilk=false;
hanky7.isSoft=true;
hanky7.isWashable=true;
hanky7.isPrinted=false;
hanky7.isPlain=true;
hanky7.manufactureDate="16-01-2026";
hanky7.countryOfOrigin="India";
hanky7.sellerName="FashionHub";
hanky7.warranty="No Warranty";
hanky7.rating=4;
hanky7.customerReview="Soft cloth";
hanky7.isEcoFriendly=true;
hanky7.isReusable=true;
hanky7.packagingType="Paper Cover";
hanky7.weight=0.05;
hanky7.discount=5;

System.out.println("Brand: "+hanky7.brand);
System.out.println("Colour: "+hanky7.colour);
System.out.println("Material: "+hanky7.material);
System.out.println("Size: "+hanky7.size);
System.out.println("Shape: "+hanky7.shape);
System.out.println("Price: "+hanky7.price);
System.out.println("Quantity: "+hanky7.quantity);
System.out.println("Pattern: "+hanky7.pattern);
System.out.println("Cotton: "+hanky7.isCotton);
System.out.println("Silk: "+hanky7.isSilk);
System.out.println("Soft: "+hanky7.isSoft);
System.out.println("Washable: "+hanky7.isWashable);
System.out.println("Printed: "+hanky7.isPrinted);
System.out.println("Plain: "+hanky7.isPlain);
System.out.println("Manufacture Date: "+hanky7.manufactureDate);
System.out.println("Country: "+hanky7.countryOfOrigin);
System.out.println("Seller: "+hanky7.sellerName);
System.out.println("Warranty: "+hanky7.warranty);
System.out.println("Rating: "+hanky7.rating);
System.out.println("Customer Review: "+hanky7.customerReview);
System.out.println("Eco Friendly: "+hanky7.isEcoFriendly);
System.out.println("Reusable: "+hanky7.isReusable);
System.out.println("Packaging: "+hanky7.packagingType);
System.out.println("Weight: "+hanky7.weight);
System.out.println("Discount: "+hanky7.discount);

Handkerchief hanky8 = new Handkerchief();
hanky8.brand="Adidas";
hanky8.colour="Grey";
hanky8.material="Linen";
hanky8.size="Large";
hanky8.shape="Square";
hanky8.price=65;
hanky8.quantity=2;
hanky8.pattern="Plain";
hanky8.isCotton=false;
hanky8.isSilk=false;
hanky8.isSoft=true;
hanky8.isWashable=true;
hanky8.isPrinted=false;
hanky8.isPlain=true;
hanky8.manufactureDate="17-01-2026";
hanky8.countryOfOrigin="India";
hanky8.sellerName="MenFashion";
hanky8.warranty="No Warranty";
hanky8.rating=5;
hanky8.customerReview="Premium cloth";
hanky8.isEcoFriendly=true;
hanky8.isReusable=true;
hanky8.packagingType="Box";
hanky8.weight=0.06;
hanky8.discount=6;

System.out.println("Brand: "+hanky8.brand);
System.out.println("Colour: "+hanky8.colour);
System.out.println("Material: "+hanky8.material);
System.out.println("Size: "+hanky8.size);
System.out.println("Shape: "+hanky8.shape);
System.out.println("Price: "+hanky8.price);
System.out.println("Quantity: "+hanky8.quantity);
System.out.println("Pattern: "+hanky8.pattern);
System.out.println("Cotton: "+hanky8.isCotton);
System.out.println("Silk: "+hanky8.isSilk);
System.out.println("Soft: "+hanky8.isSoft);
System.out.println("Washable: "+hanky8.isWashable);
System.out.println("Printed: "+hanky8.isPrinted);
System.out.println("Plain: "+hanky8.isPlain);
System.out.println("Manufacture Date: "+hanky8.manufactureDate);
System.out.println("Country: "+hanky8.countryOfOrigin);
System.out.println("Seller: "+hanky8.sellerName);
System.out.println("Warranty: "+hanky8.warranty);
System.out.println("Rating: "+hanky8.rating);
System.out.println("Customer Review: "+hanky8.customerReview);
System.out.println("Eco Friendly: "+hanky8.isEcoFriendly);
System.out.println("Reusable: "+hanky8.isReusable);
System.out.println("Packaging: "+hanky8.packagingType);
System.out.println("Weight: "+hanky8.weight);
System.out.println("Discount: "+hanky8.discount);

Handkerchief hanky9= new Handkerchief();
hanky9.brand="Levis";
hanky9.colour="White";
hanky9.material="Cotton";
hanky9.size="Medium";
hanky9.shape="Square";
hanky9.price=52;
hanky9.quantity=2;
hanky9.pattern="Printed";
hanky9.isCotton=true;
hanky9.isSilk=false;
hanky9.isSoft=true;
hanky9.isWashable=true;
hanky9.isPrinted=true;
hanky9.isPlain=false;
hanky9.manufactureDate="18-01-2026";
hanky9.countryOfOrigin="India";
hanky9.sellerName="ClothBazaar";
hanky9.warranty="No Warranty";
hanky9.rating=4;
hanky9.customerReview="Good cloth";
hanky9.isEcoFriendly=true;
hanky9.isReusable=true;
hanky9.packagingType="Plastic Cover";
hanky9.weight=0.05;
hanky9.discount=5;

System.out.println("Brand: "+hanky9.brand);
System.out.println("Colour: "+hanky9.colour);
System.out.println("Material: "+hanky9.material);
System.out.println("Size: "+hanky9.size);
System.out.println("Shape: "+hanky9.shape);
System.out.println("Price: "+hanky9.price);
System.out.println("Quantity: "+hanky9.quantity);
System.out.println("Pattern: "+hanky9.pattern);
System.out.println("Cotton: "+hanky9.isCotton);
System.out.println("Silk: "+hanky9.isSilk);
System.out.println("Soft: "+hanky9.isSoft);
System.out.println("Washable: "+hanky9.isWashable);
System.out.println("Printed: "+hanky9.isPrinted);
System.out.println("Plain: "+hanky9.isPlain);
System.out.println("Manufacture Date: "+hanky9.manufactureDate);
System.out.println("Country: "+hanky9.countryOfOrigin);
System.out.println("Seller: "+hanky9.sellerName);
System.out.println("Warranty: "+hanky9.warranty);
System.out.println("Rating: "+hanky9.rating);
System.out.println("Customer Review: "+hanky9.customerReview);
System.out.println("Eco Friendly: "+hanky9.isEcoFriendly);
System.out.println("Reusable: "+hanky9.isReusable);
System.out.println("Packaging: "+hanky9.packagingType);
System.out.println("Weight: "+hanky9.weight);
System.out.println("Discount: "+hanky9.discount);

Handkerchief hanky10 = new Handkerchief();
hanky10.brand="USPA";
hanky10.colour="Brown";
hanky10.material="Cotton";
hanky10.size="Medium";
hanky10.shape="Square";
hanky10.price=58;
hanky10.quantity=3;
hanky10.pattern="Plain";
hanky10.isCotton=true;
hanky10.isSilk=false;
hanky10.isSoft=true;
hanky10.isWashable=true;
hanky10.isPrinted=false;
hanky10.isPlain=true;
hanky10.manufactureDate="19-01-2026";
hanky10.countryOfOrigin="India";
hanky10.sellerName="StyleStore";
hanky10.warranty="No Warranty";
hanky10.rating=4;
hanky10.customerReview="Nice fabric";
hanky10.isEcoFriendly=true;
hanky10.isReusable=true;
hanky10.packagingType="Paper Cover";
hanky10.weight=0.05;
hanky10.discount=5;

System.out.println("Brand: "+hanky10.brand);
System.out.println("Colour: "+hanky10.colour);
System.out.println("Material: "+hanky10.material);
System.out.println("Size: "+hanky10.size);
System.out.println("Shape: "+hanky10.shape);
System.out.println("Price: "+hanky10.price);
System.out.println("Quantity: "+hanky10.quantity);
System.out.println("Pattern: "+hanky10.pattern);
System.out.println("Cotton: "+hanky10.isCotton);
System.out.println("Silk: "+hanky10.isSilk);
System.out.println("Soft: "+hanky10.isSoft);
System.out.println("Washable: "+hanky10.isWashable);
System.out.println("Printed: "+hanky10.isPrinted);
System.out.println("Plain: "+hanky10.isPlain);
System.out.println("Manufacture Date: "+hanky10.manufactureDate);
System.out.println("Country: "+hanky10.countryOfOrigin);
System.out.println("Seller: "+hanky10.sellerName);
System.out.println("Warranty: "+hanky10.warranty);
System.out.println("Rating: "+hanky10.rating);
System.out.println("Customer Review: "+hanky10.customerReview);
System.out.println("Eco Friendly: "+hanky10.isEcoFriendly);
System.out.println("Reusable: "+hanky10.isReusable);
System.out.println("Packaging: "+hanky10.packagingType);
System.out.println("Weight: "+hanky10.weight);
System.out.println("Discount: "+hanky10.discount);


Handkerchief hanky11 = new Handkerchief();
hanky11.brand="Arrow";
hanky11.colour="White";
hanky11.material="Cotton";
hanky11.size="Medium";
hanky11.shape="Square";
hanky11.price=50;
hanky11.quantity=2;
hanky11.pattern="Plain";
hanky11.isCotton=true;
hanky11.isSilk=false;
hanky11.isSoft=true;
hanky11.isWashable=true;
hanky11.isPrinted=false;
hanky11.isPlain=true;
hanky11.manufactureDate="20-01-2026";
hanky11.countryOfOrigin="India";
hanky11.sellerName="MenStore";
hanky11.warranty="No Warranty";
hanky11.rating=4;
hanky11.customerReview="Good quality";
hanky11.isEcoFriendly=true;
hanky11.isReusable=true;
hanky11.packagingType="Plastic Cover";
hanky11.weight=0.05;
hanky11.discount=4;

System.out.println("Brand: "+hanky11.brand);
System.out.println("Colour: "+hanky11.colour);
System.out.println("Material: "+hanky11.material);
System.out.println("Size: "+hanky11.size);
System.out.println("Shape: "+hanky11.shape);
System.out.println("Price: "+hanky11.price);
System.out.println("Quantity: "+hanky11.quantity);
System.out.println("Pattern: "+hanky11.pattern);
System.out.println("Cotton: "+hanky11.isCotton);
System.out.println("Silk: "+hanky11.isSilk);
System.out.println("Soft: "+hanky11.isSoft);
System.out.println("Washable: "+hanky11.isWashable);
System.out.println("Printed: "+hanky11.isPrinted);
System.out.println("Plain: "+hanky11.isPlain);
System.out.println("Manufacture Date: "+hanky11.manufactureDate);
System.out.println("Country: "+hanky11.countryOfOrigin);
System.out.println("Seller: "+hanky11.sellerName);
System.out.println("Warranty: "+hanky11.warranty);
System.out.println("Rating: "+hanky11.rating);
System.out.println("Customer Review: "+hanky11.customerReview);
System.out.println("Eco Friendly: "+hanky11.isEcoFriendly);
System.out.println("Reusable: "+hanky11.isReusable);
System.out.println("Packaging: "+hanky11.packagingType);
System.out.println("Weight: "+hanky11.weight);
System.out.println("Discount: "+hanky11.discount);

Handkerchief hanky12 = new Handkerchief();
hanky12.brand="LouisPhilippe";
hanky12.colour="Blue";
hanky12.material="Cotton";
hanky12.size="Large";
hanky12.shape="Square";
hanky12.price=70;
hanky12.quantity=2;
hanky12.pattern="Printed";
hanky12.isCotton=true;
hanky12.isSilk=false;
hanky12.isSoft=true;
hanky12.isWashable=true;
hanky12.isPrinted=true;
hanky12.isPlain=false;
hanky12.manufactureDate="21-01-2026";
hanky12.countryOfOrigin="India";
hanky12.sellerName="ClothHub";
hanky12.warranty="No Warranty";
hanky12.rating=5;
hanky12.customerReview="Premium quality";
hanky12.isEcoFriendly=true;
hanky12.isReusable=true;
hanky12.packagingType="Box";
hanky12.weight=0.06;
hanky12.discount=7;

System.out.println("Brand: "+hanky12.brand);
System.out.println("Colour: "+hanky12.colour);
System.out.println("Material: "+hanky12.material);
System.out.println("Size: "+hanky12.size);
System.out.println("Shape: "+hanky12.shape);
System.out.println("Price: "+hanky12.price);
System.out.println("Quantity: "+hanky12.quantity);
System.out.println("Pattern: "+hanky12.pattern);
System.out.println("Cotton: "+hanky12.isCotton);
System.out.println("Silk: "+hanky12.isSilk);
System.out.println("Soft: "+hanky12.isSoft);
System.out.println("Washable: "+hanky12.isWashable);
System.out.println("Printed: "+hanky12.isPrinted);
System.out.println("Plain: "+hanky12.isPlain);
System.out.println("Manufacture Date: "+hanky12.manufactureDate);
System.out.println("Country: "+hanky12.countryOfOrigin);
System.out.println("Seller: "+hanky12.sellerName);
System.out.println("Warranty: "+hanky12.warranty);
System.out.println("Rating: "+hanky12.rating);
System.out.println("Customer Review: "+hanky12.customerReview);
System.out.println("Eco Friendly: "+hanky12.isEcoFriendly);
System.out.println("Reusable: "+hanky12.isReusable);
System.out.println("Packaging: "+hanky12.packagingType);
System.out.println("Weight: "+hanky12.weight);
System.out.println("Discount: "+hanky12.discount);

Handkerchief hanky13 = new Handkerchief();
hanky13.brand="VanHeusen";
hanky13.colour="Grey";
hanky13.material="Linen";
hanky13.size="Medium";
hanky13.shape="Square";
hanky13.price=65;
hanky13.quantity=2;
hanky13.pattern="Plain";
hanky13.isCotton=false;
hanky13.isSilk=false;
hanky13.isSoft=true;
hanky13.isWashable=true;
hanky13.isPrinted=false;
hanky13.isPlain=true;
hanky13.manufactureDate="22-01-2026";
hanky13.countryOfOrigin="India";
hanky13.sellerName="TextileWorld";
hanky13.warranty="No Warranty";
hanky13.rating=4;
hanky13.customerReview="Good fabric";
hanky13.isEcoFriendly=true;
hanky13.isReusable=true;
hanky13.packagingType="Paper Cover";
hanky13.weight=0.05;
hanky13.discount=5;

System.out.println("Brand: "+hanky13.brand);
System.out.println("Colour: "+hanky13.colour);
System.out.println("Material: "+hanky13.material);
System.out.println("Size: "+hanky13.size);
System.out.println("Shape: "+hanky13.shape);
System.out.println("Price: "+hanky13.price);
System.out.println("Quantity: "+hanky13.quantity);
System.out.println("Pattern: "+hanky13.pattern);
System.out.println("Cotton: "+hanky13.isCotton);
System.out.println("Silk: "+hanky13.isSilk);
System.out.println("Soft: "+hanky13.isSoft);
System.out.println("Washable: "+hanky13.isWashable);
System.out.println("Printed: "+hanky13.isPrinted);
System.out.println("Plain: "+hanky13.isPlain);
System.out.println("Manufacture Date: "+hanky13.manufactureDate);
System.out.println("Country: "+hanky13.countryOfOrigin);
System.out.println("Seller: "+hanky13.sellerName);
System.out.println("Warranty: "+hanky13.warranty);
System.out.println("Rating: "+hanky13.rating);
System.out.println("Customer Review: "+hanky13.customerReview);
System.out.println("Eco Friendly: "+hanky13.isEcoFriendly);
System.out.println("Reusable: "+hanky13.isReusable);
System.out.println("Packaging: "+hanky13.packagingType);
System.out.println("Weight: "+hanky13.weight);
System.out.println("Discount: "+hanky13.discount);


Handkerchief hanky14 = new Handkerchief();
hanky14.brand="ParkAvenue";
hanky14.colour="Black";
hanky14.material="Cotton";
hanky14.size="Medium";
hanky14.shape="Square";
hanky14.price=60;
hanky14.quantity=3;
hanky14.pattern="Printed";
hanky14.isCotton=true;
hanky14.isSilk=false;
hanky14.isSoft=true;
hanky14.isWashable=true;
hanky14.isPrinted=true;
hanky14.isPlain=false;
hanky14.manufactureDate="23-01-2026";
hanky14.countryOfOrigin="India";
hanky14.sellerName="ClothBazaar";
hanky14.warranty="No Warranty";
hanky14.rating=4;
hanky14.customerReview="Nice cloth";
hanky14.isEcoFriendly=true;
hanky14.isReusable=true;
hanky14.packagingType="Plastic Cover";
hanky14.weight=0.05;
hanky14.discount=5;

System.out.println("Brand: "+hanky14.brand);
System.out.println("Colour: "+hanky14.colour);
System.out.println("Material: "+hanky14.material);
System.out.println("Size: "+hanky14.size);
System.out.println("Shape: "+hanky14.shape);
System.out.println("Price: "+hanky14.price);
System.out.println("Quantity: "+hanky14.quantity);
System.out.println("Pattern: "+hanky14.pattern);
System.out.println("Cotton: "+hanky14.isCotton);
System.out.println("Silk: "+hanky14.isSilk);
System.out.println("Soft: "+hanky14.isSoft);
System.out.println("Washable: "+hanky14.isWashable);
System.out.println("Printed: "+hanky14.isPrinted);
System.out.println("Plain: "+hanky14.isPlain);
System.out.println("Manufacture Date: "+hanky14.manufactureDate);
System.out.println("Country: "+hanky14.countryOfOrigin);
System.out.println("Seller: "+hanky14.sellerName);
System.out.println("Warranty: "+hanky14.warranty);
System.out.println("Rating: "+hanky14.rating);
System.out.println("Customer Review: "+hanky14.customerReview);
System.out.println("Eco Friendly: "+hanky14.isEcoFriendly);
System.out.println("Reusable: "+hanky14.isReusable);
System.out.println("Packaging: "+hanky14.packagingType);
System.out.println("Weight: "+hanky14.weight);
System.out.println("Discount: "+hanky14.discount);


Handkerchief hanky15 = new Handkerchief();
hanky15.brand="MonteCarlo";
hanky15.colour="Green";
hanky15.material="Cotton";
hanky15.size="Medium";
hanky15.shape="Square";
hanky15.price=55;
hanky15.quantity=2;
hanky15.pattern="Plain";
hanky15.isCotton=true;
hanky15.isSilk=false;
hanky15.isSoft=true;
hanky15.isWashable=true;
hanky15.isPrinted=false;
hanky15.isPlain=true;
hanky15.manufactureDate="24-01-2026";
hanky15.countryOfOrigin="India";
hanky15.sellerName="FashionStore";
hanky15.warranty="No Warranty";
hanky15.rating=4;
hanky15.customerReview="Soft material";
hanky15.isEcoFriendly=true;
hanky15.isReusable=true;
hanky15.packagingType="Paper Cover";
hanky15.weight=0.05;
hanky15.discount=4;

System.out.println("Brand: "+hanky15.brand);
System.out.println("Colour: "+hanky15.colour);
System.out.println("Material: "+hanky15.material);
System.out.println("Size: "+hanky15.size);
System.out.println("Shape: "+hanky15.shape);
System.out.println("Price: "+hanky15.price);
System.out.println("Quantity: "+hanky15.quantity);
System.out.println("Pattern: "+hanky15.pattern);
System.out.println("Cotton: "+hanky15.isCotton);
System.out.println("Silk: "+hanky15.isSilk);
System.out.println("Soft: "+hanky15.isSoft);
System.out.println("Washable: "+hanky15.isWashable);
System.out.println("Printed: "+hanky15.isPrinted);
System.out.println("Plain: "+hanky15.isPlain);
System.out.println("Manufacture Date: "+hanky15.manufactureDate);
System.out.println("Country: "+hanky15.countryOfOrigin);
System.out.println("Seller: "+hanky15.sellerName);
System.out.println("Warranty: "+hanky15.warranty);
System.out.println("Rating: "+hanky15.rating);
System.out.println("Customer Review: "+hanky15.customerReview);
System.out.println("Eco Friendly: "+hanky15.isEcoFriendly);
System.out.println("Reusable: "+hanky15.isReusable);
System.out.println("Packaging: "+hanky15.packagingType);
System.out.println("Weight: "+hanky15.weight);
System.out.println("Discount: "+hanky15.discount);

Handkerchief hanky16 = new Handkerchief();
hanky16.brand="Roadster";
hanky16.colour="Blue";
hanky16.material="Cotton";
hanky16.size="Medium";
hanky16.shape="Square";
hanky16.price=48;
hanky16.quantity=3;
hanky16.pattern="Printed";
hanky16.isCotton=true;
hanky16.isSilk=false;
hanky16.isSoft=true;
hanky16.isWashable=true;
hanky16.isPrinted=true;
hanky16.isPlain=false;
hanky16.manufactureDate="25-01-2026";
hanky16.countryOfOrigin="India";
hanky16.sellerName="StyleMart";
hanky16.warranty="No Warranty";
hanky16.rating=4;
hanky16.customerReview="Nice design";
hanky16.isEcoFriendly=true;
hanky16.isReusable=true;
hanky16.packagingType="Plastic Cover";
hanky16.weight=0.05;
hanky16.discount=5;

System.out.println("Brand: "+hanky16.brand);
System.out.println("Colour: "+hanky16.colour);
System.out.println("Material: "+hanky16.material);
System.out.println("Size: "+hanky16.size);
System.out.println("Shape: "+hanky16.shape);
System.out.println("Price: "+hanky16.price);
System.out.println("Quantity: "+hanky16.quantity);
System.out.println("Pattern: "+hanky16.pattern);
System.out.println("Cotton: "+hanky16.isCotton);
System.out.println("Silk: "+hanky16.isSilk);
System.out.println("Soft: "+hanky16.isSoft);
System.out.println("Washable: "+hanky16.isWashable);
System.out.println("Printed: "+hanky16.isPrinted);
System.out.println("Plain: "+hanky16.isPlain);
System.out.println("Manufacture Date: "+hanky16.manufactureDate);
System.out.println("Country: "+hanky16.countryOfOrigin);
System.out.println("Seller: "+hanky16.sellerName);
System.out.println("Warranty: "+hanky16.warranty);
System.out.println("Rating: "+hanky16.rating);
System.out.println("Customer Review: "+hanky16.customerReview);
System.out.println("Eco Friendly: "+hanky16.isEcoFriendly);
System.out.println("Reusable: "+hanky16.isReusable);
System.out.println("Packaging: "+hanky16.packagingType);
System.out.println("Weight: "+hanky16.weight);
System.out.println("Discount: "+hanky16.discount);

Handkerchief hanky17= new Handkerchief();
hanky17.brand="HRX";
hanky17.colour="Grey";
hanky17.material="Cotton";
hanky17.size="Large";
hanky17.shape="Square";
hanky17.price=52;
hanky17.quantity=2;
hanky17.pattern="Plain";
hanky17.isCotton=true;
hanky17.isSilk=false;
hanky17.isSoft=true;
hanky17.isWashable=true;
hanky17.isPrinted=false;
hanky17.isPlain=true;
hanky17.manufactureDate="26-01-2026";
hanky17.countryOfOrigin="India";
hanky17.sellerName="ClothHouse";
hanky17.warranty="No Warranty";
hanky17.rating=4;
hanky17.customerReview="Good cloth";
hanky17.isEcoFriendly=true;
hanky17.isReusable=true;
hanky17.packagingType="Paper Cover";
hanky17.weight=0.05;
hanky17.discount=4;

System.out.println("Brand: "+hanky17.brand);
System.out.println("Colour: "+hanky17.colour);
System.out.println("Material: "+hanky17.material);
System.out.println("Size: "+hanky17.size);
System.out.println("Shape: "+hanky17.shape);
System.out.println("Price: "+hanky17.price);
System.out.println("Quantity: "+hanky17.quantity);
System.out.println("Pattern: "+hanky17.pattern);
System.out.println("Cotton: "+hanky17.isCotton);
System.out.println("Silk: "+hanky17.isSilk);
System.out.println("Soft: "+hanky17.isSoft);
System.out.println("Washable: "+hanky17.isWashable);
System.out.println("Printed: "+hanky17.isPrinted);
System.out.println("Plain: "+hanky17.isPlain);
System.out.println("Manufacture Date: "+hanky17.manufactureDate);
System.out.println("Country: "+hanky17.countryOfOrigin);
System.out.println("Seller: "+hanky17.sellerName);
System.out.println("Warranty: "+hanky17.warranty);
System.out.println("Rating: "+hanky17.rating);
System.out.println("Customer Review: "+hanky17.customerReview);
System.out.println("Eco Friendly: "+hanky17.isEcoFriendly);
System.out.println("Reusable: "+hanky17.isReusable);
System.out.println("Packaging: "+hanky17.packagingType);
System.out.println("Weight: "+hanky17.weight);
System.out.println("Discount: "+hanky17.discount);

Handkerchief hanky18 = new Handkerchief();
hanky18.brand="Zara";
hanky18.colour="White";
hanky18.material="Linen";
hanky18.size="Medium";
hanky18.shape="Square";
hanky18.price=75;
hanky18.quantity=2;
hanky18.pattern="Plain";
hanky18.isCotton=false;
hanky18.isSilk=false;
hanky18.isSoft=true;
hanky18.isWashable=true;
hanky18.isPrinted=false;
hanky18.isPlain=true;
hanky18.manufactureDate="27-01-2026";
hanky18.countryOfOrigin="India";
hanky18.sellerName="PremiumStore";
hanky18.warranty="No Warranty";
hanky18.rating=5;
hanky18.customerReview="Premium fabric";
hanky18.isEcoFriendly=true;
hanky18.isReusable=true;
hanky18.packagingType="Box";
hanky18.weight=0.06;
hanky18.discount=6;

System.out.println("Brand: "+hanky18.brand);
System.out.println("Colour: "+hanky18.colour);
System.out.println("Material: "+hanky18.material);
System.out.println("Size: "+hanky18.size);
System.out.println("Shape: "+hanky18.shape);
System.out.println("Price: "+hanky18.price);
System.out.println("Quantity: "+hanky18.quantity);
System.out.println("Pattern: "+hanky18.pattern);
System.out.println("Cotton: "+hanky18.isCotton);
System.out.println("Silk: "+hanky18.isSilk);
System.out.println("Soft: "+hanky18.isSoft);
System.out.println("Washable: "+hanky18.isWashable);
System.out.println("Printed: "+hanky18.isPrinted);
System.out.println("Plain: "+hanky18.isPlain);
System.out.println("Manufacture Date: "+hanky18.manufactureDate);
System.out.println("Country: "+hanky18.countryOfOrigin);
System.out.println("Seller: "+hanky18.sellerName);
System.out.println("Warranty: "+hanky18.warranty);
System.out.println("Rating: "+hanky18.rating);
System.out.println("Customer Review: "+hanky18.customerReview);
System.out.println("Eco Friendly: "+hanky18.isEcoFriendly);
System.out.println("Reusable: "+hanky18.isReusable);
System.out.println("Packaging: "+hanky18.packagingType);
System.out.println("Weight: "+hanky18.weight);
System.out.println("Discount: "+hanky18.discount);

Handkerchief hanky19 = new Handkerchief();
hanky19.brand="H&M";
hanky19.colour="Black";
hanky19.material="Cotton";
hanky19.size="Medium";
hanky19.shape="Square";
hanky19.price=60;
hanky19.quantity=2;
hanky19.pattern="Printed";
hanky19.isCotton=true;
hanky19.isSilk=false;
hanky19.isSoft=true;
hanky19.isWashable=true;
hanky19.isPrinted=true;
hanky19.isPlain=false;
hanky19.manufactureDate="28-01-2026";
hanky19.countryOfOrigin="India";
hanky19.sellerName="FashionBazaar";
hanky19.warranty="No Warranty";
hanky19.rating=4;
hanky19.customerReview="Nice cloth";
hanky19.isEcoFriendly=true;
hanky19.isReusable=true;
hanky19.packagingType="Plastic Cover";
hanky19.weight=0.05;
hanky19.discount=5;

System.out.println("Brand: "+hanky19.brand);
System.out.println("Colour: "+hanky19.colour);
System.out.println("Material: "+hanky19.material);
System.out.println("Size: "+hanky19.size);
System.out.println("Shape: "+hanky19.shape);
System.out.println("Price: "+hanky19.price);
System.out.println("Quantity: "+hanky19.quantity);
System.out.println("Pattern: "+hanky19.pattern);
System.out.println("Cotton: "+hanky19.isCotton);
System.out.println("Silk: "+hanky19.isSilk);
System.out.println("Soft: "+hanky19.isSoft);
System.out.println("Washable: "+hanky19.isWashable);
System.out.println("Printed: "+hanky19.isPrinted);
System.out.println("Plain: "+hanky19.isPlain);
System.out.println("Manufacture Date: "+hanky19.manufactureDate);
System.out.println("Country: "+hanky19.countryOfOrigin);
System.out.println("Seller: "+hanky19.sellerName);
System.out.println("Warranty: "+hanky19.warranty);
System.out.println("Rating: "+hanky19.rating);
System.out.println("Customer Review: "+hanky19.customerReview);
System.out.println("Eco Friendly: "+hanky19.isEcoFriendly);
System.out.println("Reusable: "+hanky19.isReusable);
System.out.println("Packaging: "+hanky19.packagingType);
System.out.println("Weight: "+hanky19.weight);
System.out.println("Discount: "+hanky19.discount);


Handkerchief hanky20 = new Handkerchief();
hanky20.brand="Gucci";
hanky20.colour="Cream";
hanky20.material="Silk";
hanky20.size="Large";
hanky20.shape="Square";
hanky20.price=120;
hanky20.quantity=1;
hanky20.pattern="Designer";
hanky20.isCotton=false;
hanky20.isSilk=true;
hanky20.isSoft=true;
hanky20.isWashable=false;
hanky20.isPrinted=true;
hanky20.isPlain=false;
hanky20.manufactureDate="29-01-2026";
hanky20.countryOfOrigin="Italy";
hanky20.sellerName="LuxuryStore";
hanky20.warranty="No Warranty";
hanky20.rating=5;
hanky20.customerReview="Luxury quality";
hanky20.isEcoFriendly=true;
hanky20.isReusable=true;
hanky20.packagingType="Gift Box";
hanky20.weight=0.07;
hanky20.discount=10;

System.out.println("Brand: "+hanky20.brand);
System.out.println("Colour: "+hanky20.colour);
System.out.println("Material: "+hanky20.material);
System.out.println("Size: "+hanky20.size);
System.out.println("Shape: "+hanky20.shape);
System.out.println("Price: "+hanky20.price);
System.out.println("Quantity: "+hanky20.quantity);
System.out.println("Pattern: "+hanky20.pattern);
System.out.println("Cotton: "+hanky20.isCotton);
System.out.println("Silk: "+hanky20.isSilk);
System.out.println("Soft: "+hanky20.isSoft);
System.out.println("Washable: "+hanky20.isWashable);
System.out.println("Printed: "+hanky20.isPrinted);
System.out.println("Plain: "+hanky20.isPlain);
System.out.println("Manufacture Date: "+hanky20.manufactureDate);
System.out.println("Country: "+hanky20.countryOfOrigin);
System.out.println("Seller: "+hanky20.sellerName);
System.out.println("Warranty: "+hanky20.warranty);
System.out.println("Rating: "+hanky20.rating);
System.out.println("Customer Review: "+hanky20.customerReview);
System.out.println("Eco Friendly: "+hanky20.isEcoFriendly);
System.out.println("Reusable: "+hanky20.isReusable);
System.out.println("Packaging: "+hanky20.packagingType);
System.out.println("Weight: "+hanky20.weight);
System.out.println("Discount: "+hanky20.discount);
}
}



