class HelmetExecutor {

    public static void main(String[] args) {

        Helmet helmet1 = new Helmet();

        helmet1.brand = "Vega";
        helmet1.type = "Full Face";
        helmet1.colour = "Black";
        helmet1.price = 1200;
        helmet1.size = "M";
        helmet1.weight = 1.2;
        helmet1.material = "ABS Plastic";
        helmet1.isFullFace = true;
        helmet1.isISIApproved = true;
        helmet1.isVisorAvailable = true;
        helmet1.isScratchResistant = true;
        helmet1.isVentilationAvailable = true;
        helmet1.warranty = "1 Year";
        helmet1.countryOfOrigin = "India";
        helmet1.stock = 25;
        helmet1.rating = 4;
        helmet1.customerReview = "Good quality";
        helmet1.manufactureDate = "10-02-2026";
        helmet1.sellerName = "HelmetWorld";
        helmet1.isLightWeight = true;
        helmet1.isAntiFog = false;
        helmet1.strapType = "Quick Release";
        helmet1.helmetModel = "Vega Bolt";
        helmet1.usageType = "Bike Riding";
        helmet1.discount = 10;

        System.out.println("Brand: " + helmet1.brand);
        System.out.println("Type: " + helmet1.type);
        System.out.println("Colour: " + helmet1.colour);
        System.out.println("Price: " + helmet1.price);
        System.out.println("Size: " + helmet1.size);
        System.out.println("Weight: " + helmet1.weight);
        System.out.println("Material: " + helmet1.material);
        System.out.println("Full Face: " + helmet1.isFullFace);
        System.out.println("ISI Approved: " + helmet1.isISIApproved);
        System.out.println("Visor Available: " + helmet1.isVisorAvailable);
        System.out.println("Scratch Resistant: " + helmet1.isScratchResistant);
        System.out.println("Ventilation: " + helmet1.isVentilationAvailable);
        System.out.println("Warranty: " + helmet1.warranty);
        System.out.println("Country: " + helmet1.countryOfOrigin);
        System.out.println("Stock: " + helmet1.stock);
        System.out.println("Rating: " + helmet1.rating);
        System.out.println("Customer Review: " + helmet1.customerReview);
        System.out.println("Manufacture Date: " + helmet1.manufactureDate);
        System.out.println("Seller Name: " + helmet1.sellerName);
        System.out.println("Light Weight: " + helmet1.isLightWeight);
        System.out.println("Anti Fog: " + helmet1.isAntiFog);
        System.out.println("Strap Type: " + helmet1.strapType);
        System.out.println("Model: " + helmet1.helmetModel);
        System.out.println("Usage: " + helmet1.usageType);
        System.out.println("Discount: " + helmet1.discount);
             
Helmet helmet2 = new Helmet();
helmet2.brand="Studds";
helmet2.type="Full Face";
helmet2.colour="Red";
helmet2.price=1400;
helmet2.size="L";
helmet2.weight=1.3;
helmet2.material="ABS Plastic";
helmet2.isFullFace=true;
helmet2.isISIApproved=true;
helmet2.isVisorAvailable=true;
helmet2.isScratchResistant=true;
helmet2.isVentilationAvailable=true;
helmet2.warranty="1 Year";
helmet2.countryOfOrigin="India";
helmet2.stock=20;
helmet2.rating=4;
helmet2.customerReview="Strong helmet";
helmet2.manufactureDate="05-01-2026";
helmet2.sellerName="BikeGear";
helmet2.isLightWeight=false;
helmet2.isAntiFog=true;
helmet2.strapType="Quick Release";
helmet2.helmetModel="Studds Thunder";
helmet2.usageType="Bike Riding";
helmet2.discount=8;

System.out.println("Brand: "+helmet2.brand);
System.out.println("Type: "+helmet2.type);
System.out.println("Colour: "+helmet2.colour);
System.out.println("Price: "+helmet2.price);
System.out.println("Size: "+helmet2.size);
System.out.println("Weight: "+helmet2.weight);
System.out.println("Material: "+helmet2.material);
System.out.println("Full Face: "+helmet2.isFullFace);
System.out.println("ISI Approved: "+helmet2.isISIApproved);
System.out.println("Visor Available: "+helmet2.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet2.isScratchResistant);
System.out.println("Ventilation: "+helmet2.isVentilationAvailable);
System.out.println("Warranty: "+helmet2.warranty);
System.out.println("Country: "+helmet2.countryOfOrigin);
System.out.println("Stock: "+helmet2.stock);
System.out.println("Rating: "+helmet2.rating);
System.out.println("Customer Review: "+helmet2.customerReview);
System.out.println("Manufacture Date: "+helmet2.manufactureDate);
System.out.println("Seller Name: "+helmet2.sellerName);
System.out.println("Light Weight: "+helmet2.isLightWeight);
System.out.println("Anti Fog: "+helmet2.isAntiFog);
System.out.println("Strap Type: "+helmet2.strapType);
System.out.println("Model: "+helmet2.helmetModel);
System.out.println("Usage: "+helmet2.usageType);
System.out.println("Discount: "+helmet2.discount);


Helmet helmet3 = new Helmet();
helmet3.brand="Steelbird";
helmet3.type="Full Face";
helmet3.colour="Blue";
helmet3.price=1350;
helmet3.size="M";
helmet3.weight=1.2;
helmet3.material="ABS";
helmet3.isFullFace=true;
helmet3.isISIApproved=true;
helmet3.isVisorAvailable=true;
helmet3.isScratchResistant=true;
helmet3.isVentilationAvailable=true;
helmet3.warranty="1 Year";
helmet3.countryOfOrigin="India";
helmet3.stock=18;
helmet3.rating=4;
helmet3.customerReview="Good comfort";
helmet3.manufactureDate="10-02-2026";
helmet3.sellerName="HelmetStore";
helmet3.isLightWeight=true;
helmet3.isAntiFog=false;
helmet3.strapType="Lock Strap";
helmet3.helmetModel="Steelbird Air";
helmet3.usageType="Bike Riding";
helmet3.discount=10;

System.out.println("Brand: "+helmet3.brand);
System.out.println("Type: "+helmet3.type);
System.out.println("Colour: "+helmet3.colour);
System.out.println("Price: "+helmet3.price);
System.out.println("Size: "+helmet3.size);
System.out.println("Weight: "+helmet3.weight);
System.out.println("Material: "+helmet3.material);
System.out.println("Full Face: "+helmet3.isFullFace);
System.out.println("ISI Approved: "+helmet3.isISIApproved);
System.out.println("Visor Available: "+helmet3.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet3.isScratchResistant);
System.out.println("Ventilation: "+helmet3.isVentilationAvailable);
System.out.println("Warranty: "+helmet3.warranty);
System.out.println("Country: "+helmet3.countryOfOrigin);
System.out.println("Stock: "+helmet3.stock);
System.out.println("Rating: "+helmet3.rating);
System.out.println("Customer Review: "+helmet3.customerReview);
System.out.println("Manufacture Date: "+helmet3.manufactureDate);
System.out.println("Seller Name: "+helmet3.sellerName);
System.out.println("Light Weight: "+helmet3.isLightWeight);
System.out.println("Anti Fog: "+helmet3.isAntiFog);
System.out.println("Strap Type: "+helmet3.strapType);
System.out.println("Model: "+helmet3.helmetModel);
System.out.println("Usage: "+helmet3.usageType);
System.out.println("Discount: "+helmet3.discount);


Helmet helmet4 = new Helmet();
helmet4.brand="Vega";
helmet4.type="Open Face";
helmet4.colour="Black";
helmet4.price=1100;
helmet4.size="M";
helmet4.weight=1.1;
helmet4.material="Plastic";
helmet4.isFullFace=false;
helmet4.isISIApproved=true;
helmet4.isVisorAvailable=true;
helmet4.isScratchResistant=false;
helmet4.isVentilationAvailable=true;
helmet4.warranty="6 Months";
helmet4.countryOfOrigin="India";
helmet4.stock=15;
helmet4.rating=3;
helmet4.customerReview="Average";
helmet4.manufactureDate="20-01-2026";
helmet4.sellerName="BikeShop";
helmet4.isLightWeight=true;
helmet4.isAntiFog=false;
helmet4.strapType="Clip";
helmet4.helmetModel="Vega Jet";
helmet4.usageType="Scooter";
helmet4.discount=5;

System.out.println("Brand: "+helmet4.brand);
System.out.println("Type: "+helmet4.type);
System.out.println("Colour: "+helmet4.colour);
System.out.println("Price: "+helmet4.price);
System.out.println("Size: "+helmet4.size);
System.out.println("Weight: "+helmet4.weight);
System.out.println("Material: "+helmet4.material);
System.out.println("Full Face: "+helmet4.isFullFace);
System.out.println("ISI Approved: "+helmet4.isISIApproved);
System.out.println("Visor Available: "+helmet4.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet4.isScratchResistant);
System.out.println("Ventilation: "+helmet4.isVentilationAvailable);
System.out.println("Warranty: "+helmet4.warranty);
System.out.println("Country: "+helmet4.countryOfOrigin);
System.out.println("Stock: "+helmet4.stock);
System.out.println("Rating: "+helmet4.rating);
System.out.println("Customer Review: "+helmet4.customerReview);
System.out.println("Manufacture Date: "+helmet4.manufactureDate);
System.out.println("Seller Name: "+helmet4.sellerName);
System.out.println("Light Weight: "+helmet4.isLightWeight);
System.out.println("Anti Fog: "+helmet4.isAntiFog);
System.out.println("Strap Type: "+helmet4.strapType);
System.out.println("Model: "+helmet4.helmetModel);
System.out.println("Usage: "+helmet4.usageType);
System.out.println("Discount: "+helmet4.discount);


Helmet helmet5 = new Helmet();
helmet5.brand="Axor";
helmet5.type="Full Face";
helmet5.colour="White";
helmet5.price=3200;
helmet5.size="L";
helmet5.weight=1.4;
helmet5.material="Fiber";
helmet5.isFullFace=true;
helmet5.isISIApproved=true;
helmet5.isVisorAvailable=true;
helmet5.isScratchResistant=true;
helmet5.isVentilationAvailable=true;
helmet5.warranty="2 Years";
helmet5.countryOfOrigin="India";
helmet5.stock=10;
helmet5.rating=5;
helmet5.customerReview="Premium quality";
helmet5.manufactureDate="15-02-2026";
helmet5.sellerName="MotoStore";
helmet5.isLightWeight=true;
helmet5.isAntiFog=true;
helmet5.strapType="Double D Ring";
helmet5.helmetModel="Axor Apex";
helmet5.usageType="Racing";
helmet5.discount=12;

System.out.println("Brand: "+helmet5.brand);
System.out.println("Type: "+helmet5.type);
System.out.println("Colour: "+helmet5.colour);
System.out.println("Price: "+helmet5.price);
System.out.println("Size: "+helmet5.size);
System.out.println("Weight: "+helmet5.weight);
System.out.println("Material: "+helmet5.material);
System.out.println("Full Face: "+helmet5.isFullFace);
System.out.println("ISI Approved: "+helmet5.isISIApproved);
System.out.println("Visor Available: "+helmet5.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet5.isScratchResistant);
System.out.println("Ventilation: "+helmet5.isVentilationAvailable);
System.out.println("Warranty: "+helmet5.warranty);
System.out.println("Country: "+helmet5.countryOfOrigin);
System.out.println("Stock: "+helmet5.stock);
System.out.println("Rating: "+helmet5.rating);
System.out.println("Customer Review: "+helmet5.customerReview);
System.out.println("Manufacture Date: "+helmet5.manufactureDate);
System.out.println("Seller Name: "+helmet5.sellerName);
System.out.println("Light Weight: "+helmet5.isLightWeight);
System.out.println("Anti Fog: "+helmet5.isAntiFog);
System.out.println("Strap Type: "+helmet5.strapType);
System.out.println("Model: "+helmet5.helmetModel);
System.out.println("Usage: "+helmet5.usageType);
System.out.println("Discount: "+helmet5.discount);


Helmet helmet6 = new Helmet();
helmet6.brand="Studds";
helmet6.type="Open Face";
helmet6.colour="Black";
helmet6.price=1800;
helmet6.size="M";
helmet6.weight=1.2;
helmet6.material="ABS Plastic";
helmet6.isFullFace=false;
helmet6.isISIApproved=true;
helmet6.isVisorAvailable=true;
helmet6.isScratchResistant=false;
helmet6.isVentilationAvailable=true;
helmet6.warranty="1 Year";
helmet6.countryOfOrigin="India";
helmet6.stock=20;
helmet6.rating=4;
helmet6.customerReview="Good and comfortable";
helmet6.manufactureDate="10-01-2026";
helmet6.sellerName="BikeZone";
helmet6.isLightWeight=true;
helmet6.isAntiFog=false;
helmet6.strapType="Quick Release";
helmet6.helmetModel="Studds Chrome";
helmet6.usageType="City Ride";
helmet6.discount=8;

System.out.println("Brand: "+helmet6.brand);
System.out.println("Type: "+helmet6.type);
System.out.println("Colour: "+helmet6.colour);
System.out.println("Price: "+helmet6.price);
System.out.println("Size: "+helmet6.size);
System.out.println("Weight: "+helmet6.weight);
System.out.println("Material: "+helmet6.material);
System.out.println("Full Face: "+helmet6.isFullFace);
System.out.println("ISI Approved: "+helmet6.isISIApproved);
System.out.println("Visor Available: "+helmet6.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet6.isScratchResistant);
System.out.println("Ventilation: "+helmet6.isVentilationAvailable);
System.out.println("Warranty: "+helmet6.warranty);
System.out.println("Country: "+helmet6.countryOfOrigin);
System.out.println("Stock: "+helmet6.stock);
System.out.println("Rating: "+helmet6.rating);
System.out.println("Customer Review: "+helmet6.customerReview);
System.out.println("Manufacture Date: "+helmet6.manufactureDate);
System.out.println("Seller Name: "+helmet6.sellerName);
System.out.println("Light Weight: "+helmet6.isLightWeight);
System.out.println("Anti Fog: "+helmet6.isAntiFog);
System.out.println("Strap Type: "+helmet6.strapType);
System.out.println("Model: "+helmet6.helmetModel);
System.out.println("Usage: "+helmet6.usageType);
System.out.println("Discount: "+helmet6.discount);



Helmet helmet7 = new Helmet();
helmet7.brand="Vega";
helmet7.type="Full Face";
helmet7.colour="Red";
helmet7.price=2500;
helmet7.size="L";
helmet7.weight=1.3;
helmet7.material="Fiber";
helmet7.isFullFace=true;
helmet7.isISIApproved=true;
helmet7.isVisorAvailable=true;
helmet7.isScratchResistant=true;
helmet7.isVentilationAvailable=true;
helmet7.warranty="1 Year";
helmet7.countryOfOrigin="India";
helmet7.stock=15;
helmet7.rating=4;
helmet7.customerReview="Stylish design";
helmet7.manufactureDate="05-02-2026";
helmet7.sellerName="MotoShop";
helmet7.isLightWeight=true;
helmet7.isAntiFog=true;
helmet7.strapType="Quick Release";
helmet7.helmetModel="Vega Bolt";
helmet7.usageType="Daily Ride";
helmet7.discount=10;

System.out.println("Brand: "+helmet7.brand);
System.out.println("Type: "+helmet7.type);
System.out.println("Colour: "+helmet7.colour);
System.out.println("Price: "+helmet7.price);
System.out.println("Size: "+helmet7.size);
System.out.println("Weight: "+helmet7.weight);
System.out.println("Material: "+helmet7.material);
System.out.println("Full Face: "+helmet7.isFullFace);
System.out.println("ISI Approved: "+helmet7.isISIApproved);
System.out.println("Visor Available: "+helmet7.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet7.isScratchResistant);
System.out.println("Ventilation: "+helmet7.isVentilationAvailable);
System.out.println("Warranty: "+helmet7.warranty);
System.out.println("Country: "+helmet7.countryOfOrigin);
System.out.println("Stock: "+helmet7.stock);
System.out.println("Rating: "+helmet7.rating);
System.out.println("Customer Review: "+helmet7.customerReview);
System.out.println("Manufacture Date: "+helmet7.manufactureDate);
System.out.println("Seller Name: "+helmet7.sellerName);
System.out.println("Light Weight: "+helmet7.isLightWeight);
System.out.println("Anti Fog: "+helmet7.isAntiFog);
System.out.println("Strap Type: "+helmet7.strapType);
System.out.println("Model: "+helmet7.helmetModel);
System.out.println("Usage: "+helmet7.usageType);
System.out.println("Discount: "+helmet7.discount);


Helmet helmet8 = new Helmet();
helmet8.brand="Steelbird";
helmet8.type="Modular";
helmet8.colour="Blue";
helmet8.price=2700;
helmet8.size="M";
helmet8.weight=1.35;
helmet8.material="Polycarbonate";
helmet8.isFullFace=true;
helmet8.isISIApproved=true;
helmet8.isVisorAvailable=true;
helmet8.isScratchResistant=true;
helmet8.isVentilationAvailable=true;
helmet8.warranty="2 Years";
helmet8.countryOfOrigin="India";
helmet8.stock=18;
helmet8.rating=4;
helmet8.customerReview="Strong and durable";
helmet8.manufactureDate="20-01-2026";
helmet8.sellerName="HelmetHub";
helmet8.isLightWeight=true;
helmet8.isAntiFog=true;
helmet8.strapType="Double D Ring";
helmet8.helmetModel="Steelbird SBA";
helmet8.usageType="Touring";
helmet8.discount=9;

System.out.println("Brand: "+helmet8.brand);
System.out.println("Type: "+helmet8.type);
System.out.println("Colour: "+helmet8.colour);
System.out.println("Price: "+helmet8.price);
System.out.println("Size: "+helmet8.size);
System.out.println("Weight: "+helmet8.weight);
System.out.println("Material: "+helmet8.material);
System.out.println("Full Face: "+helmet8.isFullFace);
System.out.println("ISI Approved: "+helmet8.isISIApproved);
System.out.println("Visor Available: "+helmet8.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet8.isScratchResistant);
System.out.println("Ventilation: "+helmet8.isVentilationAvailable);
System.out.println("Warranty: "+helmet8.warranty);
System.out.println("Country: "+helmet8.countryOfOrigin);
System.out.println("Stock: "+helmet8.stock);
System.out.println("Rating: "+helmet8.rating);
System.out.println("Customer Review: "+helmet8.customerReview);
System.out.println("Manufacture Date: "+helmet8.manufactureDate);
System.out.println("Seller Name: "+helmet8.sellerName);
System.out.println("Light Weight: "+helmet8.isLightWeight);
System.out.println("Anti Fog: "+helmet8.isAntiFog);
System.out.println("Strap Type: "+helmet8.strapType);
System.out.println("Model: "+helmet8.helmetModel);
System.out.println("Usage: "+helmet8.usageType);
System.out.println("Discount: "+helmet8.discount);


Helmet helmet9 = new Helmet();
helmet9.brand="LS2";
helmet9.type="Full Face";
helmet9.colour="Yellow";
helmet9.price=4500;
helmet9.size="L";
helmet9.weight=1.45;
helmet9.material="Carbon Fiber";
helmet9.isFullFace=true;
helmet9.isISIApproved=true;
helmet9.isVisorAvailable=true;
helmet9.isScratchResistant=true;
helmet9.isVentilationAvailable=true;
helmet9.warranty="3 Years";
helmet9.countryOfOrigin="Spain";
helmet9.stock=12;
helmet9.rating=5;
helmet9.customerReview="High performance helmet";
helmet9.manufactureDate="12-02-2026";
helmet9.sellerName="ProRiders";
helmet9.isLightWeight=true;
helmet9.isAntiFog=true;
helmet9.strapType="Double D Ring";
helmet9.helmetModel="LS2 Storm";
helmet9.usageType="Racing";
helmet9.discount=15;

System.out.println("Brand: "+helmet9.brand);
System.out.println("Type: "+helmet9.type);
System.out.println("Colour: "+helmet9.colour);
System.out.println("Price: "+helmet9.price);
System.out.println("Size: "+helmet9.size);
System.out.println("Weight: "+helmet9.weight);
System.out.println("Material: "+helmet9.material);
System.out.println("Full Face: "+helmet9.isFullFace);
System.out.println("ISI Approved: "+helmet9.isISIApproved);
System.out.println("Visor Available: "+helmet9.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet9.isScratchResistant);
System.out.println("Ventilation: "+helmet9.isVentilationAvailable);
System.out.println("Warranty: "+helmet9.warranty);
System.out.println("Country: "+helmet9.countryOfOrigin);
System.out.println("Stock: "+helmet9.stock);
System.out.println("Rating: "+helmet9.rating);
System.out.println("Customer Review: "+helmet9.customerReview);
System.out.println("Manufacture Date: "+helmet9.manufactureDate);
System.out.println("Seller Name: "+helmet9.sellerName);
System.out.println("Light Weight: "+helmet9.isLightWeight);
System.out.println("Anti Fog: "+helmet9.isAntiFog);
System.out.println("Strap Type: "+helmet9.strapType);
System.out.println("Model: "+helmet9.helmetModel);
System.out.println("Usage: "+helmet9.usageType);
System.out.println("Discount: "+helmet9.discount);


Helmet helmet10 = new Helmet();
helmet10.brand="Royal Enfield";
helmet10.type="Half Face";
helmet10.colour="Brown";
helmet10.price=3000;
helmet10.size="M";
helmet10.weight=1.25;
helmet10.material="ABS";
helmet10.isFullFace=false;
helmet10.isISIApproved=true;
helmet10.isVisorAvailable=true;
helmet10.isScratchResistant=true;
helmet10.isVentilationAvailable=true;
helmet10.warranty="2 Years";
helmet10.countryOfOrigin="India";
helmet10.stock=14;
helmet10.rating=4;
helmet10.customerReview="Classic style helmet";
helmet10.manufactureDate="01-02-2026";
helmet10.sellerName="RE Store";
helmet10.isLightWeight=true;
helmet10.isAntiFog=false;
helmet10.strapType="Quick Release";
helmet10.helmetModel="RE Classic";
helmet10.usageType="Cruising";
helmet10.discount=11;

System.out.println("Brand: "+helmet10.brand);
System.out.println("Type: "+helmet10.type);
System.out.println("Colour: "+helmet10.colour);
System.out.println("Price: "+helmet10.price);
System.out.println("Size: "+helmet10.size);
System.out.println("Weight: "+helmet10.weight);
System.out.println("Material: "+helmet10.material);
System.out.println("Full Face: "+helmet10.isFullFace);
System.out.println("ISI Approved: "+helmet10.isISIApproved);
System.out.println("Visor Available: "+helmet10.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet10.isScratchResistant);
System.out.println("Ventilation: "+helmet10.isVentilationAvailable);
System.out.println("Warranty: "+helmet10.warranty);
System.out.println("Country: "+helmet10.countryOfOrigin);
System.out.println("Stock: "+helmet10.stock);
System.out.println("Rating: "+helmet10.rating);
System.out.println("Customer Review: "+helmet10.customerReview);
System.out.println("Manufacture Date: "+helmet10.manufactureDate);
System.out.println("Seller Name: "+helmet10.sellerName);
System.out.println("Light Weight: "+helmet10.isLightWeight);
System.out.println("Anti Fog: "+helmet10.isAntiFog);
System.out.println("Strap Type: "+helmet10.strapType);
System.out.println("Model: "+helmet10.helmetModel);
System.out.println("Usage: "+helmet10.usageType);
System.out.println("Discount: "+helmet10.discount);

Helmet helmet11 = new Helmet();
helmet11.brand="MT";
helmet11.type="Full Face";
helmet11.colour="Black";
helmet11.price=3500;
helmet11.size="L";
helmet11.weight=1.4;
helmet11.material="Polycarbonate";
helmet11.isFullFace=true;
helmet11.isISIApproved=true;
helmet11.isVisorAvailable=true;
helmet11.isScratchResistant=true;
helmet11.isVentilationAvailable=true;
helmet11.warranty="2 Years";
helmet11.countryOfOrigin="Spain";
helmet11.stock=10;
helmet11.rating=5;
helmet11.customerReview="Very safe helmet";
helmet11.manufactureDate="05-01-2026";
helmet11.sellerName="HelmetWorld";
helmet11.isLightWeight=true;
helmet11.isAntiFog=true;
helmet11.strapType="Double D Ring";
helmet11.helmetModel="MT Thunder";
helmet11.usageType="Racing";
helmet11.discount=10;

System.out.println("Brand: "+helmet11.brand);
System.out.println("Type: "+helmet11.type);
System.out.println("Colour: "+helmet11.colour);
System.out.println("Price: "+helmet11.price);
System.out.println("Size: "+helmet11.size);
System.out.println("Weight: "+helmet11.weight);
System.out.println("Material: "+helmet11.material);
System.out.println("Full Face: "+helmet11.isFullFace);
System.out.println("ISI Approved: "+helmet11.isISIApproved);
System.out.println("Visor Available: "+helmet11.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet11.isScratchResistant);
System.out.println("Ventilation: "+helmet11.isVentilationAvailable);
System.out.println("Warranty: "+helmet11.warranty);
System.out.println("Country: "+helmet11.countryOfOrigin);
System.out.println("Stock: "+helmet11.stock);
System.out.println("Rating: "+helmet11.rating);
System.out.println("Customer Review: "+helmet11.customerReview);
System.out.println("Manufacture Date: "+helmet11.manufactureDate);
System.out.println("Seller Name: "+helmet11.sellerName);
System.out.println("Light Weight: "+helmet11.isLightWeight);
System.out.println("Anti Fog: "+helmet11.isAntiFog);
System.out.println("Strap Type: "+helmet11.strapType);
System.out.println("Model: "+helmet11.helmetModel);
System.out.println("Usage: "+helmet11.usageType);
System.out.println("Discount: "+helmet11.discount);


Helmet helmet12 = new Helmet();
helmet12.brand="Studds";
helmet12.type="Half Face";
helmet12.colour="Grey";
helmet12.price=1500;
helmet12.size="M";
helmet12.weight=1.1;
helmet12.material="ABS";
helmet12.isFullFace=false;
helmet12.isISIApproved=true;
helmet12.isVisorAvailable=true;
helmet12.isScratchResistant=false;
helmet12.isVentilationAvailable=true;
helmet12.warranty="1 Year";
helmet12.countryOfOrigin="India";
helmet12.stock=22;
helmet12.rating=4;
helmet12.customerReview="Affordable helmet";
helmet12.manufactureDate="10-01-2026";
helmet12.sellerName="BikeMart";
helmet12.isLightWeight=true;
helmet12.isAntiFog=false;
helmet12.strapType="Quick Release";
helmet12.helmetModel="Studds Ninja";
helmet12.usageType="City Ride";
helmet12.discount=7;

System.out.println("Brand: "+helmet12.brand);
System.out.println("Type: "+helmet12.type);
System.out.println("Colour: "+helmet12.colour);
System.out.println("Price: "+helmet12.price);
System.out.println("Size: "+helmet12.size);
System.out.println("Weight: "+helmet12.weight);
System.out.println("Material: "+helmet12.material);
System.out.println("Full Face: "+helmet12.isFullFace);
System.out.println("ISI Approved: "+helmet12.isISIApproved);
System.out.println("Visor Available: "+helmet12.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet12.isScratchResistant);
System.out.println("Ventilation: "+helmet12.isVentilationAvailable);
System.out.println("Warranty: "+helmet12.warranty);
System.out.println("Country: "+helmet12.countryOfOrigin);
System.out.println("Stock: "+helmet12.stock);
System.out.println("Rating: "+helmet12.rating);
System.out.println("Customer Review: "+helmet12.customerReview);
System.out.println("Manufacture Date: "+helmet12.manufactureDate);
System.out.println("Seller Name: "+helmet12.sellerName);
System.out.println("Light Weight: "+helmet12.isLightWeight);
System.out.println("Anti Fog: "+helmet12.isAntiFog);
System.out.println("Strap Type: "+helmet12.strapType);
System.out.println("Model: "+helmet12.helmetModel);
System.out.println("Usage: "+helmet12.usageType);
System.out.println("Discount: "+helmet12.discount);


Helmet helmet13 = new Helmet();
helmet13.brand="Vega";
helmet13.type="Full Face";
helmet13.colour="Blue";
helmet13.price=2400;
helmet13.size="L";
helmet13.weight=1.3;
helmet13.material="Fiber";
helmet13.isFullFace=true;
helmet13.isISIApproved=true;
helmet13.isVisorAvailable=true;
helmet13.isScratchResistant=true;
helmet13.isVentilationAvailable=true;
helmet13.warranty="1 Year";
helmet13.countryOfOrigin="India";
helmet13.stock=18;
helmet13.rating=4;
helmet13.customerReview="Comfortable";
helmet13.manufactureDate="02-02-2026";
helmet13.sellerName="MotoZone";
helmet13.isLightWeight=true;
helmet13.isAntiFog=true;
helmet13.strapType="Quick Release";
helmet13.helmetModel="Vega Crux";
helmet13.usageType="Daily Ride";
helmet13.discount=9;

System.out.println("Brand: "+helmet13.brand);
System.out.println("Type: "+helmet13.type);
System.out.println("Colour: "+helmet13.colour);
System.out.println("Price: "+helmet13.price);
System.out.println("Size: "+helmet13.size);
System.out.println("Weight: "+helmet13.weight);
System.out.println("Material: "+helmet13.material);
System.out.println("Full Face: "+helmet13.isFullFace);
System.out.println("ISI Approved: "+helmet13.isISIApproved);
System.out.println("Visor Available: "+helmet13.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet13.isScratchResistant);
System.out.println("Ventilation: "+helmet13.isVentilationAvailable);
System.out.println("Warranty: "+helmet13.warranty);
System.out.println("Country: "+helmet13.countryOfOrigin);
System.out.println("Stock: "+helmet13.stock);
System.out.println("Rating: "+helmet13.rating);
System.out.println("Customer Review: "+helmet13.customerReview);
System.out.println("Manufacture Date: "+helmet13.manufactureDate);
System.out.println("Seller Name: "+helmet13.sellerName);
System.out.println("Light Weight: "+helmet13.isLightWeight);
System.out.println("Anti Fog: "+helmet13.isAntiFog);
System.out.println("Strap Type: "+helmet13.strapType);
System.out.println("Model: "+helmet13.helmetModel);
System.out.println("Usage: "+helmet13.usageType);
System.out.println("Discount: "+helmet13.discount);


Helmet helmet14 = new Helmet();
helmet14.brand="Steelbird";
helmet14.type="Modular";
helmet14.colour="Red";
helmet14.price=2900;
helmet14.size="M";
helmet14.weight=1.35;
helmet14.material="Polycarbonate";
helmet14.isFullFace=true;
helmet14.isISIApproved=true;
helmet14.isVisorAvailable=true;
helmet14.isScratchResistant=true;
helmet14.isVentilationAvailable=true;
helmet14.warranty="2 Years";
helmet14.countryOfOrigin="India";
helmet14.stock=14;
helmet14.rating=4;
helmet14.customerReview="Strong build";
helmet14.manufactureDate="18-01-2026";
helmet14.sellerName="HelmetHub";
helmet14.isLightWeight=true;
helmet14.isAntiFog=true;
helmet14.strapType="Double D Ring";
helmet14.helmetModel="Steelbird SBA 7";
helmet14.usageType="Touring";
helmet14.discount=8;

System.out.println("Brand: "+helmet14.brand);
System.out.println("Type: "+helmet14.type);
System.out.println("Colour: "+helmet14.colour);
System.out.println("Price: "+helmet14.price);
System.out.println("Size: "+helmet14.size);
System.out.println("Weight: "+helmet14.weight);
System.out.println("Material: "+helmet14.material);
System.out.println("Full Face: "+helmet14.isFullFace);
System.out.println("ISI Approved: "+helmet14.isISIApproved);
System.out.println("Visor Available: "+helmet14.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet14.isScratchResistant);
System.out.println("Ventilation: "+helmet14.isVentilationAvailable);
System.out.println("Warranty: "+helmet14.warranty);
System.out.println("Country: "+helmet14.countryOfOrigin);
System.out.println("Stock: "+helmet14.stock);
System.out.println("Rating: "+helmet14.rating);
System.out.println("Customer Review: "+helmet14.customerReview);
System.out.println("Manufacture Date: "+helmet14.manufactureDate);
System.out.println("Seller Name: "+helmet14.sellerName);
System.out.println("Light Weight: "+helmet14.isLightWeight);
System.out.println("Anti Fog: "+helmet14.isAntiFog);
System.out.println("Strap Type: "+helmet14.strapType);
System.out.println("Model: "+helmet14.helmetModel);
System.out.println("Usage: "+helmet14.usageType);
System.out.println("Discount: "+helmet14.discount);


Helmet helmet15 = new Helmet();
helmet15.brand="LS2";
helmet15.type="Full Face";
helmet15.colour="Yellow";
helmet15.price=4800;
helmet15.size="L";
helmet15.weight=1.45;
helmet15.material="Carbon Fiber";
helmet15.isFullFace=true;
helmet15.isISIApproved=true;
helmet15.isVisorAvailable=true;
helmet15.isScratchResistant=true;
helmet15.isVentilationAvailable=true;
helmet15.warranty="3 Years";
helmet15.countryOfOrigin="Spain";
helmet15.stock=8;
helmet15.rating=5;
helmet15.customerReview="Premium helmet";
helmet15.manufactureDate="12-02-2026";
helmet15.sellerName="ProStore";
helmet15.isLightWeight=true;
helmet15.isAntiFog=true;
helmet15.strapType="Double D Ring";
helmet15.helmetModel="LS2 Rapid";
helmet15.usageType="Racing";
helmet15.discount=14;

System.out.println("Brand: "+helmet15.brand);
System.out.println("Type: "+helmet15.type);
System.out.println("Colour: "+helmet15.colour);
System.out.println("Price: "+helmet15.price);
System.out.println("Size: "+helmet15.size);
System.out.println("Weight: "+helmet15.weight);
System.out.println("Material: "+helmet15.material);
System.out.println("Full Face: "+helmet15.isFullFace);
System.out.println("ISI Approved: "+helmet15.isISIApproved);
System.out.println("Visor Available: "+helmet15.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet15.isScratchResistant);
System.out.println("Ventilation: "+helmet15.isVentilationAvailable);
System.out.println("Warranty: "+helmet15.warranty);
System.out.println("Country: "+helmet15.countryOfOrigin);
System.out.println("Stock: "+helmet15.stock);
System.out.println("Rating: "+helmet15.rating);
System.out.println("Customer Review: "+helmet15.customerReview);
System.out.println("Manufacture Date: "+helmet15.manufactureDate);
System.out.println("Seller Name: "+helmet15.sellerName);
System.out.println("Light Weight: "+helmet15.isLightWeight);
System.out.println("Anti Fog: "+helmet15.isAntiFog);
System.out.println("Strap Type: "+helmet15.strapType);
System.out.println("Model: "+helmet15.helmetModel);
System.out.println("Usage: "+helmet15.usageType);
System.out.println("Discount: "+helmet15.discount);


Helmet helmet16 = new Helmet();
helmet16.brand="Royal Enfield";
helmet16.type="Half Face";
helmet16.colour="Brown";
helmet16.price=3100;
helmet16.size="M";
helmet16.weight=1.25;
helmet16.material="ABS";
helmet16.isFullFace=false;
helmet16.isISIApproved=true;
helmet16.isVisorAvailable=true;
helmet16.isScratchResistant=true;
helmet16.isVentilationAvailable=true;
helmet16.warranty="2 Years";
helmet16.countryOfOrigin="India";
helmet16.stock=16;
helmet16.rating=4;
helmet16.customerReview="Classic helmet";
helmet16.manufactureDate="01-02-2026";
helmet16.sellerName="RE Store";
helmet16.isLightWeight=true;
helmet16.isAntiFog=false;
helmet16.strapType="Quick Release";
helmet16.helmetModel="RE Street";
helmet16.usageType="Cruising";
helmet16.discount=10;

System.out.println("Brand: "+helmet16.brand);
System.out.println("Type: "+helmet16.type);
System.out.println("Colour: "+helmet16.colour);
System.out.println("Price: "+helmet16.price);
System.out.println("Size: "+helmet16.size);
System.out.println("Weight: "+helmet16.weight);
System.out.println("Material: "+helmet16.material);
System.out.println("Full Face: "+helmet16.isFullFace);
System.out.println("ISI Approved: "+helmet16.isISIApproved);
System.out.println("Visor Available: "+helmet16.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet16.isScratchResistant);
System.out.println("Ventilation: "+helmet16.isVentilationAvailable);
System.out.println("Warranty: "+helmet16.warranty);
System.out.println("Country: "+helmet16.countryOfOrigin);
System.out.println("Stock: "+helmet16.stock);
System.out.println("Rating: "+helmet16.rating);
System.out.println("Customer Review: "+helmet16.customerReview);
System.out.println("Manufacture Date: "+helmet16.manufactureDate);
System.out.println("Seller Name: "+helmet16.sellerName);
System.out.println("Light Weight: "+helmet16.isLightWeight);
System.out.println("Anti Fog: "+helmet16.isAntiFog);
System.out.println("Strap Type: "+helmet16.strapType);
System.out.println("Model: "+helmet16.helmetModel);
System.out.println("Usage: "+helmet16.usageType);
System.out.println("Discount: "+helmet16.discount);


Helmet helmet17 = new Helmet();
helmet17.brand="Axor";
helmet17.type="Full Face";
helmet17.colour="Green";
helmet17.price=3400;
helmet17.size="L";
helmet17.weight=1.38;
helmet17.material="Fiber";
helmet17.isFullFace=true;
helmet17.isISIApproved=true;
helmet17.isVisorAvailable=true;
helmet17.isScratchResistant=true;
helmet17.isVentilationAvailable=true;
helmet17.warranty="2 Years";
helmet17.countryOfOrigin="India";
helmet17.stock=12;
helmet17.rating=5;
helmet17.customerReview="Excellent safety";
helmet17.manufactureDate="14-02-2026";
helmet17.sellerName="MotoStore";
helmet17.isLightWeight=true;
helmet17.isAntiFog=true;
helmet17.strapType="Double D Ring";
helmet17.helmetModel="Axor Rage";
helmet17.usageType="Racing";
helmet17.discount=12;

System.out.println("Brand: "+helmet17.brand);
System.out.println("Type: "+helmet17.type);
System.out.println("Colour: "+helmet17.colour);
System.out.println("Price: "+helmet17.price);
System.out.println("Size: "+helmet17.size);
System.out.println("Weight: "+helmet17.weight);
System.out.println("Material: "+helmet17.material);
System.out.println("Full Face: "+helmet17.isFullFace);
System.out.println("ISI Approved: "+helmet17.isISIApproved);
System.out.println("Visor Available: "+helmet17.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet17.isScratchResistant);
System.out.println("Ventilation: "+helmet17.isVentilationAvailable);
System.out.println("Warranty: "+helmet17.warranty);
System.out.println("Country: "+helmet17.countryOfOrigin);
System.out.println("Stock: "+helmet17.stock);
System.out.println("Rating: "+helmet17.rating);
System.out.println("Customer Review: "+helmet17.customerReview);
System.out.println("Manufacture Date: "+helmet17.manufactureDate);
System.out.println("Seller Name: "+helmet17.sellerName);
System.out.println("Light Weight: "+helmet17.isLightWeight);
System.out.println("Anti Fog: "+helmet17.isAntiFog);
System.out.println("Strap Type: "+helmet17.strapType);
System.out.println("Model: "+helmet17.helmetModel);
System.out.println("Usage: "+helmet17.usageType);
System.out.println("Discount: "+helmet17.discount);


Helmet helmet18 = new Helmet();
helmet18.brand="Studds";
helmet18.type="Open Face";
helmet18.colour="White";
helmet18.price=1700;
helmet18.size="M";
helmet18.weight=1.2;
helmet18.material="ABS";
helmet18.isFullFace=false;
helmet18.isISIApproved=true;
helmet18.isVisorAvailable=true;
helmet18.isScratchResistant=false;
helmet18.isVentilationAvailable=true;
helmet18.warranty="1 Year";
helmet18.countryOfOrigin="India";
helmet18.stock=20;
helmet18.rating=4;
helmet18.customerReview="Nice design";
helmet18.manufactureDate="08-01-2026";
helmet18.sellerName="BikeShop";
helmet18.isLightWeight=true;
helmet18.isAntiFog=false;
helmet18.strapType="Quick Release";
helmet18.helmetModel="Studds Urban";
helmet18.usageType="City Ride";
helmet18.discount=6;

System.out.println("Brand: "+helmet18.brand);
System.out.println("Type: "+helmet18.type);
System.out.println("Colour: "+helmet18.colour);
System.out.println("Price: "+helmet18.price);
System.out.println("Size: "+helmet18.size);
System.out.println("Weight: "+helmet18.weight);
System.out.println("Material: "+helmet18.material);
System.out.println("Full Face: "+helmet18.isFullFace);
System.out.println("ISI Approved: "+helmet18.isISIApproved);
System.out.println("Visor Available: "+helmet18.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet18.isScratchResistant);
System.out.println("Ventilation: "+helmet18.isVentilationAvailable);
System.out.println("Warranty: "+helmet18.warranty);
System.out.println("Country: "+helmet18.countryOfOrigin);
System.out.println("Stock: "+helmet18.stock);
System.out.println("Rating: "+helmet18.rating);
System.out.println("Customer Review: "+helmet18.customerReview);
System.out.println("Manufacture Date: "+helmet18.manufactureDate);
System.out.println("Seller Name: "+helmet18.sellerName);
System.out.println("Light Weight: "+helmet18.isLightWeight);
System.out.println("Anti Fog: "+helmet18.isAntiFog);
System.out.println("Strap Type: "+helmet18.strapType);
System.out.println("Model: "+helmet18.helmetModel);
System.out.println("Usage: "+helmet18.usageType);
System.out.println("Discount: "+helmet18.discount);


Helmet helmet19 = new Helmet();
helmet19.brand="Vega";
helmet19.type="Full Face";
helmet19.colour="Black";
helmet19.price=2600;
helmet19.size="L";
helmet19.weight=1.3;
helmet19.material="Fiber";
helmet19.isFullFace=true;
helmet19.isISIApproved=true;
helmet19.isVisorAvailable=true;
helmet19.isScratchResistant=true;
helmet19.isVentilationAvailable=true;
helmet19.warranty="1 Year";
helmet19.countryOfOrigin="India";
helmet19.stock=17;
helmet19.rating=4;
helmet19.customerReview="Good helmet";
helmet19.manufactureDate="03-02-2026";
helmet19.sellerName="HelmetMart";
helmet19.isLightWeight=true;
helmet19.isAntiFog=true;
helmet19.strapType="Quick Release";
helmet19.helmetModel="Vega Cliff";
helmet19.usageType="Daily Ride";
helmet19.discount=9;

System.out.println("Brand: "+helmet19.brand);
System.out.println("Type: "+helmet19.type);
System.out.println("Colour: "+helmet19.colour);
System.out.println("Price: "+helmet19.price);
System.out.println("Size: "+helmet19.size);
System.out.println("Weight: "+helmet19.weight);
System.out.println("Material: "+helmet19.material);
System.out.println("Full Face: "+helmet19.isFullFace);
System.out.println("ISI Approved: "+helmet19.isISIApproved);
System.out.println("Visor Available: "+helmet19.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet19.isScratchResistant);
System.out.println("Ventilation: "+helmet19.isVentilationAvailable);
System.out.println("Warranty: "+helmet19.warranty);
System.out.println("Country: "+helmet19.countryOfOrigin);
System.out.println("Stock: "+helmet19.stock);
System.out.println("Rating: "+helmet19.rating);
System.out.println("Customer Review: "+helmet19.customerReview);
System.out.println("Manufacture Date: "+helmet19.manufactureDate);
System.out.println("Seller Name: "+helmet19.sellerName);
System.out.println("Light Weight: "+helmet19.isLightWeight);
System.out.println("Anti Fog: "+helmet19.isAntiFog);
System.out.println("Strap Type: "+helmet19.strapType);
System.out.println("Model: "+helmet19.helmetModel);
System.out.println("Usage: "+helmet19.usageType);
System.out.println("Discount: "+helmet19.discount);


Helmet helmet20 = new Helmet();
helmet20.brand="Steelbird";
helmet20.type="Modular";
helmet20.colour="Orange";
helmet20.price=3000;
helmet20.size="M";
helmet20.weight=1.36;
helmet20.material="Polycarbonate";
helmet20.isFullFace=true;
helmet20.isISIApproved=true;
helmet20.isVisorAvailable=true;
helmet20.isScratchResistant=true;
helmet20.isVentilationAvailable=true;
helmet20.warranty="2 Years";
helmet20.countryOfOrigin="India";
helmet20.stock=13;
helmet20.rating=4;
helmet20.customerReview="Strong helmet";
helmet20.manufactureDate="20-01-2026";
helmet20.sellerName="HelmetWorld";
helmet20.isLightWeight=true;
helmet20.isAntiFog=true;
helmet20.strapType="Double D Ring";
helmet20.helmetModel="Steelbird Air";
helmet20.usageType="Touring";
helmet20.discount=11;

System.out.println("Brand: "+helmet20.brand);
System.out.println("Type: "+helmet20.type);
System.out.println("Colour: "+helmet20.colour);
System.out.println("Price: "+helmet20.price);
System.out.println("Size: "+helmet20.size);
System.out.println("Weight: "+helmet20.weight);
System.out.println("Material: "+helmet20.material);
System.out.println("Full Face: "+helmet20.isFullFace);
System.out.println("ISI Approved: "+helmet20.isISIApproved);
System.out.println("Visor Available: "+helmet20.isVisorAvailable);
System.out.println("Scratch Resistant: "+helmet20.isScratchResistant);
System.out.println("Ventilation: "+helmet20.isVentilationAvailable);
System.out.println("Warranty: "+helmet20.warranty);
System.out.println("Country: "+helmet20.countryOfOrigin);
System.out.println("Stock: "+helmet20.stock);
System.out.println("Rating: "+helmet20.rating);
System.out.println("Customer Review: "+helmet20.customerReview);
System.out.println("Manufacture Date: "+helmet20.manufactureDate);
System.out.println("Seller Name: "+helmet20.sellerName);
System.out.println("Light Weight: "+helmet20.isLightWeight);
System.out.println("Anti Fog: "+helmet20.isAntiFog);
System.out.println("Strap Type: "+helmet20.strapType);
System.out.println("Model: "+helmet20.helmetModel);
System.out.println("Usage: "+helmet20.usageType);
System.out.println("Discount: "+helmet20.discount);
}

}