class KeyBoardExecutor{
   public static void main(String[] args){

	Keyboard keyboard1 = new Keyboard();
	keyboard1.brand = "Logitech";
	keyboard1.model = "K120";
	keyboard1.type = "Membrane";
	keyboard1.connectionType = "USB";
	keyboard1.isMechanical = false;
	keyboard1.isBacklit = false;
	keyboard1.hasNumericKeypad = true;
	keyboard1.isErgonomic = false;
	keyboard1.isGaming = false;
	keyboard1.keySwitchType = "Rubber Dome";
	keyboard1.numberOfKeys = 104;
	keyboard1.colour = "Black";
	keyboard1.layout = "QWERTY";
	keyboard1.weight = 500;
	keyboard1.length = 45.0;
	keyboard1.width = 15.0;
	keyboard1.isWaterResistant = false;
	keyboard1.isWireless = false;
	keyboard1.material = "Plastic";
	keyboard1.countryOfOrigin = "China";
	keyboard1.price = 750;
	keyboard1.quantity = 10;
	keyboard1.customerReview = "Basic and reliable";
	keyboard1.rating = 4;
	keyboard1.isStockAvailable = true;
	keyboard1.warranty = "1 year";

	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard1.brand);
	System.out.println("model : " + keyboard1.model);
	System.out.println("type : " + keyboard1.type);
	System.out.println("connectionType : " + keyboard1.connectionType);
	System.out.println("isMechanical : " + keyboard1.isMechanical);
	System.out.println("isBacklit : " + keyboard1.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard1.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard1.isErgonomic);
	System.out.println("isGaming : " + keyboard1.isGaming);
	System.out.println("keySwitchType : " + keyboard1.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard1.numberOfKeys);
	System.out.println("colour : " + keyboard1.colour);
	System.out.println("layout : " + keyboard1.layout);
	System.out.println("weight : " + keyboard1.weight);
	System.out.println("length : " + keyboard1.length);
	System.out.println("width : " + keyboard1.width);
	System.out.println("isWaterResistant : " + keyboard1.isWaterResistant);
	System.out.println("isWireless : " + keyboard1.isWireless);
	System.out.println("material : " + keyboard1.material);
	System.out.println("countryOfOrigin : " + keyboard1.countryOfOrigin);
	System.out.println("price : " + keyboard1.price);
	System.out.println("quantity : " + keyboard1.quantity);
	System.out.println("customerReview : " + keyboard1.customerReview);
	System.out.println("rating : " + keyboard1.rating);
	System.out.println("isStockAvailable : " + keyboard1.isStockAvailable);
	System.out.println("warranty : " + keyboard1.warranty);

	// ---------------- Keyboard 2 ----------------
	Keyboard keyboard2 = new Keyboard();
	keyboard2.brand = "HP";
	keyboard2.model = "K1500";
	keyboard2.type = "Membrane";
	keyboard2.connectionType = "USB";
	keyboard2.isMechanical = false;
	keyboard2.isBacklit = false;
	keyboard2.hasNumericKeypad = true;
	keyboard2.isErgonomic = false;
	keyboard2.isGaming = false;
	keyboard2.keySwitchType = "Rubber Dome";
	keyboard2.numberOfKeys = 105;
	keyboard2.colour = "Black";
	keyboard2.layout = "QWERTY";
	keyboard2.weight = 510;
	keyboard2.length = 46.0;
	keyboard2.width = 15.2;
	keyboard2.isWaterResistant = false;
	keyboard2.isWireless = false;
	keyboard2.material = "Plastic";
	keyboard2.countryOfOrigin = "China";
	keyboard2.price = 780;
	keyboard2.quantity = 8;
	keyboard2.customerReview = "Comfortable typing experience";
	keyboard2.rating = 4;
	keyboard2.isStockAvailable = true;
	keyboard2.warranty = "1 year";

	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard2.brand);
	System.out.println("model : " + keyboard2.model);
	System.out.println("type : " + keyboard2.type);
	System.out.println("connectionType : " + keyboard2.connectionType);
	System.out.println("isMechanical : " + keyboard2.isMechanical);
	System.out.println("isBacklit : " + keyboard2.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard2.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard2.isErgonomic);
	System.out.println("isGaming : " + keyboard2.isGaming);
	System.out.println("keySwitchType : " + keyboard2.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard2.numberOfKeys);
	System.out.println("colour : " + keyboard2.colour);
	System.out.println("layout : " + keyboard2.layout);
	System.out.println("weight : " + keyboard2.weight);
	System.out.println("length : " + keyboard2.length);
	System.out.println("width : " + keyboard2.width);
	System.out.println("isWaterResistant : " + keyboard2.isWaterResistant);
	System.out.println("isWireless : " + keyboard2.isWireless);
	System.out.println("material : " + keyboard2.material);
	System.out.println("countryOfOrigin : " + keyboard2.countryOfOrigin);
	System.out.println("price : " + keyboard2.price);
	System.out.println("quantity : " + keyboard2.quantity);
	System.out.println("customerReview : " + keyboard2.customerReview);
	System.out.println("rating : " + keyboard2.rating);
	System.out.println("isStockAvailable : " + keyboard2.isStockAvailable);
	System.out.println("warranty : " + keyboard2.warranty);



	// ---------------- Keyboard 3 ----------------
	Keyboard keyboard3 = new Keyboard();
	keyboard3.brand = "Dell";
	keyboard3.model = "KB216";
	keyboard3.type = "Membrane";
	keyboard3.connectionType = "USB";
	keyboard3.isMechanical = false;
	keyboard3.isBacklit = false;
	keyboard3.hasNumericKeypad = true;
	keyboard3.isErgonomic = false;
	keyboard3.isGaming = false;
	keyboard3.keySwitchType = "Rubber Dome";
	keyboard3.numberOfKeys = 104;
	keyboard3.colour = "Black";
	keyboard3.layout = "QWERTY";
	keyboard3.weight = 520;
	keyboard3.length = 45.5;
	keyboard3.width = 15.0;
	keyboard3.isWaterResistant = false;
	keyboard3.isWireless = false;
	keyboard3.material = "Plastic";
	keyboard3.countryOfOrigin = "China";
	keyboard3.price = 800;
	keyboard3.quantity = 7;
	keyboard3.customerReview = "Reliable for daily use";
	keyboard3.rating = 4;
	keyboard3.isStockAvailable = true;
	keyboard3.warranty = "1 year";

	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard3.brand);
	System.out.println("model : " + keyboard3.model);
	System.out.println("type : " + keyboard3.type);
	System.out.println("connectionType : " + keyboard3.connectionType);
	System.out.println("isMechanical : " + keyboard3.isMechanical);
	System.out.println("isBacklit : " + keyboard3.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard3.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard3.isErgonomic);
	System.out.println("isGaming : " + keyboard3.isGaming);
	System.out.println("keySwitchType : " + keyboard3.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard3.numberOfKeys);
	System.out.println("colour : " + keyboard3.colour);
	System.out.println("layout : " + keyboard3.layout);
	System.out.println("weight : " + keyboard3.weight);
	System.out.println("length : " + keyboard3.length);
	System.out.println("width : " + keyboard3.width);
	System.out.println("isWaterResistant : " + keyboard3.isWaterResistant);
	System.out.println("isWireless : " + keyboard3.isWireless);
	System.out.println("material : " + keyboard3.material);
	System.out.println("countryOfOrigin : " + keyboard3.countryOfOrigin);
	System.out.println("price : " + keyboard3.price);
	System.out.println("quantity : " + keyboard3.quantity);
	System.out.println("customerReview : " + keyboard3.customerReview);
	System.out.println("rating : " + keyboard3.rating);
	System.out.println("isStockAvailable : " + keyboard3.isStockAvailable);
	System.out.println("warranty : " + keyboard3.warranty);

	// ---------------- Keyboard 4 ----------------
	Keyboard keyboard4 = new Keyboard();
	keyboard4.brand = "Corsair";
	keyboard4.model = "K55 RGB";
	keyboard4.type = "Membrane";
	keyboard4.connectionType = "USB";
	keyboard4.isMechanical = false;
	keyboard4.isBacklit = true;
	keyboard4.hasNumericKeypad = true;
	keyboard4.isErgonomic = true;
	keyboard4.isGaming = true;
	keyboard4.keySwitchType = "Rubber Dome";
	keyboard4.numberOfKeys = 104;
	keyboard4.colour = "Black with RGB";
	keyboard4.layout = "QWERTY";
	keyboard4.weight = 1200;
	keyboard4.length = 44.0;
	keyboard4.width = 14.0;
	keyboard4.isWaterResistant = true;
	keyboard4.isWireless = false;
	keyboard4.material = "Plastic";
	keyboard4.countryOfOrigin = "China";
	keyboard4.price = 3500;
	keyboard4.quantity = 5;
	keyboard4.customerReview = "Good gaming keyboard with RGB";
	keyboard4.rating = 5;
	keyboard4.isStockAvailable = true;
	keyboard4.warranty = "2 years";

	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard4.brand);
	System.out.println("model : " + keyboard4.model);
	System.out.println("type : " + keyboard4.type);
	System.out.println("connectionType : " + keyboard4.connectionType);
	System.out.println("isMechanical : " + keyboard4.isMechanical);
	System.out.println("isBacklit : " + keyboard4.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard4.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard4.isErgonomic);
	System.out.println("isGaming : " + keyboard4.isGaming);
	System.out.println("keySwitchType : " + keyboard4.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard4.numberOfKeys);
	System.out.println("colour : " + keyboard4.colour);
	System.out.println("layout : " + keyboard4.layout);
	System.out.println("weight : " + keyboard4.weight);
	System.out.println("length : " + keyboard4.length);
	System.out.println("width : " + keyboard4.width);
	System.out.println("isWaterResistant : " + keyboard4.isWaterResistant);
	System.out.println("isWireless : " + keyboard4.isWireless);
	System.out.println("material : " + keyboard4.material);
	System.out.println("countryOfOrigin : " + keyboard4.countryOfOrigin);
	System.out.println("price : " + keyboard4.price);
	System.out.println("quantity : " + keyboard4.quantity);
	System.out.println("customerReview : " + keyboard4.customerReview);
	System.out.println("rating : " + keyboard4.rating);
	System.out.println("isStockAvailable : " + keyboard4.isStockAvailable);
	System.out.println("warranty : " + keyboard4.warranty);



	// ---------------- Keyboard 5 ----------------
	Keyboard keyboard5 = new Keyboard();
	keyboard5.brand = "Corsair";
	keyboard5.model = "K55 RGB";
	keyboard5.type = "Membrane";
	keyboard5.connectionType = "Wired";
	keyboard5.isMechanical = false;
	keyboard5.isBacklit = true;
	keyboard5.hasNumericKeypad = true;
	keyboard5.isErgonomic = true;
	keyboard5.isGaming = true;
	keyboard5.keySwitchType = "Membrane";
	keyboard5.numberOfKeys = 104;
	keyboard5.colour = "Black";
	keyboard5.layout = "QWERTY";
	keyboard5.weight = 800;
	keyboard5.length = 460;
	keyboard5.width = 170;
	keyboard5.isWaterResistant = true;
	keyboard5.isWireless = false;
	keyboard5.material = "Plastic";
	keyboard5.countryOfOrigin = "China";
	keyboard5.price = 4500;
	keyboard5.quantity = 5;
	keyboard5.customerReview = "Excellent gaming keyboard";
	keyboard5.rating = 5;
	keyboard5.isStockAvailable = true;
	keyboard5.warranty = "2 Years";

	// SOP for Keyboard 5
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard5.brand);
	System.out.println("model : " + keyboard5.model);
	System.out.println("type : " + keyboard5.type);
	System.out.println("connectionType : " + keyboard5.connectionType);
	System.out.println("isMechanical : " + keyboard5.isMechanical);
	System.out.println("isBacklit : " + keyboard5.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard5.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard5.isErgonomic);
	System.out.println("isGaming : " + keyboard5.isGaming);
	System.out.println("keySwitchType : " + keyboard5.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard5.numberOfKeys);
	System.out.println("colour : " + keyboard5.colour);
	System.out.println("layout : " + keyboard5.layout);
	System.out.println("weight : " + keyboard5.weight);
	System.out.println("length : " + keyboard5.length);
	System.out.println("width : " + keyboard5.width);
	System.out.println("isWaterResistant : " + keyboard5.isWaterResistant);
	System.out.println("isWireless : " + keyboard5.isWireless);
	System.out.println("material : " + keyboard5.material);
	System.out.println("countryOfOrigin : " + keyboard5.countryOfOrigin);
	System.out.println("price : " + keyboard5.price);
	System.out.println("quantity : " + keyboard5.quantity);
	System.out.println("customerReview : " + keyboard5.customerReview);
	System.out.println("rating : " + keyboard5.rating);
	System.out.println("isStockAvailable : " + keyboard5.isStockAvailable);
	System.out.println("warranty : " + keyboard5.warranty);


	// ---------------- Keyboard 6 ----------------
	Keyboard keyboard6 = new Keyboard();
	keyboard6.brand = "Razer";
	keyboard6.model = "BlackWidow";
	keyboard6.type = "Mechanical";
	keyboard6.connectionType = "Wired";
	keyboard6.isMechanical = true;
	keyboard6.isBacklit = true;
	keyboard6.hasNumericKeypad = true;
	keyboard6.isErgonomic = true;
	keyboard6.isGaming = true;
	keyboard6.keySwitchType = "Green Switch";
	keyboard6.numberOfKeys = 105;
	keyboard6.colour = "Black";
	keyboard6.layout = "QWERTY";
	keyboard6.weight = 1000;
	keyboard6.length = 450;
	keyboard6.width = 180;
	keyboard6.isWaterResistant = false;
	keyboard6.isWireless = false;
	keyboard6.material = "Plastic";
	keyboard6.countryOfOrigin = "USA";
	keyboard6.price = 7500;
	keyboard6.quantity = 3;
	keyboard6.customerReview = "Perfect for gaming";
	keyboard6.rating = 5;
	keyboard6.isStockAvailable = true;
	keyboard6.warranty = "2 Years";

	// SOP for Keyboard 6
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard6.brand);
	System.out.println("model : " + keyboard6.model);
	System.out.println("type : " + keyboard6.type);
	System.out.println("connectionType : " + keyboard6.connectionType);
	System.out.println("isMechanical : " + keyboard6.isMechanical);
	System.out.println("isBacklit : " + keyboard6.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard6.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard6.isErgonomic);
	System.out.println("isGaming : " + keyboard6.isGaming);
	System.out.println("keySwitchType : " + keyboard6.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard6.numberOfKeys);
	System.out.println("colour : " + keyboard6.colour);
	System.out.println("layout : " + keyboard6.layout);
	System.out.println("weight : " + keyboard6.weight);
	System.out.println("length : " + keyboard6.length);
	System.out.println("width : " + keyboard6.width);
	System.out.println("isWaterResistant : " + keyboard6.isWaterResistant);
	System.out.println("isWireless : " + keyboard6.isWireless);
	System.out.println("material : " + keyboard6.material);
	System.out.println("countryOfOrigin : " + keyboard6.countryOfOrigin);
	System.out.println("price : " + keyboard6.price);
	System.out.println("quantity : " + keyboard6.quantity);
	System.out.println("customerReview : " + keyboard6.customerReview);
	System.out.println("rating : " + keyboard6.rating);
	System.out.println("isStockAvailable : " + keyboard6.isStockAvailable);
	System.out.println("warranty : " + keyboard6.warranty);


	// ---------------- Keyboard 7 ----------------
	Keyboard keyboard7 = new Keyboard();
	keyboard7.brand = "HP";
	keyboard7.model = "K1500";
	keyboard7.type = "Membrane";
	keyboard7.connectionType = "Wired";
	keyboard7.isMechanical = false;
	keyboard7.isBacklit = false;
	keyboard7.hasNumericKeypad = true;
	keyboard7.isErgonomic = false;
	keyboard7.isGaming = false;
	keyboard7.keySwitchType = "Membrane";
	keyboard7.numberOfKeys = 104;
	keyboard7.colour = "Black";
	keyboard7.layout = "QWERTY";
	keyboard7.weight = 600;
	keyboard7.length = 440;
	keyboard7.width = 160;
	keyboard7.isWaterResistant = false;
	keyboard7.isWireless = false;
	keyboard7.material = "Plastic";
	keyboard7.countryOfOrigin = "China";
	keyboard7.price = 1300;
	keyboard7.quantity = 8;
	keyboard7.customerReview = "Standard office keyboard";
	keyboard7.rating = 4;
	keyboard7.isStockAvailable = true;
	keyboard7.warranty = "1 Year";

	// SOP for Keyboard 7
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard7.brand);
	System.out.println("model : " + keyboard7.model);
	System.out.println("type : " + keyboard7.type);
	System.out.println("connectionType : " + keyboard7.connectionType);
	System.out.println("isMechanical : " + keyboard7.isMechanical);
	System.out.println("isBacklit : " + keyboard7.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard7.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard7.isErgonomic);
	System.out.println("isGaming : " + keyboard7.isGaming);
	System.out.println("keySwitchType : " + keyboard7.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard7.numberOfKeys);
	System.out.println("colour : " + keyboard7.colour);
	System.out.println("layout : " + keyboard7.layout);
	System.out.println("weight : " + keyboard7.weight);
	System.out.println("length : " + keyboard7.length);
	System.out.println("width : " + keyboard7.width);
	System.out.println("isWaterResistant : " + keyboard7.isWaterResistant);
	System.out.println("isWireless : " + keyboard7.isWireless);
	System.out.println("material : " + keyboard7.material);
	System.out.println("countryOfOrigin : " + keyboard7.countryOfOrigin);
	System.out.println("price : " + keyboard7.price);
	System.out.println("quantity : " + keyboard7.quantity);
	System.out.println("customerReview : " + keyboard7.customerReview);
	System.out.println("rating : " + keyboard7.rating);
	System.out.println("isStockAvailable : " + keyboard7.isStockAvailable);
	System.out.println("warranty : " + keyboard7.warranty);


	// ---------------- Keyboard 8 ----------------
	Keyboard keyboard8 = new Keyboard();
	keyboard8.brand = "Dell";
	keyboard8.model = "KB216";
	keyboard8.type = "Membrane";
	keyboard8.connectionType = "Wired";
	keyboard8.isMechanical = false;
	keyboard8.isBacklit = false;
	keyboard8.hasNumericKeypad = true;
	keyboard8.isErgonomic = false;
	keyboard8.isGaming = false;
	keyboard8.keySwitchType = "Membrane";
	keyboard8.numberOfKeys = 104;
	keyboard8.colour = "Black";
	keyboard8.layout = "QWERTY";
	keyboard8.weight = 550;
	keyboard8.length = 430;
	keyboard8.width = 150;
	keyboard8.isWaterResistant = false;
	keyboard8.isWireless = false;
	keyboard8.material = "Plastic";
	keyboard8.countryOfOrigin = "China";
	keyboard8.price = 1400;
	keyboard8.quantity = 6;
	keyboard8.customerReview = "Reliable for daily use";
	keyboard8.rating = 4;
	keyboard8.isStockAvailable = true;
	keyboard8.warranty = "1 Year";

	// SOP for Keyboard 8
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard8.brand);
	System.out.println("model : " + keyboard8.model);
	System.out.println("type : " + keyboard8.type);
	System.out.println("connectionType : " + keyboard8.connectionType);
	System.out.println("isMechanical : " + keyboard8.isMechanical);
	System.out.println("isBacklit : " + keyboard8.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard8.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard8.isErgonomic);
	System.out.println("isGaming : " + keyboard8.isGaming);
	System.out.println("keySwitchType : " + keyboard8.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard8.numberOfKeys);
	System.out.println("colour : " + keyboard8.colour);
	System.out.println("layout : " + keyboard8.layout);
	System.out.println("weight : " + keyboard8.weight);
	System.out.println("length : " + keyboard8.length);
	System.out.println("width : " + keyboard8.width);
	System.out.println("isWaterResistant : " + keyboard8.isWaterResistant);
	System.out.println("isWireless : " + keyboard8.isWireless);
	System.out.println("material : " + keyboard8.material);
	System.out.println("countryOfOrigin : " + keyboard8.countryOfOrigin);
	System.out.println("price : " + keyboard8.price);
	System.out.println("quantity : " + keyboard8.quantity);
	System.out.println("customerReview : " + keyboard8.customerReview);
	System.out.println("rating : " + keyboard8.rating);
	System.out.println("isStockAvailable : " + keyboard8.isStockAvailable);
	System.out.println("warranty : " + keyboard8.warranty);


	// ---------------- Keyboard 9 ----------------
	Keyboard keyboard9 = new Keyboard();
	keyboard9.brand = "Microsoft";
	keyboard9.model = "Wired Desktop 600";
	keyboard9.type = "Membrane";
	keyboard9.connectionType = "Wired";
	keyboard9.isMechanical = false;
	keyboard9.isBacklit = false;
	keyboard9.hasNumericKeypad = true;
	keyboard9.isErgonomic = true;
	keyboard9.isGaming = false;
	keyboard9.keySwitchType = "Membrane";
	keyboard9.numberOfKeys = 104;
	keyboard9.colour = "Black";
	keyboard9.layout = "QWERTY";
	keyboard9.weight = 580;
	keyboard9.length = 440;
	keyboard9.width = 160;
	keyboard9.isWaterResistant = true;
	keyboard9.isWireless = false;
	keyboard9.material = "Plastic";
	keyboard9.countryOfOrigin = "China";
	keyboard9.price = 1800;
	keyboard9.quantity = 4;
	keyboard9.customerReview = "Comfortable typing";
	keyboard9.rating = 4;
	keyboard9.isStockAvailable = true;
	keyboard9.warranty = "1 Year";

	// SOP for Keyboard 9
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard9.brand);
	System.out.println("model : " + keyboard9.model);
	System.out.println("type : " + keyboard9.type);
	System.out.println("connectionType : " + keyboard9.connectionType);
	System.out.println("isMechanical : " + keyboard9.isMechanical);
	System.out.println("isBacklit : " + keyboard9.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard9.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard9.isErgonomic);
	System.out.println("isGaming : " + keyboard9.isGaming);
	System.out.println("keySwitchType : " + keyboard9.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard9.numberOfKeys);
	System.out.println("colour : " + keyboard9.colour);
	System.out.println("layout : " + keyboard9.layout);
	System.out.println("weight : " + keyboard9.weight);
	System.out.println("length : " + keyboard9.length);
	System.out.println("width : " + keyboard9.width);
	System.out.println("isWaterResistant : " + keyboard9.isWaterResistant);
	System.out.println("isWireless : " + keyboard9.isWireless);
	System.out.println("material : " + keyboard9.material);
	System.out.println("countryOfOrigin : " + keyboard9.countryOfOrigin);
	System.out.println("price : " + keyboard9.price);
	System.out.println("quantity : " + keyboard9.quantity);
	System.out.println("customerReview : " + keyboard9.customerReview);
	System.out.println("rating : " + keyboard9.rating);
	System.out.println("isStockAvailable : " + keyboard9.isStockAvailable);
	System.out.println("warranty : " + keyboard9.warranty);


	// ---------------- Keyboard 10 ----------------
	Keyboard keyboard10 = new Keyboard();
	keyboard10.brand = "Logitech";
	keyboard10.model = "K120";
	keyboard10.type = "Membrane";
	keyboard10.connectionType = "Wired";
	keyboard10.isMechanical = false;
	keyboard10.isBacklit = false;
	keyboard10.hasNumericKeypad = true;
	keyboard10.isErgonomic = false;
	keyboard10.isGaming = false;
	keyboard10.keySwitchType = "Membrane";
	keyboard10.numberOfKeys = 104;
	keyboard10.colour = "Black";
	keyboard10.layout = "QWERTY";
	keyboard10.weight = 500;
	keyboard10.length = 450;
	keyboard10.width = 150;
	keyboard10.isWaterResistant = false;
	keyboard10.isWireless = false;
	keyboard10.material = "Plastic";
	keyboard10.countryOfOrigin = "China";
	keyboard10.price = 1200;
	keyboard10.quantity = 10;
	keyboard10.customerReview = "Good basic keyboard";
	keyboard10.rating = 4;
	keyboard10.isStockAvailable = true;
	keyboard10.warranty = "1 Year";

	// SOP for Keyboard 10
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard10.brand);
	System.out.println("model : " + keyboard10.model);
	System.out.println("type : " + keyboard10.type);
	System.out.println("connectionType : " + keyboard10.connectionType);
	System.out.println("isMechanical : " + keyboard10.isMechanical);
	System.out.println("isBacklit : " + keyboard10.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard10.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard10.isErgonomic);
	System.out.println("isGaming : " + keyboard10.isGaming);
	System.out.println("keySwitchType : " + keyboard10.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard10.numberOfKeys);
	System.out.println("colour : " + keyboard10.colour);
	System.out.println("layout : " + keyboard10.layout);
	System.out.println("weight : " + keyboard10.weight);
	System.out.println("length : " + keyboard10.length);
	System.out.println("width : " + keyboard10.width);
	System.out.println("isWaterResistant : " + keyboard10.isWaterResistant);
	System.out.println("isWireless : " + keyboard10.isWireless);
	System.out.println("material : " + keyboard10.material);
	System.out.println("countryOfOrigin : " + keyboard10.countryOfOrigin);
	System.out.println("price : " + keyboard10.price);
	System.out.println("quantity : " + keyboard10.quantity);
	System.out.println("customerReview : " + keyboard10.customerReview);
	System.out.println("rating : " + keyboard10.rating);
	System.out.println("isStockAvailable : " + keyboard10.isStockAvailable);
	System.out.println("warranty : " + keyboard10.warranty);


	// ---------------- Keyboard 11 ----------------
	Keyboard keyboard11 = new Keyboard();
	keyboard11.brand = "HyperX";
	keyboard11.model = "Alloy FPS";
	keyboard11.type = "Mechanical";
	keyboard11.connectionType = "Wired";
	keyboard11.isMechanical = true;
	keyboard11.isBacklit = true;
	keyboard11.hasNumericKeypad = false;
	keyboard11.isErgonomic = true;
	keyboard11.isGaming = true;
	keyboard11.keySwitchType = "Red Switch";
	keyboard11.numberOfKeys = 87;
	keyboard11.colour = "Black";
	keyboard11.layout = "QWERTY";
	keyboard11.weight = 900;
	keyboard11.length = 360;
	keyboard11.width = 140;
	keyboard11.isWaterResistant = false;
	keyboard11.isWireless = false;
	keyboard11.material = "Metal + Plastic";
	keyboard11.countryOfOrigin = "China";
	keyboard11.price = 6500;
	keyboard11.quantity = 4;
	keyboard11.customerReview = "Compact and responsive";
	keyboard11.rating = 5;
	keyboard11.isStockAvailable = true;
	keyboard11.warranty = "2 Years";

	// SOP for Keyboard 11
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard11.brand);
	System.out.println("model : " + keyboard11.model);
	System.out.println("type : " + keyboard11.type);
	System.out.println("connectionType : " + keyboard11.connectionType);
	System.out.println("isMechanical : " + keyboard11.isMechanical);
	System.out.println("isBacklit : " + keyboard11.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard11.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard11.isErgonomic);
	System.out.println("isGaming : " + keyboard11.isGaming);
	System.out.println("keySwitchType : " + keyboard11.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard11.numberOfKeys);
	System.out.println("colour : " + keyboard11.colour);
	System.out.println("layout : " + keyboard11.layout);
	System.out.println("weight : " + keyboard11.weight);
	System.out.println("length : " + keyboard11.length);
	System.out.println("width : " + keyboard11.width);
	System.out.println("isWaterResistant : " + keyboard11.isWaterResistant);
	System.out.println("isWireless : " + keyboard11.isWireless);
	System.out.println("material : " + keyboard11.material);
	System.out.println("countryOfOrigin : " + keyboard11.countryOfOrigin);
	System.out.println("price : " + keyboard11.price);
	System.out.println("quantity : " + keyboard11.quantity);
	System.out.println("customerReview : " + keyboard11.customerReview);
	System.out.println("rating : " + keyboard11.rating);
	System.out.println("isStockAvailable : " + keyboard11.isStockAvailable);
	System.out.println("warranty : " + keyboard11.warranty);


	// ---------------- Keyboard 12 ----------------
	Keyboard keyboard12 = new Keyboard();
	keyboard12.brand = "SteelSeries";
	keyboard12.model = "Apex 3";
	keyboard12.type = "Membrane";
	keyboard12.connectionType = "Wired";
	keyboard12.isMechanical = false;
	keyboard12.isBacklit = true;
	keyboard12.hasNumericKeypad = true;
	keyboard12.isErgonomic = true;
	keyboard12.isGaming = true;
	keyboard12.keySwitchType = "Membrane";
	keyboard12.numberOfKeys = 104;
	keyboard12.colour = "Black";
	keyboard12.layout = "QWERTY";
	keyboard12.weight = 800;
	keyboard12.length = 460;
	keyboard12.width = 160;
	keyboard12.isWaterResistant = true;
	keyboard12.isWireless = false;
	keyboard12.material = "Plastic";
	keyboard12.countryOfOrigin = "China";
	keyboard12.price = 5500;
	keyboard12.quantity = 5;
	keyboard12.customerReview = "Silent and smooth typing";
	keyboard12.rating = 5;
	keyboard12.isStockAvailable = true;
	keyboard12.warranty = "2 Years";

	// SOP for Keyboard 12
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard12.brand);
	System.out.println("model : " + keyboard12.model);
	System.out.println("type : " + keyboard12.type);
	System.out.println("connectionType : " + keyboard12.connectionType);
	System.out.println("isMechanical : " + keyboard12.isMechanical);
	System.out.println("isBacklit : " + keyboard12.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard12.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard12.isErgonomic);
	System.out.println("isGaming : " + keyboard12.isGaming);
	System.out.println("keySwitchType : " + keyboard12.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard12.numberOfKeys);
	System.out.println("colour : " + keyboard12.colour);
	System.out.println("layout : " + keyboard12.layout);
	System.out.println("weight : " + keyboard12.weight);
	System.out.println("length : " + keyboard12.length);
	System.out.println("width : " + keyboard12.width);
	System.out.println("isWaterResistant : " + keyboard12.isWaterResistant);
	System.out.println("isWireless : " + keyboard12.isWireless);
	System.out.println("material : " + keyboard12.material);
	System.out.println("countryOfOrigin : " + keyboard12.countryOfOrigin);
	System.out.println("price : " + keyboard12.price);
	System.out.println("quantity : " + keyboard12.quantity);
	System.out.println("customerReview : " + keyboard12.customerReview);
	System.out.println("rating : " + keyboard12.rating);
	System.out.println("isStockAvailable : " + keyboard12.isStockAvailable);
	System.out.println("warranty : " + keyboard12.warranty);


	// ---------------- Keyboard 13 ----------------
	Keyboard keyboard13 = new Keyboard();
	keyboard13.brand = "Razer";
	keyboard13.model = "Huntsman Mini";
	keyboard13.type = "Mechanical";
	keyboard13.connectionType = "Wired";
	keyboard13.isMechanical = true;
	keyboard13.isBacklit = true;
	keyboard13.hasNumericKeypad = false;
	keyboard13.isErgonomic = true;
	keyboard13.isGaming = true;
	keyboard13.keySwitchType = "Optical Switch";
	keyboard13.numberOfKeys = 60;
	keyboard13.colour = "Black";
	keyboard13.layout = "QWERTY";
	keyboard13.weight = 700;
	keyboard13.length = 300;
	keyboard13.width = 100;
	keyboard13.isWaterResistant = false;
	keyboard13.isWireless = false;
	keyboard13.material = "Metal + Plastic";
	keyboard13.countryOfOrigin = "China";
	keyboard13.price = 8500;
	keyboard13.quantity = 2;
	keyboard13.customerReview = "Very compact and fast";
	keyboard13.rating = 5;
	keyboard13.isStockAvailable = true;
	keyboard13.warranty = "2 Years";

	// SOP for Keyboard 13
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard13.brand);
	System.out.println("model : " + keyboard13.model);
	System.out.println("type : " + keyboard13.type);
	System.out.println("connectionType : " + keyboard13.connectionType);
	System.out.println("isMechanical : " + keyboard13.isMechanical);
	System.out.println("isBacklit : " + keyboard13.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard13.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard13.isErgonomic);
	System.out.println("isGaming : " + keyboard13.isGaming);
	System.out.println("keySwitchType : " + keyboard13.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard13.numberOfKeys);
	System.out.println("colour : " + keyboard13.colour);
	System.out.println("layout : " + keyboard13.layout);
	System.out.println("weight : " + keyboard13.weight);
	System.out.println("length : " + keyboard13.length);
	System.out.println("width : " + keyboard13.width);
	System.out.println("isWaterResistant : " + keyboard13.isWaterResistant);
	System.out.println("isWireless : " + keyboard13.isWireless);
	System.out.println("material : " + keyboard13.material);
	System.out.println("countryOfOrigin : " + keyboard13.countryOfOrigin);
	System.out.println("price : " + keyboard13.price);
	System.out.println("quantity : " + keyboard13.quantity);
	System.out.println("customerReview : " + keyboard13.customerReview);
	System.out.println("rating : " + keyboard13.rating);
	System.out.println("isStockAvailable : " + keyboard13.isStockAvailable);
	System.out.println("warranty : " + keyboard13.warranty);



	// ---------------- Keyboard 14 ----------------
	Keyboard keyboard14 = new Keyboard();
	keyboard14.brand = "Logitech";
	keyboard14.model = "G213 Prodigy";
	keyboard14.type = "Membrane";
	keyboard14.connectionType = "Wired";
	keyboard14.isMechanical = false;
	keyboard14.isBacklit = true;
	keyboard14.hasNumericKeypad = true;
	keyboard14.isErgonomic = true;
	keyboard14.isGaming = true;
	keyboard14.keySwitchType = "Membrane";
	keyboard14.numberOfKeys = 104;
	keyboard14.colour = "Black";
	keyboard14.layout = "QWERTY";
	keyboard14.weight = 900;
	keyboard14.length = 450;
	keyboard14.width = 150;
	keyboard14.isWaterResistant = true;
	keyboard14.isWireless = false;
	keyboard14.material = "Plastic";
	keyboard14.countryOfOrigin = "China";
	keyboard14.price = 6000;
	keyboard14.quantity = 3;
	keyboard14.customerReview = "Good for gaming and typing";
	keyboard14.rating = 5;
	keyboard14.isStockAvailable = true;
	keyboard14.warranty = "2 Years";

	// SOP for Keyboard 14
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard14.brand);
	System.out.println("model : " + keyboard14.model);
	System.out.println("type : " + keyboard14.type);
	System.out.println("connectionType : " + keyboard14.connectionType);
	System.out.println("isMechanical : " + keyboard14.isMechanical);
	System.out.println("isBacklit : " + keyboard14.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard14.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard14.isErgonomic);
	System.out.println("isGaming : " + keyboard14.isGaming);
	System.out.println("keySwitchType : " + keyboard14.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard14.numberOfKeys);
	System.out.println("colour : " + keyboard14.colour);
	System.out.println("layout : " + keyboard14.layout);
	System.out.println("weight : " + keyboard14.weight);
	System.out.println("length : " + keyboard14.length);
	System.out.println("width : " + keyboard14.width);
	System.out.println("isWaterResistant : " + keyboard14.isWaterResistant);
	System.out.println("isWireless : " + keyboard14.isWireless);
	System.out.println("material : " + keyboard14.material);
	System.out.println("countryOfOrigin : " + keyboard14.countryOfOrigin);
	System.out.println("price : " + keyboard14.price);
	System.out.println("quantity : " + keyboard14.quantity);
	System.out.println("customerReview : " + keyboard14.customerReview);
	System.out.println("rating : " + keyboard14.rating);
	System.out.println("isStockAvailable : " + keyboard14.isStockAvailable);
	System.out.println("warranty : " + keyboard14.warranty);


	// ---------------- Keyboard 15 ----------------
	Keyboard keyboard15 = new Keyboard();
	keyboard15.brand = "Corsair";
	keyboard15.model = "K55 RGB";
	keyboard15.type = "Membrane";
	keyboard15.connectionType = "Wired";
	keyboard15.isMechanical = false;
	keyboard15.isBacklit = true;
	keyboard15.hasNumericKeypad = true;
	keyboard15.isErgonomic = true;
	keyboard15.isGaming = true;
	keyboard15.keySwitchType = "Membrane";
	keyboard15.numberOfKeys = 104;
	keyboard15.colour = "Black";
	keyboard15.layout = "QWERTY";
	keyboard15.weight = 850;
	keyboard15.length = 440;
	keyboard15.width = 145;
	keyboard15.isWaterResistant = false;
	keyboard15.isWireless = false;
	keyboard15.material = "Plastic";
	keyboard15.countryOfOrigin = "China";
	keyboard15.price = 5200;
	keyboard15.quantity = 4;
	keyboard15.customerReview = "Good RGB effects";
	keyboard15.rating = 4;
	keyboard15.isStockAvailable = true;
	keyboard15.warranty = "2 Years";

	// SOP for Keyboard 15
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard15.brand);
	System.out.println("model : " + keyboard15.model);
	System.out.println("type : " + keyboard15.type);
	System.out.println("connectionType : " + keyboard15.connectionType);
	System.out.println("isMechanical : " + keyboard15.isMechanical);
	System.out.println("isBacklit : " + keyboard15.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard15.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard15.isErgonomic);
	System.out.println("isGaming : " + keyboard15.isGaming);
	System.out.println("keySwitchType : " + keyboard15.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard15.numberOfKeys);
	System.out.println("colour : " + keyboard15.colour);
	System.out.println("layout : " + keyboard15.layout);
	System.out.println("weight : " + keyboard15.weight);
	System.out.println("length : " + keyboard15.length);
	System.out.println("width : " + keyboard15.width);
	System.out.println("isWaterResistant : " + keyboard15.isWaterResistant);
	System.out.println("isWireless : " + keyboard15.isWireless);
	System.out.println("material : " + keyboard15.material);
	System.out.println("countryOfOrigin : " + keyboard15.countryOfOrigin);
	System.out.println("price : " + keyboard15.price);
	System.out.println("quantity : " + keyboard15.quantity);
	System.out.println("customerReview : " + keyboard15.customerReview);
	System.out.println("rating : " + keyboard15.rating);
	System.out.println("isStockAvailable : " + keyboard15.isStockAvailable);
	System.out.println("warranty : " + keyboard15.warranty);


	// ---------------- Keyboard 16 ----------------
	Keyboard keyboard16 = new Keyboard();
	keyboard16.brand = "Redragon";
	keyboard16.model = "K552";
	keyboard16.type = "Mechanical";
	keyboard16.connectionType = "Wired";
	keyboard16.isMechanical = true;
	keyboard16.isBacklit = true;
	keyboard16.hasNumericKeypad = false;
	keyboard16.isErgonomic = true;
	keyboard16.isGaming = true;
	keyboard16.keySwitchType = "Outemu Red";
	keyboard16.numberOfKeys = 87;
	keyboard16.colour = "Black";
	keyboard16.layout = "QWERTY";
	keyboard16.weight = 950;
	keyboard16.length = 360;
	keyboard16.width = 135;
	keyboard16.isWaterResistant = false;
	keyboard16.isWireless = false;
	keyboard16.material = "Plastic + Metal";
	keyboard16.countryOfOrigin = "China";
	keyboard16.price = 4500;
	keyboard16.quantity = 3;
	keyboard16.customerReview = "Good mechanical feel";
	keyboard16.rating = 4;
	keyboard16.isStockAvailable = true;
	keyboard16.warranty = "1 Year";

	// SOP for Keyboard 16
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard16.brand);
	System.out.println("model : " + keyboard16.model);
	System.out.println("type : " + keyboard16.type);
	System.out.println("connectionType : " + keyboard16.connectionType);
	System.out.println("isMechanical : " + keyboard16.isMechanical);
	System.out.println("isBacklit : " + keyboard16.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard16.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard16.isErgonomic);
	System.out.println("isGaming : " + keyboard16.isGaming);
	System.out.println("keySwitchType : " + keyboard16.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard16.numberOfKeys);
	System.out.println("colour : " + keyboard16.colour);
	System.out.println("layout : " + keyboard16.layout);
	System.out.println("weight : " + keyboard16.weight);
	System.out.println("length : " + keyboard16.length);
	System.out.println("width : " + keyboard16.width);
	System.out.println("isWaterResistant : " + keyboard16.isWaterResistant);
	System.out.println("isWireless : " + keyboard16.isWireless);
	System.out.println("material : " + keyboard16.material);
	System.out.println("countryOfOrigin : " + keyboard16.countryOfOrigin);
	System.out.println("price : " + keyboard16.price);
	System.out.println("quantity : " + keyboard16.quantity);
	System.out.println("customerReview : " + keyboard16.customerReview);
	System.out.println("rating : " + keyboard16.rating);
	System.out.println("isStockAvailable : " + keyboard16.isStockAvailable);
	System.out.println("warranty : " + keyboard16.warranty);


	// ---------------- Keyboard 17 ----------------
	Keyboard keyboard17 = new Keyboard();
	keyboard17.brand = "ASUS";
	keyboard17.model = "ROG Strix Scope";
	keyboard17.type = "Mechanical";
	keyboard17.connectionType = "Wired";
	keyboard17.isMechanical = true;
	keyboard17.isBacklit = true;
	keyboard17.hasNumericKeypad = true;
	keyboard17.isErgonomic = true;
	keyboard17.isGaming = true;
	keyboard17.keySwitchType = "Cherry MX Red";
	keyboard17.numberOfKeys = 104;
	keyboard17.colour = "Black";
	keyboard17.layout = "QWERTY";
	keyboard17.weight = 1100;
	keyboard17.length = 470;
	keyboard17.width = 165;
	keyboard17.isWaterResistant = false;
	keyboard17.isWireless = false;
	keyboard17.material = "Aluminum + Plastic";
	keyboard17.countryOfOrigin = "China";
	keyboard17.price = 9500;
	keyboard17.quantity = 2;
	keyboard17.customerReview = "Excellent build quality";
	keyboard17.rating = 5;
	keyboard17.isStockAvailable = true;
	keyboard17.warranty = "2 Years";

	// SOP for Keyboard 17
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard17.brand);
	System.out.println("model : " + keyboard17.model);
	System.out.println("type : " + keyboard17.type);
	System.out.println("connectionType : " + keyboard17.connectionType);
	System.out.println("isMechanical : " + keyboard17.isMechanical);
	System.out.println("isBacklit : " + keyboard17.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard17.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard17.isErgonomic);
	System.out.println("isGaming : " + keyboard17.isGaming);
	System.out.println("keySwitchType : " + keyboard17.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard17.numberOfKeys);
	System.out.println("colour : " + keyboard17.colour);
	System.out.println("layout : " + keyboard17.layout);
	System.out.println("weight : " + keyboard17.weight);
	System.out.println("length : " + keyboard17.length);
	System.out.println("width : " + keyboard17.width);
	System.out.println("isWaterResistant : " + keyboard17.isWaterResistant);
	System.out.println("isWireless : " + keyboard17.isWireless);
	System.out.println("material : " + keyboard17.material);
	System.out.println("countryOfOrigin : " + keyboard17.countryOfOrigin);
	System.out.println("price : " + keyboard17.price);
	System.out.println("quantity : " + keyboard17.quantity);
	System.out.println("customerReview : " + keyboard17.customerReview);
	System.out.println("rating : " + keyboard17.rating);
	System.out.println("isStockAvailable : " + keyboard17.isStockAvailable);
	System.out.println("warranty : " + keyboard17.warranty);




	// ---------------- Keyboard 18 ----------------
	Keyboard keyboard18 = new Keyboard();
	keyboard18.brand = "Cooler Master";
	keyboard18.model = "CK552";
	keyboard18.type = "Mechanical";
	keyboard18.connectionType = "Wired";
	keyboard18.isMechanical = true;
	keyboard18.isBacklit = true;
	keyboard18.hasNumericKeypad = true;
	keyboard18.isErgonomic = true;
	keyboard18.isGaming = true;
	keyboard18.keySwitchType = "Gateron Red";
	keyboard18.numberOfKeys = 104;
	keyboard18.colour = "Black";
	keyboard18.layout = "QWERTY";
	keyboard18.weight = 950;
	keyboard18.length = 450;
	keyboard18.width = 160;
	keyboard18.isWaterResistant = false;
	keyboard18.isWireless = false;
	keyboard18.material = "Aluminum + Plastic";
	keyboard18.countryOfOrigin = "China";
	keyboard18.price = 7000;
	keyboard18.quantity = 3;
	keyboard18.customerReview = "Good mechanical keyboard for gaming";
	keyboard18.rating = 5;
	keyboard18.isStockAvailable = true;
	keyboard18.warranty = "2 Years";

	// SOP for Keyboard 18
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard18.brand);
	System.out.println("model : " + keyboard18.model);
	System.out.println("type : " + keyboard18.type);
	System.out.println("connectionType : " + keyboard18.connectionType);
	System.out.println("isMechanical : " + keyboard18.isMechanical);
	System.out.println("isBacklit : " + keyboard18.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard18.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard18.isErgonomic);
	System.out.println("isGaming : " + keyboard18.isGaming);
	System.out.println("keySwitchType : " + keyboard18.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard18.numberOfKeys);
	System.out.println("colour : " + keyboard18.colour);
	System.out.println("layout : " + keyboard18.layout);
	System.out.println("weight : " + keyboard18.weight);
	System.out.println("length : " + keyboard18.length);
	System.out.println("width : " + keyboard18.width);
	System.out.println("isWaterResistant : " + keyboard18.isWaterResistant);
	System.out.println("isWireless : " + keyboard18.isWireless);
	System.out.println("material : " + keyboard18.material);
	System.out.println("countryOfOrigin : " + keyboard18.countryOfOrigin);
	System.out.println("price : " + keyboard18.price);
	System.out.println("quantity : " + keyboard18.quantity);
	System.out.println("customerReview : " + keyboard18.customerReview);
	System.out.println("rating : " + keyboard18.rating);
	System.out.println("isStockAvailable : " + keyboard18.isStockAvailable);
	System.out.println("warranty : " + keyboard18.warranty);


	// ---------------- Keyboard 19 ----------------
	Keyboard keyboard19 = new Keyboard();
	keyboard19.brand = "Roccat";
	keyboard19.model = "Vulcan 121 AIMO";
	keyboard19.type = "Mechanical";
	keyboard19.connectionType = "Wired";
	keyboard19.isMechanical = true;
	keyboard19.isBacklit = true;
	keyboard19.hasNumericKeypad = true;
	keyboard19.isErgonomic = true;
	keyboard19.isGaming = true;
	keyboard19.keySwitchType = "Titan Switch";
	keyboard19.numberOfKeys = 105;
	keyboard19.colour = "Titanium Grey";
	keyboard19.layout = "QWERTY";
	keyboard19.weight = 1100;
	keyboard19.length = 470;
	keyboard19.width = 170;
	keyboard19.isWaterResistant = false;
	keyboard19.isWireless = false;
	keyboard19.material = "Aluminum + Plastic";
	keyboard19.countryOfOrigin = "China";
	keyboard19.price = 10500;
	keyboard19.quantity = 2;
	keyboard19.customerReview = "Excellent tactile feedback";
	keyboard19.rating = 5;
	keyboard19.isStockAvailable = true;
	keyboard19.warranty = "2 Years";

	// SOP for Keyboard 19
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard19.brand);
	System.out.println("model : " + keyboard19.model);
	System.out.println("type : " + keyboard19.type);
	System.out.println("connectionType : " + keyboard19.connectionType);
	System.out.println("isMechanical : " + keyboard19.isMechanical);
	System.out.println("isBacklit : " + keyboard19.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard19.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard19.isErgonomic);
	System.out.println("isGaming : " + keyboard19.isGaming);
	System.out.println("keySwitchType : " + keyboard19.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard19.numberOfKeys);
	System.out.println("colour : " + keyboard19.colour);
	System.out.println("layout : " + keyboard19.layout);
	System.out.println("weight : " + keyboard19.weight);
	System.out.println("length : " + keyboard19.length);
	System.out.println("width : " + keyboard19.width);
	System.out.println("isWaterResistant : " + keyboard19.isWaterResistant);
	System.out.println("isWireless : " + keyboard19.isWireless);
	System.out.println("material : " + keyboard19.material);
	System.out.println("countryOfOrigin : " + keyboard19.countryOfOrigin);
	System.out.println("price : " + keyboard19.price);
	System.out.println("quantity : " + keyboard19.quantity);
	System.out.println("customerReview : " + keyboard19.customerReview);
	System.out.println("rating : " + keyboard19.rating);
	System.out.println("isStockAvailable : " + keyboard19.isStockAvailable);
	System.out.println("warranty : " + keyboard19.warranty);


	// ---------------- Keyboard 20 ----------------
	Keyboard keyboard20 = new Keyboard();
	keyboard20.brand = "MSI";
	keyboard20.model = "Vigor GK50";
	keyboard20.type = "Mechanical";
	keyboard20.connectionType = "Wired";
	keyboard20.isMechanical = true;
	keyboard20.isBacklit = true;
	keyboard20.hasNumericKeypad = true;
	keyboard20.isErgonomic = true;
	keyboard20.isGaming = true;
	keyboard20.keySwitchType = "Red Switch";
	keyboard20.numberOfKeys = 104;
	keyboard20.colour = "Black";
	keyboard20.layout = "QWERTY";
	keyboard20.weight = 1000;
	keyboard20.length = 460;
	keyboard20.width = 160;
	keyboard20.isWaterResistant = false;
	keyboard20.isWireless = false;
	keyboard20.material = "Aluminum + Plastic";
	keyboard20.countryOfOrigin = "China";
	keyboard20.price = 8500;
	keyboard20.quantity = 3;
	keyboard20.customerReview = "Responsive and durable";
	keyboard20.rating = 5;
	keyboard20.isStockAvailable = true;
	keyboard20.warranty = "2 Years";

	// SOP for Keyboard 20
	System.out.println("after init instance variable");
	System.out.println("brand : " + keyboard20.brand);
	System.out.println("model : " + keyboard20.model);
	System.out.println("type : " + keyboard20.type);
	System.out.println("connectionType : " + keyboard20.connectionType);
	System.out.println("isMechanical : " + keyboard20.isMechanical);
	System.out.println("isBacklit : " + keyboard20.isBacklit);
	System.out.println("hasNumericKeypad : " + keyboard20.hasNumericKeypad);
	System.out.println("isErgonomic : " + keyboard20.isErgonomic);
	System.out.println("isGaming : " + keyboard20.isGaming);
	System.out.println("keySwitchType : " + keyboard20.keySwitchType);
	System.out.println("numberOfKeys : " + keyboard20.numberOfKeys);
	System.out.println("colour : " + keyboard20.colour);
	System.out.println("layout : " + keyboard20.layout);
	System.out.println("weight : " + keyboard20.weight);
	System.out.println("length : " + keyboard20.length);
	System.out.println("width : " + keyboard20.width);
	System.out.println("isWaterResistant : " + keyboard20.isWaterResistant);
	System.out.println("isWireless : " + keyboard20.isWireless);
	System.out.println("material : " + keyboard20.material);
	System.out.println("countryOfOrigin : " + keyboard20.countryOfOrigin);
	System.out.println("price : " + keyboard20.price);
	System.out.println("quantity : " + keyboard20.quantity);
	System.out.println("customerReview : " + keyboard20.customerReview);
	System.out.println("rating : " + keyboard20.rating);
	System.out.println("isStockAvailable : " + keyboard20.isStockAvailable);
	System.out.println("warranty : " + keyboard20.warranty);

	}

	}