class LightBulbExecutor {

    public static void main(String[] args) {

        LightBulb bulb1 = new LightBulb();

        bulb1.brand = "Philips";
        bulb1.type = "LED";
        bulb1.colour = "White";
        bulb1.wattage = 9;
        bulb1.voltage = 220;
        bulb1.price = 120;
        bulb1.material = "Plastic";
        bulb1.isLED = true;
        bulb1.isSmartBulb = false;
        bulb1.isDimmable = false;
        bulb1.isRechargeable = false;
        bulb1.isEnergyEfficient = true;
        bulb1.lifeSpanHours = 15000;
        bulb1.weight = 50;
        bulb1.length = 10;
        bulb1.diameter = 5;
        bulb1.baseType = "B22";
        bulb1.countryOfOrigin = "India";
        bulb1.warranty = "1 Year";
        bulb1.quantity = 20;
        bulb1.isStockAvailable = true;
        bulb1.customerReview = "Good quality";
        bulb1.rating = 5;

        System.out.println("Brand: " + bulb1.brand);
        System.out.println("Type: " + bulb1.type);
        System.out.println("Colour: " + bulb1.colour);
        System.out.println("Wattage: " + bulb1.wattage);
        System.out.println("Voltage: " + bulb1.voltage);
        System.out.println("Price: " + bulb1.price);
        System.out.println("Material: " + bulb1.material);
        System.out.println("LED: " + bulb1.isLED);
        System.out.println("Smart Bulb: " + bulb1.isSmartBulb);
        System.out.println("Dimmable: " + bulb1.isDimmable);
        System.out.println("Rechargeable: " + bulb1.isRechargeable);
        System.out.println("Energy Efficient: " + bulb1.isEnergyEfficient);
        System.out.println("Life Span Hours: " + bulb1.lifeSpanHours);
        System.out.println("Weight: " + bulb1.weight);
        System.out.println("Length: " + bulb1.length);
        System.out.println("Diameter: " + bulb1.diameter);
        System.out.println("Base Type: " + bulb1.baseType);
        System.out.println("Country Of Origin: " + bulb1.countryOfOrigin);
        System.out.println("Warranty: " + bulb1.warranty);
        System.out.println("Quantity: " + bulb1.quantity);
        System.out.println("Stock Available: " + bulb1.isStockAvailable);
        System.out.println("Customer Review: " + bulb1.customerReview);
        System.out.println("Rating: " + bulb1.rating);
    
	LightBulb bulb2 = new LightBulb();
	bulb2.brand = "Havells";
	bulb2.type = "LED";
	bulb2.colour = "Warm White";
	bulb2.wattage = 12;
	bulb2.voltage = 220;
	bulb2.price = 150;
	bulb2.material = "Glass";
	bulb2.isLED = true;
	bulb2.isSmartBulb = false;
	bulb2.isDimmable = true;
	bulb2.isRechargeable = false;
	bulb2.isEnergyEfficient = true;
	bulb2.lifeSpanHours = 20000;
	bulb2.weight = 55;
	bulb2.length = 11;
	bulb2.diameter = 6;
	bulb2.baseType = "E27";
	bulb2.countryOfOrigin = "India";
	bulb2.warranty = "2 Years";
	bulb2.quantity = 15;
	bulb2.isStockAvailable = true;
	bulb2.customerReview = "Very bright";
	bulb2.rating = 4;

	System.out.println("Brand: " + bulb2.brand);
	System.out.println("Type: " + bulb2.type);
	System.out.println("Colour: " + bulb2.colour);
	System.out.println("Wattage: " + bulb2.wattage);
	System.out.println("Voltage: " + bulb2.voltage);
	System.out.println("Price: " + bulb2.price);
	System.out.println("Material: " + bulb2.material);
	System.out.println("LED: " + bulb2.isLED);
	System.out.println("Smart Bulb: " + bulb2.isSmartBulb);
	System.out.println("Dimmable: " + bulb2.isDimmable);
	System.out.println("Rechargeable: " + bulb2.isRechargeable);
	System.out.println("Energy Efficient: " + bulb2.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb2.lifeSpanHours);
	System.out.println("Weight: " + bulb2.weight);
	System.out.println("Length: " + bulb2.length);
	System.out.println("Diameter: " + bulb2.diameter);
	System.out.println("Base Type: " + bulb2.baseType);
	System.out.println("Country Of Origin: " + bulb2.countryOfOrigin);
	System.out.println("Warranty: " + bulb2.warranty);
	System.out.println("Quantity: " + bulb2.quantity);
	System.out.println("Stock Available: " + bulb2.isStockAvailable);
	System.out.println("Customer Review: " + bulb2.customerReview);
	System.out.println("Rating: " + bulb2.rating);


	LightBulb bulb3 = new LightBulb();
	bulb3.brand = "Syska";
	bulb3.type = "LED";
	bulb3.colour = "Cool White";
	bulb3.wattage = 7;
	bulb3.voltage = 220;
	bulb3.price = 110;
	bulb3.material = "Plastic";
	bulb3.isLED = true;
	bulb3.isSmartBulb = false;
	bulb3.isDimmable = false;
	bulb3.isRechargeable = false;
	bulb3.isEnergyEfficient = true;
	bulb3.lifeSpanHours = 18000;
	bulb3.weight = 45;
	bulb3.length = 9;
	bulb3.diameter = 5;
	bulb3.baseType = "B22";
	bulb3.countryOfOrigin = "India";
	bulb3.warranty = "1 Year";
	bulb3.quantity = 10;
	bulb3.isStockAvailable = true;
	bulb3.customerReview = "Nice brightness";
	bulb3.rating = 4;

	System.out.println("Brand: " + bulb3.brand);
	System.out.println("Type: " + bulb3.type);
	System.out.println("Colour: " + bulb3.colour);
	System.out.println("Wattage: " + bulb3.wattage);
	System.out.println("Voltage: " + bulb3.voltage);
	System.out.println("Price: " + bulb3.price);
	System.out.println("Material: " + bulb3.material);
	System.out.println("LED: " + bulb3.isLED);
	System.out.println("Smart Bulb: " + bulb3.isSmartBulb);
	System.out.println("Dimmable: " + bulb3.isDimmable);
	System.out.println("Rechargeable: " + bulb3.isRechargeable);
	System.out.println("Energy Efficient: " + bulb3.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb3.lifeSpanHours);
	System.out.println("Weight: " + bulb3.weight);
	System.out.println("Length: " + bulb3.length);
	System.out.println("Diameter: " + bulb3.diameter);
	System.out.println("Base Type: " + bulb3.baseType);
	System.out.println("Country Of Origin: " + bulb3.countryOfOrigin);
	System.out.println("Warranty: " + bulb3.warranty);
	System.out.println("Quantity: " + bulb3.quantity);
	System.out.println("Stock Available: " + bulb3.isStockAvailable);
	System.out.println("Customer Review: " + bulb3.customerReview);
	System.out.println("Rating: " + bulb3.rating);


	LightBulb bulb4 = new LightBulb();
	bulb4.brand = "Wipro";
	bulb4.type = "LED";
	bulb4.colour = "Warm White";
	bulb4.wattage = 9;
	bulb4.voltage = 220;
	bulb4.price = 130;
	bulb4.material = "Glass";
	bulb4.isLED = true;
	bulb4.isSmartBulb = false;
	bulb4.isDimmable = true;
	bulb4.isRechargeable = false;
	bulb4.isEnergyEfficient = true;
	bulb4.lifeSpanHours = 20000;
	bulb4.weight = 50;
	bulb4.length = 10;
	bulb4.diameter = 6;
	bulb4.baseType = "E27";
	bulb4.countryOfOrigin = "India";
	bulb4.warranty = "2 Years";
	bulb4.quantity = 12;
	bulb4.isStockAvailable = true;
	bulb4.customerReview = "Good product";
	bulb4.rating = 4;

	System.out.println("Brand: " + bulb4.brand);
	System.out.println("Type: " + bulb4.type);
	System.out.println("Colour: " + bulb4.colour);
	System.out.println("Wattage: " + bulb4.wattage);
	System.out.println("Voltage: " + bulb4.voltage);
	System.out.println("Price: " + bulb4.price);
	System.out.println("Material: " + bulb4.material);
	System.out.println("LED: " + bulb4.isLED);
	System.out.println("Smart Bulb: " + bulb4.isSmartBulb);
	System.out.println("Dimmable: " + bulb4.isDimmable);
	System.out.println("Rechargeable: " + bulb4.isRechargeable);
	System.out.println("Energy Efficient: " + bulb4.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb4.lifeSpanHours);
	System.out.println("Weight: " + bulb4.weight);
	System.out.println("Length: " + bulb4.length);
	System.out.println("Diameter: " + bulb4.diameter);
	System.out.println("Base Type: " + bulb4.baseType);
	System.out.println("Country Of Origin: " + bulb4.countryOfOrigin);
	System.out.println("Warranty: " + bulb4.warranty);
	System.out.println("Quantity: " + bulb4.quantity);
	System.out.println("Stock Available: " + bulb4.isStockAvailable);
	System.out.println("Customer Review: " + bulb4.customerReview);
	System.out.println("Rating: " + bulb4.rating);


	LightBulb bulb5 = new LightBulb();
	bulb5.brand = "Bajaj";
	bulb5.type = "LED";
	bulb5.colour = "White";
	bulb5.wattage = 12;
	bulb5.voltage = 220;
	bulb5.price = 160;
	bulb5.material = "Plastic";
	bulb5.isLED = true;
	bulb5.isSmartBulb = false;
	bulb5.isDimmable = false;
	bulb5.isRechargeable = false;
	bulb5.isEnergyEfficient = true;
	bulb5.lifeSpanHours = 22000;
	bulb5.weight = 60;
	bulb5.length = 11;
	bulb5.diameter = 6;
	bulb5.baseType = "B22";
	bulb5.countryOfOrigin = "India";
	bulb5.warranty = "2 Years";
	bulb5.quantity = 18;
	bulb5.isStockAvailable = true;
	bulb5.customerReview = "Very good";
	bulb5.rating = 5;

	System.out.println("Brand: " + bulb5.brand);
	System.out.println("Type: " + bulb5.type);
	System.out.println("Colour: " + bulb5.colour);
	System.out.println("Wattage: " + bulb5.wattage);
	System.out.println("Voltage: " + bulb5.voltage);
	System.out.println("Price: " + bulb5.price);
	System.out.println("Material: " + bulb5.material);
	System.out.println("LED: " + bulb5.isLED);
	System.out.println("Smart Bulb: " + bulb5.isSmartBulb);
	System.out.println("Dimmable: " + bulb5.isDimmable);
	System.out.println("Rechargeable: " + bulb5.isRechargeable);
	System.out.println("Energy Efficient: " + bulb5.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb5.lifeSpanHours);
	System.out.println("Weight: " + bulb5.weight);
	System.out.println("Length: " + bulb5.length);
	System.out.println("Diameter: " + bulb5.diameter);
	System.out.println("Base Type: " + bulb5.baseType);
	System.out.println("Country Of Origin: " + bulb5.countryOfOrigin);
	System.out.println("Warranty: " + bulb5.warranty);
	System.out.println("Quantity: " + bulb5.quantity);
	System.out.println("Stock Available: " + bulb5.isStockAvailable);
	System.out.println("Customer Review: " + bulb5.customerReview);
	System.out.println("Rating: " + bulb5.rating);


	LightBulb bulb6 = new LightBulb();
	bulb6.brand = "Panasonic";
	bulb6.type = "LED";
	bulb6.colour = "Cool White";
	bulb6.wattage = 10;
	bulb6.voltage = 220;
	bulb6.price = 170;
	bulb6.material = "Glass";
	bulb6.isLED = true;
	bulb6.isSmartBulb = false;
	bulb6.isDimmable = true;
	bulb6.isRechargeable = false;
	bulb6.isEnergyEfficient = true;
	bulb6.lifeSpanHours = 25000;
	bulb6.weight = 58;
	bulb6.length = 10;
	bulb6.diameter = 6;
	bulb6.baseType = "E27";
	bulb6.countryOfOrigin = "Japan";
	bulb6.warranty = "2 Years";
	bulb6.quantity = 14;
	bulb6.isStockAvailable = true;
	bulb6.customerReview = "Excellent";
	bulb6.rating = 5;

	System.out.println("Brand: " + bulb6.brand);
	System.out.println("Type: " + bulb6.type);
	System.out.println("Colour: " + bulb6.colour);
	System.out.println("Wattage: " + bulb6.wattage);
	System.out.println("Voltage: " + bulb6.voltage);
	System.out.println("Price: " + bulb6.price);
	System.out.println("Material: " + bulb6.material);
	System.out.println("LED: " + bulb6.isLED);
	System.out.println("Smart Bulb: " + bulb6.isSmartBulb);
	System.out.println("Dimmable: " + bulb6.isDimmable);
	System.out.println("Rechargeable: " + bulb6.isRechargeable);
	System.out.println("Energy Efficient: " + bulb6.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb6.lifeSpanHours);
	System.out.println("Weight: " + bulb6.weight);
	System.out.println("Length: " + bulb6.length);
	System.out.println("Diameter: " + bulb6.diameter);
	System.out.println("Base Type: " + bulb6.baseType);
	System.out.println("Country Of Origin: " + bulb6.countryOfOrigin);
	System.out.println("Warranty: " + bulb6.warranty);
	System.out.println("Quantity: " + bulb6.quantity);
	System.out.println("Stock Available: " + bulb6.isStockAvailable);
	System.out.println("Customer Review: " + bulb6.customerReview);
	System.out.println("Rating: " + bulb6.rating);


	LightBulb bulb7 = new LightBulb();
	bulb7.brand = "Philips";
	bulb7.type = "LED";
	bulb7.colour = "Warm White";
	bulb7.wattage = 8;
	bulb7.voltage = 220;
	bulb7.price = 150;
	bulb7.material = "Plastic";
	bulb7.isLED = true;
	bulb7.isSmartBulb = false;
	bulb7.isDimmable = true;
	bulb7.isRechargeable = false;
	bulb7.isEnergyEfficient = true;
	bulb7.lifeSpanHours = 24000;
	bulb7.weight = 52;
	bulb7.length = 10;
	bulb7.diameter = 6;
	bulb7.baseType = "B22";
	bulb7.countryOfOrigin = "India";
	bulb7.warranty = "2 Years";
	bulb7.quantity = 16;
	bulb7.isStockAvailable = true;
	bulb7.customerReview = "Bright light";
	bulb7.rating = 4;

	System.out.println("Brand: " + bulb7.brand);
	System.out.println("Type: " + bulb7.type);
	System.out.println("Colour: " + bulb7.colour);
	System.out.println("Wattage: " + bulb7.wattage);
	System.out.println("Voltage: " + bulb7.voltage);
	System.out.println("Price: " + bulb7.price);
	System.out.println("Material: " + bulb7.material);
	System.out.println("LED: " + bulb7.isLED);
	System.out.println("Smart Bulb: " + bulb7.isSmartBulb);
	System.out.println("Dimmable: " + bulb7.isDimmable);
	System.out.println("Rechargeable: " + bulb7.isRechargeable);
	System.out.println("Energy Efficient: " + bulb7.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb7.lifeSpanHours);
	System.out.println("Weight: " + bulb7.weight);
	System.out.println("Length: " + bulb7.length);
	System.out.println("Diameter: " + bulb7.diameter);
	System.out.println("Base Type: " + bulb7.baseType);
	System.out.println("Country Of Origin: " + bulb7.countryOfOrigin);
	System.out.println("Warranty: " + bulb7.warranty);
	System.out.println("Quantity: " + bulb7.quantity);
	System.out.println("Stock Available: " + bulb7.isStockAvailable);
	System.out.println("Customer Review: " + bulb7.customerReview);
	System.out.println("Rating: " + bulb7.rating);


	LightBulb bulb8 = new LightBulb();
	bulb8.brand = "Havells";
	bulb8.type = "LED";
	bulb8.colour = "White";
	bulb8.wattage = 9;
	bulb8.voltage = 220;
	bulb8.price = 155;
	bulb8.material = "Glass";
	bulb8.isLED = true;
	bulb8.isSmartBulb = false;
	bulb8.isDimmable = false;
	bulb8.isRechargeable = false;
	bulb8.isEnergyEfficient = true;
	bulb8.lifeSpanHours = 23000;
	bulb8.weight = 55;
	bulb8.length = 10;
	bulb8.diameter = 6;
	bulb8.baseType = "E27";
	bulb8.countryOfOrigin = "India";
	bulb8.warranty = "2 Years";
	bulb8.quantity = 14;
	bulb8.isStockAvailable = true;
	bulb8.customerReview = "Good brightness";
	bulb8.rating = 4;

	System.out.println("Brand: " + bulb8.brand);
	System.out.println("Type: " + bulb8.type);
	System.out.println("Colour: " + bulb8.colour);
	System.out.println("Wattage: " + bulb8.wattage);
	System.out.println("Voltage: " + bulb8.voltage);
	System.out.println("Price: " + bulb8.price);
	System.out.println("Material: " + bulb8.material);
	System.out.println("LED: " + bulb8.isLED);
	System.out.println("Smart Bulb: " + bulb8.isSmartBulb);
	System.out.println("Dimmable: " + bulb8.isDimmable);
	System.out.println("Rechargeable: " + bulb8.isRechargeable);
	System.out.println("Energy Efficient: " + bulb8.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb8.lifeSpanHours);
	System.out.println("Weight: " + bulb8.weight);
	System.out.println("Length: " + bulb8.length);
	System.out.println("Diameter: " + bulb8.diameter);
	System.out.println("Base Type: " + bulb8.baseType);
	System.out.println("Country Of Origin: " + bulb8.countryOfOrigin);
	System.out.println("Warranty: " + bulb8.warranty);
	System.out.println("Quantity: " + bulb8.quantity);
	System.out.println("Stock Available: " + bulb8.isStockAvailable);
	System.out.println("Customer Review: " + bulb8.customerReview);
	System.out.println("Rating: " + bulb8.rating);


	LightBulb bulb9 = new LightBulb();
	bulb9.brand = "Eveready";
	bulb9.type = "LED";
	bulb9.colour = "Cool White";
	bulb9.wattage = 10;
	bulb9.voltage = 220;
	bulb9.price = 140;
	bulb9.material = "Plastic";
	bulb9.isLED = true;
	bulb9.isSmartBulb = false;
	bulb9.isDimmable = false;
	bulb9.isRechargeable = false;
	bulb9.isEnergyEfficient = true;
	bulb9.lifeSpanHours = 21000;
	bulb9.weight = 50;
	bulb9.length = 9;
	bulb9.diameter = 5;
	bulb9.baseType = "B22";
	bulb9.countryOfOrigin = "India";
	bulb9.warranty = "1 Year";
	bulb9.quantity = 11;
	bulb9.isStockAvailable = true;
	bulb9.customerReview = "Affordable";
	bulb9.rating = 4;

	System.out.println("Brand: " + bulb9.brand);
	System.out.println("Type: " + bulb9.type);
	System.out.println("Colour: " + bulb9.colour);
	System.out.println("Wattage: " + bulb9.wattage);
	System.out.println("Voltage: " + bulb9.voltage);
	System.out.println("Price: " + bulb9.price);
	System.out.println("Material: " + bulb9.material);
	System.out.println("LED: " + bulb9.isLED);
	System.out.println("Smart Bulb: " + bulb9.isSmartBulb);
	System.out.println("Dimmable: " + bulb9.isDimmable);
	System.out.println("Rechargeable: " + bulb9.isRechargeable);
	System.out.println("Energy Efficient: " + bulb9.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb9.lifeSpanHours);
	System.out.println("Weight: " + bulb9.weight);
	System.out.println("Length: " + bulb9.length);
	System.out.println("Diameter: " + bulb9.diameter);
	System.out.println("Base Type: " + bulb9.baseType);
	System.out.println("Country Of Origin: " + bulb9.countryOfOrigin);
	System.out.println("Warranty: " + bulb9.warranty);
	System.out.println("Quantity: " + bulb9.quantity);
	System.out.println("Stock Available: " + bulb9.isStockAvailable);
	System.out.println("Customer Review: " + bulb9.customerReview);
	System.out.println("Rating: " + bulb9.rating);


	LightBulb bulb10 = new LightBulb();
	bulb10.brand = "Orient";
	bulb10.type = "LED";
	bulb10.colour = "Warm White";
	bulb10.wattage = 11;
	bulb10.voltage = 220;
	bulb10.price = 165;
	bulb10.material = "Glass";
	bulb10.isLED = true;
	bulb10.isSmartBulb = false;
	bulb10.isDimmable = true;
	bulb10.isRechargeable = false;
	bulb10.isEnergyEfficient = true;
	bulb10.lifeSpanHours = 26000;
	bulb10.weight = 58;
	bulb10.length = 11;
	bulb10.diameter = 6;
	bulb10.baseType = "E27";
	bulb10.countryOfOrigin = "India";
	bulb10.warranty = "2 Years";
	bulb10.quantity = 17;
	bulb10.isStockAvailable = true;
	bulb10.customerReview = "Nice quality";
	bulb10.rating = 5;

	System.out.println("Brand: " + bulb10.brand);
	System.out.println("Type: " + bulb10.type);
	System.out.println("Colour: " + bulb10.colour);
	System.out.println("Wattage: " + bulb10.wattage);
	System.out.println("Voltage: " + bulb10.voltage);
	System.out.println("Price: " + bulb10.price);
	System.out.println("Material: " + bulb10.material);
	System.out.println("LED: " + bulb10.isLED);
	System.out.println("Smart Bulb: " + bulb10.isSmartBulb);
	System.out.println("Dimmable: " + bulb10.isDimmable);
	System.out.println("Rechargeable: " + bulb10.isRechargeable);
	System.out.println("Energy Efficient: " + bulb10.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb10.lifeSpanHours);
	System.out.println("Weight: " + bulb10.weight);
	System.out.println("Length: " + bulb10.length);
	System.out.println("Diameter: " + bulb10.diameter);
	System.out.println("Base Type: " + bulb10.baseType);
	System.out.println("Country Of Origin: " + bulb10.countryOfOrigin);
	System.out.println("Warranty: " + bulb10.warranty);
	System.out.println("Quantity: " + bulb10.quantity);
	System.out.println("Stock Available: " + bulb10.isStockAvailable);
	System.out.println("Customer Review: " + bulb10.customerReview);
	System.out.println("Rating: " + bulb10.rating);


	LightBulb bulb11 = new LightBulb();
	bulb11.brand = "Crompton";
	bulb11.type = "LED";
	bulb11.colour = "White";
	bulb11.wattage = 9;
	bulb11.voltage = 220;
	bulb11.price = 150;
	bulb11.material = "Plastic";
	bulb11.isLED = true;
	bulb11.isSmartBulb = false;
	bulb11.isDimmable = false;
	bulb11.isRechargeable = false;
	bulb11.isEnergyEfficient = true;
	bulb11.lifeSpanHours = 24000;
	bulb11.weight = 53;
	bulb11.length = 10;
	bulb11.diameter = 6;
	bulb11.baseType = "B22";
	bulb11.countryOfOrigin = "India";
	bulb11.warranty = "2 Years";
	bulb11.quantity = 15;
	bulb11.isStockAvailable = true;
	bulb11.customerReview = "Reliable";
	bulb11.rating = 4;

	System.out.println("Brand: " + bulb11.brand);
	System.out.println("Type: " + bulb11.type);
	System.out.println("Colour: " + bulb11.colour);
	System.out.println("Wattage: " + bulb11.wattage);
	System.out.println("Voltage: " + bulb11.voltage);
	System.out.println("Price: " + bulb11.price);
	System.out.println("Material: " + bulb11.material);
	System.out.println("LED: " + bulb11.isLED);
	System.out.println("Smart Bulb: " + bulb11.isSmartBulb);
	System.out.println("Dimmable: " + bulb11.isDimmable);
	System.out.println("Rechargeable: " + bulb11.isRechargeable);
	System.out.println("Energy Efficient: " + bulb11.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb11.lifeSpanHours);
	System.out.println("Weight: " + bulb11.weight);
	System.out.println("Length: " + bulb11.length);
	System.out.println("Diameter: " + bulb11.diameter);
	System.out.println("Base Type: " + bulb11.baseType);
	System.out.println("Country Of Origin: " + bulb11.countryOfOrigin);
	System.out.println("Warranty: " + bulb11.warranty);
	System.out.println("Quantity: " + bulb11.quantity);
	System.out.println("Stock Available: " + bulb11.isStockAvailable);
	System.out.println("Customer Review: " + bulb11.customerReview);
	System.out.println("Rating: " + bulb11.rating);


	LightBulb bulb12 = new LightBulb();
	bulb12.brand = "Surya";
	bulb12.type = "LED";
	bulb12.colour = "Cool White";
	bulb12.wattage = 10;
	bulb12.voltage = 220;
	bulb12.price = 145;
	bulb12.material = "Glass";
	bulb12.isLED = true;
	bulb12.isSmartBulb = false;
	bulb12.isDimmable = false;
	bulb12.isRechargeable = false;
	bulb12.isEnergyEfficient = true;
	bulb12.lifeSpanHours = 22000;
	bulb12.weight = 54;
	bulb12.length = 10;
	bulb12.diameter = 6;
	bulb12.baseType = "E27";
	bulb12.countryOfOrigin = "India";
	bulb12.warranty = "2 Years";
	bulb12.quantity = 13;
	bulb12.isStockAvailable = true;
	bulb12.customerReview = "Good value";
	bulb12.rating = 4;

	System.out.println("Brand: " + bulb12.brand);
	System.out.println("Type: " + bulb12.type);
	System.out.println("Colour: " + bulb12.colour);
	System.out.println("Wattage: " + bulb12.wattage);
	System.out.println("Voltage: " + bulb12.voltage);
	System.out.println("Price: " + bulb12.price);
	System.out.println("Material: " + bulb12.material);
	System.out.println("LED: " + bulb12.isLED);
	System.out.println("Smart Bulb: " + bulb12.isSmartBulb);
	System.out.println("Dimmable: " + bulb12.isDimmable);
	System.out.println("Rechargeable: " + bulb12.isRechargeable);
	System.out.println("Energy Efficient: " + bulb12.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb12.lifeSpanHours);
	System.out.println("Weight: " + bulb12.weight);
	System.out.println("Length: " + bulb12.length);
	System.out.println("Diameter: " + bulb12.diameter);
	System.out.println("Base Type: " + bulb12.baseType);
	System.out.println("Country Of Origin: " + bulb12.countryOfOrigin);
	System.out.println("Warranty: " + bulb12.warranty);
	System.out.println("Quantity: " + bulb12.quantity);
	System.out.println("Stock Available: " + bulb12.isStockAvailable);
	System.out.println("Customer Review: " + bulb12.customerReview);
	System.out.println("Rating: " + bulb12.rating);

	LightBulb bulb13 = new LightBulb();
	bulb13.brand = "Philips";
	bulb13.type = "LED";
	bulb13.colour = "Warm White";
	bulb13.wattage = 12;
	bulb13.voltage = 220;
	bulb13.price = 175;
	bulb13.material = "Glass";
	bulb13.isLED = true;
	bulb13.isSmartBulb = false;
	bulb13.isDimmable = true;
	bulb13.isRechargeable = false;
	bulb13.isEnergyEfficient = true;
	bulb13.lifeSpanHours = 26000;
	bulb13.weight = 60;
	bulb13.length = 11;
	bulb13.diameter = 6;
	bulb13.baseType = "B22";
	bulb13.countryOfOrigin = "India";
	bulb13.warranty = "2 Years";
	bulb13.quantity = 20;
	bulb13.isStockAvailable = true;
	bulb13.customerReview = "Very bright";
	bulb13.rating = 5;

	System.out.println("Brand: " + bulb13.brand);
	System.out.println("Type: " + bulb13.type);
	System.out.println("Colour: " + bulb13.colour);
	System.out.println("Wattage: " + bulb13.wattage);
	System.out.println("Voltage: " + bulb13.voltage);
	System.out.println("Price: " + bulb13.price);
	System.out.println("Material: " + bulb13.material);
	System.out.println("LED: " + bulb13.isLED);
	System.out.println("Smart Bulb: " + bulb13.isSmartBulb);
	System.out.println("Dimmable: " + bulb13.isDimmable);
	System.out.println("Rechargeable: " + bulb13.isRechargeable);
	System.out.println("Energy Efficient: " + bulb13.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb13.lifeSpanHours);
	System.out.println("Weight: " + bulb13.weight);
	System.out.println("Length: " + bulb13.length);
	System.out.println("Diameter: " + bulb13.diameter);
	System.out.println("Base Type: " + bulb13.baseType);
	System.out.println("Country Of Origin: " + bulb13.countryOfOrigin);
	System.out.println("Warranty: " + bulb13.warranty);
	System.out.println("Quantity: " + bulb13.quantity);
	System.out.println("Stock Available: " + bulb13.isStockAvailable);
	System.out.println("Customer Review: " + bulb13.customerReview);
	System.out.println("Rating: " + bulb13.rating);


	LightBulb bulb14 = new LightBulb();
	bulb14.brand = "Havells";
	bulb14.type = "LED";
	bulb14.colour = "Cool White";
	bulb14.wattage = 9;
	bulb14.voltage = 220;
	bulb14.price = 165;
	bulb14.material = "Plastic";
	bulb14.isLED = true;
	bulb14.isSmartBulb = false;
	bulb14.isDimmable = false;
	bulb14.isRechargeable = false;
	bulb14.isEnergyEfficient = true;
	bulb14.lifeSpanHours = 23000;
	bulb14.weight = 55;
	bulb14.length = 10;
	bulb14.diameter = 6;
	bulb14.baseType = "E27";
	bulb14.countryOfOrigin = "India";
	bulb14.warranty = "2 Years";
	bulb14.quantity = 18;
	bulb14.isStockAvailable = true;
	bulb14.customerReview = "Good light";
	bulb14.rating = 4;

	System.out.println("Brand: " + bulb14.brand);
	System.out.println("Type: " + bulb14.type);
	System.out.println("Colour: " + bulb14.colour);
	System.out.println("Wattage: " + bulb14.wattage);
	System.out.println("Voltage: " + bulb14.voltage);
	System.out.println("Price: " + bulb14.price);
	System.out.println("Material: " + bulb14.material);
	System.out.println("LED: " + bulb14.isLED);
	System.out.println("Smart Bulb: " + bulb14.isSmartBulb);
	System.out.println("Dimmable: " + bulb14.isDimmable);
	System.out.println("Rechargeable: " + bulb14.isRechargeable);
	System.out.println("Energy Efficient: " + bulb14.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb14.lifeSpanHours);
	System.out.println("Weight: " + bulb14.weight);
	System.out.println("Length: " + bulb14.length);
	System.out.println("Diameter: " + bulb14.diameter);
	System.out.println("Base Type: " + bulb14.baseType);
	System.out.println("Country Of Origin: " + bulb14.countryOfOrigin);
	System.out.println("Warranty: " + bulb14.warranty);
	System.out.println("Quantity: " + bulb14.quantity);
	System.out.println("Stock Available: " + bulb14.isStockAvailable);
	System.out.println("Customer Review: " + bulb14.customerReview);
	System.out.println("Rating: " + bulb14.rating);


	LightBulb bulb15 = new LightBulb();
	bulb15.brand = "Crompton";
	bulb15.type = "LED";
	bulb15.colour = "White";
	bulb15.wattage = 10;
	bulb15.voltage = 220;
	bulb15.price = 150;
	bulb15.material = "Glass";
	bulb15.isLED = true;
	bulb15.isSmartBulb = false;
	bulb15.isDimmable = false;
	bulb15.isRechargeable = false;
	bulb15.isEnergyEfficient = true;
	bulb15.lifeSpanHours = 24000;
	bulb15.weight = 56;
	bulb15.length = 10;
	bulb15.diameter = 6;
	bulb15.baseType = "B22";
	bulb15.countryOfOrigin = "India";
	bulb15.warranty = "2 Years";
	bulb15.quantity = 16;
	bulb15.isStockAvailable = true;
	bulb15.customerReview = "Nice product";
	bulb15.rating = 4;

	System.out.println("Brand: " + bulb15.brand);
	System.out.println("Type: " + bulb15.type);
	System.out.println("Colour: " + bulb15.colour);
	System.out.println("Wattage: " + bulb15.wattage);
	System.out.println("Voltage: " + bulb15.voltage);
	System.out.println("Price: " + bulb15.price);
	System.out.println("Material: " + bulb15.material);
	System.out.println("LED: " + bulb15.isLED);
	System.out.println("Smart Bulb: " + bulb15.isSmartBulb);
	System.out.println("Dimmable: " + bulb15.isDimmable);
	System.out.println("Rechargeable: " + bulb15.isRechargeable);
	System.out.println("Energy Efficient: " + bulb15.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb15.lifeSpanHours);
	System.out.println("Weight: " + bulb15.weight);
	System.out.println("Length: " + bulb15.length);
	System.out.println("Diameter: " + bulb15.diameter);
	System.out.println("Base Type: " + bulb15.baseType);
	System.out.println("Country Of Origin: " + bulb15.countryOfOrigin);
	System.out.println("Warranty: " + bulb15.warranty);
	System.out.println("Quantity: " + bulb15.quantity);
	System.out.println("Stock Available: " + bulb15.isStockAvailable);
	System.out.println("Customer Review: " + bulb15.customerReview);
	System.out.println("Rating: " + bulb15.rating);


	LightBulb bulb16 = new LightBulb();
	bulb16.brand = "Wipro";
	bulb16.type = "LED";
	bulb16.colour = "Cool White";
	bulb16.wattage = 8;
	bulb16.voltage = 220;
	bulb16.price = 145;
	bulb16.material = "Plastic";
	bulb16.isLED = true;
	bulb16.isSmartBulb = false;
	bulb16.isDimmable = true;
	bulb16.isRechargeable = false;
	bulb16.isEnergyEfficient = true;
	bulb16.lifeSpanHours = 22000;
	bulb16.weight = 50;
	bulb16.length = 9;
	bulb16.diameter = 5;
	bulb16.baseType = "E27";
	bulb16.countryOfOrigin = "India";
	bulb16.warranty = "1 Year";
	bulb16.quantity = 14;
	bulb16.isStockAvailable = true;
	bulb16.customerReview = "Affordable";
	bulb16.rating = 4;

	System.out.println("Brand: " + bulb16.brand);
	System.out.println("Type: " + bulb16.type);
	System.out.println("Colour: " + bulb16.colour);
	System.out.println("Wattage: " + bulb16.wattage);
	System.out.println("Voltage: " + bulb16.voltage);
	System.out.println("Price: " + bulb16.price);
	System.out.println("Material: " + bulb16.material);
	System.out.println("LED: " + bulb16.isLED);
	System.out.println("Smart Bulb: " + bulb16.isSmartBulb);
	System.out.println("Dimmable: " + bulb16.isDimmable);
	System.out.println("Rechargeable: " + bulb16.isRechargeable);
	System.out.println("Energy Efficient: " + bulb16.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb16.lifeSpanHours);
	System.out.println("Weight: " + bulb16.weight);
	System.out.println("Length: " + bulb16.length);
	System.out.println("Diameter: " + bulb16.diameter);
	System.out.println("Base Type: " + bulb16.baseType);
	System.out.println("Country Of Origin: " + bulb16.countryOfOrigin);
	System.out.println("Warranty: " + bulb16.warranty);
	System.out.println("Quantity: " + bulb16.quantity);
	System.out.println("Stock Available: " + bulb16.isStockAvailable);
	System.out.println("Customer Review: " + bulb16.customerReview);
	System.out.println("Rating: " + bulb16.rating);


	LightBulb bulb17 = new LightBulb();
	bulb17.brand = "Syska";
	bulb17.type = "LED";
	bulb17.colour = "Warm White";
	bulb17.wattage = 9;
	bulb17.voltage = 220;
	bulb17.price = 155;
	bulb17.material = "Glass";
	bulb17.isLED = true;
	bulb17.isSmartBulb = false;
	bulb17.isDimmable = false;
	bulb17.isRechargeable = false;
	bulb17.isEnergyEfficient = true;
	bulb17.lifeSpanHours = 23000;
	bulb17.weight = 54;
	bulb17.length = 10;
	bulb17.diameter = 6;
	bulb17.baseType = "B22";
	bulb17.countryOfOrigin = "India";
	bulb17.warranty = "2 Years";
	bulb17.quantity = 15;
	bulb17.isStockAvailable = true;
	bulb17.customerReview = "Nice brightness";
	bulb17.rating = 4;

	System.out.println("Brand: " + bulb17.brand);
	System.out.println("Type: " + bulb17.type);
	System.out.println("Colour: " + bulb17.colour);
	System.out.println("Wattage: " + bulb17.wattage);
	System.out.println("Voltage: " + bulb17.voltage);
	System.out.println("Price: " + bulb17.price);
	System.out.println("Material: " + bulb17.material);
	System.out.println("LED: " + bulb17.isLED);
	System.out.println("Smart Bulb: " + bulb17.isSmartBulb);
	System.out.println("Dimmable: " + bulb17.isDimmable);
	System.out.println("Rechargeable: " + bulb17.isRechargeable);
	System.out.println("Energy Efficient: " + bulb17.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb17.lifeSpanHours);
	System.out.println("Weight: " + bulb17.weight);
	System.out.println("Length: " + bulb17.length);
	System.out.println("Diameter: " + bulb17.diameter);
	System.out.println("Base Type: " + bulb17.baseType);
	System.out.println("Country Of Origin: " + bulb17.countryOfOrigin);
	System.out.println("Warranty: " + bulb17.warranty);
	System.out.println("Quantity: " + bulb17.quantity);
	System.out.println("Stock Available: " + bulb17.isStockAvailable);
	System.out.println("Customer Review: " + bulb17.customerReview);
	System.out.println("Rating: " + bulb17.rating);


	LightBulb bulb18 = new LightBulb();
	bulb18.brand = "Havells";
	bulb18.type = "LED";
	bulb18.colour = "Cool White";
	bulb18.wattage = 11;
	bulb18.voltage = 220;
	bulb18.price = 170;
	bulb18.material = "Plastic";
	bulb18.isLED = true;
	bulb18.isSmartBulb = false;
	bulb18.isDimmable = true;
	bulb18.isRechargeable = false;
	bulb18.isEnergyEfficient = true;
	bulb18.lifeSpanHours = 25000;
	bulb18.weight = 58;
	bulb18.length = 11;
	bulb18.diameter = 6;
	bulb18.baseType = "E27";
	bulb18.countryOfOrigin = "India";
	bulb18.warranty = "2 Years";
	bulb18.quantity = 18;
	bulb18.isStockAvailable = true;
	bulb18.customerReview = "Very good";
	bulb18.rating = 5;

	System.out.println("Brand: " + bulb18.brand);
	System.out.println("Type: " + bulb18.type);
	System.out.println("Colour: " + bulb18.colour);
	System.out.println("Wattage: " + bulb18.wattage);
	System.out.println("Voltage: " + bulb18.voltage);
	System.out.println("Price: " + bulb18.price);
	System.out.println("Material: " + bulb18.material);
	System.out.println("LED: " + bulb18.isLED);
	System.out.println("Smart Bulb: " + bulb18.isSmartBulb);
	System.out.println("Dimmable: " + bulb18.isDimmable);
	System.out.println("Rechargeable: " + bulb18.isRechargeable);
	System.out.println("Energy Efficient: " + bulb18.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb18.lifeSpanHours);
	System.out.println("Weight: " + bulb18.weight);
	System.out.println("Length: " + bulb18.length);
	System.out.println("Diameter: " + bulb18.diameter);
	System.out.println("Base Type: " + bulb18.baseType);
	System.out.println("Country Of Origin: " + bulb18.countryOfOrigin);
	System.out.println("Warranty: " + bulb18.warranty);
	System.out.println("Quantity: " + bulb18.quantity);
	System.out.println("Stock Available: " + bulb18.isStockAvailable);
	System.out.println("Customer Review: " + bulb18.customerReview);
	System.out.println("Rating: " + bulb18.rating);


	LightBulb bulb19 = new LightBulb();
	bulb19.brand = "Crompton";
	bulb19.type = "LED";
	bulb19.colour = "White";
	bulb19.wattage = 10;
	bulb19.voltage = 220;
	bulb19.price = 160;
	bulb19.material = "Glass";
	bulb19.isLED = true;
	bulb19.isSmartBulb = false;
	bulb19.isDimmable = false;
	bulb19.isRechargeable = false;
	bulb19.isEnergyEfficient = true;
	bulb19.lifeSpanHours = 24000;
	bulb19.weight = 56;
	bulb19.length = 10;
	bulb19.diameter = 6;
	bulb19.baseType = "B22";
	bulb19.countryOfOrigin = "India";
	bulb19.warranty = "2 Years";
	bulb19.quantity = 16;
	bulb19.isStockAvailable = true;
	bulb19.customerReview = "Nice quality";
	bulb19.rating = 4;

	System.out.println("Brand: " + bulb19.brand);
	System.out.println("Type: " + bulb19.type);
	System.out.println("Colour: " + bulb19.colour);
	System.out.println("Wattage: " + bulb19.wattage);
	System.out.println("Voltage: " + bulb19.voltage);
	System.out.println("Price: " + bulb19.price);
	System.out.println("Material: " + bulb19.material);
	System.out.println("LED: " + bulb19.isLED);
	System.out.println("Smart Bulb: " + bulb19.isSmartBulb);
	System.out.println("Dimmable: " + bulb19.isDimmable);
	System.out.println("Rechargeable: " + bulb19.isRechargeable);
	System.out.println("Energy Efficient: " + bulb19.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb19.lifeSpanHours);
	System.out.println("Weight: " + bulb19.weight);
	System.out.println("Length: " + bulb19.length);
	System.out.println("Diameter: " + bulb19.diameter);
	System.out.println("Base Type: " + bulb19.baseType);
	System.out.println("Country Of Origin: " + bulb19.countryOfOrigin);
	System.out.println("Warranty: " + bulb19.warranty);
	System.out.println("Quantity: " + bulb19.quantity);
	System.out.println("Stock Available: " + bulb19.isStockAvailable);
	System.out.println("Customer Review: " + bulb19.customerReview);
	System.out.println("Rating: " + bulb19.rating);


	LightBulb bulb20 = new LightBulb();
	bulb20.brand = "Bajaj";
	bulb20.type = "LED";
	bulb20.colour = "Cool White";
	bulb20.wattage = 12;
	bulb20.voltage = 220;
	bulb20.price = 180;
	bulb20.material = "Plastic";
	bulb20.isLED = true;
	bulb20.isSmartBulb = false;
	bulb20.isDimmable = true;
	bulb20.isRechargeable = false;
	bulb20.isEnergyEfficient = true;
	bulb20.lifeSpanHours = 27000;
	bulb20.weight = 60;
	bulb20.length = 11;
	bulb20.diameter = 6;
	bulb20.baseType = "E27";
	bulb20.countryOfOrigin = "India";
	bulb20.warranty = "2 Years";
	bulb20.quantity = 20;
	bulb20.isStockAvailable = true;
	bulb20.customerReview = "Excellent";
	bulb20.rating = 5;

	System.out.println("Brand: " + bulb20.brand);
	System.out.println("Type: " + bulb20.type);
	System.out.println("Colour: " + bulb20.colour);
	System.out.println("Wattage: " + bulb20.wattage);
	System.out.println("Voltage: " + bulb20.voltage);
	System.out.println("Price: " + bulb20.price);
	System.out.println("Material: " + bulb20.material);
	System.out.println("LED: " + bulb20.isLED);
	System.out.println("Smart Bulb: " + bulb20.isSmartBulb);
	System.out.println("Dimmable: " + bulb20.isDimmable);
	System.out.println("Rechargeable: " + bulb20.isRechargeable);
	System.out.println("Energy Efficient: " + bulb20.isEnergyEfficient);
	System.out.println("Life Span Hours: " + bulb20.lifeSpanHours);
	System.out.println("Weight: " + bulb20.weight);
	System.out.println("Length: " + bulb20.length);
	System.out.println("Diameter: " + bulb20.diameter);
	System.out.println("Base Type: " + bulb20.baseType);
	System.out.println("Country Of Origin: " + bulb20.countryOfOrigin);
	System.out.println("Warranty: " + bulb20.warranty);
	System.out.println("Quantity: " + bulb20.quantity);
	System.out.println("Stock Available: " + bulb20.isStockAvailable);
	System.out.println("Customer Review: " + bulb20.customerReview);
	System.out.println("Rating: " + bulb20.rating);

	}

	}