class LipGlossExecutor{
    public static void main(String[] args){
   // ---------------- LipGloss 1 ----------------
LipGloss lipGloss1 = new LipGloss();
lipGloss1.name = "Cherry Shine";
lipGloss1.brand = "Maybelline";
lipGloss1.shadeName = "Red Cherry";
lipGloss1.finishType = "Glossy";
lipGloss1.price = 350;
lipGloss1.quantity = 2;
lipGloss1.weight = 5;
lipGloss1.isMatte = false;
lipGloss1.isGlossy = true;
lipGloss1.isLongLasting = true;
lipGloss1.isWaterproof = false;
lipGloss1.isVegan = true;
lipGloss1.isCrueltyFree = true;
lipGloss1.isFragranceFree = false;
lipGloss1.mainIngredients = "Shea Butter, Vitamin E";
lipGloss1.expiryDate = "12-2026";
lipGloss1.manufactureDate = "12-2025";
lipGloss1.packagingType = "Tube";
lipGloss1.colourFamily = "Red";
lipGloss1.skinSafe = true;
lipGloss1.rating = 5;
lipGloss1.customerReview = "Rich red color, soft on lips";
lipGloss1.isStockAvailable = true;
lipGloss1.countryOfOrigin = "India";
lipGloss1.scent = "Mild";

System.out.println("------ LipGloss 1 Details ------");
System.out.println("name : " + lipGloss1.name);
System.out.println("brand : " + lipGloss1.brand);
System.out.println("shadeName : " + lipGloss1.shadeName);
System.out.println("finishType : " + lipGloss1.finishType);
System.out.println("price : " + lipGloss1.price);
System.out.println("quantity : " + lipGloss1.quantity);
System.out.println("weight : " + lipGloss1.weight);
System.out.println("isMatte : " + lipGloss1.isMatte);
System.out.println("isGlossy : " + lipGloss1.isGlossy);
System.out.println("isLongLasting : " + lipGloss1.isLongLasting);
System.out.println("isWaterproof : " + lipGloss1.isWaterproof);
System.out.println("isVegan : " + lipGloss1.isVegan);
System.out.println("isCrueltyFree : " + lipGloss1.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss1.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss1.mainIngredients);
System.out.println("expiryDate : " + lipGloss1.expiryDate);
System.out.println("manufactureDate : " + lipGloss1.manufactureDate);
System.out.println("packagingType : " + lipGloss1.packagingType);
System.out.println("colourFamily : " + lipGloss1.colourFamily);
System.out.println("skinSafe : " + lipGloss1.skinSafe);
System.out.println("rating : " + lipGloss1.rating);
System.out.println("customerReview : " + lipGloss1.customerReview);
System.out.println("isStockAvailable : " + lipGloss1.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss1.countryOfOrigin);
System.out.println("scent : " + lipGloss1.scent);

// ---------------- LipGloss 2 ----------------
LipGloss lipGloss2 = new LipGloss();
lipGloss2.name = "Peach Glow";
lipGloss2.brand = "Lakme";
lipGloss2.shadeName = "Peach";
lipGloss2.finishType = "Glossy";
lipGloss2.price = 300;
lipGloss2.quantity = 1;
lipGloss2.weight = 4.5;
lipGloss2.isMatte = false;
lipGloss2.isGlossy = true;
lipGloss2.isLongLasting = true;
lipGloss2.isWaterproof = false;
lipGloss2.isVegan = true;
lipGloss2.isCrueltyFree = true;
lipGloss2.isFragranceFree = false;
lipGloss2.mainIngredients = "Vitamin E, Coconut Oil";
lipGloss2.expiryDate = "10-2026";
lipGloss2.manufactureDate = "10-2025";
lipGloss2.packagingType = "Tube";
lipGloss2.colourFamily = "Peach";
lipGloss2.skinSafe = true;
lipGloss2.rating = 4;
lipGloss2.customerReview = "Soft and nourishing";
lipGloss2.isStockAvailable = true;
lipGloss2.countryOfOrigin = "India";
lipGloss2.scent = "Fruity";

System.out.println("------ LipGloss 2 Details ------");
System.out.println("name : " + lipGloss2.name);
System.out.println("brand : " + lipGloss2.brand);
System.out.println("shadeName : " + lipGloss2.shadeName);
System.out.println("finishType : " + lipGloss2.finishType);
System.out.println("price : " + lipGloss2.price);
System.out.println("quantity : " + lipGloss2.quantity);
System.out.println("weight : " + lipGloss2.weight);
System.out.println("isMatte : " + lipGloss2.isMatte);
System.out.println("isGlossy : " + lipGloss2.isGlossy);
System.out.println("isLongLasting : " + lipGloss2.isLongLasting);
System.out.println("isWaterproof : " + lipGloss2.isWaterproof);
System.out.println("isVegan : " + lipGloss2.isVegan);
System.out.println("isCrueltyFree : " + lipGloss2.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss2.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss2.mainIngredients);
System.out.println("expiryDate : " + lipGloss2.expiryDate);
System.out.println("manufactureDate : " + lipGloss2.manufactureDate);
System.out.println("packagingType : " + lipGloss2.packagingType);
System.out.println("colourFamily : " + lipGloss2.colourFamily);
System.out.println("skinSafe : " + lipGloss2.skinSafe);
System.out.println("rating : " + lipGloss2.rating);
System.out.println("customerReview : " + lipGloss2.customerReview);
System.out.println("isStockAvailable : " + lipGloss2.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss2.countryOfOrigin);
System.out.println("scent : " + lipGloss2.scent);

// ---------------- LipGloss 3 ----------------
LipGloss lipGloss3 = new LipGloss();
lipGloss3.name = "Coral Kiss";
lipGloss3.brand = "L'Oreal";
lipGloss3.shadeName = "Coral";
lipGloss3.finishType = "Glossy";
lipGloss3.price = 320;
lipGloss3.quantity = 1;
lipGloss3.weight = 4.8;
lipGloss3.isMatte = false;
lipGloss3.isGlossy = true;
lipGloss3.isLongLasting = true;
lipGloss3.isWaterproof = false;
lipGloss3.isVegan = true;
lipGloss3.isCrueltyFree = true;
lipGloss3.isFragranceFree = false;
lipGloss3.mainIngredients = "Jojoba Oil, Vitamin E";
lipGloss3.expiryDate = "11-2026";
lipGloss3.manufactureDate = "11-2025";
lipGloss3.packagingType = "Tube";
lipGloss3.colourFamily = "Coral";
lipGloss3.skinSafe = true;
lipGloss3.rating = 4;
lipGloss3.customerReview = "Soft coral color, smooth application";
lipGloss3.isStockAvailable = true;
lipGloss3.countryOfOrigin = "India";
lipGloss3.scent = "Mild";

// ---------------- SOP LipGloss 3 ----------------
System.out.println("------ LipGloss 3 Details ------");
System.out.println("name : " + lipGloss3.name);
System.out.println("brand : " + lipGloss3.brand);
System.out.println("shadeName : " + lipGloss3.shadeName);
System.out.println("finishType : " + lipGloss3.finishType);
System.out.println("price : " + lipGloss3.price);
System.out.println("quantity : " + lipGloss3.quantity);
System.out.println("weight : " + lipGloss3.weight);
System.out.println("isMatte : " + lipGloss3.isMatte);
System.out.println("isGlossy : " + lipGloss3.isGlossy);
System.out.println("isLongLasting : " + lipGloss3.isLongLasting);
System.out.println("isWaterproof : " + lipGloss3.isWaterproof);
System.out.println("isVegan : " + lipGloss3.isVegan);
System.out.println("isCrueltyFree : " + lipGloss3.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss3.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss3.mainIngredients);
System.out.println("expiryDate : " + lipGloss3.expiryDate);
System.out.println("manufactureDate : " + lipGloss3.manufactureDate);
System.out.println("packagingType : " + lipGloss3.packagingType);
System.out.println("colourFamily : " + lipGloss3.colourFamily);
System.out.println("skinSafe : " + lipGloss3.skinSafe);
System.out.println("rating : " + lipGloss3.rating);
System.out.println("customerReview : " + lipGloss3.customerReview);
System.out.println("isStockAvailable : " + lipGloss3.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss3.countryOfOrigin);
System.out.println("scent : " + lipGloss3.scent);


// ---------------- LipGloss 4 ----------------
LipGloss lipGloss4 = new LipGloss();
lipGloss4.name = "Pink Delight";
lipGloss4.brand = "Revlon";
lipGloss4.shadeName = "Baby Pink";
lipGloss4.finishType = "Glossy";
lipGloss4.price = 300;
lipGloss4.quantity = 2;
lipGloss4.weight = 4.5;
lipGloss4.isMatte = false;
lipGloss4.isGlossy = true;
lipGloss4.isLongLasting = true;
lipGloss4.isWaterproof = false;
lipGloss4.isVegan = true;
lipGloss4.isCrueltyFree = true;
lipGloss4.isFragranceFree = false;
lipGloss4.mainIngredients = "Shea Butter, Vitamin E";
lipGloss4.expiryDate = "06-2026";
lipGloss4.manufactureDate = "06-2025";
lipGloss4.packagingType = "Tube";
lipGloss4.colourFamily = "Pink";
lipGloss4.skinSafe = true;
lipGloss4.rating = 4;
lipGloss4.customerReview = "Smooth and shiny";
lipGloss4.isStockAvailable = true;
lipGloss4.countryOfOrigin = "India";
lipGloss4.scent = "Mild";

System.out.println("------ LipGloss 4 Details ------");
System.out.println("name : " + lipGloss4.name);
System.out.println("brand : " + lipGloss4.brand);
System.out.println("shadeName : " + lipGloss4.shadeName);
System.out.println("finishType : " + lipGloss4.finishType);
System.out.println("price : " + lipGloss4.price);
System.out.println("quantity : " + lipGloss4.quantity);
System.out.println("weight : " + lipGloss4.weight);
System.out.println("isMatte : " + lipGloss4.isMatte);
System.out.println("isGlossy : " + lipGloss4.isGlossy);
System.out.println("isLongLasting : " + lipGloss4.isLongLasting);
System.out.println("isWaterproof : " + lipGloss4.isWaterproof);
System.out.println("isVegan : " + lipGloss4.isVegan);
System.out.println("isCrueltyFree : " + lipGloss4.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss4.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss4.mainIngredients);
System.out.println("expiryDate : " + lipGloss4.expiryDate);
System.out.println("manufactureDate : " + lipGloss4.manufactureDate);
System.out.println("packagingType : " + lipGloss4.packagingType);
System.out.println("colourFamily : " + lipGloss4.colourFamily);
System.out.println("skinSafe : " + lipGloss4.skinSafe);
System.out.println("rating : " + lipGloss4.rating);
System.out.println("customerReview : " + lipGloss4.customerReview);
System.out.println("isStockAvailable : " + lipGloss4.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss4.countryOfOrigin);
System.out.println("scent : " + lipGloss4.scent);

// ---------------- LipGloss 5 ----------------
LipGloss lipGloss5 = new LipGloss();
lipGloss5.name = "Nude Elegance";
lipGloss5.brand = "Nykaa";
lipGloss5.shadeName = "Soft Nude";
lipGloss5.finishType = "Matte";
lipGloss5.price = 400;
lipGloss5.quantity = 1;
lipGloss5.weight = 4;
lipGloss5.isMatte = true;
lipGloss5.isGlossy = false;
lipGloss5.isLongLasting = true;
lipGloss5.isWaterproof = true;
lipGloss5.isVegan = true;
lipGloss5.isCrueltyFree = true;
lipGloss5.isFragranceFree = false;
lipGloss5.mainIngredients = "Almond Oil, Vitamin E";
lipGloss5.expiryDate = "09-2026";
lipGloss5.manufactureDate = "09-2025";
lipGloss5.packagingType = "Tube";
lipGloss5.colourFamily = "Nude";
lipGloss5.skinSafe = true;
lipGloss5.rating = 5;
lipGloss5.customerReview = "Soft, long-lasting matte";
lipGloss5.isStockAvailable = true;
lipGloss5.countryOfOrigin = "India";
lipGloss5.scent = "Light";

System.out.println("------ LipGloss 5 Details ------");
System.out.println("name : " + lipGloss5.name);
System.out.println("brand : " + lipGloss5.brand);
System.out.println("shadeName : " + lipGloss5.shadeName);
System.out.println("finishType : " + lipGloss5.finishType);
System.out.println("price : " + lipGloss5.price);
System.out.println("quantity : " + lipGloss5.quantity);
System.out.println("weight : " + lipGloss5.weight);
System.out.println("isMatte : " + lipGloss5.isMatte);
System.out.println("isGlossy : " + lipGloss5.isGlossy);
System.out.println("isLongLasting : " + lipGloss5.isLongLasting);
System.out.println("isWaterproof : " + lipGloss5.isWaterproof);
System.out.println("isVegan : " + lipGloss5.isVegan);
System.out.println("isCrueltyFree : " + lipGloss5.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss5.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss5.mainIngredients);
System.out.println("expiryDate : " + lipGloss5.expiryDate);
System.out.println("manufactureDate : " + lipGloss5.manufactureDate);
System.out.println("packagingType : " + lipGloss5.packagingType);
System.out.println("colourFamily : " + lipGloss5.colourFamily);
System.out.println("skinSafe : " + lipGloss5.skinSafe);
System.out.println("rating : " + lipGloss5.rating);
System.out.println("customerReview : " + lipGloss5.customerReview);
System.out.println("isStockAvailable : " + lipGloss5.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss5.countryOfOrigin);
System.out.println("scent : " + lipGloss5.scent);

// ---------------- LipGloss 6 ----------------
LipGloss lipGloss6 = new LipGloss();
lipGloss6.name = "Berry Blast";
lipGloss6.brand = "Maybelline";
lipGloss6.shadeName = "Berry Pink";
lipGloss6.finishType = "Glossy";
lipGloss6.price = 360;
lipGloss6.quantity = 2;
lipGloss6.weight = 5;
lipGloss6.isMatte = false;
lipGloss6.isGlossy = true;
lipGloss6.isLongLasting = true;
lipGloss6.isWaterproof = false;
lipGloss6.isVegan = true;
lipGloss6.isCrueltyFree = true;
lipGloss6.isFragranceFree = false;
lipGloss6.mainIngredients = "Cocoa Butter, Vitamin E";
lipGloss6.expiryDate = "07-2026";
lipGloss6.manufactureDate = "07-2025";
lipGloss6.packagingType = "Tube";
lipGloss6.colourFamily = "Pink";
lipGloss6.skinSafe = true;
lipGloss6.rating = 5;
lipGloss6.customerReview = "Rich berry shade, moisturizing";
lipGloss6.isStockAvailable = true;
lipGloss6.countryOfOrigin = "India";
lipGloss6.scent = "Fruity";

// ---------------- SOP LipGloss 6 ----------------
System.out.println("------ LipGloss 6 Details ------");
System.out.println("name : " + lipGloss6.name);
System.out.println("brand : " + lipGloss6.brand);
System.out.println("shadeName : " + lipGloss6.shadeName);
System.out.println("finishType : " + lipGloss6.finishType);
System.out.println("price : " + lipGloss6.price);
System.out.println("quantity : " + lipGloss6.quantity);
System.out.println("weight : " + lipGloss6.weight);
System.out.println("isMatte : " + lipGloss6.isMatte);
System.out.println("isGlossy : " + lipGloss6.isGlossy);
System.out.println("isLongLasting : " + lipGloss6.isLongLasting);
System.out.println("isWaterproof : " + lipGloss6.isWaterproof);
System.out.println("isVegan : " + lipGloss6.isVegan);
System.out.println("isCrueltyFree : " + lipGloss6.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss6.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss6.mainIngredients);
System.out.println("expiryDate : " + lipGloss6.expiryDate);
System.out.println("manufactureDate : " + lipGloss6.manufactureDate);
System.out.println("packagingType : " + lipGloss6.packagingType);
System.out.println("colourFamily : " + lipGloss6.colourFamily);
System.out.println("skinSafe : " + lipGloss6.skinSafe);
System.out.println("rating : " + lipGloss6.rating);
System.out.println("customerReview : " + lipGloss6.customerReview);
System.out.println("isStockAvailable : " + lipGloss6.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss6.countryOfOrigin);
System.out.println("scent : " + lipGloss6.scent);


// ---------------- LipGloss 7 ----------------
LipGloss lipGloss7 = new LipGloss();
lipGloss7.name = "Coral Crush";
lipGloss7.brand = "Lakme";
lipGloss7.shadeName = "Coral Red";
lipGloss7.finishType = "Glossy";
lipGloss7.price = 380;
lipGloss7.quantity = 2;
lipGloss7.weight = 4.5;
lipGloss7.isMatte = false;
lipGloss7.isGlossy = true;
lipGloss7.isLongLasting = true;
lipGloss7.isWaterproof = false;
lipGloss7.isVegan = true;
lipGloss7.isCrueltyFree = true;
lipGloss7.isFragranceFree = false;
lipGloss7.mainIngredients = "Vitamin E, Coconut Oil";
lipGloss7.expiryDate = "10-2026";
lipGloss7.manufactureDate = "10-2025";
lipGloss7.packagingType = "Tube";
lipGloss7.colourFamily = "Coral";
lipGloss7.skinSafe = true;
lipGloss7.rating = 5;
lipGloss7.customerReview = "Bright coral shade, smooth texture";
lipGloss7.isStockAvailable = true;
lipGloss7.countryOfOrigin = "India";
lipGloss7.scent = "Fruity";

System.out.println("------ LipGloss 7 Details ------");
System.out.println("name : " + lipGloss7.name);
System.out.println("brand : " + lipGloss7.brand);
System.out.println("shadeName : " + lipGloss7.shadeName);
System.out.println("finishType : " + lipGloss7.finishType);
System.out.println("price : " + lipGloss7.price);
System.out.println("quantity : " + lipGloss7.quantity);
System.out.println("weight : " + lipGloss7.weight);
System.out.println("isMatte : " + lipGloss7.isMatte);
System.out.println("isGlossy : " + lipGloss7.isGlossy);
System.out.println("isLongLasting : " + lipGloss7.isLongLasting);
System.out.println("isWaterproof : " + lipGloss7.isWaterproof);
System.out.println("isVegan : " + lipGloss7.isVegan);
System.out.println("isCrueltyFree : " + lipGloss7.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss7.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss7.mainIngredients);
System.out.println("expiryDate : " + lipGloss7.expiryDate);
System.out.println("manufactureDate : " + lipGloss7.manufactureDate);
System.out.println("packagingType : " + lipGloss7.packagingType);
System.out.println("colourFamily : " + lipGloss7.colourFamily);
System.out.println("skinSafe : " + lipGloss7.skinSafe);
System.out.println("rating : " + lipGloss7.rating);
System.out.println("customerReview : " + lipGloss7.customerReview);
System.out.println("isStockAvailable : " + lipGloss7.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss7.countryOfOrigin);
System.out.println("scent : " + lipGloss7.scent);

// ---------------- LipGloss 8 ----------------
LipGloss lipGloss8 = new LipGloss();
lipGloss8.name = "Peach Glow";
lipGloss8.brand = "Colorbar";
lipGloss8.shadeName = "Peach Pink";
lipGloss8.finishType = "Glossy";
lipGloss8.price = 370;
lipGloss8.quantity = 1;
lipGloss8.weight = 4;
lipGloss8.isMatte = false;
lipGloss8.isGlossy = true;
lipGloss8.isLongLasting = true;
lipGloss8.isWaterproof = false;
lipGloss8.isVegan = true;
lipGloss8.isCrueltyFree = true;
lipGloss8.isFragranceFree = false;
lipGloss8.mainIngredients = "Shea Butter, Almond Oil";
lipGloss8.expiryDate = "11-2026";
lipGloss8.manufactureDate = "11-2025";
lipGloss8.packagingType = "Tube";
lipGloss8.colourFamily = "Peach";
lipGloss8.skinSafe = true;
lipGloss8.rating = 4;
lipGloss8.customerReview = "Light peach color, moisturizing";
lipGloss8.isStockAvailable = true;
lipGloss8.countryOfOrigin = "India";
lipGloss8.scent = "Sweet";

System.out.println("------ LipGloss 8 Details ------");
System.out.println("name : " + lipGloss8.name);
System.out.println("brand : " + lipGloss8.brand);
System.out.println("shadeName : " + lipGloss8.shadeName);
System.out.println("finishType : " + lipGloss8.finishType);
System.out.println("price : " + lipGloss8.price);
System.out.println("quantity : " + lipGloss8.quantity);
System.out.println("weight : " + lipGloss8.weight);
System.out.println("isMatte : " + lipGloss8.isMatte);
System.out.println("isGlossy : " + lipGloss8.isGlossy);
System.out.println("isLongLasting : " + lipGloss8.isLongLasting);
System.out.println("isWaterproof : " + lipGloss8.isWaterproof);
System.out.println("isVegan : " + lipGloss8.isVegan);
System.out.println("isCrueltyFree : " + lipGloss8.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss8.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss8.mainIngredients);
System.out.println("expiryDate : " + lipGloss8.expiryDate);
System.out.println("manufactureDate : " + lipGloss8.manufactureDate);
System.out.println("packagingType : " + lipGloss8.packagingType);
System.out.println("colourFamily : " + lipGloss8.colourFamily);
System.out.println("skinSafe : " + lipGloss8.skinSafe);
System.out.println("rating : " + lipGloss8.rating);
System.out.println("customerReview : " + lipGloss8.customerReview);
System.out.println("isStockAvailable : " + lipGloss8.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss8.countryOfOrigin);
System.out.println("scent : " + lipGloss8.scent);

// ---------------- LipGloss 9 ----------------
LipGloss lipGloss9 = new LipGloss();
lipGloss9.name = "Ruby Kiss";
lipGloss9.brand = "Maybelline";
lipGloss9.shadeName = "Deep Red";
lipGloss9.finishType = "Glossy";
lipGloss9.price = 400;
lipGloss9.quantity = 1;
lipGloss9.weight = 5;
lipGloss9.isMatte = false;
lipGloss9.isGlossy = true;
lipGloss9.isLongLasting = true;
lipGloss9.isWaterproof = true;
lipGloss9.isVegan = true;
lipGloss9.isCrueltyFree = true;
lipGloss9.isFragranceFree = false;
lipGloss9.mainIngredients = "Cocoa Butter, Vitamin E";
lipGloss9.expiryDate = "12-2026";
lipGloss9.manufactureDate = "12-2025";
lipGloss9.packagingType = "Tube";
lipGloss9.colourFamily = "Red";
lipGloss9.skinSafe = true;
lipGloss9.rating = 5;
lipGloss9.customerReview = "Rich red color, long-lasting";
lipGloss9.isStockAvailable = true;
lipGloss9.countryOfOrigin = "India";
lipGloss9.scent = "Fruity";

System.out.println("------ LipGloss 9 Details ------");
System.out.println("name : " + lipGloss9.name);
System.out.println("brand : " + lipGloss9.brand);
System.out.println("shadeName : " + lipGloss9.shadeName);
System.out.println("finishType : " + lipGloss9.finishType);
System.out.println("price : " + lipGloss9.price);
System.out.println("quantity : " + lipGloss9.quantity);
System.out.println("weight : " + lipGloss9.weight);
System.out.println("isMatte : " + lipGloss9.isMatte);
System.out.println("isGlossy : " + lipGloss9.isGlossy);
System.out.println("isLongLasting : " + lipGloss9.isLongLasting);
System.out.println("isWaterproof : " + lipGloss9.isWaterproof);
System.out.println("isVegan : " + lipGloss9.isVegan);
System.out.println("isCrueltyFree : " + lipGloss9.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss9.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss9.mainIngredients);
System.out.println("expiryDate : " + lipGloss9.expiryDate);
System.out.println("manufactureDate : " + lipGloss9.manufactureDate);
System.out.println("packagingType : " + lipGloss9.packagingType);
System.out.println("colourFamily : " + lipGloss9.colourFamily);
System.out.println("skinSafe : " + lipGloss9.skinSafe);
System.out.println("rating : " + lipGloss9.rating);
System.out.println("customerReview : " + lipGloss9.customerReview);
System.out.println("isStockAvailable : " + lipGloss9.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss9.countryOfOrigin);
System.out.println("scent : " + lipGloss9.scent);

// ---------------- LipGloss 10 ----------------
LipGloss lipGloss10 = new LipGloss();
lipGloss10.name = "Peachy Shine";
lipGloss10.brand = "Lakme";
lipGloss10.shadeName = "Peach Glow";
lipGloss10.finishType = "Glossy";
lipGloss10.price = 360;
lipGloss10.quantity = 2;
lipGloss10.weight = 4.5;
lipGloss10.isMatte = false;
lipGloss10.isGlossy = true;
lipGloss10.isLongLasting = true;
lipGloss10.isWaterproof = false;
lipGloss10.isVegan = true;
lipGloss10.isCrueltyFree = true;
lipGloss10.isFragranceFree = false;
lipGloss10.mainIngredients = "Almond Oil, Vitamin E";
lipGloss10.expiryDate = "01-2027";
lipGloss10.manufactureDate = "01-2026";
lipGloss10.packagingType = "Tube";
lipGloss10.colourFamily = "Peach";
lipGloss10.skinSafe = true;
lipGloss10.rating = 4;
lipGloss10.customerReview = "Shiny peach gloss, moisturizing";
lipGloss10.isStockAvailable = true;
lipGloss10.countryOfOrigin = "India";
lipGloss10.scent = "Sweet";

System.out.println("------ LipGloss 10 Details ------");
System.out.println("name : " + lipGloss10.name);
System.out.println("brand : " + lipGloss10.brand);
System.out.println("shadeName : " + lipGloss10.shadeName);
System.out.println("finishType : " + lipGloss10.finishType);
System.out.println("price : " + lipGloss10.price);
System.out.println("quantity : " + lipGloss10.quantity);
System.out.println("weight : " + lipGloss10.weight);
System.out.println("isMatte : " + lipGloss10.isMatte);
System.out.println("isGlossy : " + lipGloss10.isGlossy);
System.out.println("isLongLasting : " + lipGloss10.isLongLasting);
System.out.println("isWaterproof : " + lipGloss10.isWaterproof);
System.out.println("isVegan : " + lipGloss10.isVegan);
System.out.println("isCrueltyFree : " + lipGloss10.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss10.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss10.mainIngredients);
System.out.println("expiryDate : " + lipGloss10.expiryDate);
System.out.println("manufactureDate : " + lipGloss10.manufactureDate);
System.out.println("packagingType : " + lipGloss10.packagingType);
System.out.println("colourFamily : " + lipGloss10.colourFamily);
System.out.println("skinSafe : " + lipGloss10.skinSafe);
System.out.println("rating : " + lipGloss10.rating);
System.out.println("customerReview : " + lipGloss10.customerReview);
System.out.println("isStockAvailable : " + lipGloss10.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss10.countryOfOrigin);
System.out.println("scent : " + lipGloss10.scent);


// ---------------- LipGloss 11 ----------------
LipGloss lipGloss11 = new LipGloss();
lipGloss11.name = "Strawberry Delight";
lipGloss11.brand = "Colorbar";
lipGloss11.shadeName = "Strawberry Pink";
lipGloss11.finishType = "Glossy";
lipGloss11.price = 370;
lipGloss11.quantity = 1;
lipGloss11.weight = 4.5;
lipGloss11.isMatte = false;
lipGloss11.isGlossy = true;
lipGloss11.isLongLasting = true;
lipGloss11.isWaterproof = false;
lipGloss11.isVegan = true;
lipGloss11.isCrueltyFree = true;
lipGloss11.isFragranceFree = false;
lipGloss11.mainIngredients = "Shea Butter, Vitamin E";
lipGloss11.expiryDate = "02-2027";
lipGloss11.manufactureDate = "02-2026";
lipGloss11.packagingType = "Tube";
lipGloss11.colourFamily = "Pink";
lipGloss11.skinSafe = true;
lipGloss11.rating = 4;
lipGloss11.customerReview = "Smooth, moisturizing pink shade";
lipGloss11.isStockAvailable = true;
lipGloss11.countryOfOrigin = "India";
lipGloss11.scent = "Fruity";

System.out.println("------ LipGloss 11 Details ------");
System.out.println("name : " + lipGloss11.name);
System.out.println("brand : " + lipGloss11.brand);
System.out.println("shadeName : " + lipGloss11.shadeName);
System.out.println("finishType : " + lipGloss11.finishType);
System.out.println("price : " + lipGloss11.price);
System.out.println("quantity : " + lipGloss11.quantity);
System.out.println("weight : " + lipGloss11.weight);
System.out.println("isMatte : " + lipGloss11.isMatte);
System.out.println("isGlossy : " + lipGloss11.isGlossy);
System.out.println("isLongLasting : " + lipGloss11.isLongLasting);
System.out.println("isWaterproof : " + lipGloss11.isWaterproof);
System.out.println("isVegan : " + lipGloss11.isVegan);
System.out.println("isCrueltyFree : " + lipGloss11.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss11.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss11.mainIngredients);
System.out.println("expiryDate : " + lipGloss11.expiryDate);
System.out.println("manufactureDate : " + lipGloss11.manufactureDate);
System.out.println("packagingType : " + lipGloss11.packagingType);
System.out.println("colourFamily : " + lipGloss11.colourFamily);
System.out.println("skinSafe : " + lipGloss11.skinSafe);
System.out.println("rating : " + lipGloss11.rating);
System.out.println("customerReview : " + lipGloss11.customerReview);
System.out.println("isStockAvailable : " + lipGloss11.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss11.countryOfOrigin);
System.out.println("scent : " + lipGloss11.scent);

// ---------------- LipGloss 12 ----------------
LipGloss lipGloss12 = new LipGloss();
lipGloss12.name = "Nude Charm";
lipGloss12.brand = "Lakme";
lipGloss12.shadeName = "Nude Beige";
lipGloss12.finishType = "Glossy";
lipGloss12.price = 350;
lipGloss12.quantity = 2;
lipGloss12.weight = 4;
lipGloss12.isMatte = false;
lipGloss12.isGlossy = true;
lipGloss12.isLongLasting = true;
lipGloss12.isWaterproof = false;
lipGloss12.isVegan = true;
lipGloss12.isCrueltyFree = true;
lipGloss12.isFragranceFree = true;
lipGloss12.mainIngredients = "Almond Oil, Cocoa Butter";
lipGloss12.expiryDate = "03-2027";
lipGloss12.manufactureDate = "03-2026";
lipGloss12.packagingType = "Tube";
lipGloss12.colourFamily = "Nude";
lipGloss12.skinSafe = true;
lipGloss12.rating = 5;
lipGloss12.customerReview = "Perfect nude shade, soft texture";
lipGloss12.isStockAvailable = true;
lipGloss12.countryOfOrigin = "India";
lipGloss12.scent = "Mild";

System.out.println("------ LipGloss 12 Details ------");
System.out.println("name : " + lipGloss12.name);
System.out.println("brand : " + lipGloss12.brand);
System.out.println("shadeName : " + lipGloss12.shadeName);
System.out.println("finishType : " + lipGloss12.finishType);
System.out.println("price : " + lipGloss12.price);
System.out.println("quantity : " + lipGloss12.quantity);
System.out.println("weight : " + lipGloss12.weight);
System.out.println("isMatte : " + lipGloss12.isMatte);
System.out.println("isGlossy : " + lipGloss12.isGlossy);
System.out.println("isLongLasting : " + lipGloss12.isLongLasting);
System.out.println("isWaterproof : " + lipGloss12.isWaterproof);
System.out.println("isVegan : " + lipGloss12.isVegan);
System.out.println("isCrueltyFree : " + lipGloss12.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss12.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss12.mainIngredients);
System.out.println("expiryDate : " + lipGloss12.expiryDate);
System.out.println("manufactureDate : " + lipGloss12.manufactureDate);
System.out.println("packagingType : " + lipGloss12.packagingType);
System.out.println("colourFamily : " + lipGloss12.colourFamily);
System.out.println("skinSafe : " + lipGloss12.skinSafe);
System.out.println("rating : " + lipGloss12.rating);
System.out.println("customerReview : " + lipGloss12.customerReview);
System.out.println("isStockAvailable : " + lipGloss12.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss12.countryOfOrigin);
System.out.println("scent : " + lipGloss12.scent);

// ---------------- LipGloss 13 ----------------
LipGloss lipGloss13 = new LipGloss();
lipGloss13.name = "Pink Blossom";
lipGloss13.brand = "Colorbar";
lipGloss13.shadeName = "Bubblegum Pink";
lipGloss13.finishType = "Glossy";
lipGloss13.price = 360;
lipGloss13.quantity = 1;
lipGloss13.weight = 4;
lipGloss13.isMatte = false;
lipGloss13.isGlossy = true;
lipGloss13.isLongLasting = true;
lipGloss13.isWaterproof = false;
lipGloss13.isVegan = true;
lipGloss13.isCrueltyFree = true;
lipGloss13.isFragranceFree = false;
lipGloss13.mainIngredients = "Shea Butter, Aloe Vera";
lipGloss13.expiryDate = "04-2027";
lipGloss13.manufactureDate = "04-2026";
lipGloss13.packagingType = "Tube";
lipGloss13.colourFamily = "Pink";
lipGloss13.skinSafe = true;
lipGloss13.rating = 5;
lipGloss13.customerReview = "Bright pink shade, moisturizing";
lipGloss13.isStockAvailable = true;
lipGloss13.countryOfOrigin = "India";
lipGloss13.scent = "Fruity";

System.out.println("------ LipGloss 13 Details ------");
System.out.println("name : " + lipGloss13.name);
System.out.println("brand : " + lipGloss13.brand);
System.out.println("shadeName : " + lipGloss13.shadeName);
System.out.println("finishType : " + lipGloss13.finishType);
System.out.println("price : " + lipGloss13.price);
System.out.println("quantity : " + lipGloss13.quantity);
System.out.println("weight : " + lipGloss13.weight);
System.out.println("isMatte : " + lipGloss13.isMatte);
System.out.println("isGlossy : " + lipGloss13.isGlossy);
System.out.println("isLongLasting : " + lipGloss13.isLongLasting);
System.out.println("isWaterproof : " + lipGloss13.isWaterproof);
System.out.println("isVegan : " + lipGloss13.isVegan);
System.out.println("isCrueltyFree : " + lipGloss13.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss13.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss13.mainIngredients);
System.out.println("expiryDate : " + lipGloss13.expiryDate);
System.out.println("manufactureDate : " + lipGloss13.manufactureDate);
System.out.println("packagingType : " + lipGloss13.packagingType);
System.out.println("colourFamily : " + lipGloss13.colourFamily);
System.out.println("skinSafe : " + lipGloss13.skinSafe);
System.out.println("rating : " + lipGloss13.rating);
System.out.println("customerReview : " + lipGloss13.customerReview);
System.out.println("isStockAvailable : " + lipGloss13.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss13.countryOfOrigin);
System.out.println("scent : " + lipGloss13.scent);


// ---------------- LipGloss 14 ----------------
LipGloss lipGloss14 = new LipGloss();
lipGloss14.name = "Peach Glow";
lipGloss14.brand = "Lakme";
lipGloss14.shadeName = "Peachy Pink";
lipGloss14.finishType = "Glossy";
lipGloss14.price = 340;
lipGloss14.quantity = 2;
lipGloss14.weight = 4.2;
lipGloss14.isMatte = false;
lipGloss14.isGlossy = true;
lipGloss14.isLongLasting = true;
lipGloss14.isWaterproof = false;
lipGloss14.isVegan = true;
lipGloss14.isCrueltyFree = true;
lipGloss14.isFragranceFree = false;
lipGloss14.mainIngredients = "Cocoa Butter, Vitamin E";
lipGloss14.expiryDate = "05-2027";
lipGloss14.manufactureDate = "05-2026";
lipGloss14.packagingType = "Tube";
lipGloss14.colourFamily = "Peach";
lipGloss14.skinSafe = true;
lipGloss14.rating = 4;
lipGloss14.customerReview = "Lovely peach shade, smooth finish";
lipGloss14.isStockAvailable = true;
lipGloss14.countryOfOrigin = "India";
lipGloss14.scent = "Fruity";

System.out.println("------ LipGloss 14 Details ------");
System.out.println("name : " + lipGloss14.name);
System.out.println("brand : " + lipGloss14.brand);
System.out.println("shadeName : " + lipGloss14.shadeName);
System.out.println("finishType : " + lipGloss14.finishType);
System.out.println("price : " + lipGloss14.price);
System.out.println("quantity : " + lipGloss14.quantity);
System.out.println("weight : " + lipGloss14.weight);
System.out.println("isMatte : " + lipGloss14.isMatte);
System.out.println("isGlossy : " + lipGloss14.isGlossy);
System.out.println("isLongLasting : " + lipGloss14.isLongLasting);
System.out.println("isWaterproof : " + lipGloss14.isWaterproof);
System.out.println("isVegan : " + lipGloss14.isVegan);
System.out.println("isCrueltyFree : " + lipGloss14.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss14.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss14.mainIngredients);
System.out.println("expiryDate : " + lipGloss14.expiryDate);
System.out.println("manufactureDate : " + lipGloss14.manufactureDate);
System.out.println("packagingType : " + lipGloss14.packagingType);
System.out.println("colourFamily : " + lipGloss14.colourFamily);
System.out.println("skinSafe : " + lipGloss14.skinSafe);
System.out.println("rating : " + lipGloss14.rating);
System.out.println("customerReview : " + lipGloss14.customerReview);
System.out.println("isStockAvailable : " + lipGloss14.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss14.countryOfOrigin);
System.out.println("scent : " + lipGloss14.scent);

// ---------------- LipGloss 15 ----------------
LipGloss lipGloss15 = new LipGloss();
lipGloss15.name = "Berry Kiss";
lipGloss15.brand = "Colorbar";
lipGloss15.shadeName = "Berry Red";
lipGloss15.finishType = "Glossy";
lipGloss15.price = 370;
lipGloss15.quantity = 1;
lipGloss15.weight = 4.5;
lipGloss15.isMatte = false;
lipGloss15.isGlossy = true;
lipGloss15.isLongLasting = true;
lipGloss15.isWaterproof = false;
lipGloss15.isVegan = true;
lipGloss15.isCrueltyFree = true;
lipGloss15.isFragranceFree = false;
lipGloss15.mainIngredients = "Shea Butter, Vitamin E";
lipGloss15.expiryDate = "06-2027";
lipGloss15.manufactureDate = "06-2026";
lipGloss15.packagingType = "Tube";
lipGloss15.colourFamily = "Red";
lipGloss15.skinSafe = true;
lipGloss15.rating = 5;
lipGloss15.customerReview = "Deep red shade, long lasting";
lipGloss15.isStockAvailable = true;
lipGloss15.countryOfOrigin = "India";
lipGloss15.scent = "Berry";

System.out.println("------ LipGloss 15 Details ------");
System.out.println("name : " + lipGloss15.name);
System.out.println("brand : " + lipGloss15.brand);
System.out.println("shadeName : " + lipGloss15.shadeName);
System.out.println("finishType : " + lipGloss15.finishType);
System.out.println("price : " + lipGloss15.price);
System.out.println("quantity : " + lipGloss15.quantity);
System.out.println("weight : " + lipGloss15.weight);
System.out.println("isMatte : " + lipGloss15.isMatte);
System.out.println("isGlossy : " + lipGloss15.isGlossy);
System.out.println("isLongLasting : " + lipGloss15.isLongLasting);
System.out.println("isWaterproof : " + lipGloss15.isWaterproof);
System.out.println("isVegan : " + lipGloss15.isVegan);
System.out.println("isCrueltyFree : " + lipGloss15.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss15.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss15.mainIngredients);
System.out.println("expiryDate : " + lipGloss15.expiryDate);
System.out.println("manufactureDate : " + lipGloss15.manufactureDate);
System.out.println("packagingType : " + lipGloss15.packagingType);
System.out.println("colourFamily : " + lipGloss15.colourFamily);
System.out.println("skinSafe : " + lipGloss15.skinSafe);
System.out.println("rating : " + lipGloss15.rating);
System.out.println("customerReview : " + lipGloss15.customerReview);
System.out.println("isStockAvailable : " + lipGloss15.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss15.countryOfOrigin);
System.out.println("scent : " + lipGloss15.scent);

// ---------------- LipGloss 16 ----------------
LipGloss lipGloss16 = new LipGloss();
lipGloss16.name = "Coral Charm";
lipGloss16.brand = "Maybelline";
lipGloss16.shadeName = "Coral Pink";
lipGloss16.finishType = "Glossy";
lipGloss16.price = 360;
lipGloss16.quantity = 2;
lipGloss16.weight = 4.2;
lipGloss16.isMatte = false;
lipGloss16.isGlossy = true;
lipGloss16.isLongLasting = true;
lipGloss16.isWaterproof = false;
lipGloss16.isVegan = true;
lipGloss16.isCrueltyFree = true;
lipGloss16.isFragranceFree = false;
lipGloss16.mainIngredients = "Vitamin E, Almond Oil";
lipGloss16.expiryDate = "07-2027";
lipGloss16.manufactureDate = "07-2026";
lipGloss16.packagingType = "Tube";
lipGloss16.colourFamily = "Coral";
lipGloss16.skinSafe = true;
lipGloss16.rating = 5;
lipGloss16.customerReview = "Beautiful coral shade, smooth application";
lipGloss16.isStockAvailable = true;
lipGloss16.countryOfOrigin = "India";
lipGloss16.scent = "Fruity";

System.out.println("------ LipGloss 16 Details ------");
System.out.println("name : " + lipGloss16.name);
System.out.println("brand : " + lipGloss16.brand);
System.out.println("shadeName : " + lipGloss16.shadeName);
System.out.println("finishType : " + lipGloss16.finishType);
System.out.println("price : " + lipGloss16.price);
System.out.println("quantity : " + lipGloss16.quantity);
System.out.println("weight : " + lipGloss16.weight);
System.out.println("isMatte : " + lipGloss16.isMatte);
System.out.println("isGlossy : " + lipGloss16.isGlossy);
System.out.println("isLongLasting : " + lipGloss16.isLongLasting);
System.out.println("isWaterproof : " + lipGloss16.isWaterproof);
System.out.println("isVegan : " + lipGloss16.isVegan);
System.out.println("isCrueltyFree : " + lipGloss16.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss16.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss16.mainIngredients);
System.out.println("expiryDate : " + lipGloss16.expiryDate);
System.out.println("manufactureDate : " + lipGloss16.manufactureDate);
System.out.println("packagingType : " + lipGloss16.packagingType);
System.out.println("colourFamily : " + lipGloss16.colourFamily);
System.out.println("skinSafe : " + lipGloss16.skinSafe);
System.out.println("rating : " + lipGloss16.rating);
System.out.println("customerReview : " + lipGloss16.customerReview);
System.out.println("isStockAvailable : " + lipGloss16.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss16.countryOfOrigin);
System.out.println("scent : " + lipGloss16.scent);

// ---------------- LipGloss 17 ----------------
LipGloss lipGloss17 = new LipGloss();
lipGloss17.name = "Pink Blossom";
lipGloss17.brand = "Revlon";
lipGloss17.shadeName = "Soft Pink";
lipGloss17.finishType = "Glossy";
lipGloss17.price = 320;
lipGloss17.quantity = 1;
lipGloss17.weight = 4.0;
lipGloss17.isMatte = false;
lipGloss17.isGlossy = true;
lipGloss17.isLongLasting = true;
lipGloss17.isWaterproof = false;
lipGloss17.isVegan = true;
lipGloss17.isCrueltyFree = true;
lipGloss17.isFragranceFree = false;
lipGloss17.mainIngredients = "Jojoba Oil, Vitamin E";
lipGloss17.expiryDate = "08-2027";
lipGloss17.manufactureDate = "08-2026";
lipGloss17.packagingType = "Tube";
lipGloss17.colourFamily = "Pink";
lipGloss17.skinSafe = true;
lipGloss17.rating = 5;
lipGloss17.customerReview = "Soft pink and moisturizing";
lipGloss17.isStockAvailable = true;
lipGloss17.countryOfOrigin = "India";
lipGloss17.scent = "Floral";

System.out.println("------ LipGloss 17 Details ------");
System.out.println("name : " + lipGloss17.name);
System.out.println("brand : " + lipGloss17.brand);
System.out.println("shadeName : " + lipGloss17.shadeName);
System.out.println("finishType : " + lipGloss17.finishType);
System.out.println("price : " + lipGloss17.price);
System.out.println("quantity : " + lipGloss17.quantity);
System.out.println("weight : " + lipGloss17.weight);
System.out.println("isMatte : " + lipGloss17.isMatte);
System.out.println("isGlossy : " + lipGloss17.isGlossy);
System.out.println("isLongLasting : " + lipGloss17.isLongLasting);
System.out.println("isWaterproof : " + lipGloss17.isWaterproof);
System.out.println("isVegan : " + lipGloss17.isVegan);
System.out.println("isCrueltyFree : " + lipGloss17.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss17.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss17.mainIngredients);
System.out.println("expiryDate : " + lipGloss17.expiryDate);
System.out.println("manufactureDate : " + lipGloss17.manufactureDate);
System.out.println("packagingType : " + lipGloss17.packagingType);
System.out.println("colourFamily : " + lipGloss17.colourFamily);
System.out.println("skinSafe : " + lipGloss17.skinSafe);
System.out.println("rating : " + lipGloss17.rating);
System.out.println("customerReview : " + lipGloss17.customerReview);
System.out.println("isStockAvailable : " + lipGloss17.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss17.countryOfOrigin);
System.out.println("scent : " + lipGloss17.scent);

// ---------------- LipGloss 18 ----------------
LipGloss lipGloss18 = new LipGloss();
lipGloss18.name = "Berry Delight";
lipGloss18.brand = "Lakme";
lipGloss18.shadeName = "Dark Berry";
lipGloss18.finishType = "Glossy";
lipGloss18.price = 380;
lipGloss18.quantity = 2;
lipGloss18.weight = 4.3;
lipGloss18.isMatte = false;
lipGloss18.isGlossy = true;
lipGloss18.isLongLasting = true;
lipGloss18.isWaterproof = false;
lipGloss18.isVegan = true;
lipGloss18.isCrueltyFree = true;
lipGloss18.isFragranceFree = false;
lipGloss18.mainIngredients = "Shea Butter, Vitamin E";
lipGloss18.expiryDate = "09-2027";
lipGloss18.manufactureDate = "09-2026";
lipGloss18.packagingType = "Tube";
lipGloss18.colourFamily = "Berry";
lipGloss18.skinSafe = true;
lipGloss18.rating = 4;
lipGloss18.customerReview = "Intense berry color and smooth feel";
lipGloss18.isStockAvailable = true;
lipGloss18.countryOfOrigin = "India";
lipGloss18.scent = "Berry";

System.out.println("------ LipGloss 18 Details ------");
System.out.println("name : " + lipGloss18.name);
System.out.println("brand : " + lipGloss18.brand);
System.out.println("shadeName : " + lipGloss18.shadeName);
System.out.println("finishType : " + lipGloss18.finishType);
System.out.println("price : " + lipGloss18.price);
System.out.println("quantity : " + lipGloss18.quantity);
System.out.println("weight : " + lipGloss18.weight);
System.out.println("isMatte : " + lipGloss18.isMatte);
System.out.println("isGlossy : " + lipGloss18.isGlossy);
System.out.println("isLongLasting : " + lipGloss18.isLongLasting);
System.out.println("isWaterproof : " + lipGloss18.isWaterproof);
System.out.println("isVegan : " + lipGloss18.isVegan);
System.out.println("isCrueltyFree : " + lipGloss18.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss18.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss18.mainIngredients);
System.out.println("expiryDate : " + lipGloss18.expiryDate);
System.out.println("manufactureDate : " + lipGloss18.manufactureDate);
System.out.println("packagingType : " + lipGloss18.packagingType);
System.out.println("colourFamily : " + lipGloss18.colourFamily);
System.out.println("skinSafe : " + lipGloss18.skinSafe);
System.out.println("rating : " + lipGloss18.rating);
System.out.println("customerReview : " + lipGloss18.customerReview);
System.out.println("isStockAvailable : " + lipGloss18.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss18.countryOfOrigin);
System.out.println("scent : " + lipGloss18.scent);

// ---------------- LipGloss 19 ----------------
LipGloss lipGloss19 = new LipGloss();
lipGloss19.name = "Nude Elegance";
lipGloss19.brand = "Colorbar";
lipGloss19.shadeName = "Nude Beige";
lipGloss19.finishType = "Glossy";
lipGloss19.price = 360;
lipGloss19.quantity = 1;
lipGloss19.weight = 4.1;
lipGloss19.isMatte = false;
lipGloss19.isGlossy = true;
lipGloss19.isLongLasting = true;
lipGloss19.isWaterproof = false;
lipGloss19.isVegan = true;
lipGloss19.isCrueltyFree = true;
lipGloss19.isFragranceFree = false;
lipGloss19.mainIngredients = "Vitamin E, Almond Oil";
lipGloss19.expiryDate = "10-2027";
lipGloss19.manufactureDate = "10-2026";
lipGloss19.packagingType = "Tube";
lipGloss19.colourFamily = "Nude";
lipGloss19.skinSafe = true;
lipGloss19.rating = 5;
lipGloss19.customerReview = "Perfect nude shade for daily wear";
lipGloss19.isStockAvailable = true;
lipGloss19.countryOfOrigin = "India";
lipGloss19.scent = "Mild";

System.out.println("------ LipGloss 19 Details ------");
System.out.println("name : " + lipGloss19.name);
System.out.println("brand : " + lipGloss19.brand);
System.out.println("shadeName : " + lipGloss19.shadeName);
System.out.println("finishType : " + lipGloss19.finishType);
System.out.println("price : " + lipGloss19.price);
System.out.println("quantity : " + lipGloss19.quantity);
System.out.println("weight : " + lipGloss19.weight);
System.out.println("isMatte : " + lipGloss19.isMatte);
System.out.println("isGlossy : " + lipGloss19.isGlossy);
System.out.println("isLongLasting : " + lipGloss19.isLongLasting);
System.out.println("isWaterproof : " + lipGloss19.isWaterproof);
System.out.println("isVegan : " + lipGloss19.isVegan);
System.out.println("isCrueltyFree : " + lipGloss19.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss19.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss19.mainIngredients);
System.out.println("expiryDate : " + lipGloss19.expiryDate);
System.out.println("manufactureDate : " + lipGloss19.manufactureDate);
System.out.println("packagingType : " + lipGloss19.packagingType);
System.out.println("colourFamily : " + lipGloss19.colourFamily);
System.out.println("skinSafe : " + lipGloss19.skinSafe);
System.out.println("rating : " + lipGloss19.rating);
System.out.println("customerReview : " + lipGloss19.customerReview);
System.out.println("isStockAvailable : " + lipGloss19.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss19.countryOfOrigin);
System.out.println("scent : " + lipGloss19.scent);

// ---------------- LipGloss 20 ----------------
LipGloss lipGloss20 = new LipGloss();
lipGloss20.name = "Coral Shine";
lipGloss20.brand = "Maybelline";
lipGloss20.shadeName = "Coral Red";
lipGloss20.finishType = "Glossy";
lipGloss20.price = 370;
lipGloss20.quantity = 2;
lipGloss20.weight = 4.4;
lipGloss20.isMatte = false;
lipGloss20.isGlossy = true;
lipGloss20.isLongLasting = true;
lipGloss20.isWaterproof = false;
lipGloss20.isVegan = true;
lipGloss20.isCrueltyFree = true;
lipGloss20.isFragranceFree = false;
lipGloss20.mainIngredients = "Coconut Oil, Vitamin E";
lipGloss20.expiryDate = "11-2027";
lipGloss20.manufactureDate = "11-2026";
lipGloss20.packagingType = "Tube";
lipGloss20.colourFamily = "Coral";
lipGloss20.skinSafe = true;
lipGloss20.rating = 5;
lipGloss20.customerReview = "Bright coral gloss, smooth finish";
lipGloss20.isStockAvailable = true;
lipGloss20.countryOfOrigin = "India";
lipGloss20.scent = "Fruity";

System.out.println("------ LipGloss 20 Details ------");
System.out.println("name : " + lipGloss20.name);
System.out.println("brand : " + lipGloss20.brand);
System.out.println("shadeName : " + lipGloss20.shadeName);
System.out.println("finishType : " + lipGloss20.finishType);
System.out.println("price : " + lipGloss20.price);
System.out.println("quantity : " + lipGloss20.quantity);
System.out.println("weight : " + lipGloss20.weight);
System.out.println("isMatte : " + lipGloss20.isMatte);
System.out.println("isGlossy : " + lipGloss20.isGlossy);
System.out.println("isLongLasting : " + lipGloss20.isLongLasting);
System.out.println("isWaterproof : " + lipGloss20.isWaterproof);
System.out.println("isVegan : " + lipGloss20.isVegan);
System.out.println("isCrueltyFree : " + lipGloss20.isCrueltyFree);
System.out.println("isFragranceFree : " + lipGloss20.isFragranceFree);
System.out.println("mainIngredients : " + lipGloss20.mainIngredients);
System.out.println("expiryDate : " + lipGloss20.expiryDate);
System.out.println("manufactureDate : " + lipGloss20.manufactureDate);
System.out.println("packagingType : " + lipGloss20.packagingType);
System.out.println("colourFamily : " + lipGloss20.colourFamily);
System.out.println("skinSafe : " + lipGloss20.skinSafe);
System.out.println("rating : " + lipGloss20.rating);
System.out.println("customerReview : " + lipGloss20.customerReview);
System.out.println("isStockAvailable : " + lipGloss20.isStockAvailable);
System.out.println("countryOfOrigin : " + lipGloss20.countryOfOrigin);
System.out.println("scent : " + lipGloss20.scent);



	}
	
}