public class MatchboxStore {
    public static void main(String[] args) {

        // ---------------- Matchbox 1 ----------------
        Matchbox matchbox1 = new Matchbox();
        matchbox1.brand = "Swan";
        matchbox1.type = "Safety";
        matchbox1.material = "Wood";
        matchbox1.numberOfMatches = 50;
        matchbox1.matchHeadMaterial = "Red Phosphorus";
        matchbox1.boxColour = "Red";
        matchbox1.packagingType = "Box";
        matchbox1.weight = 30.5;
        matchbox1.length = 4.5;
        matchbox1.width = 3.0;
        matchbox1.height = 1.2;
        matchbox1.isFlammable = true;
        matchbox1.isChildSafe = false;
        matchbox1.isWaterResistant = false;
        matchbox1.isReusable = false;
        matchbox1.isEcoFriendly = true;
        matchbox1.manufactureDate = "01-2026";
        matchbox1.expiryDate = "01-2030";
        matchbox1.safetyInstructions = "Keep away from children and fire";
        matchbox1.countryOfOrigin = "India";
        matchbox1.price = 25.0;
        matchbox1.quantity = 5;
        matchbox1.customerReview = "Reliable and long-lasting matches";
        matchbox1.rating = 5;
        matchbox1.isStockAvailable = true;
        matchbox1.scent = "None";

        System.out.println("after init instance variable");
        System.out.println("brand : " + matchbox1.brand);
        System.out.println("type : " + matchbox1.type);
        System.out.println("material : " + matchbox1.material);
        System.out.println("numberOfMatches : " + matchbox1.numberOfMatches);
        System.out.println("matchHeadMaterial : " + matchbox1.matchHeadMaterial);
        System.out.println("boxColour : " + matchbox1.boxColour);
        System.out.println("packagingType : " + matchbox1.packagingType);
        System.out.println("weight : " + matchbox1.weight);
        System.out.println("length : " + matchbox1.length);
        System.out.println("width : " + matchbox1.width);
        System.out.println("height : " + matchbox1.height);
        System.out.println("isFlammable : " + matchbox1.isFlammable);
        System.out.println("isChildSafe : " + matchbox1.isChildSafe);
        System.out.println("isWaterResistant : " + matchbox1.isWaterResistant);
        System.out.println("isReusable : " + matchbox1.isReusable);
        System.out.println("isEcoFriendly : " + matchbox1.isEcoFriendly);
        System.out.println("manufactureDate : " + matchbox1.manufactureDate);
        System.out.println("expiryDate : " + matchbox1.expiryDate);
        System.out.println("safetyInstructions : " + matchbox1.safetyInstructions);
        System.out.println("countryOfOrigin : " + matchbox1.countryOfOrigin);
        System.out.println("price : " + matchbox1.price);
        System.out.println("quantity : " + matchbox1.quantity);
        System.out.println("customerReview : " + matchbox1.customerReview);
        System.out.println("rating : " + matchbox1.rating);
        System.out.println("isStockAvailable : " + matchbox1.isStockAvailable);
        System.out.println("scent : " + matchbox1.scent);



// ---------------- Matchbox 2 ----------------
Matchbox matchbox2 = new Matchbox();
matchbox2.brand = "RedFlame";
matchbox2.type = "Strike Anywhere";
matchbox2.material = "Cardboard";
matchbox2.numberOfMatches = 40;
matchbox2.matchHeadMaterial = "Sulfur";
matchbox2.boxColour = "Blue";
matchbox2.packagingType = "Box";
matchbox2.weight = 28.0;
matchbox2.length = 4.2;
matchbox2.width = 2.8;
matchbox2.height = 1.0;
matchbox2.isFlammable = true;
matchbox2.isChildSafe = true;
matchbox2.isWaterResistant = false;
matchbox2.isReusable = false;
matchbox2.isEcoFriendly = false;
matchbox2.manufactureDate = "02-2026";
matchbox2.expiryDate = "02-2030";
matchbox2.safetyInstructions = "Handle with care";
matchbox2.countryOfOrigin = "India";
matchbox2.price = 20.0;
matchbox2.quantity = 10;
matchbox2.customerReview = "Easy to light and safe";
matchbox2.rating = 4;
matchbox2.isStockAvailable = true;
matchbox2.scent = "Pine";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox2.brand);
System.out.println("type : " + matchbox2.type);
System.out.println("material : " + matchbox2.material);
System.out.println("numberOfMatches : " + matchbox2.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox2.matchHeadMaterial);
System.out.println("boxColour : " + matchbox2.boxColour);
System.out.println("packagingType : " + matchbox2.packagingType);
System.out.println("weight : " + matchbox2.weight);
System.out.println("length : " + matchbox2.length);
System.out.println("width : " + matchbox2.width);
System.out.println("height : " + matchbox2.height);
System.out.println("isFlammable : " + matchbox2.isFlammable);
System.out.println("isChildSafe : " + matchbox2.isChildSafe);
System.out.println("isWaterResistant : " + matchbox2.isWaterResistant);
System.out.println("isReusable : " + matchbox2.isReusable);
System.out.println("isEcoFriendly : " + matchbox2.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox2.manufactureDate);
System.out.println("expiryDate : " + matchbox2.expiryDate);
System.out.println("safetyInstructions : " + matchbox2.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox2.countryOfOrigin);
System.out.println("price : " + matchbox2.price);
System.out.println("quantity : " + matchbox2.quantity);
System.out.println("customerReview : " + matchbox2.customerReview);
System.out.println("rating : " + matchbox2.rating);
System.out.println("isStockAvailable : " + matchbox2.isStockAvailable);
System.out.println("scent : " + matchbox2.scent);

// ---------------- Matchbox 3 ----------------
Matchbox matchbox3 = new Matchbox();
matchbox3.brand = "FireLite";
matchbox3.type = "Safety";
matchbox3.material = "Wood";
matchbox3.numberOfMatches = 60;
matchbox3.matchHeadMaterial = "Red Phosphorus";
matchbox3.boxColour = "Green";
matchbox3.packagingType = "Box";
matchbox3.weight = 32.0;
matchbox3.length = 4.8;
matchbox3.width = 3.2;
matchbox3.height = 1.3;
matchbox3.isFlammable = true;
matchbox3.isChildSafe = false;
matchbox3.isWaterResistant = true;
matchbox3.isReusable = false;
matchbox3.isEcoFriendly = true;
matchbox3.manufactureDate = "03-2026";
matchbox3.expiryDate = "03-2030";
matchbox3.safetyInstructions = "Keep away from children";
matchbox3.countryOfOrigin = "India";
matchbox3.price = 30.0;
matchbox3.quantity = 8;
matchbox3.customerReview = "Durable and strong";
matchbox3.rating = 5;
matchbox3.isStockAvailable = true;
matchbox3.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox3.brand);
System.out.println("type : " + matchbox3.type);
System.out.println("material : " + matchbox3.material);
System.out.println("numberOfMatches : " + matchbox3.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox3.matchHeadMaterial);
System.out.println("boxColour : " + matchbox3.boxColour);
System.out.println("packagingType : " + matchbox3.packagingType);
System.out.println("weight : " + matchbox3.weight);
System.out.println("length : " + matchbox3.length);
System.out.println("width : " + matchbox3.width);
System.out.println("height : " + matchbox3.height);
System.out.println("isFlammable : " + matchbox3.isFlammable);
System.out.println("isChildSafe : " + matchbox3.isChildSafe);
System.out.println("isWaterResistant : " + matchbox3.isWaterResistant);
System.out.println("isReusable : " + matchbox3.isReusable);
System.out.println("isEcoFriendly : " + matchbox3.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox3.manufactureDate);
System.out.println("expiryDate : " + matchbox3.expiryDate);
System.out.println("safetyInstructions : " + matchbox3.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox3.countryOfOrigin);
System.out.println("price : " + matchbox3.price);
System.out.println("quantity : " + matchbox3.quantity);
System.out.println("customerReview : " + matchbox3.customerReview);
System.out.println("rating : " + matchbox3.rating);
System.out.println("isStockAvailable : " + matchbox3.isStockAvailable);
System.out.println("scent : " + matchbox3.scent);


// ---------------- Matchbox 4 ----------------
Matchbox matchbox4 = new Matchbox();
matchbox4.brand = "QuickLight";
matchbox4.type = "Strike Anywhere";
matchbox4.material = "Cardboard";
matchbox4.numberOfMatches = 55;
matchbox4.matchHeadMaterial = "Sulfur";
matchbox4.boxColour = "Yellow";
matchbox4.packagingType = "Box";
matchbox4.weight = 31.0;
matchbox4.length = 4.6;
matchbox4.width = 3.1;
matchbox4.height = 1.1;
matchbox4.isFlammable = true;
matchbox4.isChildSafe = true;
matchbox4.isWaterResistant = false;
matchbox4.isReusable = false;
matchbox4.isEcoFriendly = false;
matchbox4.manufactureDate = "04-2026";
matchbox4.expiryDate = "04-2030";
matchbox4.safetyInstructions = "Keep away from children and fire";
matchbox4.countryOfOrigin = "India";
matchbox4.price = 22.0;
matchbox4.quantity = 7;
matchbox4.customerReview = "Works well, easy to strike";
matchbox4.rating = 4;
matchbox4.isStockAvailable = true;
matchbox4.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox4.brand);
System.out.println("type : " + matchbox4.type);
System.out.println("material : " + matchbox4.material);
System.out.println("numberOfMatches : " + matchbox4.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox4.matchHeadMaterial);
System.out.println("boxColour : " + matchbox4.boxColour);
System.out.println("packagingType : " + matchbox4.packagingType);
System.out.println("weight : " + matchbox4.weight);
System.out.println("length : " + matchbox4.length);
System.out.println("width : " + matchbox4.width);
System.out.println("height : " + matchbox4.height);
System.out.println("isFlammable : " + matchbox4.isFlammable);
System.out.println("isChildSafe : " + matchbox4.isChildSafe);
System.out.println("isWaterResistant : " + matchbox4.isWaterResistant);
System.out.println("isReusable : " + matchbox4.isReusable);
System.out.println("isEcoFriendly : " + matchbox4.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox4.manufactureDate);
System.out.println("expiryDate : " + matchbox4.expiryDate);
System.out.println("safetyInstructions : " + matchbox4.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox4.countryOfOrigin);
System.out.println("price : " + matchbox4.price);
System.out.println("quantity : " + matchbox4.quantity);
System.out.println("customerReview : " + matchbox4.customerReview);
System.out.println("rating : " + matchbox4.rating);
System.out.println("isStockAvailable : " + matchbox4.isStockAvailable);
System.out.println("scent : " + matchbox4.scent);

// ---------------- Matchbox 5 ----------------
Matchbox matchbox5 = new Matchbox();
matchbox5.brand = "GoldenStrike";
matchbox5.type = "Safety";
matchbox5.material = "Wood";
matchbox5.numberOfMatches = 45;
matchbox5.matchHeadMaterial = "Red Phosphorus";
matchbox5.boxColour = "Orange";
matchbox5.packagingType = "Box";
matchbox5.weight = 29.5;
matchbox5.length = 4.4;
matchbox5.width = 3.0;
matchbox5.height = 1.2;
matchbox5.isFlammable = true;
matchbox5.isChildSafe = false;
matchbox5.isWaterResistant = true;
matchbox5.isReusable = false;
matchbox5.isEcoFriendly = true;
matchbox5.manufactureDate = "05-2026";
matchbox5.expiryDate = "05-2030";
matchbox5.safetyInstructions = "Do not expose to water";
matchbox5.countryOfOrigin = "India";
matchbox5.price = 24.0;
matchbox5.quantity = 6;
matchbox5.customerReview = "Bright and long-lasting";
matchbox5.rating = 5;
matchbox5.isStockAvailable = true;
matchbox5.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox5.brand);
System.out.println("type : " + matchbox5.type);
System.out.println("material : " + matchbox5.material);
System.out.println("numberOfMatches : " + matchbox5.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox5.matchHeadMaterial);
System.out.println("boxColour : " + matchbox5.boxColour);
System.out.println("packagingType : " + matchbox5.packagingType);
System.out.println("weight : " + matchbox5.weight);
System.out.println("length : " + matchbox5.length);
System.out.println("width : " + matchbox5.width);
System.out.println("height : " + matchbox5.height);
System.out.println("isFlammable : " + matchbox5.isFlammable);
System.out.println("isChildSafe : " + matchbox5.isChildSafe);
System.out.println("isWaterResistant : " + matchbox5.isWaterResistant);
System.out.println("isReusable : " + matchbox5.isReusable);
System.out.println("isEcoFriendly : " + matchbox5.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox5.manufactureDate);
System.out.println("expiryDate : " + matchbox5.expiryDate);
System.out.println("safetyInstructions : " + matchbox5.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox5.countryOfOrigin);
System.out.println("price : " + matchbox5.price);
System.out.println("quantity : " + matchbox5.quantity);
System.out.println("customerReview : " + matchbox5.customerReview);
System.out.println("rating : " + matchbox5.rating);
System.out.println("isStockAvailable : " + matchbox5.isStockAvailable);
System.out.println("scent : " + matchbox5.scent);

// ---------------- Matchbox 6 ----------------
Matchbox matchbox6 = new Matchbox();
matchbox6.brand = "BrightFire";
matchbox6.type = "Strike Anywhere";
matchbox6.material = "Cardboard";
matchbox6.numberOfMatches = 60;
matchbox6.matchHeadMaterial = "Sulfur";
matchbox6.boxColour = "Purple";
matchbox6.packagingType = "Box";
matchbox6.weight = 33.0;
matchbox6.length = 4.7;
matchbox6.width = 3.3;
matchbox6.height = 1.3;
matchbox6.isFlammable = true;
matchbox6.isChildSafe = true;
matchbox6.isWaterResistant = false;
matchbox6.isReusable = false;
matchbox6.isEcoFriendly = false;
matchbox6.manufactureDate = "06-2026";
matchbox6.expiryDate = "06-2030";
matchbox6.safetyInstructions = "Keep away from moisture";
matchbox6.countryOfOrigin = "India";
matchbox6.price = 26.0;
matchbox6.quantity = 5;
matchbox6.customerReview = "Easy to use and safe";
matchbox6.rating = 4;
matchbox6.isStockAvailable = true;
matchbox6.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox6.brand);
System.out.println("type : " + matchbox6.type);
System.out.println("material : " + matchbox6.material);
System.out.println("numberOfMatches : " + matchbox6.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox6.matchHeadMaterial);
System.out.println("boxColour : " + matchbox6.boxColour);
System.out.println("packagingType : " + matchbox6.packagingType);
System.out.println("weight : " + matchbox6.weight);
System.out.println("length : " + matchbox6.length);
System.out.println("width : " + matchbox6.width);
System.out.println("height : " + matchbox6.height);
System.out.println("isFlammable : " + matchbox6.isFlammable);
System.out.println("isChildSafe : " + matchbox6.isChildSafe);
System.out.println("isWaterResistant : " + matchbox6.isWaterResistant);
System.out.println("isReusable : " + matchbox6.isReusable);
System.out.println("isEcoFriendly : " + matchbox6.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox6.manufactureDate);
System.out.println("expiryDate : " + matchbox6.expiryDate);
System.out.println("safetyInstructions : " + matchbox6.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox6.countryOfOrigin);
System.out.println("price : " + matchbox6.price);
System.out.println("quantity : " + matchbox6.quantity);
System.out.println("customerReview : " + matchbox6.customerReview);
System.out.println("rating : " + matchbox6.rating);
System.out.println("isStockAvailable : " + matchbox6.isStockAvailable);
System.out.println("scent : " + matchbox6.scent);


// ---------------- Matchbox 7 ----------------
Matchbox matchbox7 = new Matchbox();
matchbox7.brand = "SparkLite";
matchbox7.type = "Safety";
matchbox7.material = "Wood";
matchbox7.numberOfMatches = 50;
matchbox7.matchHeadMaterial = "Red Phosphorus";
matchbox7.boxColour = "Red";
matchbox7.packagingType = "Box";
matchbox7.weight = 30.0;
matchbox7.length = 4.5;
matchbox7.width = 3.0;
matchbox7.height = 1.2;
matchbox7.isFlammable = true;
matchbox7.isChildSafe = false;
matchbox7.isWaterResistant = true;
matchbox7.isReusable = false;
matchbox7.isEcoFriendly = true;
matchbox7.manufactureDate = "07-2026";
matchbox7.expiryDate = "07-2030";
matchbox7.safetyInstructions = "Keep away from children";
matchbox7.countryOfOrigin = "India";
matchbox7.price = 28.0;
matchbox7.quantity = 6;
matchbox7.customerReview = "Easy to use, good quality";
matchbox7.rating = 5;
matchbox7.isStockAvailable = true;
matchbox7.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox7.brand);
System.out.println("type : " + matchbox7.type);
System.out.println("material : " + matchbox7.material);
System.out.println("numberOfMatches : " + matchbox7.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox7.matchHeadMaterial);
System.out.println("boxColour : " + matchbox7.boxColour);
System.out.println("packagingType : " + matchbox7.packagingType);
System.out.println("weight : " + matchbox7.weight);
System.out.println("length : " + matchbox7.length);
System.out.println("width : " + matchbox7.width);
System.out.println("height : " + matchbox7.height);
System.out.println("isFlammable : " + matchbox7.isFlammable);
System.out.println("isChildSafe : " + matchbox7.isChildSafe);
System.out.println("isWaterResistant : " + matchbox7.isWaterResistant);
System.out.println("isReusable : " + matchbox7.isReusable);
System.out.println("isEcoFriendly : " + matchbox7.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox7.manufactureDate);
System.out.println("expiryDate : " + matchbox7.expiryDate);
System.out.println("safetyInstructions : " + matchbox7.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox7.countryOfOrigin);
System.out.println("price : " + matchbox7.price);
System.out.println("quantity : " + matchbox7.quantity);
System.out.println("customerReview : " + matchbox7.customerReview);
System.out.println("rating : " + matchbox7.rating);
System.out.println("isStockAvailable : " + matchbox7.isStockAvailable);
System.out.println("scent : " + matchbox7.scent);

// ---------------- Matchbox 8 ----------------
Matchbox matchbox8 = new Matchbox();
matchbox8.brand = "FireKing";
matchbox8.type = "Strike Anywhere";
matchbox8.material = "Cardboard";
matchbox8.numberOfMatches = 65;
matchbox8.matchHeadMaterial = "Sulfur";
matchbox8.boxColour = "Green";
matchbox8.packagingType = "Box";
matchbox8.weight = 35.0;
matchbox8.length = 4.9;
matchbox8.width = 3.4;
matchbox8.height = 1.4;
matchbox8.isFlammable = true;
matchbox8.isChildSafe = true;
matchbox8.isWaterResistant = false;
matchbox8.isReusable = false;
matchbox8.isEcoFriendly = false;
matchbox8.manufactureDate = "08-2026";
matchbox8.expiryDate = "08-2030";
matchbox8.safetyInstructions = "Handle with care";
matchbox8.countryOfOrigin = "India";
matchbox8.price = 30.0;
matchbox8.quantity = 5;
matchbox8.customerReview = "High quality matches";
matchbox8.rating = 5;
matchbox8.isStockAvailable = true;
matchbox8.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox8.brand);
System.out.println("type : " + matchbox8.type);
System.out.println("material : " + matchbox8.material);
System.out.println("numberOfMatches : " + matchbox8.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox8.matchHeadMaterial);
System.out.println("boxColour : " + matchbox8.boxColour);
System.out.println("packagingType : " + matchbox8.packagingType);
System.out.println("weight : " + matchbox8.weight);
System.out.println("length : " + matchbox8.length);
System.out.println("width : " + matchbox8.width);
System.out.println("height : " + matchbox8.height);
System.out.println("isFlammable : " + matchbox8.isFlammable);
System.out.println("isChildSafe : " + matchbox8.isChildSafe);
System.out.println("isWaterResistant : " + matchbox8.isWaterResistant);
System.out.println("isReusable : " + matchbox8.isReusable);
System.out.println("isEcoFriendly : " + matchbox8.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox8.manufactureDate);
System.out.println("expiryDate : " + matchbox8.expiryDate);
System.out.println("safetyInstructions : " + matchbox8.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox8.countryOfOrigin);
System.out.println("price : " + matchbox8.price);
System.out.println("quantity : " + matchbox8.quantity);
System.out.println("customerReview : " + matchbox8.customerReview);
System.out.println("rating : " + matchbox8.rating);
System.out.println("isStockAvailable : " + matchbox8.isStockAvailable);
System.out.println("scent : " + matchbox8.scent);

// ---------------- Matchbox 9 ----------------
Matchbox matchbox9 = new Matchbox();
matchbox9.brand = "FlamePro";
matchbox9.type = "Safety";
matchbox9.material = "Wood";
matchbox9.numberOfMatches = 55;
matchbox9.matchHeadMaterial = "Red Phosphorus";
matchbox9.boxColour = "Orange";
matchbox9.packagingType = "Box";
matchbox9.weight = 32.0;
matchbox9.length = 4.8;
matchbox9.width = 3.2;
matchbox9.height = 1.3;
matchbox9.isFlammable = true;
matchbox9.isChildSafe = false;
matchbox9.isWaterResistant = true;
matchbox9.isReusable = false;
matchbox9.isEcoFriendly = true;
matchbox9.manufactureDate = "09-2026";
matchbox9.expiryDate = "09-2030";
matchbox9.safetyInstructions = "Keep away from water";
matchbox9.countryOfOrigin = "India";
matchbox9.price = 32.0;
matchbox9.quantity = 4;
matchbox9.customerReview = "Good quality matches, easy to strike";
matchbox9.rating = 5;
matchbox9.isStockAvailable = true;
matchbox9.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox9.brand);
System.out.println("type : " + matchbox9.type);
System.out.println("material : " + matchbox9.material);
System.out.println("numberOfMatches : " + matchbox9.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox9.matchHeadMaterial);
System.out.println("boxColour : " + matchbox9.boxColour);
System.out.println("packagingType : " + matchbox9.packagingType);
System.out.println("weight : " + matchbox9.weight);
System.out.println("length : " + matchbox9.length);
System.out.println("width : " + matchbox9.width);
System.out.println("height : " + matchbox9.height);
System.out.println("isFlammable : " + matchbox9.isFlammable);
System.out.println("isChildSafe : " + matchbox9.isChildSafe);
System.out.println("isWaterResistant : " + matchbox9.isWaterResistant);
System.out.println("isReusable : " + matchbox9.isReusable);
System.out.println("isEcoFriendly : " + matchbox9.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox9.manufactureDate);
System.out.println("expiryDate : " + matchbox9.expiryDate);
System.out.println("safetyInstructions : " + matchbox9.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox9.countryOfOrigin);
System.out.println("price : " + matchbox9.price);
System.out.println("quantity : " + matchbox9.quantity);
System.out.println("customerReview : " + matchbox9.customerReview);
System.out.println("rating : " + matchbox9.rating);
System.out.println("isStockAvailable : " + matchbox9.isStockAvailable);
System.out.println("scent : " + matchbox9.scent);

// ---------------- Matchbox 10 ----------------
Matchbox matchbox10 = new Matchbox();
matchbox10.brand = "FireX";
matchbox10.type = "Strike Anywhere";
matchbox10.material = "Cardboard";
matchbox10.numberOfMatches = 70;
matchbox10.matchHeadMaterial = "Sulfur";
matchbox10.boxColour = "Black";
matchbox10.packagingType = "Box";
matchbox10.weight = 36.0;
matchbox10.length = 5.0;
matchbox10.width = 3.5;
matchbox10.height = 1.5;
matchbox10.isFlammable = true;
matchbox10.isChildSafe = true;
matchbox10.isWaterResistant = false;
matchbox10.isReusable = false;
matchbox10.isEcoFriendly = false;
matchbox10.manufactureDate = "10-2026";
matchbox10.expiryDate = "10-2030";
matchbox10.safetyInstructions = "Keep dry and away from fire";
matchbox10.countryOfOrigin = "India";
matchbox10.price = 35.0;
matchbox10.quantity = 5;
matchbox10.customerReview = "Strong and reliable";
matchbox10.rating = 5;
matchbox10.isStockAvailable = true;
matchbox10.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox10.brand);
System.out.println("type : " + matchbox10.type);
System.out.println("material : " + matchbox10.material);
System.out.println("numberOfMatches : " + matchbox10.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox10.matchHeadMaterial);
System.out.println("boxColour : " + matchbox10.boxColour);
System.out.println("packagingType : " + matchbox10.packagingType);
System.out.println("weight : " + matchbox10.weight);
System.out.println("length : " + matchbox10.length);
System.out.println("width : " + matchbox10.width);
System.out.println("height : " + matchbox10.height);
System.out.println("isFlammable : " + matchbox10.isFlammable);
System.out.println("isChildSafe : " + matchbox10.isChildSafe);
System.out.println("isWaterResistant : " + matchbox10.isWaterResistant);
System.out.println("isReusable : " + matchbox10.isReusable);
System.out.println("isEcoFriendly : " + matchbox10.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox10.manufactureDate);
System.out.println("expiryDate : " + matchbox10.expiryDate);
System.out.println("safetyInstructions : " + matchbox10.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox10.countryOfOrigin);
System.out.println("price : " + matchbox10.price);
System.out.println("quantity : " + matchbox10.quantity);
System.out.println("customerReview : " + matchbox10.customerReview);
System.out.println("rating : " + matchbox10.rating);
System.out.println("isStockAvailable : " + matchbox10.isStockAvailable);
System.out.println("scent : " + matchbox10.scent);

// ---------------- Matchbox 11 ----------------
Matchbox matchbox11 = new Matchbox();
matchbox11.brand = "QuickFlame";
matchbox11.type = "Safety";
matchbox11.material = "Wood";
matchbox11.numberOfMatches = 60;
matchbox11.matchHeadMaterial = "Red Phosphorus";
matchbox11.boxColour = "Yellow";
matchbox11.packagingType = "Box";
matchbox11.weight = 33.0;
matchbox11.length = 4.7;
matchbox11.width = 3.1;
matchbox11.height = 1.3;
matchbox11.isFlammable = true;
matchbox11.isChildSafe = false;
matchbox11.isWaterResistant = true;
matchbox11.isReusable = false;
matchbox11.isEcoFriendly = true;
matchbox11.manufactureDate = "11-2026";
matchbox11.expiryDate = "11-2030";
matchbox11.safetyInstructions = "Keep away from children and fire";
matchbox11.countryOfOrigin = "India";
matchbox11.price = 30.0;
matchbox11.quantity = 4;
matchbox11.customerReview = "Easy to use, bright flame";
matchbox11.rating = 5;
matchbox11.isStockAvailable = true;
matchbox11.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox11.brand);
System.out.println("type : " + matchbox11.type);
System.out.println("material : " + matchbox11.material);
System.out.println("numberOfMatches : " + matchbox11.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox11.matchHeadMaterial);
System.out.println("boxColour : " + matchbox11.boxColour);
System.out.println("packagingType : " + matchbox11.packagingType);
System.out.println("weight : " + matchbox11.weight);
System.out.println("length : " + matchbox11.length);
System.out.println("width : " + matchbox11.width);
System.out.println("height : " + matchbox11.height);
System.out.println("isFlammable : " + matchbox11.isFlammable);
System.out.println("isChildSafe : " + matchbox11.isChildSafe);
System.out.println("isWaterResistant : " + matchbox11.isWaterResistant);
System.out.println("isReusable : " + matchbox11.isReusable);
System.out.println("isEcoFriendly : " + matchbox11.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox11.manufactureDate);
System.out.println("expiryDate : " + matchbox11.expiryDate);
System.out.println("safetyInstructions : " + matchbox11.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox11.countryOfOrigin);
System.out.println("price : " + matchbox11.price);
System.out.println("quantity : " + matchbox11.quantity);
System.out.println("customerReview : " + matchbox11.customerReview);
System.out.println("rating : " + matchbox11.rating);
System.out.println("isStockAvailable : " + matchbox11.isStockAvailable);
System.out.println("scent : " + matchbox11.scent);

// ---------------- Matchbox 12 ----------------
Matchbox matchbox12 = new Matchbox();
matchbox12.brand = "SparkSafe";
matchbox12.type = "Safety";
matchbox12.material = "Wood";
matchbox12.numberOfMatches = 55;
matchbox12.matchHeadMaterial = "Red Phosphorus";
matchbox12.boxColour = "Blue";
matchbox12.packagingType = "Box";
matchbox12.weight = 31.0;
matchbox12.length = 4.6;
matchbox12.width = 3.0;
matchbox12.height = 1.2;
matchbox12.isFlammable = true;
matchbox12.isChildSafe = false;
matchbox12.isWaterResistant = true;
matchbox12.isReusable = false;
matchbox12.isEcoFriendly = true;
matchbox12.manufactureDate = "12-2026";
matchbox12.expiryDate = "12-2030";
matchbox12.safetyInstructions = "Keep away from children";
matchbox12.countryOfOrigin = "India";
matchbox12.price = 28.0;
matchbox12.quantity = 5;
matchbox12.customerReview = "Reliable and safe";
matchbox12.rating = 5;
matchbox12.isStockAvailable = true;
matchbox12.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox12.brand);
System.out.println("type : " + matchbox12.type);
System.out.println("material : " + matchbox12.material);
System.out.println("numberOfMatches : " + matchbox12.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox12.matchHeadMaterial);
System.out.println("boxColour : " + matchbox12.boxColour);
System.out.println("packagingType : " + matchbox12.packagingType);
System.out.println("weight : " + matchbox12.weight);
System.out.println("length : " + matchbox12.length);
System.out.println("width : " + matchbox12.width);
System.out.println("height : " + matchbox12.height);
System.out.println("isFlammable : " + matchbox12.isFlammable);
System.out.println("isChildSafe : " + matchbox12.isChildSafe);
System.out.println("isWaterResistant : " + matchbox12.isWaterResistant);
System.out.println("isReusable : " + matchbox12.isReusable);
System.out.println("isEcoFriendly : " + matchbox12.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox12.manufactureDate);
System.out.println("expiryDate : " + matchbox12.expiryDate);
System.out.println("safetyInstructions : " + matchbox12.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox12.countryOfOrigin);
System.out.println("price : " + matchbox12.price);
System.out.println("quantity : " + matchbox12.quantity);
System.out.println("customerReview : " + matchbox12.customerReview);
System.out.println("rating : " + matchbox12.rating);
System.out.println("isStockAvailable : " + matchbox12.isStockAvailable);
System.out.println("scent : " + matchbox12.scent);



// ---------------- Matchbox 13 ----------------
Matchbox matchbox13 = new Matchbox();
matchbox13.brand = "BrightFlame";
matchbox13.type = "Strike Anywhere";
matchbox13.material = "Cardboard";
matchbox13.numberOfMatches = 65;
matchbox13.matchHeadMaterial = "Sulfur";
matchbox13.boxColour = "Red";
matchbox13.packagingType = "Box";
matchbox13.weight = 34.0;
matchbox13.length = 5.1;
matchbox13.width = 3.4;
matchbox13.height = 1.4;
matchbox13.isFlammable = true;
matchbox13.isChildSafe = true;
matchbox13.isWaterResistant = false;
matchbox13.isReusable = false;
matchbox13.isEcoFriendly = false;
matchbox13.manufactureDate = "01-2027";
matchbox13.expiryDate = "01-2031";
matchbox13.safetyInstructions = "Store in dry place, away from children";
matchbox13.countryOfOrigin = "India";
matchbox13.price = 32.0;
matchbox13.quantity = 6;
matchbox13.customerReview = "Good quality, consistent flame";
matchbox13.rating = 5;
matchbox13.isStockAvailable = true;
matchbox13.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox13.brand);
System.out.println("type : " + matchbox13.type);
System.out.println("material : " + matchbox13.material);
System.out.println("numberOfMatches : " + matchbox13.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox13.matchHeadMaterial);
System.out.println("boxColour : " + matchbox13.boxColour);
System.out.println("packagingType : " + matchbox13.packagingType);
System.out.println("weight : " + matchbox13.weight);
System.out.println("length : " + matchbox13.length);
System.out.println("width : " + matchbox13.width);
System.out.println("height : " + matchbox13.height);
System.out.println("isFlammable : " + matchbox13.isFlammable);
System.out.println("isChildSafe : " + matchbox13.isChildSafe);
System.out.println("isWaterResistant : " + matchbox13.isWaterResistant);
System.out.println("isReusable : " + matchbox13.isReusable);
System.out.println("isEcoFriendly : " + matchbox13.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox13.manufactureDate);
System.out.println("expiryDate : " + matchbox13.expiryDate);
System.out.println("safetyInstructions : " + matchbox13.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox13.countryOfOrigin);
System.out.println("price : " + matchbox13.price);
System.out.println("quantity : " + matchbox13.quantity);
System.out.println("customerReview : " + matchbox13.customerReview);
System.out.println("rating : " + matchbox13.rating);
System.out.println("isStockAvailable : " + matchbox13.isStockAvailable);
System.out.println("scent : " + matchbox13.scent);

// ---------------- Matchbox 14 ----------------
Matchbox matchbox14 = new Matchbox();
matchbox14.brand = "SafeStrike";
matchbox14.type = "Safety";
matchbox14.material = "Wood";
matchbox14.numberOfMatches = 50;
matchbox14.matchHeadMaterial = "Red Phosphorus";
matchbox14.boxColour = "Green";
matchbox14.packagingType = "Box";
matchbox14.weight = 30.0;
matchbox14.length = 4.5;
matchbox14.width = 3.0;
matchbox14.height = 1.2;
matchbox14.isFlammable = true;
matchbox14.isChildSafe = false;
matchbox14.isWaterResistant = true;
matchbox14.isReusable = false;
matchbox14.isEcoFriendly = true;
matchbox14.manufactureDate = "02-2027";
matchbox14.expiryDate = "02-2031";
matchbox14.safetyInstructions = "Keep away from fire and children";
matchbox14.countryOfOrigin = "India";
matchbox14.price = 29.0;
matchbox14.quantity = 5;
matchbox14.customerReview = "Safe and easy to light";
matchbox14.rating = 5;
matchbox14.isStockAvailable = true;
matchbox14.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox14.brand);
System.out.println("type : " + matchbox14.type);
System.out.println("material : " + matchbox14.material);
System.out.println("numberOfMatches : " + matchbox14.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox14.matchHeadMaterial);
System.out.println("boxColour : " + matchbox14.boxColour);
System.out.println("packagingType : " + matchbox14.packagingType);
System.out.println("weight : " + matchbox14.weight);
System.out.println("length : " + matchbox14.length);
System.out.println("width : " + matchbox14.width);
System.out.println("height : " + matchbox14.height);
System.out.println("isFlammable : " + matchbox14.isFlammable);
System.out.println("isChildSafe : " + matchbox14.isChildSafe);
System.out.println("isWaterResistant : " + matchbox14.isWaterResistant);
System.out.println("isReusable : " + matchbox14.isReusable);
System.out.println("isEcoFriendly : " + matchbox14.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox14.manufactureDate);
System.out.println("expiryDate : " + matchbox14.expiryDate);
System.out.println("safetyInstructions : " + matchbox14.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox14.countryOfOrigin);
System.out.println("price : " + matchbox14.price);
System.out.println("quantity : " + matchbox14.quantity);
System.out.println("customerReview : " + matchbox14.customerReview);
System.out.println("rating : " + matchbox14.rating);
System.out.println("isStockAvailable : " + matchbox14.isStockAvailable);
System.out.println("scent : " + matchbox14.scent);

// ---------------- Matchbox 15 ----------------
Matchbox matchbox15 = new Matchbox();
matchbox15.brand = "RedSpark";
matchbox15.type = "Strike Anywhere";
matchbox15.material = "Cardboard";
matchbox15.numberOfMatches = 75;
matchbox15.matchHeadMaterial = "Sulfur";
matchbox15.boxColour = "Orange";
matchbox15.packagingType = "Box";
matchbox15.weight = 37.0;
matchbox15.length = 5.2;
matchbox15.width = 3.6;
matchbox15.height = 1.6;
matchbox15.isFlammable = true;
matchbox15.isChildSafe = true;
matchbox15.isWaterResistant = false;
matchbox15.isReusable = false;
matchbox15.isEcoFriendly = false;
matchbox15.manufactureDate = "03-2027";
matchbox15.expiryDate = "03-2031";
matchbox15.safetyInstructions = "Keep in dry place away from children";
matchbox15.countryOfOrigin = "India";
matchbox15.price = 36.0;
matchbox15.quantity = 5;
matchbox15.customerReview = "High quality matches";
matchbox15.rating = 5;
matchbox15.isStockAvailable = true;
matchbox15.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox15.brand);
System.out.println("type : " + matchbox15.type);
System.out.println("material : " + matchbox15.material);
System.out.println("numberOfMatches : " + matchbox15.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox15.matchHeadMaterial);
System.out.println("boxColour : " + matchbox15.boxColour);
System.out.println("packagingType : " + matchbox15.packagingType);
System.out.println("weight : " + matchbox15.weight);
System.out.println("length : " + matchbox15.length);
System.out.println("width : " + matchbox15.width);
System.out.println("height : " + matchbox15.height);
System.out.println("isFlammable : " + matchbox15.isFlammable);
System.out.println("isChildSafe : " + matchbox15.isChildSafe);
System.out.println("isWaterResistant : " + matchbox15.isWaterResistant);
System.out.println("isReusable : " + matchbox15.isReusable);
System.out.println("isEcoFriendly : " + matchbox15.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox15.manufactureDate);
System.out.println("expiryDate : " + matchbox15.expiryDate);
System.out.println("safetyInstructions : " + matchbox15.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox15.countryOfOrigin);
System.out.println("price : " + matchbox15.price);
System.out.println("quantity : " + matchbox15.quantity);
System.out.println("customerReview : " + matchbox15.customerReview);
System.out.println("rating : " + matchbox15.rating);
System.out.println("isStockAvailable : " + matchbox15.isStockAvailable);
System.out.println("scent : " + matchbox15.scent);



// ---------------- Matchbox 16 ----------------
Matchbox matchbox16 = new Matchbox();
matchbox16.brand = "QuickFire";
matchbox16.type = "Safety";
matchbox16.material = "Wood";
matchbox16.numberOfMatches = 60;
matchbox16.matchHeadMaterial = "Red Phosphorus";
matchbox16.boxColour = "Purple";
matchbox16.packagingType = "Box";
matchbox16.weight = 32.0;
matchbox16.length = 4.8;
matchbox16.width = 3.2;
matchbox16.height = 1.3;
matchbox16.isFlammable = true;
matchbox16.isChildSafe = false;
matchbox16.isWaterResistant = true;
matchbox16.isReusable = false;
matchbox16.isEcoFriendly = true;
matchbox16.manufactureDate = "04-2027";
matchbox16.expiryDate = "04-2031";
matchbox16.safetyInstructions = "Keep away from children and moisture";
matchbox16.countryOfOrigin = "India";
matchbox16.price = 31.0;
matchbox16.quantity = 6;
matchbox16.customerReview = "Safe and long-lasting";
matchbox16.rating = 5;
matchbox16.isStockAvailable = true;
matchbox16.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox16.brand);
System.out.println("type : " + matchbox16.type);
System.out.println("material : " + matchbox16.material);
System.out.println("numberOfMatches : " + matchbox16.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox16.matchHeadMaterial);
System.out.println("boxColour : " + matchbox16.boxColour);
System.out.println("packagingType : " + matchbox16.packagingType);
System.out.println("weight : " + matchbox16.weight);
System.out.println("length : " + matchbox16.length);
System.out.println("width : " + matchbox16.width);
System.out.println("height : " + matchbox16.height);
System.out.println("isFlammable : " + matchbox16.isFlammable);
System.out.println("isChildSafe : " + matchbox16.isChildSafe);
System.out.println("isWaterResistant : " + matchbox16.isWaterResistant);
System.out.println("isReusable : " + matchbox16.isReusable);
System.out.println("isEcoFriendly : " + matchbox16.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox16.manufactureDate);
System.out.println("expiryDate : " + matchbox16.expiryDate);
System.out.println("safetyInstructions : " + matchbox16.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox16.countryOfOrigin);
System.out.println("price : " + matchbox16.price);
System.out.println("quantity : " + matchbox16.quantity);
System.out.println("customerReview : " + matchbox16.customerReview);
System.out.println("rating : " + matchbox16.rating);
System.out.println("isStockAvailable : " + matchbox16.isStockAvailable);
System.out.println("scent : " + matchbox16.scent);

// ---------------- Matchbox 17 ----------------
Matchbox matchbox17 = new Matchbox();
matchbox17.brand = "FireLite";
matchbox17.type = "Strike Anywhere";
matchbox17.material = "Cardboard";
matchbox17.numberOfMatches = 70;
matchbox17.matchHeadMaterial = "Sulfur";
matchbox17.boxColour = "Brown";
matchbox17.packagingType = "Box";
matchbox17.weight = 35.0;
matchbox17.length = 5.0;
matchbox17.width = 3.5;
matchbox17.height = 1.5;
matchbox17.isFlammable = true;
matchbox17.isChildSafe = true;
matchbox17.isWaterResistant = false;
matchbox17.isReusable = false;
matchbox17.isEcoFriendly = false;
matchbox17.manufactureDate = "05-2027";
matchbox17.expiryDate = "05-2031";
matchbox17.safetyInstructions = "Store away from fire and moisture";
matchbox17.countryOfOrigin = "India";
matchbox17.price = 34.0;
matchbox17.quantity = 5;
matchbox17.customerReview = "Reliable matches, easy to light";
matchbox17.rating = 5;
matchbox17.isStockAvailable = true;
matchbox17.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox17.brand);
System.out.println("type : " + matchbox17.type);
System.out.println("material : " + matchbox17.material);
System.out.println("numberOfMatches : " + matchbox17.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox17.matchHeadMaterial);
System.out.println("boxColour : " + matchbox17.boxColour);
System.out.println("packagingType : " + matchbox17.packagingType);
System.out.println("weight : " + matchbox17.weight);
System.out.println("length : " + matchbox17.length);
System.out.println("width : " + matchbox17.width);
System.out.println("height : " + matchbox17.height);
System.out.println("isFlammable : " + matchbox17.isFlammable);
System.out.println("isChildSafe : " + matchbox17.isChildSafe);
System.out.println("isWaterResistant : " + matchbox17.isWaterResistant);
System.out.println("isReusable : " + matchbox17.isReusable);
System.out.println("isEcoFriendly : " + matchbox17.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox17.manufactureDate);
System.out.println("expiryDate : " + matchbox17.expiryDate);
System.out.println("safetyInstructions : " + matchbox17.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox17.countryOfOrigin);
System.out.println("price : " + matchbox17.price);
System.out.println("quantity : " + matchbox17.quantity);
System.out.println("customerReview : " + matchbox17.customerReview);
System.out.println("rating : " + matchbox17.rating);
System.out.println("isStockAvailable : " + matchbox17.isStockAvailable);
System.out.println("scent : " + matchbox17.scent);

// ---------------- Matchbox 18 ----------------
Matchbox matchbox18 = new Matchbox();
matchbox18.brand = "SparkMaster";
matchbox18.type = "Safety";
matchbox18.material = "Wood";
matchbox18.numberOfMatches = 65;
matchbox18.matchHeadMaterial = "Red Phosphorus";
matchbox18.boxColour = "Pink";
matchbox18.packagingType = "Box";
matchbox18.weight = 33.0;
matchbox18.length = 4.9;
matchbox18.width = 3.3;
matchbox18.height = 1.4;
matchbox18.isFlammable = true;
matchbox18.isChildSafe = false;
matchbox18.isWaterResistant = true;
matchbox18.isReusable = false;
matchbox18.isEcoFriendly = true;
matchbox18.manufactureDate = "06-2027";
matchbox18.expiryDate = "06-2031";
matchbox18.safetyInstructions = "Keep away from children and water";
matchbox18.countryOfOrigin = "India";
matchbox18.price = 33.0;
matchbox18.quantity = 5;
matchbox18.customerReview = "Safe and durable";
matchbox18.rating = 5;
matchbox18.isStockAvailable = true;
matchbox18.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox18.brand);
System.out.println("type : " + matchbox18.type);
System.out.println("material : " + matchbox18.material);
System.out.println("numberOfMatches : " + matchbox18.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox18.matchHeadMaterial);
System.out.println("boxColour : " + matchbox18.boxColour);
System.out.println("packagingType : " + matchbox18.packagingType);
System.out.println("weight : " + matchbox18.weight);
System.out.println("length : " + matchbox18.length);
System.out.println("width : " + matchbox18.width);
System.out.println("height : " + matchbox18.height);
System.out.println("isFlammable : " + matchbox18.isFlammable);
System.out.println("isChildSafe : " + matchbox18.isChildSafe);
System.out.println("isWaterResistant : " + matchbox18.isWaterResistant);
System.out.println("isReusable : " + matchbox18.isReusable);
System.out.println("isEcoFriendly : " + matchbox18.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox18.manufactureDate);
System.out.println("expiryDate : " + matchbox18.expiryDate);
System.out.println("safetyInstructions : " + matchbox18.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox18.countryOfOrigin);
System.out.println("price : " + matchbox18.price);
System.out.println("quantity : " + matchbox18.quantity);
System.out.println("customerReview : " + matchbox18.customerReview);
System.out.println("rating : " + matchbox18.rating);
System.out.println("isStockAvailable : " + matchbox18.isStockAvailable);
System.out.println("scent : " + matchbox18.scent);

// ---------------- Matchbox 19 ----------------
Matchbox matchbox19 = new Matchbox();
matchbox19.brand = "FlamePro";
matchbox19.type = "Strike Anywhere";
matchbox19.material = "Cardboard";
matchbox19.numberOfMatches = 72;
matchbox19.matchHeadMaterial = "Sulfur";
matchbox19.boxColour = "White";
matchbox19.packagingType = "Box";
matchbox19.weight = 36.0;
matchbox19.length = 5.1;
matchbox19.width = 3.5;
matchbox19.height = 1.5;
matchbox19.isFlammable = true;
matchbox19.isChildSafe = true;
matchbox19.isWaterResistant = false;
matchbox19.isReusable = false;
matchbox19.isEcoFriendly = false;
matchbox19.manufactureDate = "07-2027";
matchbox19.expiryDate = "07-2031";
matchbox19.safetyInstructions = "Keep away from children and water";
matchbox19.countryOfOrigin = "India";
matchbox19.price = 35.0;
matchbox19.quantity = 6;
matchbox19.customerReview = "Bright flame, good quality";
matchbox19.rating = 5;
matchbox19.isStockAvailable = true;
matchbox19.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox19.brand);
System.out.println("type : " + matchbox19.type);
System.out.println("material : " + matchbox19.material);
System.out.println("numberOfMatches : " + matchbox19.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox19.matchHeadMaterial);
System.out.println("boxColour : " + matchbox19.boxColour);
System.out.println("packagingType : " + matchbox19.packagingType);
System.out.println("weight : " + matchbox19.weight);
System.out.println("length : " + matchbox19.length);
System.out.println("width : " + matchbox19.width);
System.out.println("height : " + matchbox19.height);
System.out.println("isFlammable : " + matchbox19.isFlammable);
System.out.println("isChildSafe : " + matchbox19.isChildSafe);
System.out.println("isWaterResistant : " + matchbox19.isWaterResistant);
System.out.println("isReusable : " + matchbox19.isReusable);
System.out.println("isEcoFriendly : " + matchbox19.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox19.manufactureDate);
System.out.println("expiryDate : " + matchbox19.expiryDate);
System.out.println("safetyInstructions : " + matchbox19.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox19.countryOfOrigin);
System.out.println("price : " + matchbox19.price);
System.out.println("quantity : " + matchbox19.quantity);
System.out.println("customerReview : " + matchbox19.customerReview);
System.out.println("rating : " + matchbox19.rating);
System.out.println("isStockAvailable : " + matchbox19.isStockAvailable);
System.out.println("scent : " + matchbox19.scent);

// ---------------- Matchbox 20 ----------------
Matchbox matchbox20 = new Matchbox();
matchbox20.brand = "SafeSpark";
matchbox20.type = "Safety";
matchbox20.material = "Wood";
matchbox20.numberOfMatches = 68;
matchbox20.matchHeadMaterial = "Red Phosphorus";
matchbox20.boxColour = "Orange";
matchbox20.packagingType = "Box";
matchbox20.weight = 34.0;
matchbox20.length = 5.0;
matchbox20.width = 3.4;
matchbox20.height = 1.4;
matchbox20.isFlammable = true;
matchbox20.isChildSafe = false;
matchbox20.isWaterResistant = true;
matchbox20.isReusable = false;
matchbox20.isEcoFriendly = true;
matchbox20.manufactureDate = "08-2027";
matchbox20.expiryDate = "08-2031";
matchbox20.safetyInstructions = "Keep away from fire and children";
matchbox20.countryOfOrigin = "India";
matchbox20.price = 33.0;
matchbox20.quantity = 5;
matchbox20.customerReview = "Safe and reliable";
matchbox20.rating = 5;
matchbox20.isStockAvailable = true;
matchbox20.scent = "None";

System.out.println("after init instance variable");
System.out.println("brand : " + matchbox20.brand);
System.out.println("type : " + matchbox20.type);
System.out.println("material : " + matchbox20.material);
System.out.println("numberOfMatches : " + matchbox20.numberOfMatches);
System.out.println("matchHeadMaterial : " + matchbox20.matchHeadMaterial);
System.out.println("boxColour : " + matchbox20.boxColour);
System.out.println("packagingType : " + matchbox20.packagingType);
System.out.println("weight : " + matchbox20.weight);
System.out.println("length : " + matchbox20.length);
System.out.println("width : " + matchbox20.width);
System.out.println("height : " + matchbox20.height);
System.out.println("isFlammable : " + matchbox20.isFlammable);
System.out.println("isChildSafe : " + matchbox20.isChildSafe);
System.out.println("isWaterResistant : " + matchbox20.isWaterResistant);
System.out.println("isReusable : " + matchbox20.isReusable);
System.out.println("isEcoFriendly : " + matchbox20.isEcoFriendly);
System.out.println("manufactureDate : " + matchbox20.manufactureDate);
System.out.println("expiryDate : " + matchbox20.expiryDate);
System.out.println("safetyInstructions : " + matchbox20.safetyInstructions);
System.out.println("countryOfOrigin : " + matchbox20.countryOfOrigin);
System.out.println("price : " + matchbox20.price);
System.out.println("quantity : " + matchbox20.quantity);
System.out.println("customerReview : " + matchbox20.customerReview);
System.out.println("rating : " + matchbox20.rating);
System.out.println("isStockAvailable : " + matchbox20.isStockAvailable);
System.out.println("scent : " + matchbox20.scent);


}
}