class SunGlassExecutor {
    public static void main(String[] args) {
        // ---------------- Sunglass 1 ----------------
        Sunglass sunglass1 = new Sunglass();
        sunglass1.brand="Ray-Ban";
        sunglass1.model="Aviator Classic";
        sunglass1.frameMaterial="Metal";
        sunglass1.lensMaterial="Glass";
        sunglass1.lensColour="Green";
        sunglass1.frameColour="Gold";
        sunglass1.shape="Aviator";
        sunglass1.isUVProtected=true;
        sunglass1.isPolarized=true;
        sunglass1.isScratchResistant=true;
        sunglass1.isWaterResistant=false;
        sunglass1.isAntiReflective=true;
        sunglass1.isLightweight=true;
        sunglass1.price=12000;
        sunglass1.quantity=2;
        sunglass1.weight=25;
        sunglass1.gender="Unisex";
        sunglass1.style="Classic";
        sunglass1.countryOfOrigin="Italy";
        sunglass1.sellerName="Ray-Ban Official Store";
        sunglass1.warranty="1 Year";
        sunglass1.rating=5;
        sunglass1.customerReview="Stylish and durable!";
        sunglass1.isStockAvailable=true;
        sunglass1.packagingType="Box";

        System.out.println("Brand: "+sunglass1.brand);
        System.out.println("Model: "+sunglass1.model);
        System.out.println("Frame Material: "+sunglass1.frameMaterial);
        System.out.println("Lens Material: "+sunglass1.lensMaterial);
        System.out.println("Lens Colour: "+sunglass1.lensColour);
        System.out.println("Frame Colour: "+sunglass1.frameColour);
        System.out.println("Shape: "+sunglass1.shape);
        System.out.println("UV Protected: "+sunglass1.isUVProtected);
        System.out.println("Polarized: "+sunglass1.isPolarized);
        System.out.println("Scratch Resistant: "+sunglass1.isScratchResistant);
        System.out.println("Water Resistant: "+sunglass1.isWaterResistant);
        System.out.println("Anti Reflective: "+sunglass1.isAntiReflective);
        System.out.println("Lightweight: "+sunglass1.isLightweight);
        System.out.println("Price: "+sunglass1.price);
        System.out.println("Quantity: "+sunglass1.quantity);
        System.out.println("Weight: "+sunglass1.weight);
        System.out.println("Gender: "+sunglass1.gender);
        System.out.println("Style: "+sunglass1.style);
        System.out.println("Country: "+sunglass1.countryOfOrigin);
        System.out.println("Seller: "+sunglass1.sellerName);
        System.out.println("Warranty: "+sunglass1.warranty);
        System.out.println("Rating: "+sunglass1.rating);
        System.out.println("Customer Review: "+sunglass1.customerReview);
        System.out.println("Stock Available: "+sunglass1.isStockAvailable);
        System.out.println("Packaging: "+sunglass1.packagingType);

        // ---------------- Sunglass 2 ----------------
        Sunglass sunglass2 = new Sunglass();
        sunglass2.brand="Oakley";
        sunglass2.model="Holbrook";
        sunglass2.frameMaterial="Plastic";
        sunglass2.lensMaterial="Polycarbonate";
        sunglass2.lensColour="Black";
        sunglass2.frameColour="Matte Black";
        sunglass2.shape="Square";
        sunglass2.isUVProtected=true;
        sunglass2.isPolarized=true;
        sunglass2.isScratchResistant=true;
        sunglass2.isWaterResistant=true;
        sunglass2.isAntiReflective=false;
        sunglass2.isLightweight=true;
        sunglass2.price=8500;
        sunglass2.quantity=3;
        sunglass2.weight=30;
        sunglass2.gender="Male";
        sunglass2.style="Sport";
        sunglass2.countryOfOrigin="USA";
        sunglass2.sellerName="Oakley Store";
        sunglass2.warranty="2 Years";
        sunglass2.rating=4;
        sunglass2.customerReview="Good for outdoor activities";
        sunglass2.isStockAvailable=true;
        sunglass2.packagingType="Case";

        System.out.println("\nBrand: "+sunglass2.brand);
        System.out.println("Model: "+sunglass2.model);
        System.out.println("Frame Material: "+sunglass2.frameMaterial);
        System.out.println("Lens Material: "+sunglass2.lensMaterial);
        System.out.println("Lens Colour: "+sunglass2.lensColour);
        System.out.println("Frame Colour: "+sunglass2.frameColour);
        System.out.println("Shape: "+sunglass2.shape);
        System.out.println("UV Protected: "+sunglass2.isUVProtected);
        System.out.println("Polarized: "+sunglass2.isPolarized);
        System.out.println("Scratch Resistant: "+sunglass2.isScratchResistant);
        System.out.println("Water Resistant: "+sunglass2.isWaterResistant);
        System.out.println("Anti Reflective: "+sunglass2.isAntiReflective);
        System.out.println("Lightweight: "+sunglass2.isLightweight);
        System.out.println("Price: "+sunglass2.price);
        System.out.println("Quantity: "+sunglass2.quantity);
        System.out.println("Weight: "+sunglass2.weight);
        System.out.println("Gender: "+sunglass2.gender);
        System.out.println("Style: "+sunglass2.style);
        System.out.println("Country: "+sunglass2.countryOfOrigin);
        System.out.println("Seller: "+sunglass2.sellerName);
        System.out.println("Warranty: "+sunglass2.warranty);
        System.out.println("Rating: "+sunglass2.rating);
        System.out.println("Customer Review: "+sunglass2.customerReview);
        System.out.println("Stock Available: "+sunglass2.isStockAvailable);
        System.out.println("Packaging: "+sunglass2.packagingType);
		
		
		
		// ---------------- Sunglass 3 ----------------
Sunglass sunglass3 = new Sunglass();
sunglass3.brand="Fastrack";
sunglass3.model="Ranger";
sunglass3.frameMaterial="Plastic";
sunglass3.lensMaterial="Polycarbonate";
sunglass3.lensColour="Brown";
sunglass3.frameColour="Black";
sunglass3.shape="Round";
sunglass3.isUVProtected=true;
sunglass3.isPolarized=false;
sunglass3.isScratchResistant=true;
sunglass3.isWaterResistant=false;
sunglass3.isAntiReflective=false;
sunglass3.isLightweight=true;
sunglass3.price=3500;
sunglass3.quantity=5;
sunglass3.weight=20;
sunglass3.gender="Unisex";
sunglass3.style="Casual";
sunglass3.countryOfOrigin="India";
sunglass3.sellerName="Fastrack Store";
sunglass3.warranty="6 Months";
sunglass3.rating=4;
sunglass3.customerReview="Trendy and lightweight";
sunglass3.isStockAvailable=true;
sunglass3.packagingType="Box";

System.out.println("\nBrand: "+sunglass3.brand);
System.out.println("Model: "+sunglass3.model);
System.out.println("Frame Material: "+sunglass3.frameMaterial);
System.out.println("Lens Material: "+sunglass3.lensMaterial);
System.out.println("Lens Colour: "+sunglass3.lensColour);
System.out.println("Frame Colour: "+sunglass3.frameColour);
System.out.println("Shape: "+sunglass3.shape);
System.out.println("UV Protected: "+sunglass3.isUVProtected);
System.out.println("Polarized: "+sunglass3.isPolarized);
System.out.println("Scratch Resistant: "+sunglass3.isScratchResistant);
System.out.println("Water Resistant: "+sunglass3.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass3.isAntiReflective);
System.out.println("Lightweight: "+sunglass3.isLightweight);
System.out.println("Price: "+sunglass3.price);
System.out.println("Quantity: "+sunglass3.quantity);
System.out.println("Weight: "+sunglass3.weight);
System.out.println("Gender: "+sunglass3.gender);
System.out.println("Style: "+sunglass3.style);
System.out.println("Country: "+sunglass3.countryOfOrigin);
System.out.println("Seller: "+sunglass3.sellerName);
System.out.println("Warranty: "+sunglass3.warranty);
System.out.println("Rating: "+sunglass3.rating);
System.out.println("Customer Review: "+sunglass3.customerReview);
System.out.println("Stock Available: "+sunglass3.isStockAvailable);
System.out.println("Packaging: "+sunglass3.packagingType);

// ---------------- Sunglass 4 ----------------
Sunglass sunglass4 = new Sunglass();
sunglass4.brand="Polaroid";
sunglass4.model="PLD 101";
sunglass4.frameMaterial="Metal";
sunglass4.lensMaterial="Glass";
sunglass4.lensColour="Blue";
sunglass4.frameColour="Silver";
sunglass4.shape="Square";
sunglass4.isUVProtected=true;
sunglass4.isPolarized=true;
sunglass4.isScratchResistant=false;
sunglass4.isWaterResistant=true;
sunglass4.isAntiReflective=true;
sunglass4.isLightweight=true;
sunglass4.price=4500;
sunglass4.quantity=4;
sunglass4.weight=22;
sunglass4.gender="Female";
sunglass4.style="Fashion";
sunglass4.countryOfOrigin="Italy";
sunglass4.sellerName="Polaroid Store";
sunglass4.warranty="1 Year";
sunglass4.rating=5;
sunglass4.customerReview="Stylish and safe for UV";
sunglass4.isStockAvailable=true;
sunglass4.packagingType="Box";

System.out.println("\nBrand: "+sunglass4.brand);
System.out.println("Model: "+sunglass4.model);
System.out.println("Frame Material: "+sunglass4.frameMaterial);
System.out.println("Lens Material: "+sunglass4.lensMaterial);
System.out.println("Lens Colour: "+sunglass4.lensColour);
System.out.println("Frame Colour: "+sunglass4.frameColour);
System.out.println("Shape: "+sunglass4.shape);
System.out.println("UV Protected: "+sunglass4.isUVProtected);
System.out.println("Polarized: "+sunglass4.isPolarized);
System.out.println("Scratch Resistant: "+sunglass4.isScratchResistant);
System.out.println("Water Resistant: "+sunglass4.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass4.isAntiReflective);
System.out.println("Lightweight: "+sunglass4.isLightweight);
System.out.println("Price: "+sunglass4.price);
System.out.println("Quantity: "+sunglass4.quantity);
System.out.println("Weight: "+sunglass4.weight);
System.out.println("Gender: "+sunglass4.gender);
System.out.println("Style: "+sunglass4.style);
System.out.println("Country: "+sunglass4.countryOfOrigin);
System.out.println("Seller: "+sunglass4.sellerName);
System.out.println("Warranty: "+sunglass4.warranty);
System.out.println("Rating: "+sunglass4.rating);
System.out.println("Customer Review: "+sunglass4.customerReview);
System.out.println("Stock Available: "+sunglass4.isStockAvailable);
System.out.println("Packaging: "+sunglass4.packagingType);

// ---------------- Sunglass 5 ----------------
Sunglass sunglass5 = new Sunglass();
sunglass5.brand="Nike";
sunglass5.model="Vision X";
sunglass5.frameMaterial="Plastic";
sunglass5.lensMaterial="Polycarbonate";
sunglass5.lensColour="Grey";
sunglass5.frameColour="Black";
sunglass5.shape="Rectangle";
sunglass5.isUVProtected=true;
sunglass5.isPolarized=false;
sunglass5.isScratchResistant=true;
sunglass5.isWaterResistant=true;
sunglass5.isAntiReflective=false;
sunglass5.isLightweight=true;
sunglass5.price=5000;
sunglass5.quantity=6;
sunglass5.weight=24;
sunglass5.gender="Male";
sunglass5.style="Sports";
sunglass5.countryOfOrigin="USA";
sunglass5.sellerName="Nike Store";
sunglass5.warranty="1 Year";
sunglass5.rating=4;
sunglass5.customerReview="Perfect for outdoor sports";
sunglass5.isStockAvailable=true;
sunglass5.packagingType="Box";

System.out.println("\nBrand: "+sunglass5.brand);
System.out.println("Model: "+sunglass5.model);
System.out.println("Frame Material: "+sunglass5.frameMaterial);
System.out.println("Lens Material: "+sunglass5.lensMaterial);
System.out.println("Lens Colour: "+sunglass5.lensColour);
System.out.println("Frame Colour: "+sunglass5.frameColour);
System.out.println("Shape: "+sunglass5.shape);
System.out.println("UV Protected: "+sunglass5.isUVProtected);
System.out.println("Polarized: "+sunglass5.isPolarized);
System.out.println("Scratch Resistant: "+sunglass5.isScratchResistant);
System.out.println("Water Resistant: "+sunglass5.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass5.isAntiReflective);
System.out.println("Lightweight: "+sunglass5.isLightweight);
System.out.println("Price: "+sunglass5.price);
System.out.println("Quantity: "+sunglass5.quantity);
System.out.println("Weight: "+sunglass5.weight);
System.out.println("Gender: "+sunglass5.gender);
System.out.println("Style: "+sunglass5.style);
System.out.println("Country: "+sunglass5.countryOfOrigin);
System.out.println("Seller: "+sunglass5.sellerName);
System.out.println("Warranty: "+sunglass5.warranty);
System.out.println("Rating: "+sunglass5.rating);
System.out.println("Customer Review: "+sunglass5.customerReview);
System.out.println("Stock Available: "+sunglass5.isStockAvailable);
System.out.println("Packaging: "+sunglass5.packagingType);

// ---------------- Sunglass 6 ----------------
Sunglass sunglass6 = new Sunglass();
sunglass6.brand="Adidas";
sunglass6.model="Runner Pro";
sunglass6.frameMaterial="Metal";
sunglass6.lensMaterial="Glass";
sunglass6.lensColour="Blue";
sunglass6.frameColour="Silver";
sunglass6.shape="Oval";
sunglass6.isUVProtected=true;
sunglass6.isPolarized=true;
sunglass6.isScratchResistant=false;
sunglass6.isWaterResistant=true;
sunglass6.isAntiReflective=true;
sunglass6.isLightweight=false;
sunglass6.price=6000;
sunglass6.quantity=4;
sunglass6.weight=28;
sunglass6.gender="Unisex";
sunglass6.style="Casual";
sunglass6.countryOfOrigin="Germany";
sunglass6.sellerName="Adidas Official Store";
sunglass6.warranty="2 Years";
sunglass6.rating=5;
sunglass6.customerReview="Comfortable and durable";
sunglass6.isStockAvailable=true;
sunglass6.packagingType="Case";

System.out.println("\nBrand: "+sunglass6.brand);
System.out.println("Model: "+sunglass6.model);
System.out.println("Frame Material: "+sunglass6.frameMaterial);
System.out.println("Lens Material: "+sunglass6.lensMaterial);
System.out.println("Lens Colour: "+sunglass6.lensColour);
System.out.println("Frame Colour: "+sunglass6.frameColour);
System.out.println("Shape: "+sunglass6.shape);
System.out.println("UV Protected: "+sunglass6.isUVProtected);
System.out.println("Polarized: "+sunglass6.isPolarized);
System.out.println("Scratch Resistant: "+sunglass6.isScratchResistant);
System.out.println("Water Resistant: "+sunglass6.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass6.isAntiReflective);
System.out.println("Lightweight: "+sunglass6.isLightweight);
System.out.println("Price: "+sunglass6.price);
System.out.println("Quantity: "+sunglass6.quantity);
System.out.println("Weight: "+sunglass6.weight);
System.out.println("Gender: "+sunglass6.gender);
System.out.println("Style: "+sunglass6.style);
System.out.println("Country: "+sunglass6.countryOfOrigin);
System.out.println("Seller: "+sunglass6.sellerName);
System.out.println("Warranty: "+sunglass6.warranty);
System.out.println("Rating: "+sunglass6.rating);
System.out.println("Customer Review: "+sunglass6.customerReview);
System.out.println("Stock Available: "+sunglass6.isStockAvailable);
System.out.println("Packaging: "+sunglass6.packagingType);

// ---------------- Sunglass 7 ----------------
Sunglass sunglass7 = new Sunglass();
sunglass7.brand="Puma";
sunglass7.model="Speedster";
sunglass7.frameMaterial="Plastic";
sunglass7.lensMaterial="Polycarbonate";
sunglass7.lensColour="Black";
sunglass7.frameColour="Red";
sunglass7.shape="Rectangle";
sunglass7.isUVProtected=true;
sunglass7.isPolarized=false;
sunglass7.isScratchResistant=true;
sunglass7.isWaterResistant=false;
sunglass7.isAntiReflective=false;
sunglass7.isLightweight=true;
sunglass7.price=4000;
sunglass7.quantity=5;
sunglass7.weight=23;
sunglass7.gender="Male";
sunglass7.style="Sports";
sunglass7.countryOfOrigin="USA";
sunglass7.sellerName="Puma Store";
sunglass7.warranty="1 Year";
sunglass7.rating=4;
sunglass7.customerReview="Good for running";
sunglass7.isStockAvailable=true;
sunglass7.packagingType="Box";
System.out.println("\nBrand: "+sunglass7.brand);
System.out.println("Model: "+sunglass7.model);
System.out.println("Frame Material: "+sunglass7.frameMaterial);
System.out.println("Lens Material: "+sunglass7.lensMaterial);
System.out.println("Lens Colour: "+sunglass7.lensColour);
System.out.println("Frame Colour: "+sunglass7.frameColour);
System.out.println("Shape: "+sunglass7.shape);
System.out.println("UV Protected: "+sunglass7.isUVProtected);
System.out.println("Polarized: "+sunglass7.isPolarized);
System.out.println("Scratch Resistant: "+sunglass7.isScratchResistant);
System.out.println("Water Resistant: "+sunglass7.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass7.isAntiReflective);
System.out.println("Lightweight: "+sunglass7.isLightweight);
System.out.println("Price: "+sunglass7.price);
System.out.println("Quantity: "+sunglass7.quantity);
System.out.println("Weight: "+sunglass7.weight);
System.out.println("Gender: "+sunglass7.gender);
System.out.println("Style: "+sunglass7.style);
System.out.println("Country: "+sunglass7.countryOfOrigin);
System.out.println("Seller: "+sunglass7.sellerName);
System.out.println("Warranty: "+sunglass7.warranty);
System.out.println("Rating: "+sunglass7.rating);
System.out.println("Customer Review: "+sunglass7.customerReview);
System.out.println("Stock Available: "+sunglass7.isStockAvailable);
System.out.println("Packaging: "+sunglass7.packagingType);


// ---------------- Sunglass 8 ----------------
Sunglass sunglass8 = new Sunglass();
sunglass8.brand="Ray-Ban";
sunglass8.model="Wayfarer";
sunglass8.frameMaterial="Plastic";
sunglass8.lensMaterial="Glass";
sunglass8.lensColour="Brown";
sunglass8.frameColour="Black";
sunglass8.shape="Square";
sunglass8.isUVProtected=true;
sunglass8.isPolarized=true;
sunglass8.isScratchResistant=true;
sunglass8.isWaterResistant=false;
sunglass8.isAntiReflective=false;
sunglass8.isLightweight=true;
sunglass8.price=6500;
sunglass8.quantity=3;
sunglass8.weight=26;
sunglass8.gender="Unisex";
sunglass8.style="Classic";
sunglass8.countryOfOrigin="Italy";
sunglass8.sellerName="Ray-Ban Official Store";
sunglass8.warranty="1 Year";
sunglass8.rating=5;
sunglass8.customerReview="Stylish and durable";
sunglass8.isStockAvailable=true;
sunglass8.packagingType="Box";

System.out.println("\nBrand: "+sunglass8.brand);
System.out.println("Model: "+sunglass8.model);
System.out.println("Frame Material: "+sunglass8.frameMaterial);
System.out.println("Lens Material: "+sunglass8.lensMaterial);
System.out.println("Lens Colour: "+sunglass8.lensColour);
System.out.println("Frame Colour: "+sunglass8.frameColour);
System.out.println("Shape: "+sunglass8.shape);
System.out.println("UV Protected: "+sunglass8.isUVProtected);
System.out.println("Polarized: "+sunglass8.isPolarized);
System.out.println("Scratch Resistant: "+sunglass8.isScratchResistant);
System.out.println("Water Resistant: "+sunglass8.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass8.isAntiReflective);
System.out.println("Lightweight: "+sunglass8.isLightweight);
System.out.println("Price: "+sunglass8.price);
System.out.println("Quantity: "+sunglass8.quantity);
System.out.println("Weight: "+sunglass8.weight);
System.out.println("Gender: "+sunglass8.gender);
System.out.println("Style: "+sunglass8.style);
System.out.println("Country: "+sunglass8.countryOfOrigin);
System.out.println("Seller: "+sunglass8.sellerName);
System.out.println("Warranty: "+sunglass8.warranty);
System.out.println("Rating: "+sunglass8.rating);
System.out.println("Customer Review: "+sunglass8.customerReview);
System.out.println("Stock Available: "+sunglass8.isStockAvailable);
System.out.println("Packaging: "+sunglass8.packagingType);

// ---------------- Sunglass 9 ----------------
Sunglass sunglass9 = new Sunglass();
sunglass9.brand="Oakley";
sunglass9.model="Holbrook";
sunglass9.frameMaterial="Metal";
sunglass9.lensMaterial="Polycarbonate";
sunglass9.lensColour="Grey";
sunglass9.frameColour="Matte Black";
sunglass9.shape="Rectangle";
sunglass9.isUVProtected=true;
sunglass9.isPolarized=true;
sunglass9.isScratchResistant=true;
sunglass9.isWaterResistant=false;
sunglass9.isAntiReflective=true;
sunglass9.isLightweight=true;
sunglass9.price=7000;
sunglass9.quantity=4;
sunglass9.weight=28;
sunglass9.gender="Male";
sunglass9.style="Sports";
sunglass9.countryOfOrigin="USA";
sunglass9.sellerName="Oakley Store";
sunglass9.warranty="1 Year";
sunglass9.rating=5;
sunglass9.customerReview="Perfect for outdoor activities";
sunglass9.isStockAvailable=true;
sunglass9.packagingType="Case";

System.out.println("\nBrand: "+sunglass9.brand);
System.out.println("Model: "+sunglass9.model);
System.out.println("Frame Material: "+sunglass9.frameMaterial);
System.out.println("Lens Material: "+sunglass9.lensMaterial);
System.out.println("Lens Colour: "+sunglass9.lensColour);
System.out.println("Frame Colour: "+sunglass9.frameColour);
System.out.println("Shape: "+sunglass9.shape);
System.out.println("UV Protected: "+sunglass9.isUVProtected);
System.out.println("Polarized: "+sunglass9.isPolarized);
System.out.println("Scratch Resistant: "+sunglass9.isScratchResistant);
System.out.println("Water Resistant: "+sunglass9.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass9.isAntiReflective);
System.out.println("Lightweight: "+sunglass9.isLightweight);
System.out.println("Price: "+sunglass9.price);
System.out.println("Quantity: "+sunglass9.quantity);
System.out.println("Weight: "+sunglass9.weight);
System.out.println("Gender: "+sunglass9.gender);
System.out.println("Style: "+sunglass9.style);
System.out.println("Country: "+sunglass9.countryOfOrigin);
System.out.println("Seller: "+sunglass9.sellerName);
System.out.println("Warranty: "+sunglass9.warranty);
System.out.println("Rating: "+sunglass9.rating);
System.out.println("Customer Review: "+sunglass9.customerReview);
System.out.println("Stock Available: "+sunglass9.isStockAvailable);
System.out.println("Packaging: "+sunglass9.packagingType);

// ---------------- Sunglass 10 ----------------
Sunglass sunglass10 = new Sunglass();
sunglass10.brand="Gucci";
sunglass10.model="GG0061S";
sunglass10.frameMaterial="Metal";
sunglass10.lensMaterial="Glass";
sunglass10.lensColour="Dark Brown";
sunglass10.frameColour="Gold";
sunglass10.shape="Aviator";
sunglass10.isUVProtected=true;
sunglass10.isPolarized=true;
sunglass10.isScratchResistant=true;
sunglass10.isWaterResistant=false;
sunglass10.isAntiReflective=true;
sunglass10.isLightweight=false;
sunglass10.price=15000;
sunglass10.quantity=2;
sunglass10.weight=30;
sunglass10.gender="Unisex";
sunglass10.style="Luxury";
sunglass10.countryOfOrigin="Italy";
sunglass10.sellerName="Gucci Official Store";
sunglass10.warranty="2 Years";
sunglass10.rating=5;
sunglass10.customerReview="Premium and stylish";
sunglass10.isStockAvailable=true;
sunglass10.packagingType="Box";

System.out.println("\nBrand: "+sunglass10.brand);
System.out.println("Model: "+sunglass10.model);
System.out.println("Frame Material: "+sunglass10.frameMaterial);
System.out.println("Lens Material: "+sunglass10.lensMaterial);
System.out.println("Lens Colour: "+sunglass10.lensColour);
System.out.println("Frame Colour: "+sunglass10.frameColour);
System.out.println("Shape: "+sunglass10.shape);
System.out.println("UV Protected: "+sunglass10.isUVProtected);
System.out.println("Polarized: "+sunglass10.isPolarized);
System.out.println("Scratch Resistant: "+sunglass10.isScratchResistant);
System.out.println("Water Resistant: "+sunglass10.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass10.isAntiReflective);
System.out.println("Lightweight: "+sunglass10.isLightweight);
System.out.println("Price: "+sunglass10.price);
System.out.println("Quantity: "+sunglass10.quantity);
System.out.println("Weight: "+sunglass10.weight);
System.out.println("Gender: "+sunglass10.gender);
System.out.println("Style: "+sunglass10.style);
System.out.println("Country: "+sunglass10.countryOfOrigin);
System.out.println("Seller: "+sunglass10.sellerName);
System.out.println("Warranty: "+sunglass10.warranty);
System.out.println("Rating: "+sunglass10.rating);
System.out.println("Customer Review: "+sunglass10.customerReview);
System.out.println("Stock Available: "+sunglass10.isStockAvailable);
System.out.println("Packaging: "+sunglass10.packagingType);


// ---------------- Sunglass 11 ----------------
Sunglass sunglass11 = new Sunglass();
sunglass11.brand="Prada";
sunglass11.model="PR01OS";
sunglass11.frameMaterial="Acetate";
sunglass11.lensMaterial="Glass";
sunglass11.lensColour="Grey";
sunglass11.frameColour="Black";
sunglass11.shape="Square";
sunglass11.isUVProtected=true;
sunglass11.isPolarized=true;
sunglass11.isScratchResistant=true;
sunglass11.isWaterResistant=false;
sunglass11.isAntiReflective=true;
sunglass11.isLightweight=false;
sunglass11.price=14000;
sunglass11.quantity=2;
sunglass11.weight=32;
sunglass11.gender="Female";
sunglass11.style="Luxury";
sunglass11.countryOfOrigin="Italy";
sunglass11.sellerName="Prada Official Store";
sunglass11.warranty="2 Years";
sunglass11.rating=5;
sunglass11.customerReview="Elegant and durable";
sunglass11.isStockAvailable=true;
sunglass11.packagingType="Box";

System.out.println("\nBrand: "+sunglass11.brand);
System.out.println("Model: "+sunglass11.model);
System.out.println("Frame Material: "+sunglass11.frameMaterial);
System.out.println("Lens Material: "+sunglass11.lensMaterial);
System.out.println("Lens Colour: "+sunglass11.lensColour);
System.out.println("Frame Colour: "+sunglass11.frameColour);
System.out.println("Shape: "+sunglass11.shape);
System.out.println("UV Protected: "+sunglass11.isUVProtected);
System.out.println("Polarized: "+sunglass11.isPolarized);
System.out.println("Scratch Resistant: "+sunglass11.isScratchResistant);
System.out.println("Water Resistant: "+sunglass11.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass11.isAntiReflective);
System.out.println("Lightweight: "+sunglass11.isLightweight);
System.out.println("Price: "+sunglass11.price);
System.out.println("Quantity: "+sunglass11.quantity);
System.out.println("Weight: "+sunglass11.weight);
System.out.println("Gender: "+sunglass11.gender);
System.out.println("Style: "+sunglass11.style);
System.out.println("Country: "+sunglass11.countryOfOrigin);
System.out.println("Seller: "+sunglass11.sellerName);
System.out.println("Warranty: "+sunglass11.warranty);
System.out.println("Rating: "+sunglass11.rating);
System.out.println("Customer Review: "+sunglass11.customerReview);
System.out.println("Stock Available: "+sunglass11.isStockAvailable);
System.out.println("Packaging: "+sunglass11.packagingType);

// ---------------- Sunglass 12 ----------------
Sunglass sunglass12 = new Sunglass();
sunglass12.brand="Tom Ford";
sunglass12.model="FT0524";
sunglass12.frameMaterial="Metal";
sunglass12.lensMaterial="Polycarbonate";
sunglass12.lensColour="Brown";
sunglass12.frameColour="Gold";
sunglass12.shape="Aviator";
sunglass12.isUVProtected=true;
sunglass12.isPolarized=false;
sunglass12.isScratchResistant=true;
sunglass12.isWaterResistant=false;
sunglass12.isAntiReflective=true;
sunglass12.isLightweight=true;
sunglass12.price=16000;
sunglass12.quantity=3;
sunglass12.weight=28;
sunglass12.gender="Unisex";
sunglass12.style="Luxury";
sunglass12.countryOfOrigin="Italy";
sunglass12.sellerName="Tom Ford Store";
sunglass12.warranty="2 Years";
sunglass12.rating=5;
sunglass12.customerReview="High-end and stylish";
sunglass12.isStockAvailable=true;
sunglass12.packagingType="Box";

System.out.println("\nBrand: "+sunglass12.brand);
System.out.println("Model: "+sunglass12.model);
System.out.println("Frame Material: "+sunglass12.frameMaterial);
System.out.println("Lens Material: "+sunglass12.lensMaterial);
System.out.println("Lens Colour: "+sunglass12.lensColour);
System.out.println("Frame Colour: "+sunglass12.frameColour);
System.out.println("Shape: "+sunglass12.shape);
System.out.println("UV Protected: "+sunglass12.isUVProtected);
System.out.println("Polarized: "+sunglass12.isPolarized);
System.out.println("Scratch Resistant: "+sunglass12.isScratchResistant);
System.out.println("Water Resistant: "+sunglass12.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass12.isAntiReflective);
System.out.println("Lightweight: "+sunglass12.isLightweight);
System.out.println("Price: "+sunglass12.price);
System.out.println("Quantity: "+sunglass12.quantity);
System.out.println("Weight: "+sunglass12.weight);
System.out.println("Gender: "+sunglass12.gender);
System.out.println("Style: "+sunglass12.style);
System.out.println("Country: "+sunglass12.countryOfOrigin);
System.out.println("Seller: "+sunglass12.sellerName);
System.out.println("Warranty: "+sunglass12.warranty);
System.out.println("Rating: "+sunglass12.rating);
System.out.println("Customer Review: "+sunglass12.customerReview);
System.out.println("Stock Available: "+sunglass12.isStockAvailable);
System.out.println("Packaging: "+sunglass12.packagingType);

// ---------------- Sunglass 13 ----------------
Sunglass sunglass13 = new Sunglass();
sunglass13.brand="Maui Jim";
sunglass13.model="Peahi";
sunglass13.frameMaterial="Nylon";
sunglass13.lensMaterial="Glass";
sunglass13.lensColour="Blue";
sunglass13.frameColour="Black";
sunglass13.shape="Rectangle";
sunglass13.isUVProtected=true;
sunglass13.isPolarized=true;
sunglass13.isScratchResistant=true;
sunglass13.isWaterResistant=true;
sunglass13.isAntiReflective=false;
sunglass13.isLightweight=true;
sunglass13.price=12000;
sunglass13.quantity=2;
sunglass13.weight=27;
sunglass13.gender="Unisex";
sunglass13.style="Sport";
sunglass13.countryOfOrigin="USA";
sunglass13.sellerName="Maui Jim Official";
sunglass13.warranty="1 Year";
sunglass13.rating=5;
sunglass13.customerReview="Great for beach and sports";
sunglass13.isStockAvailable=true;
sunglass13.packagingType="Case";

System.out.println("\nBrand: "+sunglass13.brand);
System.out.println("Model: "+sunglass13.model);
System.out.println("Frame Material: "+sunglass13.frameMaterial);
System.out.println("Lens Material: "+sunglass13.lensMaterial);
System.out.println("Lens Colour: "+sunglass13.lensColour);
System.out.println("Frame Colour: "+sunglass13.frameColour);
System.out.println("Shape: "+sunglass13.shape);
System.out.println("UV Protected: "+sunglass13.isUVProtected);
System.out.println("Polarized: "+sunglass13.isPolarized);
System.out.println("Scratch Resistant: "+sunglass13.isScratchResistant);
System.out.println("Water Resistant: "+sunglass13.isWaterResistant);
System.out.println("Anti Reflective: "+sunglass13.isAntiReflective);
System.out.println("Lightweight: "+sunglass13.isLightweight);
System.out.println("Price: "+sunglass13.price);
System.out.println("Quantity: "+sunglass13.quantity);
System.out.println("Weight: "+sunglass13.weight);
System.out.println("Gender: "+sunglass13.gender);
System.out.println("Style: "+sunglass13.style);
System.out.println("Country: "+sunglass13.countryOfOrigin);
System.out.println("Seller: "+sunglass13.sellerName);
System.out.println("Warranty: "+sunglass13.warranty);
System.out.println("Rating: "+sunglass13.rating);
System.out.println("Customer Review: "+sunglass13.customerReview);
System.out.println("Stock Available: "+sunglass13.isStockAvailable);
System.out.println("Packaging: "+sunglass13.packagingType);

// ---------------- Sunglass 14 ----------------
Sunglass sunglass14 = new Sunglass();
sunglass14.brand="Persol";
sunglass14.model="PO0649";
sunglass14.frameMaterial="Acetate";
sunglass14.lensMaterial="Glass";
sunglass14.lensColour="Grey";
sunglass14.frameColour="Tortoise";
sunglass14.shape="Round";
sunglass14.isUVProtected=true;
sunglass14.isPolarized=true;
sunglass14.isScratchResistant=true;
sunglass14.isWaterResistant=false;
sunglass14.isAntiReflective=false;
sunglass14.isLightweight=true;
sunglass14.price=11000;
sunglass14.quantity=2;
sunglass14.weight=29;
sunglass14.gender="Male";
sunglass14.style="Classic";
sunglass14.countryOfOrigin="Italy";
sunglass14.sellerName="Persol Official";
sunglass14.warranty="1 Year";
sunglass14.rating=5;
sunglass14.customerReview="Comfortable and stylish";
sunglass14.isStockAvailable=true;
sunglass14.packagingType="Box";

// ---------------- Sunglass 15 ----------------
Sunglass sunglass15 = new Sunglass();
sunglass15.brand="Fendi";
sunglass15.model="FF0174S";
sunglass15.frameMaterial="Metal";
sunglass15.lensMaterial="Glass";
sunglass15.lensColour="Brown";
sunglass15.frameColour="Gold";
sunglass15.shape="Aviator";
sunglass15.isUVProtected=true;
sunglass15.isPolarized=true;
sunglass15.isScratchResistant=true;
sunglass15.isWaterResistant=false;
sunglass15.isAntiReflective=true;
sunglass15.isLightweight=false;
sunglass15.price=13000;
sunglass15.quantity=2;
sunglass15.weight=31;
sunglass15.gender="Female";
sunglass15.style="Luxury";
sunglass15.countryOfOrigin="Italy";
sunglass15.sellerName="Fendi Official Store";
sunglass15.warranty="2 Years";
sunglass15.rating=5;
sunglass15.customerReview="Premium quality";
sunglass15.isStockAvailable=true;
sunglass15.packagingType="Box";

// ---------------- Sunglass 16 ----------------
Sunglass sunglass16 = new Sunglass();
sunglass16.brand = "Gucci";
sunglass16.model = "GG0061S";
sunglass16.frameMaterial = "Acetate";
sunglass16.lensMaterial = "Glass";
sunglass16.lensColour = "Brown";
sunglass16.frameColour = "Tortoise";
sunglass16.shape = "Square";
sunglass16.isUVProtected = true;
sunglass16.isPolarized = true;
sunglass16.isScratchResistant = true;
sunglass16.isWaterResistant = false;
sunglass16.isAntiReflective = true;
sunglass16.isLightweight = true;
sunglass16.price = 15000;
sunglass16.quantity = 2;
sunglass16.weight = 30;
sunglass16.gender = "Unisex";
sunglass16.style = "Luxury";
sunglass16.countryOfOrigin = "Italy";
sunglass16.sellerName = "Gucci Official Store";
sunglass16.warranty = "2 Years";
sunglass16.rating = 5;
sunglass16.customerReview = "Stylish and durable";
sunglass16.isStockAvailable = true;
sunglass16.packagingType = "Box";

System.out.println("\nBrand: " + sunglass16.brand);
System.out.println("Model: " + sunglass16.model);
System.out.println("Frame Material: " + sunglass16.frameMaterial);
System.out.println("Lens Material: " + sunglass16.lensMaterial);
System.out.println("Lens Colour: " + sunglass16.lensColour);
System.out.println("Frame Colour: " + sunglass16.frameColour);
System.out.println("Shape: " + sunglass16.shape);
System.out.println("UV Protected: " + sunglass16.isUVProtected);
System.out.println("Polarized: " + sunglass16.isPolarized);
System.out.println("Scratch Resistant: " + sunglass16.isScratchResistant);
System.out.println("Water Resistant: " + sunglass16.isWaterResistant);
System.out.println("Anti Reflective: " + sunglass16.isAntiReflective);
System.out.println("Lightweight: " + sunglass16.isLightweight);
System.out.println("Price: " + sunglass16.price);
System.out.println("Quantity: " + sunglass16.quantity);
System.out.println("Weight: " + sunglass16.weight);
System.out.println("Gender: " + sunglass16.gender);
System.out.println("Style: " + sunglass16.style);
System.out.println("Country: " + sunglass16.countryOfOrigin);
System.out.println("Seller: " + sunglass16.sellerName);
System.out.println("Warranty: " + sunglass16.warranty);
System.out.println("Rating: " + sunglass16.rating);
System.out.println("Customer Review: " + sunglass16.customerReview);
System.out.println("Stock Available: " + sunglass16.isStockAvailable);
System.out.println("Packaging: " + sunglass16.packagingType);

// ---------------- Sunglass 17 ----------------
Sunglass sunglass17 = new Sunglass();
sunglass17.brand = "Ray-Ban";
sunglass17.model = "RB2132";
sunglass17.frameMaterial = "Plastic";
sunglass17.lensMaterial = "Glass";
sunglass17.lensColour = "Green";
sunglass17.frameColour = "Black";
sunglass17.shape = "Wayfarer";
sunglass17.isUVProtected = true;
sunglass17.isPolarized = true;
sunglass17.isScratchResistant = true;
sunglass17.isWaterResistant = false;
sunglass17.isAntiReflective = true;
sunglass17.isLightweight = true;
sunglass17.price = 12000;
sunglass17.quantity = 3;
sunglass17.weight = 25;
sunglass17.gender = "Unisex";
sunglass17.style = "Classic";
sunglass17.countryOfOrigin = "Italy";
sunglass17.sellerName = "Ray-Ban Official Store";
sunglass17.warranty = "1 Year";
sunglass17.rating = 5;
sunglass17.customerReview = "Stylish and durable!";
sunglass17.isStockAvailable = true;
sunglass17.packagingType = "Box";

System.out.println("\nBrand: " + sunglass17.brand);
System.out.println("Model: " + sunglass17.model);
System.out.println("Frame Material: " + sunglass17.frameMaterial);
System.out.println("Lens Material: " + sunglass17.lensMaterial);
System.out.println("Lens Colour: " + sunglass17.lensColour);
System.out.println("Frame Colour: " + sunglass17.frameColour);
System.out.println("Shape: " + sunglass17.shape);
System.out.println("UV Protected: " + sunglass17.isUVProtected);
System.out.println("Polarized: " + sunglass17.isPolarized);
System.out.println("Scratch Resistant: " + sunglass17.isScratchResistant);
System.out.println("Water Resistant: " + sunglass17.isWaterResistant);
System.out.println("Anti Reflective: " + sunglass17.isAntiReflective);
System.out.println("Lightweight: " + sunglass17.isLightweight);
System.out.println("Price: " + sunglass17.price);
System.out.println("Quantity: " + sunglass17.quantity);
System.out.println("Weight: " + sunglass17.weight);
System.out.println("Gender: " + sunglass17.gender);
System.out.println("Style: " + sunglass17.style);
System.out.println("Country: " + sunglass17.countryOfOrigin);
System.out.println("Seller: " + sunglass17.sellerName);
System.out.println("Warranty: " + sunglass17.warranty);
System.out.println("Rating: " + sunglass17.rating);
System.out.println("Customer Review: " + sunglass17.customerReview);
System.out.println("Stock Available: " + sunglass17.isStockAvailable);
System.out.println("Packaging: " + sunglass17.packagingType);

// ---------------- Sunglass 18 ----------------
Sunglass sunglass18 = new Sunglass();
sunglass18.brand = "Oakley";
sunglass18.model = "OO9208";
sunglass18.frameMaterial = "O Matter";
sunglass18.lensMaterial = "Plutonite";
sunglass18.lensColour = "Prizm Black";
sunglass18.frameColour = "Black";
sunglass18.shape = "Rectangle";
sunglass18.isUVProtected = true;
sunglass18.isPolarized = true;
sunglass18.isScratchResistant = true;
sunglass18.isWaterResistant = false;
sunglass18.isAntiReflective = true;
sunglass18.isLightweight = true;
sunglass18.price = 11000;
sunglass18.quantity = 2;
sunglass18.weight = 28;
sunglass18.gender = "Unisex";
sunglass18.style = "Sport";
sunglass18.countryOfOrigin = "USA";
sunglass18.sellerName = "Oakley Official Store";
sunglass18.warranty = "1 Year";
sunglass18.rating = 5;
sunglass18.customerReview = "Perfect for outdoor sports";
sunglass18.isStockAvailable = true;
sunglass18.packagingType = "Case";

System.out.println("\nBrand: " + sunglass18.brand);
System.out.println("Model: " + sunglass18.model);
System.out.println("Frame Material: " + sunglass18.frameMaterial);
System.out.println("Lens Material: " + sunglass18.lensMaterial);
System.out.println("Lens Colour: " + sunglass18.lensColour);
System.out.println("Frame Colour: " + sunglass18.frameColour);
System.out.println("Shape: " + sunglass18.shape);
System.out.println("UV Protected: " + sunglass18.isUVProtected);
System.out.println("Polarized: " + sunglass18.isPolarized);
System.out.println("Scratch Resistant: " + sunglass18.isScratchResistant);
System.out.println("Water Resistant: " + sunglass18.isWaterResistant);
System.out.println("Anti Reflective: " + sunglass18.isAntiReflective);
System.out.println("Lightweight: " + sunglass18.isLightweight);
System.out.println("Price: " + sunglass18.price);
System.out.println("Quantity: " + sunglass18.quantity);
System.out.println("Weight: " + sunglass18.weight);
System.out.println("Gender: " + sunglass18.gender);
System.out.println("Style: " + sunglass18.style);
System.out.println("Country: " + sunglass18.countryOfOrigin);
System.out.println("Seller: " + sunglass18.sellerName);
System.out.println("Warranty: " + sunglass18.warranty);
System.out.println("Rating: " + sunglass18.rating);
System.out.println("Customer Review: " + sunglass18.customerReview);
System.out.println("Stock Available: " + sunglass18.isStockAvailable);
System.out.println("Packaging: " + sunglass18.packagingType);

// ---------------- Sunglass 19 ----------------
Sunglass sunglass19 = new Sunglass();
sunglass19.brand = "Armani";
sunglass19.model = "AR8047";
sunglass19.frameMaterial = "Metal";
sunglass19.lensMaterial = "Glass";
sunglass19.lensColour = "Brown";
sunglass19.frameColour = "Gold";
sunglass19.shape = "Rectangle";
sunglass19.isUVProtected = true;
sunglass19.isPolarized = false;
sunglass19.isScratchResistant = true;
sunglass19.isWaterResistant = false;
sunglass19.isAntiReflective = true;
sunglass19.isLightweight = false;
sunglass19.price = 13000;
sunglass19.quantity = 2;
sunglass19.weight = 30;
sunglass19.gender = "Male";
sunglass19.style = "Luxury";
sunglass19.countryOfOrigin = "Italy";
sunglass19.sellerName = "Armani Official Store";
sunglass19.warranty = "2 Years";
sunglass19.rating = 5;
sunglass19.customerReview = "Elegant and premium";
sunglass19.isStockAvailable = true;
sunglass19.packagingType = "Box";

System.out.println("\nBrand: " + sunglass19.brand);
System.out.println("Model: " + sunglass19.model);
System.out.println("Frame Material: " + sunglass19.frameMaterial);
System.out.println("Lens Material: " + sunglass19.lensMaterial);
System.out.println("Lens Colour: " + sunglass19.lensColour);
System.out.println("Frame Colour: " + sunglass19.frameColour);
System.out.println("Shape: " + sunglass19.shape);
System.out.println("UV Protected: " + sunglass19.isUVProtected);
System.out.println("Polarized: " + sunglass19.isPolarized);
System.out.println("Scratch Resistant: " + sunglass19.isScratchResistant);
System.out.println("Water Resistant: " + sunglass19.isWaterResistant);
System.out.println("Anti Reflective: " + sunglass19.isAntiReflective);
System.out.println("Lightweight: " + sunglass19.isLightweight);
System.out.println("Price: " + sunglass19.price);
System.out.println("Quantity: " + sunglass19.quantity);
System.out.println("Weight: " + sunglass19.weight);
System.out.println("Gender: " + sunglass19.gender);
System.out.println("Style: " + sunglass19.style);
System.out.println("Country: " + sunglass19.countryOfOrigin);
System.out.println("Seller: " + sunglass19.sellerName);
System.out.println("Warranty: " + sunglass19.warranty);
System.out.println("Rating: " + sunglass19.rating);
System.out.println("Customer Review: " + sunglass19.customerReview);
System.out.println("Stock Available: " + sunglass19.isStockAvailable);
System.out.println("Packaging: " + sunglass19.packagingType);

// ---------------- Sunglass 20 ----------------
Sunglass sunglass20 = new Sunglass();
sunglass20.brand = "Dior";
sunglass20.model = "DIORSTELLAIRE1";
sunglass20.frameMaterial = "Metal";
sunglass20.lensMaterial = "Glass";
sunglass20.lensColour = "Grey";
sunglass20.frameColour = "Silver";
sunglass20.shape = "Cat-Eye";
sunglass20.isUVProtected = true;
sunglass20.isPolarized = true;
sunglass20.isScratchResistant = true;
sunglass20.isWaterResistant = false;
sunglass20.isAntiReflective = true;
sunglass20.isLightweight = true;
sunglass20.price = 18000;
sunglass20.quantity = 2;
sunglass20.weight = 29;
sunglass20.gender = "Female";
sunglass20.style = "Luxury";
sunglass20.countryOfOrigin = "Italy";
sunglass20.sellerName = "Dior Official Store";
sunglass20.warranty = "2 Years";
sunglass20.rating = 5;
sunglass20.customerReview = "Premium and elegant";
sunglass20.isStockAvailable = true;
sunglass20.packagingType = "Box";

System.out.println("\nBrand: " + sunglass20.brand);
System.out.println("Model: " + sunglass20.model);
System.out.println("Frame Material: " + sunglass20.frameMaterial);
System.out.println("Lens Material: " + sunglass20.lensMaterial);
System.out.println("Lens Colour: " + sunglass20.lensColour);
System.out.println("Frame Colour: " + sunglass20.frameColour);
System.out.println("Shape: " + sunglass20.shape);
System.out.println("UV Protected: " + sunglass20.isUVProtected);
System.out.println("Polarized: " + sunglass20.isPolarized);
System.out.println("Scratch Resistant: " + sunglass20.isScratchResistant);
System.out.println("Water Resistant: " + sunglass20.isWaterResistant);
System.out.println("Anti Reflective: " + sunglass20.isAntiReflective);
System.out.println("Lightweight: " + sunglass20.isLightweight);
System.out.println("Price: " + sunglass20.price);
System.out.println("Quantity: " + sunglass20.quantity);
System.out.println("Weight: " + sunglass20.weight);
System.out.println("Gender: " + sunglass20.gender);
System.out.println("Style: " + sunglass20.style);
System.out.println("Country: " + sunglass20.countryOfOrigin);
System.out.println("Seller: " + sunglass20.sellerName);
System.out.println("Warranty: " + sunglass20.warranty);
System.out.println("Rating: " + sunglass20.rating);
System.out.println("Customer Review: " + sunglass20.customerReview);
System.out.println("Stock Available: " + sunglass20.isStockAvailable);
System.out.println("Packaging: " + sunglass20.packagingType);

	}
	
}
